g2o: /home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_viewer/CMakeLists.txt File Reference
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_viewer/CMakeLists.txt File Reference
Functions
if (POLICY CMP0020) cmake_policy(SET CMP0020 OLD) endif() if(Qt4_FOUND) endif() if(Qt5_FOUND) endif() ADD_LIBRARY(viewer_library $
Function Documentation
if (POLICY CMP0020)
Definition at line 2 of file CMakeLists.txt.
References ADD_LIBRARY(), core, and SET().
Referenced by main(), and g2o::LinearSolverCholmodOnline< MatrixType >::nonZerosInL().
     {4,5} have been find_package'd() by FindQGLViewer.cmake
 if(Qt4_FOUND)
   INCLUDE(${QT_USE_FILE})
   QT4_WRAP_UI(UI_HEADERS base_main_window.ui base_properties_widget.ui)
   QT4_WRAP_CPP(UI_SOURCES main_window.h properties_widget.h)
   INCLUDE_DIRECTORIES(${QT_INCLUDES})
   SET(MY_QT_LIBRARIES ${QT_LIBRARIES})
 endif()
 if(Qt5_FOUND)
   QT5_WRAP_UI(UI_HEADERS base_main_window.ui base_properties_widget.ui)
   QT5_WRAP_CPP(UI_SOURCES main_window.h properties_widget.h)
   INCLUDE_DIRECTORIES(${Qt5Core_INCLUDE_DIRS} ${Qt5Xml_INCLUDE_DIRS} ${Qt5Gui_INCLUDE_DIRS} ${Qt5Widgets_INCLUDE_DIRS} ${Qt5OpenGL_INCLUDE_DIRS})
   SET(MY_QT_LIBRARIES ${Qt5Widgets_LIBRARIES} ${Qt5Core_LIBRARIES} ${Qt5Gui_LIBRARIES} ${Qt5Xml_LIBRARIES} ${Qt5OpenGL_LIBRARIES})
 endif()
 INCLUDE_DIRECTORIES(${QGLVIEWER_INCLUDE_DIR} ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_BINARY_DIR})
 ADD_LIBRARY(viewer_library ${G2O_LIB_TYPE}