g2o: /home/xuezhisd/CLionProjects/g2o/g2o/examples/bal/bal_example.cpp File Reference
bal_example.cpp File Reference
#include <Eigen/Core>
#include <Eigen/StdVector>
#include <Eigen/Geometry>
#include <iostream>
#include "g2o/stuff/command_args.h"
#include "g2o/core/batch_stats.h"
#include "g2o/core/sparse_optimizer.h"
#include "g2o/core/block_solver.h"
#include "g2o/core/solver.h"
#include "g2o/core/optimization_algorithm_levenberg.h"
#include "g2o/core/base_vertex.h"
#include "g2o/core/base_binary_edge.h"
#include "g2o/solvers/dense/linear_solver_dense.h"
#include "g2o/solvers/structure_only/structure_only_solver.h"
#include "g2o/solvers/pcg/linear_solver_pcg.h"
#include "EXTERNAL/ceres/autodiff.h"
Classes
class VertexCameraBAL
camera vertex which stores the parameters for a pinhole camera
class VertexPointBAL
3D world feature
class EdgeObservationBAL
edge representing the observation of a world feature by a camera
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 283 of file bal_example.cpp.
References g2o::OptimizableGraph::addEdge(), g2o::OptimizableGraph::addVertex(), g2o::SparseOptimizer::batchStatistics(), g2o::SparseOptimizer::initializeOptimization(), g2o::SparseOptimizer::optimize(), g2o::CommandArgs::param(), g2o::CommandArgs::paramLeftOver(), g2o::CommandArgs::parseArgs(), g2o::SparseOptimizer::setAlgorithm(), g2o::SparseOptimizer::setComputeBatchStatistics(), g2o::BaseVertex< D, T >::setEstimate(), g2o::OptimizableGraph::Vertex::setId(), g2o::BaseEdge< D, E >::setInformation(), g2o::OptimizableGraph::Vertex::setMarginalized(), g2o::BaseEdge< D, E >::setMeasurement(), g2o::SparseOptimizer::setVerbose(), and g2o::HyperGraph::Edge::setVertex().
 {
   int maxIterations;
   bool verbose;
   bool usePCG;
   string outputFilename;
   string inputFilename;
   string statsFilename;
   CommandArgs arg;
   arg.param("i", maxIterations, 5, "perform n iterations");
   arg.param("o", outputFilename, "", "write points into a vrml file");
   arg.param("pcg", usePCG, false, "use PCG instead of the Cholesky");
   arg.param("v", verbose, false, "verbose output of the optimization process");
   arg.param("stats", statsFilename, "", "specify a file for the statistics");
   arg.paramLeftOver("graph-input", inputFilename, "", "file which will be processed");
   arg.parseArgs(argc, argv);
   typedef g2o::BlockSolver< g2o::BlockSolverTraits<9, 3> >  BalBlockSolver;
 #ifdef G2O_HAVE_CHOLMOD
   string choleskySolverName = "CHOLMOD";
   typedef g2o::LinearSolverCholmod<BalBlockSolver::PoseMatrixType> BalLinearSolver;
 #elif defined G2O_HAVE_CSPARSE
   string choleskySolverName = "CSparse";
   typedef g2o::LinearSolverCSparse<BalBlockSolver::PoseMatrixType> BalLinearSolver;
 #else
 #error neither CSparse nor CHOLMOD are available
 #endif
   typedef g2o::LinearSolverPCG<BalBlockSolver::PoseMatrixType> BalLinearSolverPCG;
   g2o::SparseOptimizer optimizer;
   g2o::LinearSolver<BalBlockSolver::PoseMatrixType>* linearSolver = 0;
   if (usePCG) {
     cout << "Using PCG" << endl;
     linearSolver = new BalLinearSolverPCG();
   } else {
     cout << "Using Cholesky: " << choleskySolverName << endl;
     BalLinearSolver* cholesky = new BalLinearSolver();
     cholesky->setBlockOrdering(true);
     linearSolver = cholesky;
   }
   BalBlockSolver* solver_ptr = new BalBlockSolver(linearSolver);
   g2o::OptimizationAlgorithmLevenberg* solver = new g2o::OptimizationAlgorithmLevenberg(solver_ptr);
   //solver->setUserLambdaInit(1);
   optimizer.setAlgorithm(solver);
   if (statsFilename.size() > 0){
     optimizer.setComputeBatchStatistics(true);
   }
   vector<VertexPointBAL*> points;
   vector<VertexCameraBAL*> cameras;
   // parse BAL dataset
   cout << "Loading BAL dataset " << inputFilename << endl;
   {
     ifstream ifs(inputFilename.c_str());
     int numCameras, numPoints, numObservations;
     ifs >> numCameras >> numPoints >> numObservations;
     cerr << PVAR(numCameras) << " " << PVAR(numPoints) << " " << PVAR(numObservations) << endl;
     int id = 0;
     cameras.reserve(numCameras);
     for (int i = 0; i < numCameras; ++i, ++id) {
       VertexCameraBAL* cam = new VertexCameraBAL;
       cam->setId(id);
       optimizer.addVertex(cam);
       cameras.push_back(cam);
     }
     points.reserve(numPoints);
     for (int i = 0; i < numPoints; ++i, ++id) {
       VertexPointBAL* p = new VertexPointBAL;
       p->setId(id);
       p->setMarginalized(true);
       bool addedVertex = optimizer.addVertex(p);
       if (! addedVertex) {
         cerr << "failing adding vertex" << endl;
       }
       points.push_back(p);
     }
     // read in the observation
     for (int i = 0; i < numObservations; ++i) {
       int camIndex, pointIndex;
       double obsX, obsY;
       ifs >> camIndex >> pointIndex >> obsX >> obsY;
       assert(camIndex >= 0 && (size_t)camIndex < cameras.size() && "Index out of bounds");
       VertexCameraBAL* cam = cameras[camIndex];
       assert(pointIndex >= 0 && (size_t)pointIndex < points.size() && "Index out of bounds");
       VertexPointBAL* point = points[pointIndex];
       EdgeObservationBAL* e = new EdgeObservationBAL;
       e->setVertex(0, cam);
       e->setVertex(1, point);
       e->setInformation(Eigen::Matrix2d::Identity());
       e->setMeasurement(Eigen::Vector2d(obsX, obsY));
       bool addedEdge = optimizer.addEdge(e);
       if (! addedEdge) {
         cerr << "error adding edge" << endl;
       }
     }
     // read in the camera params
     Eigen::VectorXd cameraParameter(9);
     for (int i = 0; i < numCameras; ++i) {
       for (int j = 0; j < 9; ++j)
         ifs >> cameraParameter(j);
       VertexCameraBAL* cam = cameras[i];
       cam->setEstimate(cameraParameter);
     }
     // read in the points
     Eigen::Vector3d p;
     for (int i = 0; i < numPoints; ++i) {
       ifs >> p(0) >> p(1) >> p(2);
       VertexPointBAL* point = points[i];
       point->setEstimate(p);
     }
   }
   cout << "done." << endl;
   cout << "Initializing ... " << flush;
   optimizer.initializeOptimization();
   cout << "done." << endl;
   optimizer.setVerbose(verbose);
   cout << "Start to optimize" << endl;
   optimizer.optimize(maxIterations);
   if (statsFilename!=""){
     cerr << "writing stats to file \"" << statsFilename << "\" ... ";
     ofstream fout(statsFilename.c_str());
     const BatchStatisticsContainer& bsc = optimizer.batchStatistics();
     for (size_t i=0; i<bsc.size(); i++)
       fout << bsc[i] << endl;
     cerr << "done." << endl;
   }
   // dump the points
   if (outputFilename.size() > 0) {
     ofstream fout(outputFilename.c_str()); // loadable with meshlab
     fout
       << "#VRML V2.0 utf8\n"
       << "Shape {\n"
       << "  appearance Appearance {\n"
       << "    material Material {\n"
       << "      diffuseColor " << 1 << " " << 0 << " " << 0 << "\n"
       << "      ambientIntensity 0.2\n"
       << "      emissiveColor 0.0 0.0 0.0\n"
       << "      specularColor 0.0 0.0 0.0\n"
       << "      shininess 0.2\n"
       << "      transparency 0.0\n"
       << "    }\n"
       << "  }\n"
       << "  geometry PointSet {\n"
       << "    coord Coordinate {\n"
       << "      point [\n";
     for (vector<VertexPointBAL*>::const_iterator it = points.begin(); it != points.end(); ++it) {
       fout << (*it)->estimate().transpose() << endl;
     }
     fout << "    ]\n" << "  }\n" << "}\n" << "  }\n";
   }
   return 0;
 }