g2o: g2o::VelocityMeasurement Class Reference
g2o::VelocityMeasurement Class Reference
velocity measurement of a differential robot
#include <odometry_measurement.h>
Public Member Functions
VelocityMeasurement ()
VelocityMeasurement (double vl, double vr, double dt)
double vl () const
void setVl (double v)
double vr () const
void setVr (double v)
double dt () const
void setDt (double t)
const Vector2D & measurement () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Attributes
Vector2D _measurement
double _dt
Detailed Description
velocity measurement of a differential robot
Definition at line 38 of file odometry_measurement.h.
Constructor & Destructor Documentation
g2o::VelocityMeasurement::VelocityMeasurement ()
Definition at line 34 of file odometry_measurement.cpp.
                                            :
     _measurement(0., 0.), _dt(0.)
   {
   }
g2o::VelocityMeasurement::VelocityMeasurement (double vl, double vr, double dt)
Definition at line 39 of file odometry_measurement.cpp.
                                                                           :
     _measurement(vl, vr), _dt(dt)
   {
   }
Member Function Documentation
double g2o::VelocityMeasurement::dt () const inline
Definition at line 51 of file odometry_measurement.h.
Referenced by g2o::EdgeSE2PureCalib::computeError(), g2o::OdomConvert::convertToMotion(), and g2o::EdgeSE2OdomDifferentialCalib::write().
 { return _dt;}
const Vector2D& g2o::VelocityMeasurement::measurement () const inline
Definition at line 54 of file odometry_measurement.h.
 { return _measurement;}
void g2o::VelocityMeasurement::setDt (double t) inline
Definition at line 52 of file odometry_measurement.h.
 { _dt = t;}
void g2o::VelocityMeasurement::setVl (double v) inline
Definition at line 46 of file odometry_measurement.h.
Referenced by main().
 { _measurement(0) = v;}
void g2o::VelocityMeasurement::setVr (double v) inline
Definition at line 49 of file odometry_measurement.h.
Referenced by main().
 { _measurement(1) = v;}
double g2o::VelocityMeasurement::vl () const inline
Definition at line 45 of file odometry_measurement.h.
Referenced by g2o::ClosedFormCalibration::calibrate(), g2o::OdomConvert::convertToMotion(), main(), and g2o::EdgeSE2OdomDifferentialCalib::write().
 { return _measurement(0);}
double g2o::VelocityMeasurement::vr () const inline
Definition at line 48 of file odometry_measurement.h.
Referenced by g2o::ClosedFormCalibration::calibrate(), g2o::EdgeSE2PureCalib::computeError(), g2o::OdomConvert::convertToMotion(), main(), and g2o::EdgeSE2OdomDifferentialCalib::write().
 { return _measurement(1);}
Member Data Documentation
double g2o::VelocityMeasurement::_dt protected
Definition at line 58 of file odometry_measurement.h.
Vector2D g2o::VelocityMeasurement::_measurement protected
Definition at line 57 of file odometry_measurement.h.
g2o::VelocityMeasurement::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 41 of file odometry_measurement.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/sclam2d/odometry_measurement.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/sclam2d/odometry_measurement.cpp