g2o: SlamParser::AddEdge Class Reference
SlamParser::AddEdge Class Reference
#include <commands.h>
Public Member Functions
AddEdge (const std::string &tag, int id, int dimension, int id1, int id2, const std::vector< double > &values, const std::vector< double > information)
int id () const
int dimension () const
int id1 () const
int id2 () const
const std::vector< double > & values ()
const std::vector< double > & information ()
Public Member Functions inherited from SlamParser::CommandNode
CommandNode (CommandType commandType, const std::string &tag)
virtual ~CommandNode ()
CommandType commandType () const
const std::string & tag () const
Protected Attributes
int _id
int _dimension
int _id1
int _id2
std::vector< double > _values
std::vector< double > _information
Protected Attributes inherited from SlamParser::CommandNode
CommandType _commandType
std::string _tag
Detailed Description
Definition at line 75 of file commands.h.
Constructor & Destructor Documentation
SlamParser::AddEdge::AddEdge (const std::string & tag, int id, int dimension, int id1, int id2, const std::vector< double > & values, const std::vector< double > information) inline
Definition at line 78 of file commands.h.
                                                                                                                                                    :
         CommandNode(CT_ADD_EDGE, tag),
         _id(id), _dimension(dimension), _id1(id1), _id2(id2), _values(values), _information(information)
     {
     }
Member Function Documentation
int SlamParser::AddEdge::dimension () const inline
Definition at line 85 of file commands.h.
Referenced by SlamParser::SlamContextInterface::process().
 {return _dimension;}
int SlamParser::AddEdge::id () const inline
Definition at line 84 of file commands.h.
Referenced by SlamParser::SlamContextInterface::process().
 {return _id;}
int SlamParser::AddEdge::id1 () const inline
Definition at line 86 of file commands.h.
Referenced by SlamParser::SlamContextInterface::process().
 {return _id1;}
int SlamParser::AddEdge::id2 () const inline
Definition at line 87 of file commands.h.
Referenced by SlamParser::SlamContextInterface::process().
 {return _id2;}
const std::vector<double>& SlamParser::AddEdge::information () inline
Definition at line 89 of file commands.h.
Referenced by SlamParser::SlamContextInterface::process().
 { return _information;}
const std::vector<double>& SlamParser::AddEdge::values () inline
Definition at line 88 of file commands.h.
Referenced by SlamParser::SlamContextInterface::process().
 { return _values;}
Member Data Documentation
int SlamParser::AddEdge::_dimension protected
Definition at line 93 of file commands.h.
int SlamParser::AddEdge::_id protected
Definition at line 92 of file commands.h.
int SlamParser::AddEdge::_id1 protected
Definition at line 94 of file commands.h.
int SlamParser::AddEdge::_id2 protected
Definition at line 95 of file commands.h.
std::vector<double> SlamParser::AddEdge::_information protected
Definition at line 97 of file commands.h.
std::vector<double> SlamParser::AddEdge::_values protected
Definition at line 96 of file commands.h.
The documentation for this class was generated from the following file:
/home/xuezhisd/CLionProjects/g2o/g2o/examples/interactive_slam/slam_parser/parser/commands.h