g2o: g2o::HyperGraph Class Reference
g2o::HyperGraph Class Reference
#include <hyper_graph.h>
Classes
class Data
data packet for a vertex. Extend this class to store in the vertices the potential additional information you need (e.g. images, laser scans, ...).
class DataContainer
Container class that implements an interface for adding/removing Data elements in a linked list.
class Edge
struct HyperGraphElement
class Vertex
abstract Vertex, your types must derive from that one
Public Types
typedef std::bitset< HyperGraph::HGET_NUM_ELEMS > GraphElemBitset
typedef std::set< Edge * > EdgeSet
typedef std::set< Vertex * > VertexSet
typedef std::unordered_map< int, Vertex * > VertexIDMap
typedef std::vector< Vertex * > VertexContainer
Public Member Functions
HyperGraph ()
constructs an empty hyper graph
virtual ~HyperGraph ()
destroys the hyper-graph and all the vertices of the graph
Vertex * vertex (int id)
returns a vertex id in the hyper-graph, or 0 if the vertex id is not present
const Vertex * vertex (int id) const
returns a vertex id in the hyper-graph, or 0 if the vertex id is not present
virtual bool removeVertex (Vertex *v, bool detach=false)
removes a vertex from the graph. Returns true on success (vertex was present)
virtual bool removeEdge (Edge *e)
removes a vertex from the graph. Returns true on success (edge was present)
virtual void clear ()
clears the graph and empties all structures.
const VertexIDMap & vertices () const
VertexIDMap & vertices ()
const EdgeSet & edges () const
EdgeSet & edges ()
virtual bool addVertex (Vertex *v)
virtual bool addEdge (Edge *e)
virtual bool setEdgeVertex (Edge *e, int pos, Vertex *v)
virtual bool mergeVertices (Vertex *vBig, Vertex *vSmall, bool erase)
virtual bool detachVertex (Vertex *v)
virtual bool changeId (Vertex *v, int newId)
Public Attributes
class G2O_CORE_API Data
class G2O_CORE_API DataContainer
class G2O_CORE_API Vertex
class G2O_CORE_API Edge
Static Public Attributes
static const int UnassignedId = -1
static const int InvalidId = -2
Protected Attributes
VertexIDMap _vertices
EdgeSet _edges
Private Member Functions
HyperGraph (const HyperGraph &)
HyperGraph & operator= (const HyperGraph &)
Detailed Description
Class that models a directed Hyper-Graph. An hyper graph is a graph where an edge can connect one or more nodes. Both Vertices and Edges of an hyoper graph derive from the same class HyperGraphElement, thus one can implement generic algorithms that operate transparently on edges or vertices (see HyperGraphAction).
The vertices are uniquely identified by an int id, while the edges are identfied by their pointers.
Definition at line 55 of file hyper_graph.h.
Member Typedef Documentation
typedef std::set<Edge*> g2o::HyperGraph::EdgeSet
Definition at line 135 of file hyper_graph.h.
typedef std::bitset<HyperGraph::HGET_NUM_ELEMS> g2o::HyperGraph::GraphElemBitset
Definition at line 74 of file hyper_graph.h.
typedef std::vector<Vertex*> g2o::HyperGraph::VertexContainer
Definition at line 139 of file hyper_graph.h.
typedef std::unordered_map<int, Vertex*> g2o::HyperGraph::VertexIDMap
Definition at line 138 of file hyper_graph.h.
typedef std::set<Vertex*> g2o::HyperGraph::VertexSet
Definition at line 136 of file hyper_graph.h.
Constructor & Destructor Documentation
g2o::HyperGraph::HyperGraph ()
constructs an empty hyper graph
Definition at line 225 of file hyper_graph.cpp.
   {
   }
g2o::HyperGraph::~HyperGraph () virtual
destroys the hyper-graph and all the vertices of the graph
Definition at line 239 of file hyper_graph.cpp.
References clear().
   {
     clear();
   }
g2o::HyperGraph::HyperGraph (const HyperGraph &) inline private
Definition at line 279 of file hyper_graph.h.
 { }
Member Function Documentation
bool g2o::HyperGraph::addEdge (Edge * e) virtual
Adds an edge to the graph. If the edge is already in the graph, it does nothing and returns false. Otherwise it returns true.
Reimplemented in g2o::OptimizableGraph.
Definition at line 117 of file hyper_graph.cpp.
References _edges, g2o::HyperGraph::Vertex::edges(), and g2o::HyperGraph::Edge::vertices().
Referenced by g2o::OptimizableGraph::addEdge().
   {
     std::pair<EdgeSet::iterator, bool> result = _edges.insert(e);
     if (! result.second)
       return false;
     for (std::vector<Vertex*>::iterator it = e->vertices().begin(); it != e->vertices().end(); ++it) {
       Vertex* v = *it;
       if (v)
         v->edges().insert(e);
     }
     return true;
   }
bool g2o::HyperGraph::addVertex (Vertex * v) virtual
adds a vertex to the graph. The id of the vertex should be set before invoking this function. the function fails if another vertex with the same id is already in the graph. returns true, on success, or false on failure.
Reimplemented in g2o::OptimizableGraph.
Definition at line 94 of file hyper_graph.cpp.
References g2o::HyperGraph::Edge::_vertices, g2o::HyperGraph::Vertex::id(), and g2o::HyperGraph::Edge::vertex().
Referenced by g2o::OptimizableGraph::addVertex().
   {
     Vertex* vn=vertex(v->id());
     if (vn)
       return false;
     _vertices.insert( std::make_pair(v->id(),v) );
     return true;
   }
bool g2o::HyperGraph::changeId (Vertex * v, int newId) virtual
changes the id of a vertex already in the graph, and updates the bookkeeping @ returns false if the vertex is not in the graph;
Definition at line 107 of file hyper_graph.cpp.
References g2o::HyperGraph::Edge::_vertices, g2o::HyperGraph::Vertex::id(), g2o::HyperGraph::Vertex::setId(), and g2o::HyperGraph::Edge::vertex().
{
     Vertex* v2 = vertex(v->id());
     if (v != v2)
       return false;
     _vertices.erase(v->id());
     v->setId(newId);
     _vertices.insert(std::make_pair(v->id(), v));
     return true;
   }
void g2o::HyperGraph::clear () virtual
clears the graph and empties all structures.
Reimplemented in g2o::SparseOptimizer.
Definition at line 229 of file hyper_graph.cpp.
References _edges, and g2o::HyperGraph::Edge::_vertices.
Referenced by g2o::SparseOptimizer::clear(), g2o::OptimizableGraph::clearParameters(), ~HyperGraph(), and g2o::OptimizableGraph::~OptimizableGraph().
   {
     for (VertexIDMap::iterator it=_vertices.begin(); it!=_vertices.end(); ++it)
       delete (it->second);
     for (EdgeSet::iterator it=_edges.begin(); it!=_edges.end(); ++it)
       delete (*it);
     _vertices.clear();
     _edges.clear();
   }
bool g2o::HyperGraph::detachVertex (Vertex * v) virtual
detaches a vertex from all connected edges
Definition at line 166 of file hyper_graph.cpp.
References g2o::HyperGraph::Edge::_vertices, g2o::HyperGraph::Vertex::edges(), g2o::HyperGraph::Vertex::id(), setEdgeVertex(), g2o::HyperGraph::Edge::vertex(), and g2o::HyperGraph::Edge::vertices().
Referenced by removeVertex().
{
     VertexIDMap::iterator it=_vertices.find(v->id());
     if (it==_vertices.end())
       return false;
     assert(it->second==v);
     EdgeSet tmp(v->edges());
     for (EdgeSet::iterator it=tmp.begin(); it!=tmp.end(); ++it){
       HyperGraph::Edge* e = *it;
       for (size_t i = 0 ; i<e->vertices().size(); i++){
         if (v == e->vertex(i))
           setEdgeVertex(e,i,0);
       }
     }
     return true;
   }
const EdgeSet& g2o::HyperGraph::edges () const inline
Returns
the set of edges of the hyper graph
Definition at line 230 of file hyper_graph.h.
Referenced by g2o::G2oSlamInterface::addEdge(), g2o::OptimizableGraph::addGraph(), g2o::addOdometryCalibLinksDifferential(), g2o::applyAction(), g2o::OptimizableGraph::chi2(), g2o::dumpEdges(), g2o::SparseOptimizerOnline::gnuplotVisualization(), g2o::BackBoneTreeAction::init(), g2o::SparseOptimizer::initializeOptimization(), main(), g2o::OptimizableGraph::save(), g2o::saveGnuplot(), MainWindow::setRobustKernel(), g2o::JacobianWorkspace::updateSize(), g2o::OptimizableGraph::verifyInformationMatrices(), and g2o::Gm2dlIO::writeGm2dl().
 {return _edges;}
EdgeSet& g2o::HyperGraph::edges () inline
Returns
the set of edges of the hyper graph
Definition at line 232 of file hyper_graph.h.
 {return _edges;}
bool g2o::HyperGraph::mergeVertices (Vertex * vBig, Vertex * vSmall, bool erase) virtual
merges two (valid) vertices, adjusts the bookkeeping and relabels all edges. the observations of vSmall are retargeted to vBig. If erase = true, vSmall is deleted from the graph repeatedly calls setEdgeVertex(...)
Definition at line 141 of file hyper_graph.cpp.
References g2o::HyperGraph::Edge::_vertices, g2o::HyperGraph::Vertex::edges(), g2o::HyperGraph::Vertex::id(), removeVertex(), setEdgeVertex(), g2o::HyperGraph::Edge::vertex(), and g2o::HyperGraph::Edge::vertices().
   {
     VertexIDMap::iterator it=_vertices.find(vBig->id());
     if (it==_vertices.end())
       return false;
     it=_vertices.find(vSmall->id());
     if (it==_vertices.end())
       return false;
     EdgeSet tmp(vSmall->edges());
     bool ok = true;
     for(EdgeSet::iterator it=tmp.begin(); it!=tmp.end(); ++it){
       HyperGraph::Edge* e = *it;
       for (size_t i=0; i<e->vertices().size(); i++){
         Vertex* v=e->vertex(i);
         if (v==vSmall)
           ok &= setEdgeVertex(e,i,vBig);
       }
     }
     if (erase)
       removeVertex(vSmall);
     return ok;
   }
HyperGraph& g2o::HyperGraph::operator= (const HyperGraph &) inline private
Definition at line 280 of file hyper_graph.h.
 { return *this; }
bool g2o::HyperGraph::removeEdge (Edge * e) virtual
removes a vertex from the graph. Returns true on success (edge was present)
Definition at line 206 of file hyper_graph.cpp.
References _edges, g2o::HyperGraph::Vertex::edges(), and g2o::HyperGraph::Edge::vertices().
Referenced by removeVertex().
   {
     EdgeSet::iterator it = _edges.find(e);
     if (it == _edges.end())
       return false;
     _edges.erase(it);
     for (std::vector<Vertex*>::iterator vit = e->vertices().begin(); vit != e->vertices().end(); ++vit) {
       Vertex* v = *vit;
       if (!v)
         continue;
       it = v->edges().find(e);
       assert(it!=v->edges().end());
       v->edges().erase(it);
     }
     delete e;
     return true;
   }
bool g2o::HyperGraph::removeVertex (Vertex * v, bool detach = false) virtual
removes a vertex from the graph. Returns true on success (vertex was present)
Reimplemented in g2o::SparseOptimizer.
Definition at line 182 of file hyper_graph.cpp.
References g2o::HyperGraph::Edge::_vertices, detachVertex(), g2o::HyperGraph::Vertex::edges(), g2o::HyperGraph::Vertex::id(), and removeEdge().
Referenced by mergeVertices(), and g2o::SparseOptimizer::removeVertex().
   {
     if (detach){
       bool result = detachVertex(v);
       if (! result) {
         assert (0 && "inconsistency in detaching vertex, ");
       }
     }
     VertexIDMap::iterator it=_vertices.find(v->id());
     if (it==_vertices.end())
       return false;
     assert(it->second==v);
     //remove all edges which are entering or leaving v;
     EdgeSet tmp(v->edges());
     for (EdgeSet::iterator it=tmp.begin(); it!=tmp.end(); ++it){
       if (!removeEdge(*it)){
         assert(0 && "error in erasing vertex");
       }
     }
     _vertices.erase(it);
     delete v;
     return true;
   }
bool g2o::HyperGraph::setEdgeVertex (HyperGraph::Edge * e, int pos, HyperGraph::Vertex * v) virtual
Sets the vertex un position "pos" within the edge and keeps the bookkeeping consistent. If v ==0, the vertex is set to "invalid"
Reimplemented in g2o::OptimizableGraph.
Definition at line 130 of file hyper_graph.cpp.
References g2o::HyperGraph::Vertex::edges(), g2o::HyperGraph::Edge::setVertex(), and g2o::HyperGraph::Edge::vertex().
Referenced by detachVertex(), mergeVertices(), and g2o::OptimizableGraph::setEdgeVertex().
   {
     Vertex* vOld = e->vertex(pos);
     if (vOld)
       vOld->edges().erase(e);
     e->setVertex(pos, v);
     if (v)
       v->edges().insert(e);
     return true;
   }
HyperGraph::Vertex * g2o::HyperGraph::vertex (int id)
returns a vertex id in the hyper-graph, or 0 if the vertex id is not present
Definition at line 78 of file hyper_graph.cpp.
References g2o::HyperGraph::Edge::_vertices.
Referenced by g2o::OptimizableGraph::vertex().
   {
     VertexIDMap::iterator it=_vertices.find(id);
     if (it==_vertices.end())
       return 0;
     return it->second;
   }
const HyperGraph::Vertex * g2o::HyperGraph::vertex (int id) const
returns a vertex id in the hyper-graph, or 0 if the vertex id is not present
Definition at line 86 of file hyper_graph.cpp.
References g2o::HyperGraph::Edge::_vertices.
   {
     VertexIDMap::const_iterator it=_vertices.find(id);
     if (it==_vertices.end())
       return 0;
     return it->second;
   }
const VertexIDMap& g2o::HyperGraph::vertices () const inline
Returns
the map id -> vertex where the vertices are stored
Definition at line 225 of file hyper_graph.h.
Referenced by g2o::OptimizableGraph::addGraph(), g2o::applyAction(), g2o::Slam2DViewer::draw(), g2o::EstimatePropagator::EstimatePropagator(), g2o::SparseOptimizer::findGauge(), g2o::SparseOptimizer::gaugeFreedom(), g2o::HyperDijkstra::HyperDijkstra(), g2o::SparseOptimizer::initializeOptimization(), main(), g2o::SparseOptimizerOnline::optimize(), MainWindow::prepare(), g2o::G2oSlamInterface::queryState(), g2o::saveGnuplot(), g2o::SparseOptimizer::setToOrigin(), g2o::G2oSlamInterface::solve(), g2o::SolverSLAM2DLinear::solveOrientation(), updateDisplay(), g2o::Gm2dlIO::updateLaserData(), and g2o::Gm2dlIO::writeGm2dl().
 {return _vertices;}
VertexIDMap& g2o::HyperGraph::vertices () inline
Returns
the map id -> vertex where the vertices are stored
Definition at line 227 of file hyper_graph.h.
 {return _vertices;}
Member Data Documentation
EdgeSet g2o::HyperGraph::_edges protected
Definition at line 275 of file hyper_graph.h.
Referenced by addEdge(), clear(), and removeEdge().
VertexIDMap g2o::HyperGraph::_vertices protected
Definition at line 274 of file hyper_graph.h.
class G2O_CORE_API g2o::HyperGraph::Data
Definition at line 76 of file hyper_graph.h.
class G2O_CORE_API g2o::HyperGraph::DataContainer
Definition at line 77 of file hyper_graph.h.
class G2O_CORE_API g2o::HyperGraph::Edge
Definition at line 79 of file hyper_graph.h.
const int g2o::HyperGraph::InvalidId = -2 static
Definition at line 72 of file hyper_graph.h.
const int g2o::HyperGraph::UnassignedId = -1 static
Definition at line 71 of file hyper_graph.h.
Referenced by g2o::OptimizableGraph::saveEdge(), and g2o::OptimizableGraph::setFixed().
class G2O_CORE_API g2o::HyperGraph::Vertex
Definition at line 78 of file hyper_graph.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/core/hyper_graph.h
/home/xuezhisd/CLionProjects/g2o/g2o/core/hyper_graph.cpp