g2o: g2o::CacheSE2Offset Class Reference
g2o::CacheSE2Offset Class Reference
caching the offset related to a vertex
#include <parameter_se2_offset.h>
Public Member Functions
CacheSE2Offset ()
virtual void updateImpl ()
redefine this to do the update
const ParameterSE2Offset * offsetParam () const
void setOffsetParam (ParameterSE2Offset *offsetParam)
const SE2 & w2n () const
const SE2 & n2w () const
const Isometry2D & w2nMatrix () const
const Isometry2D & n2wMatrix () const
const Isometry2D & w2lMatrix () const
const Matrix2D RpInverseRInverseMatrix () const
const Matrix2D RpInverseRInversePrimeMatrix () const
Public Member Functions inherited from g2o::Cache
Cache (CacheContainer *container_=0, const ParameterVector &parameters_=ParameterVector())
CacheKey key () const
OptimizableGraph::Vertex * vertex ()
OptimizableGraph * graph ()
CacheContainer * container ()
ParameterVector & parameters ()
void update ()
virtual HyperGraph::HyperGraphElementType elementType () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Member Functions
virtual bool resolveDependancies ()
Protected Member Functions inherited from g2o::Cache
Cache * installDependency (const std::string &type_, const std::vector< int > &parameterIndices)
Protected Attributes
ParameterSE2Offset * _offsetParam
the parameter connected to the cache
SE2 _se2_w2n
SE2 _se2_n2w
Isometry2D _w2n
world to sensor transform
Isometry2D _w2l
world to local
Isometry2D _n2w
sensor to world
Matrix2D _RpInverse_RInverse
Matrix2D _RpInverse_RInversePrime
Protected Attributes inherited from g2o::Cache
bool _updateNeeded
ParameterVector _parameters
std::vector< Cache * > _parentCaches
CacheContainer * _container
Detailed Description
caching the offset related to a vertex
Definition at line 78 of file parameter_se2_offset.h.
Constructor & Destructor Documentation
g2o::CacheSE2Offset::CacheSE2Offset ()
Definition at line 65 of file parameter_se2_offset.cpp.
                                  :
     Cache(),
     _offsetParam(0)
   {
   }
Member Function Documentation
const SE2& g2o::CacheSE2Offset::n2w () const inline
Definition at line 88 of file parameter_se2_offset.h.
Referenced by g2o::EdgeSE2Offset::computeError(), and g2o::EdgeSE2Offset::setMeasurementFromState().
 {return _se2_n2w;}
const Isometry2D& g2o::CacheSE2Offset::n2wMatrix () const inline
Definition at line 91 of file parameter_se2_offset.h.
 { return _n2w;}
const ParameterSE2Offset* g2o::CacheSE2Offset::offsetParam () const inline
Definition at line 84 of file parameter_se2_offset.h.
Referenced by g2o::EdgeSE2Offset::initialEstimate(), and setOffsetParam().
 { return _offsetParam;}
bool g2o::CacheSE2Offset::resolveDependancies () protected virtual
Function to be called from a cache that has dependencies. It just invokes a sequence of installDependency(). Although the caches returned are stored in the _parentCache vector, it is better that you redefine your own cache member variables, for better readability
Reimplemented from g2o::Cache.
Definition at line 71 of file parameter_se2_offset.cpp.
References _offsetParam, and g2o::Cache::_parameters.
{
     _offsetParam = dynamic_cast <ParameterSE2Offset*> (_parameters[0]);
     return _offsetParam != 0;
   }
const Matrix2D g2o::CacheSE2Offset::RpInverseRInverseMatrix () const inline
Definition at line 94 of file parameter_se2_offset.h.
Referenced by g2o::EdgeSE2PointXYOffset::linearizeOplus().
 { return _RpInverse_RInverse; }
const Matrix2D g2o::CacheSE2Offset::RpInverseRInversePrimeMatrix () const inline
Definition at line 95 of file parameter_se2_offset.h.
Referenced by g2o::EdgeSE2PointXYOffset::linearizeOplus().
 { return _RpInverse_RInversePrime; }
void g2o::CacheSE2Offset::setOffsetParam (ParameterSE2Offset * offsetParam)
Definition at line 99 of file parameter_se2_offset.cpp.
References _offsetParam, and offsetParam().
   {
     _offsetParam = offsetParam;
   }
void g2o::CacheSE2Offset::updateImpl () virtual
redefine this to do the update
Implements g2o::Cache.
Definition at line 76 of file parameter_se2_offset.cpp.
References _n2w, _offsetParam, _RpInverse_RInverse, _RpInverse_RInversePrime, _se2_n2w, _se2_w2n, _w2l, _w2n, g2o::BaseVertex< D, T >::estimate(), g2o::SE2::inverse(), g2o::ParameterSE2Offset::offset(), g2o::SE2::rotation(), g2o::SE2::translation(), and g2o::Cache::vertex().
{
     const VertexSE2* v = static_cast<const VertexSE2*>(vertex());
     _se2_n2w = v->estimate() * _offsetParam->offset();
     _n2w = _se2_n2w.rotation().toRotationMatrix();
     _n2w.translation() = _se2_n2w.translation();
     _se2_w2n = _se2_n2w.inverse();
     _w2n = _se2_w2n.rotation().toRotationMatrix();
     _w2n.translation() = _se2_w2n.translation();
     SE2 w2l = v->estimate().inverse();
     _w2l = w2l.rotation().toRotationMatrix();
     _w2l.translation() = w2l.translation();
     double alpha=v->estimate().rotation().angle();
     double c=cos(alpha), s=sin(alpha);
     Matrix2D RInversePrime;
     RInversePrime << -s, c, -c, -s;
     _RpInverse_RInversePrime = _offsetParam->offset().rotation().toRotationMatrix().transpose()*RInversePrime;
     _RpInverse_RInverse=w2l.rotation();
   }
const Isometry2D& g2o::CacheSE2Offset::w2lMatrix () const inline
Definition at line 92 of file parameter_se2_offset.h.
Referenced by g2o::EdgeSE2PointXYOffset::computeError(), and g2o::EdgeSE2PointXYOffset::setMeasurementFromState().
 { return _w2l;}
const SE2& g2o::CacheSE2Offset::w2n () const inline
Definition at line 87 of file parameter_se2_offset.h.
Referenced by g2o::EdgeSE2Offset::computeError(), and g2o::EdgeSE2Offset::setMeasurementFromState().
 {return _se2_w2n;}
const Isometry2D& g2o::CacheSE2Offset::w2nMatrix () const inline
Definition at line 90 of file parameter_se2_offset.h.
 { return _w2n;}
Member Data Documentation
Isometry2D g2o::CacheSE2Offset::_n2w protected
sensor to world
Definition at line 104 of file parameter_se2_offset.h.
Referenced by updateImpl().
ParameterSE2Offset* g2o::CacheSE2Offset::_offsetParam protected
the parameter connected to the cache
Definition at line 98 of file parameter_se2_offset.h.
Referenced by resolveDependancies(), setOffsetParam(), and updateImpl().
Matrix2D g2o::CacheSE2Offset::_RpInverse_RInverse protected
Definition at line 105 of file parameter_se2_offset.h.
Referenced by updateImpl().
Matrix2D g2o::CacheSE2Offset::_RpInverse_RInversePrime protected
Definition at line 106 of file parameter_se2_offset.h.
Referenced by updateImpl().
SE2 g2o::CacheSE2Offset::_se2_n2w protected
Definition at line 100 of file parameter_se2_offset.h.
Referenced by updateImpl().
SE2 g2o::CacheSE2Offset::_se2_w2n protected
Definition at line 99 of file parameter_se2_offset.h.
Referenced by updateImpl().
Isometry2D g2o::CacheSE2Offset::_w2l protected
world to local
Definition at line 103 of file parameter_se2_offset.h.
Referenced by updateImpl().
Isometry2D g2o::CacheSE2Offset::_w2n protected
world to sensor transform
Definition at line 102 of file parameter_se2_offset.h.
Referenced by updateImpl().
g2o::CacheSE2Offset::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 80 of file parameter_se2_offset.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam2d/parameter_se2_offset.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam2d/parameter_se2_offset.cpp