g2o: g2o::Edge_V_V_GICP Class Reference
g2o::Edge_V_V_GICP Class Reference
#include <types_icp.h>
Public Member Functions
Edge_V_V_GICP ()
Edge_V_V_GICP (const Edge_V_V_GICP *e)
virtual bool read (std::istream &is)
read the vertex from a stream, i.e., the internal state of the vertex
virtual bool write (std::ostream &os) const
write the vertex to a stream
void computeError ()
virtual void linearizeOplus ()
Public Member Functions inherited from g2o::BaseBinaryEdge< 3, EdgeGICP, VertexSE3, VertexSE3 >
BaseBinaryEdge ()
virtual OptimizableGraph::Vertex * createFrom ()
virtual OptimizableGraph::Vertex * createTo ()
virtual OptimizableGraph::Vertex * createVertex (int i)
virtual void resize (size_t size)
virtual bool allVerticesFixed () const
virtual void linearizeOplus (JacobianWorkspace &jacobianWorkspace)
const JacobianXiOplusType & jacobianOplusXi () const
returns the result of the linearization in the manifold space for the node xi
const JacobianXjOplusType & jacobianOplusXj () const
returns the result of the linearization in the manifold space for the node xj
virtual void constructQuadraticForm ()
virtual void mapHessianMemory (double *d, int i, int j, bool rowMajor)
Public Member Functions inherited from g2o::BaseEdge< D, EdgeGICP >
BaseEdge ()
virtual ~BaseEdge ()
virtual double chi2 () const
computes the chi2 based on the cached error value, only valid after computeError has been called.
virtual const double * errorData () const
returns the error vector cached after calling the computeError;
virtual double * errorData ()
const ErrorVector & error () const
ErrorVector & error ()
EIGEN_STRONG_INLINE const InformationType & information () const
information matrix of the constraint
EIGEN_STRONG_INLINE InformationType & information ()
EIGEN_STRONG_INLINE void setInformation (const InformationType &information)
virtual const double * informationData () const
returns the memory of the information matrix, usable for example with a Eigen::Map<MatrixXD>
virtual double * informationData ()
EIGEN_STRONG_INLINE const Measurement & measurement () const
accessor functions for the measurement represented by the edge
virtual void setMeasurement (const Measurement &m)
virtual int rank () const
virtual void initialEstimate (const OptimizableGraph::VertexSet &, OptimizableGraph::Vertex *)
Public Member Functions inherited from g2o::OptimizableGraph::Edge
Edge ()
virtual ~Edge ()
virtual Edge * clone () const
virtual bool setMeasurementData (const double *m)
virtual bool getMeasurementData (double *m) const
virtual int measurementDimension () const
virtual bool setMeasurementFromState ()
RobustKernel * robustKernel () const
if NOT NULL, error of this edge will be robustifed with the kernel
void setRobustKernel (RobustKernel *ptr)
virtual double initialEstimatePossible (const OptimizableGraph::VertexSet &from, OptimizableGraph::Vertex *to)
int level () const
returns the level of the edge
void setLevel (int l)
sets the level of the edge
int dimension () const
returns the dimensions of the error function
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createFrom())
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createTo())
long long internalId () const
the internal ID of the edge
OptimizableGraph * graph ()
const OptimizableGraph * graph () const
bool setParameterId (int argNum, int paramId)
const Parameter * parameter (int argNo) const
size_t numParameters () const
void resizeParameters (size_t newSize)
Public Member Functions inherited from g2o::HyperGraph::Edge
Edge (int id=InvalidId)
creates and empty edge with no vertices
const VertexContainer & vertices () const
VertexContainer & vertices ()
const Vertex * vertex (size_t i) const
Vertex * vertex (size_t i)
void setVertex (size_t i, Vertex *v)
int id () const
void setId (int id)
virtual HyperGraphElementType elementType () const
int numUndefinedVertices () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Member Functions inherited from g2o::HyperGraph::DataContainer
DataContainer ()
virtual ~DataContainer ()
const Data * userData () const
the user data associated with this vertex
Data * userData ()
void setUserData (Data *obs)
void addUserData (Data *obs)
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
bool pl_pl
Matrix3D cov0
Matrix3D cov1
Static Public Attributes
static Matrix3D dRidx
static Matrix3D dRidy
static Matrix3D dRidz
Static Public Attributes inherited from g2o::BaseBinaryEdge< 3, EdgeGICP, VertexSE3, VertexSE3 >
static const int Di
static const int Dj
static const int Dimension
Static Public Attributes inherited from g2o::BaseEdge< D, EdgeGICP >
static const int Dimension
Additional Inherited Members
Public Types inherited from g2o::BaseBinaryEdge< 3, EdgeGICP, VertexSE3, VertexSE3 >
typedef VertexSE3 VertexXiType
typedef VertexSE3 VertexXjType
typedef BaseEdge< D, EdgeGICP >::Measurement Measurement
typedef Eigen::Matrix< double, D, Di, D==1?Eigen::RowMajor:Eigen::ColMajor >::AlignedMapType JacobianXiOplusType
typedef Eigen::Matrix< double, D, Dj, D==1?Eigen::RowMajor:Eigen::ColMajor >::AlignedMapType JacobianXjOplusType
typedef BaseEdge< D, EdgeGICP >::ErrorVector ErrorVector
typedef BaseEdge< D, EdgeGICP >::InformationType InformationType
typedef Eigen::Map< Eigen::Matrix< double, Di, Dj, Di==1?Eigen::RowMajor:Eigen::ColMajor >, Eigen::Matrix< double, Di, Dj, Di==1?Eigen::RowMajor:Eigen::ColMajor >::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockType
typedef Eigen::Map< Eigen::Matrix< double, Dj, Di, Dj==1?Eigen::RowMajor:Eigen::ColMajor >, Eigen::Matrix< double, Dj, Di, Dj==1?Eigen::RowMajor:Eigen::ColMajor >::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockTransposedType
Public Types inherited from g2o::BaseEdge< D, EdgeGICP >
typedef EdgeGICP Measurement
typedef Eigen::Matrix< double, D, 1, Eigen::ColMajor > ErrorVector
typedef Eigen::Matrix< double, D, D, Eigen::ColMajor > InformationType
Protected Member Functions inherited from g2o::BaseEdge< D, EdgeGICP >
InformationType robustInformation (const Vector3D &rho)
Protected Member Functions inherited from g2o::OptimizableGraph::Edge
template<typename ParameterType >
bool installParameter (ParameterType *&p, size_t argNo, int paramId=-1)
template<typename CacheType >
void resolveCache (CacheType *&cache, OptimizableGraph::Vertex *, const std::string &_type, const ParameterVector &parameters)
bool resolveParameters ()
virtual bool resolveCaches ()
Protected Attributes inherited from g2o::BaseBinaryEdge< 3, EdgeGICP, VertexSE3, VertexSE3 >
bool _hessianRowMajor
HessianBlockType _hessian
HessianBlockTransposedType _hessianTransposed
JacobianXiOplusType _jacobianOplusXi
JacobianXjOplusType _jacobianOplusXj
Protected Attributes inherited from g2o::BaseEdge< D, EdgeGICP >
Measurement _measurement
InformationType _information
ErrorVector _error
Protected Attributes inherited from g2o::OptimizableGraph::Edge
int _dimension
int _level
RobustKernel * _robustKernel
long long _internalId
std::vector< int > _cacheIds
std::vector< std::string > _parameterTypes
std::vector< Parameter ** > _parameters
std::vector< int > _parameterIds
Protected Attributes inherited from g2o::HyperGraph::Edge
VertexContainer _vertices
int _id
unique id
Protected Attributes inherited from g2o::HyperGraph::DataContainer
Data * _userData
Detailed Description
Definition at line 164 of file types_icp.h.
Constructor & Destructor Documentation
g2o::Edge_V_V_GICP::Edge_V_V_GICP () inline
Definition at line 168 of file types_icp.h.
 : pl_pl(false) {}
g2o::Edge_V_V_GICP::Edge_V_V_GICP (const Edge_V_V_GICP * e)
Definition at line 93 of file types_icp.cpp.
References g2o::BaseEdge< D, EdgeGICP >::_measurement, g2o::HyperGraph::Edge::_vertices, cov0, cov1, g2o::BaseEdge< D, E >::measurement(), g2o::EdgeGICP::normal0, g2o::EdgeGICP::normal1, pl_pl, g2o::EdgeGICP::pos0, g2o::EdgeGICP::pos1, g2o::EdgeGICP::R0, g2o::EdgeGICP::R1, and g2o::HyperGraph::Edge::vertex().
     : BaseBinaryEdge<3, EdgeGICP, VertexSE3, VertexSE3>()
   {
     // Temporary hack - TODO, sort out const-ness properly
     _vertices[0] = const_cast<HyperGraph::Vertex*> (e->vertex(0));
     _vertices[1] = const_cast<HyperGraph::Vertex*> (e->vertex(1));
     _measurement.pos0 = e->measurement().pos0;
     _measurement.pos1 = e->measurement().pos1;
     _measurement.normal0 = e->measurement().normal0;
     _measurement.normal1 = e->measurement().normal1;
     _measurement.R0 = e->measurement().R0;
     _measurement.R1 = e->measurement().R1;
     pl_pl = e->pl_pl;
     cov0 = e->cov0;
     cov1 = e->cov1;
     // TODO the robust kernel is not correctly copied
     //_robustKernel = e->_robustKernel;
   }
Member Function Documentation
void g2o::Edge_V_V_GICP::computeError () inline virtual
Implements g2o::OptimizableGraph::Edge.
Definition at line 180 of file types_icp.h.
References g2o::BaseVertex< D, T >::estimate(), and transform().
     {
       // from <ViewPoint> to <Point>
       const VertexSE3 *vp0 = static_cast<const VertexSE3*>(_vertices[0]);
       const VertexSE3 *vp1 = static_cast<const VertexSE3*>(_vertices[1]);
       // get vp1 point into vp0 frame
       // could be more efficient if we computed this transform just once
       Vector3D p1;
 #if 0
       if (_cnum >= 0 && 0)      // using global cache
         {
           if (_tainted[_cnum])  // set up transform
             {
               _transforms[_cnum] = vp0->estimate().inverse() * vp1->estimate();
               _tainted[_cnum] = 0;
               cout << _transforms[_cnum] << endl;
             }
           p1 = _transforms[_cnum].map(measurement().pos1); // do the transform
         }
       else
 #endif
         {
           p1 = vp1->estimate() * measurement().pos1;
           p1 = vp0->estimate().inverse() * p1;
         }
       //      cout << endl << "Error computation; points are: " << endl;
       //      cout << p0.transpose() << endl;
       //      cout << p1.transpose() << endl;
       // get their difference
       // this is simple Euclidean distance, for now
       _error = p1 - measurement().pos0;
 #if 0
       cout << "vp0" << endl << vp0->estimate() << endl;
       cout << "vp1" << endl << vp1->estimate() << endl;
       cout << "e Jac Xj" << endl <<  _jacobianOplusXj << endl << endl;
       cout << "e Jac Xi" << endl << _jacobianOplusXi << endl << endl;
 #endif
       if (!pl_pl) return;
       // re-define the information matrix
       // topLeftCorner<3,3>() is the rotation()
       const Matrix3D transform = ( vp0->estimate().inverse() *  vp1->estimate() ).matrix().topLeftCorner<3,3>();
       information() = ( cov0 + transform * cov1 * transform.transpose() ).inverse();
     }
void g2o::Edge_V_V_GICP::linearizeOplus () virtual
Linearizes the oplus operator in the vertex, and stores the result in temporary variables _jacobianOplusXi and _jacobianOplusXj
Reimplemented from g2o::BaseBinaryEdge< 3, EdgeGICP, VertexSE3, VertexSE3 >.
Definition at line 175 of file types_icp.cpp.
References g2o::BaseBinaryEdge< 3, EdgeGICP, VertexSE3, VertexSE3 >::_jacobianOplusXi, g2o::BaseBinaryEdge< 3, EdgeGICP, VertexSE3, VertexSE3 >::_jacobianOplusXj, g2o::HyperGraph::Edge::_vertices, dRidx, dRidy, dRidz, g2o::BaseVertex< D, T >::estimate(), g2o::OptimizableGraph::Vertex::fixed(), g2o::BaseEdge< D, EdgeGICP >::measurement(), and g2o::EdgeGICP::pos1.
   {
     VertexSE3* vp0 = static_cast<VertexSE3*>(_vertices[0]);
     VertexSE3* vp1 = static_cast<VertexSE3*>(_vertices[1]);
     // topLeftCorner<3,3>() is the rotation matrix
     Matrix3D R0T = vp0->estimate().matrix().topLeftCorner<3,3>().transpose();
     Vector3D p1 = measurement().pos1;
     // this could be more efficient
     if (!vp0->fixed())
       {
         Isometry3D T01 = vp0->estimate().inverse() *  vp1->estimate();
         Vector3D p1t = T01 * p1;
         _jacobianOplusXi.block<3,3>(0,0) = -Matrix3D::Identity();
         _jacobianOplusXi.block<3,1>(0,3) = dRidx*p1t;
         _jacobianOplusXi.block<3,1>(0,4) = dRidy*p1t;
         _jacobianOplusXi.block<3,1>(0,5) = dRidz*p1t;
       }
     if (!vp1->fixed())
       {
         Matrix3D R1 = vp1->estimate().matrix().topLeftCorner<3,3>();
         R0T = R0T*R1;
         _jacobianOplusXj.block<3,3>(0,0) = R0T;
         _jacobianOplusXj.block<3,1>(0,3) = R0T*dRidx.transpose()*p1;
         _jacobianOplusXj.block<3,1>(0,4) = R0T*dRidy.transpose()*p1;
         _jacobianOplusXj.block<3,1>(0,5) = R0T*dRidz.transpose()*p1;
       }
   }
bool g2o::Edge_V_V_GICP::read (std::istream & is) virtual
read the vertex from a stream, i.e., the internal state of the vertex
Implements g2o::OptimizableGraph::Edge.
Definition at line 126 of file types_icp.cpp.
References g2o::BaseEdge< D, EdgeGICP >::_measurement, g2o::BaseEdge< D, EdgeGICP >::information(), g2o::EdgeGICP::makeRot0(), g2o::BaseEdge< D, EdgeGICP >::measurement(), g2o::EdgeGICP::normal0, g2o::EdgeGICP::normal1, g2o::EdgeGICP::pos0, g2o::EdgeGICP::pos1, and g2o::EdgeGICP::R0.
   {
     // measured point and normal
     for (int i=0; i<3; i++)
       is >> _measurement.pos0[i];
     for (int i=0; i<3; i++)
       is >> _measurement.normal0[i];
     // measured point and normal
     for (int i=0; i<3; i++)
       is >> _measurement.pos1[i];
     for (int i=0; i<3; i++)
       is >> _measurement.normal1[i];
     // don't need this if we don't use it in error calculation (???)
     //    inverseMeasurement() = -measurement();
     _measurement.makeRot0();  // set up rotation matrices
     // GICP info matrices
     // point-plane only
     Matrix3D prec;
     double v = .01;
     prec << v, 0, 0,
             0, v, 0,
             0, 0, 1;
     const Matrix3D &R = measurement().R0; // plane of the point in vp0
     information() = R.transpose()*prec*R;
     //    information().setIdentity();
     //    setRobustKernel(true);
     //setHuberWidth(0.01);      // units? m?
     return true;
   }
bool g2o::Edge_V_V_GICP::write (std::ostream & os) const virtual
write the vertex to a stream
Implements g2o::OptimizableGraph::Edge.
Definition at line 208 of file types_icp.cpp.
References g2o::BaseEdge< D, EdgeGICP >::measurement(), g2o::EdgeGICP::normal0, g2o::EdgeGICP::normal1, g2o::EdgeGICP::pos0, and g2o::EdgeGICP::pos1.
   {
     // first point
     for (int i=0; i<3; i++)
       os  << measurement().pos0[i] << " ";
     for (int i=0; i<3; i++)
       os  << measurement().normal0[i] << " ";
     // second point
     for (int i=0; i<3; i++)
       os  << measurement().pos1[i] << " ";
     for (int i=0; i<3; i++)
       os  << measurement().normal1[i] << " ";
     return os.good();
   }
Member Data Documentation
Matrix3D g2o::Edge_V_V_GICP::cov0
Definition at line 173 of file types_icp.h.
Referenced by Edge_V_V_GICP().
Matrix3D g2o::Edge_V_V_GICP::cov1
Definition at line 173 of file types_icp.h.
Referenced by Edge_V_V_GICP().
Matrix3D g2o::Edge_V_V_GICP::dRidx static
Definition at line 238 of file types_icp.h.
Referenced by linearizeOplus().
Matrix3D g2o::Edge_V_V_GICP::dRidy static
Definition at line 239 of file types_icp.h.
Referenced by linearizeOplus().
Matrix3D g2o::Edge_V_V_GICP::dRidz static
Definition at line 240 of file types_icp.h.
Referenced by linearizeOplus().
g2o::Edge_V_V_GICP::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 167 of file types_icp.h.
bool g2o::Edge_V_V_GICP::pl_pl
Definition at line 172 of file types_icp.h.
Referenced by Edge_V_V_GICP().
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/icp/types_icp.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/icp/types_icp.cpp