g2o: g2o::tutorial::ParameterSE2Offset Class Reference
g2o::tutorial::ParameterSE2Offset Class Reference
#include <parameter_se2_offset.h>
Public Member Functions
ParameterSE2Offset ()
void setOffset (const SE2 &offset=SE2())
const SE2 & offset () const
const SE2 & inverseOffset () const
virtual bool read (std::istream &is)
read the data from a stream
virtual bool write (std::ostream &os) const
write the data to a stream
Public Member Functions inherited from g2o::Parameter
Parameter ()
virtual ~Parameter ()
int id () const
void setId (int id_)
virtual HyperGraph::HyperGraphElementType elementType () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Attributes
SE2 _offset
SE2 _inverseOffset
Protected Attributes inherited from g2o::Parameter
int _id
Detailed Description
Definition at line 37 of file parameter_se2_offset.h.
Constructor & Destructor Documentation
g2o::tutorial::ParameterSE2Offset::ParameterSE2Offset ()
Definition at line 34 of file parameter_se2_offset.cpp.
     {
     }
Member Function Documentation
const SE2& g2o::tutorial::ParameterSE2Offset::inverseOffset () const inline
Definition at line 46 of file parameter_se2_offset.h.
 { return _inverseOffset;}
const SE2& g2o::tutorial::ParameterSE2Offset::offset () const inline
Definition at line 45 of file parameter_se2_offset.h.
Referenced by setOffset().
 { return _offset;}
bool g2o::tutorial::ParameterSE2Offset::read (std::istream & is) virtual
read the data from a stream
Implements g2o::Parameter.
Definition at line 44 of file parameter_se2_offset.cpp.
References setOffset().
     {
       double x, y, th;
       is >> x >> y >> th;
       setOffset(SE2(x, y, th));
       return true;
     }
void g2o::tutorial::ParameterSE2Offset::setOffset (const SE2 & offset = SE2())
Definition at line 38 of file parameter_se2_offset.cpp.
References _inverseOffset, _offset, g2o::tutorial::SE2::inverse(), and offset().
Referenced by main(), and read().
     {
       _offset = offset;
       _inverseOffset = offset.inverse();
     }
bool g2o::tutorial::ParameterSE2Offset::write (std::ostream & os) const virtual
write the data to a stream
Implements g2o::Parameter.
Definition at line 52 of file parameter_se2_offset.cpp.
References _offset, g2o::tutorial::SE2::rotation(), and g2o::tutorial::SE2::translation().
     {
       os << _offset.translation().x() << " " << _offset.translation().y() << " " << _offset.rotation().angle();
       return os.good();
     }
Member Data Documentation
SE2 g2o::tutorial::ParameterSE2Offset::_inverseOffset protected
Definition at line 53 of file parameter_se2_offset.h.
Referenced by setOffset().
SE2 g2o::tutorial::ParameterSE2Offset::_offset protected
Definition at line 52 of file parameter_se2_offset.h.
Referenced by setOffset(), and write().
g2o::tutorial::ParameterSE2Offset::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 40 of file parameter_se2_offset.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/examples/tutorial_slam2d/parameter_se2_offset.h
/home/xuezhisd/CLionProjects/g2o/g2o/examples/tutorial_slam2d/parameter_se2_offset.cpp