g2o: g2o::RunG2OViewer Class Reference
g2o::RunG2OViewer Class Reference
wrapper for running the g2o viewer
#include <run_g2o_viewer.h>
Static Public Member Functions
static int run (int argc, char **argv, CommandArgs &arg)
Detailed Description
wrapper for running the g2o viewer
Definition at line 36 of file run_g2o_viewer.h.
Member Function Documentation
int g2o::RunG2OViewer::run (int argc, char ** argv, CommandArgs & arg) static
Definition at line 52 of file run_g2o_viewer.cpp.
References g2o::OptimizableGraph::addPreIterationAction(), g2o::GuiHyperGraphAction::dumpScreenshots, MainWindow::loadFromFile(), g2o::CommandArgs::paramLeftOver(), g2o::CommandArgs::parseArgs(), g2o::SparseOptimizer, MainWindow::updateDisplayedSolvers(), MainWindow::updateRobustKernels(), and g2o::GuiHyperGraphAction::viewer.
 {
   std::string inputFilename;
   arg.paramLeftOver("graph-input", inputFilename, "", "graph file which will be processed", true);
   arg.parseArgs(argc, argv);
   MainWindow mw;
   mw.updateDisplayedSolvers();
   mw.updateRobustKernels();
   mw.show();
   // redirect the output that normally goes to cerr to the textedit in the viewer
   StreamRedirect redirect(std::cerr, mw.plainTextEdit);
   // setting up the optimizer
   SparseOptimizer* optimizer = new SparseOptimizer();
   mw.viewer->graph = optimizer;
   // set up the GUI action
   GuiHyperGraphAction guiHyperGraphAction;
   guiHyperGraphAction.viewer = mw.viewer;
   //optimizer->addPostIterationAction(&guiHyperGraphAction);
   optimizer->addPreIterationAction(&guiHyperGraphAction);
   if (inputFilename.size() > 0) {
     mw.loadFromFile(QString::fromStdString(inputFilename));
   }
   QCoreApplication* myapp = QApplication::instance();
   while (mw.isVisible()) {
     guiHyperGraphAction.dumpScreenshots = mw.actionDump_Images->isChecked();
     if (myapp)
       myapp->processEvents();
     SleepThread::msleep(10);
   }
   delete optimizer;
   return 0;
 }
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_viewer/run_g2o_viewer.h
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_viewer/run_g2o_viewer.cpp