g2o: g2o::EstimatePropagatorCost Class Reference
g2o::EstimatePropagatorCost Class Reference
cost for traversing along active edges in the optimizer
#include <estimate_propagator.h>
Public Member Functions
EstimatePropagatorCost (SparseOptimizer *graph)
virtual double operator() (OptimizableGraph::Edge *edge, const OptimizableGraph::VertexSet &from, OptimizableGraph::Vertex *to_) const
virtual const char * name () const
Protected Attributes
SparseOptimizer * _graph
Detailed Description
cost for traversing along active edges in the optimizer
You may derive an own one, if necessary. The default is to return initialEstimatePossible(from, to) for the edge.
Definition at line 47 of file estimate_propagator.h.
Constructor & Destructor Documentation
g2o::EstimatePropagatorCost::EstimatePropagatorCost (SparseOptimizer * graph)
Definition at line 237 of file estimate_propagator.cpp.
                                                                         :
     _graph(graph)
   {
   }
Member Function Documentation
virtual const char* g2o::EstimatePropagatorCost::name () const inline virtual
Reimplemented in g2o::EstimatePropagatorCostOdometry.
Definition at line 51 of file estimate_propagator.h.
Referenced by g2o::SparseOptimizer::computeInitialGuess().
 { return "spanning tree";}
double g2o::EstimatePropagatorCost::operator() (OptimizableGraph::Edge * edge, const OptimizableGraph::VertexSet & from, OptimizableGraph::Vertex * to_) const virtual
Reimplemented in g2o::EstimatePropagatorCostOdometry.
Definition at line 242 of file estimate_propagator.cpp.
References _graph, g2o::SparseOptimizer::activeEdges(), g2o::SparseOptimizer::findActiveEdge(), and g2o::OptimizableGraph::Edge::initialEstimatePossible().
   {
     OptimizableGraph::Edge* e = dynamic_cast<OptimizableGraph::Edge*>(edge);
     OptimizableGraph::Vertex* to = dynamic_cast<OptimizableGraph::Vertex*>(to_);
     SparseOptimizer::EdgeContainer::const_iterator it = _graph->findActiveEdge(e);
     if (it == _graph->activeEdges().end()) // it has to be an active edge
       return std::numeric_limits<double>::max();
     return e->initialEstimatePossible(from, to);
   }
Member Data Documentation
SparseOptimizer* g2o::EstimatePropagatorCost::_graph protected
Definition at line 53 of file estimate_propagator.h.
Referenced by operator()(), and g2o::EstimatePropagatorCostOdometry::operator()().
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/core/estimate_propagator.h
/home/xuezhisd/CLionProjects/g2o/g2o/core/estimate_propagator.cpp