g2o: g2o::ParameterStereoCamera Class Reference
g2o::ParameterStereoCamera Class Reference
parameters for a camera
#include <parameter_stereo_camera.h>
Public Member Functions
ParameterStereoCamera ()
virtual bool read (std::istream &is)
read the data from a stream
virtual bool write (std::ostream &os) const
write the data to a stream
void setBaseline (double baseline_)
double baseline () const
Public Member Functions inherited from g2o::ParameterCamera
ParameterCamera ()
void setKcam (double fx, double fy, double cx, double cy)
void setOffset (const Isometry3D &offset_=Isometry3D::Identity())
const Matrix3D & Kcam () const
const Matrix3D & invKcam () const
const Matrix3D & Kcam_inverseOffsetR () const
Public Member Functions inherited from g2o::ParameterSE3Offset
ParameterSE3Offset ()
void setOffset (const Isometry3D &offset_=Isometry3D::Identity())
const Isometry3D & offset () const
rotation of the offset as 3x3 rotation matrix
const Isometry3D & inverseOffset () const
rotation of the inverse offset as 3x3 rotation matrix
Public Member Functions inherited from g2o::Parameter
Parameter ()
virtual ~Parameter ()
int id () const
void setId (int id_)
virtual HyperGraph::HyperGraphElementType elementType () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Public Attributes inherited from g2o::ParameterCamera
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Public Attributes inherited from g2o::ParameterSE3Offset
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Attributes
double _baseline
Protected Attributes inherited from g2o::ParameterCamera
Matrix3D _Kcam
Matrix3D _invKcam
Matrix3D _Kcam_inverseOffsetR
Protected Attributes inherited from g2o::ParameterSE3Offset
Isometry3D _offset
Isometry3D _inverseOffset
Protected Attributes inherited from g2o::Parameter
int _id
Detailed Description
parameters for a camera
Definition at line 38 of file parameter_stereo_camera.h.
Constructor & Destructor Documentation
g2o::ParameterStereoCamera::ParameterStereoCamera ()
Definition at line 39 of file parameter_stereo_camera.cpp.
{
     setBaseline(0.075);
   }
Member Function Documentation
double g2o::ParameterStereoCamera::baseline () const inline
Definition at line 47 of file parameter_stereo_camera.h.
 {return _baseline;}
bool g2o::ParameterStereoCamera::read (std::istream & is) virtual
read the data from a stream
Reimplemented from g2o::ParameterCamera.
Definition at line 43 of file parameter_stereo_camera.cpp.
References g2o::internal::fromVectorQT(), and g2o::internal::normalize().
{
     Vector7d off;
     for (int i=0; i<7; i++)
       is >> off[i];
     // normalize the quaternion to recover numerical precision lost by storing as human readable text
     Vector4D::MapType(off.data()+3).normalize();
     setOffset(internal::fromVectorQT(off));
     double fx,fy,cx,cy;
     is >> fx >> fy >> cx >> cy;
     setKcam(fx,fy,cx,cy);
     double baseline_;
     is >> baseline_;
     setBaseline(baseline_);
     return is.good();
   }
void g2o::ParameterStereoCamera::setBaseline (double baseline_) inline
Definition at line 46 of file parameter_stereo_camera.h.
 { _baseline = baseline_;}
bool g2o::ParameterStereoCamera::write (std::ostream & os) const virtual
write the data to a stream
Reimplemented from g2o::ParameterCamera.
Definition at line 59 of file parameter_stereo_camera.cpp.
References g2o::internal::toVectorQT().
{
     Vector7d off = internal::toVectorQT(_offset);
     for (int i=0; i<7; i++)
       os << off[i] << " ";
     os << _Kcam(0,0) << " ";
     os << _Kcam(1,1) << " ";
     os << _Kcam(0,2) << " ";
     os << _Kcam(1,2) << " ";
     os << baseline() << " ";
     return os.good();
   }
Member Data Documentation
double g2o::ParameterStereoCamera::_baseline protected
Definition at line 49 of file parameter_stereo_camera.h.
g2o::ParameterStereoCamera::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 40 of file parameter_stereo_camera.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam3d/parameter_stereo_camera.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam3d/parameter_stereo_camera.cpp