g2o: g2o::Slam2DViewer Class Reference
g2o::Slam2DViewer Class Reference
#include <slam2d_viewer.h>
Public Member Functions
Slam2DViewer (QWidget *parent=NULL, const QGLWidget *shareWidget=0, Qt::WFlags flags=0)
~Slam2DViewer ()
virtual void draw ()
void init ()
Public Attributes
SparseOptimizer * graph
bool drawCovariance
Detailed Description
Definition at line 28 of file slam2d_viewer.h.
Constructor & Destructor Documentation
g2o::Slam2DViewer::Slam2DViewer (QWidget * parent = NULL, const QGLWidget * shareWidget = 0, Qt::WFlags flags = 0)
Definition at line 131 of file slam2d_viewer.cpp.
                                                                                         :
   QGLViewer(parent, shareWidget, flags),
   graph(0), drawCovariance(false)
 {
 }
g2o::Slam2DViewer::~Slam2DViewer ()
Definition at line 137 of file slam2d_viewer.cpp.
 {
 }
Member Function Documentation
void g2o::Slam2DViewer::draw () virtual
Definition at line 141 of file slam2d_viewer.cpp.
References drawCovariance, g2o::BaseVertex< D, T >::estimate(), graph, and g2o::HyperGraph::vertices().
 {
   if (! graph)
     return;
   // drawing the graph
   glColor4f(0.00f, 0.67f, 1.00f, 1.f);
   glBegin(GL_TRIANGLES);
   for (SparseOptimizer::VertexIDMap::iterator it = graph->vertices().begin(); it != graph->vertices().end(); ++it) {
     VertexSE2* v = dynamic_cast<VertexSE2*>(it->second);
     if (v) {
       drawSE2(v);
     }
   }
   glEnd();
   glColor4f(1.00f, 0.67f, 0.00f, 1.f);
   glPointSize(2.f);
   glBegin(GL_POINTS);
   for (SparseOptimizer::VertexIDMap::iterator it = graph->vertices().begin(); it != graph->vertices().end(); ++it) {
     VertexPointXY* v = dynamic_cast<VertexPointXY*>(it->second);
     if (v) {
       glVertex3f(v->estimate()(0), v->estimate()(1), 0.f);
     }
   }
   glEnd();
   glPointSize(1.f);
   if (drawCovariance) {
     for (SparseOptimizer::VertexIDMap::iterator it = graph->vertices().begin(); it != graph->vertices().end(); ++it) {
       VertexSE2* v = dynamic_cast<VertexSE2*>(it->second);
       if (v) {
         // TODO
         //drawCov(v->estimate().translation(), v->uncertainty());
       }
     }
   }
 }
void g2o::Slam2DViewer::init ()
Definition at line 180 of file slam2d_viewer.cpp.
References g2o::types_icp::init().
 {
   QGLViewer::init();
   // some default settings i like
   glEnable(GL_LINE_SMOOTH);
   glEnable(GL_BLEND);
   glEnable(GL_DEPTH_TEST);
   glShadeModel(GL_SMOOTH);
   glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
   setAxisIsDrawn();
   // don't save state
   setStateFileName(QString::null);
   // mouse bindings
 #ifdef QGLVIEWER_DEPRECATED_MOUSEBINDING
   setMouseBinding(Qt::NoModifier, Qt::RightButton, CAMERA, ZOOM);
   setMouseBinding(Qt::NoModifier, Qt::MidButton, CAMERA, TRANSLATE);
 #else
   setMouseBinding(Qt::RightButton, CAMERA, ZOOM);
   setMouseBinding(Qt::MidButton, CAMERA, TRANSLATE);
 #endif
   // keyboard shortcuts
   setShortcut(CAMERA_MODE, 0);
   setShortcut(EXIT_VIEWER, 0);
   //setShortcut(SAVE_SCREENSHOT, 0);
   // replace camera
   qglviewer::Camera* oldcam = camera();
   qglviewer::Camera* cam = new StandardCamera();
   setCamera(cam);
   cam->setPosition(qglviewer::Vec(0., 0., 75.));
   cam->setUpVector(qglviewer::Vec(0., 1., 0.));
   cam->lookAt(qglviewer::Vec(0., 0., 0.));
   delete oldcam;
 }
Member Data Documentation
bool g2o::Slam2DViewer::drawCovariance
Definition at line 38 of file slam2d_viewer.h.
Referenced by draw().
SparseOptimizer* g2o::Slam2DViewer::graph
Definition at line 37 of file slam2d_viewer.h.
Referenced by draw().
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/examples/slam2d/slam2d_viewer.h
/home/xuezhisd/CLionProjects/g2o/g2o/examples/slam2d/slam2d_viewer.cpp