g2o: g2o::deprecated::ParameterSE3Offset Class Reference
g2o::deprecated::ParameterSE3Offset Class Reference
offset for an SE3
#include <parameter_se3_offset.h>
Public Member Functions
ParameterSE3Offset ()
virtual bool read (std::istream &is)
read the data from a stream
virtual bool write (std::ostream &os) const
write the data to a stream
void setOffset (const SE3Quat &offset_=SE3Quat())
const SE3Quat & offset () const
return the offset as SE3Quat
const Eigen::Isometry3d & offsetMatrix () const
rotation of the offset as 3x3 rotation matrix
const Eigen::Isometry3d & inverseOffsetMatrix () const
rotation of the inverse offset as 3x3 rotation matrix
Public Member Functions inherited from g2o::Parameter
Parameter ()
virtual ~Parameter ()
int id () const
void setId (int id_)
virtual HyperGraph::HyperGraphElementType elementType () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Attributes
SE3Quat _offset
Eigen::Isometry3d _offsetMatrix
Eigen::Isometry3d _inverseOffsetMatrix
Protected Attributes inherited from g2o::Parameter
int _id
Detailed Description
offset for an SE3
Definition at line 48 of file parameter_se3_offset.h.
Constructor & Destructor Documentation
g2o::deprecated::ParameterSE3Offset::ParameterSE3Offset ()
Definition at line 37 of file parameter_se3_offset.cpp.
{
     setOffset();
   }
Member Function Documentation
const Eigen::Isometry3d& g2o::deprecated::ParameterSE3Offset::inverseOffsetMatrix () const inline
rotation of the inverse offset as 3x3 rotation matrix
Definition at line 70 of file parameter_se3_offset.h.
Referenced by g2o::deprecated::EdgeSE3PointXYZ::linearizeOplus().
 { return _inverseOffsetMatrix;}
const SE3Quat& g2o::deprecated::ParameterSE3Offset::offset () const inline
return the offset as SE3Quat
Definition at line 64 of file parameter_se3_offset.h.
Referenced by g2o::deprecated::EdgeSE3Prior::initialEstimate(), g2o::deprecated::EdgeSE3Offset::initialEstimate(), g2o::deprecated::EdgeSE3Prior::linearizeOplus(), g2o::deprecated::EdgeSE3Offset::linearizeOplus(), g2o::deprecated::CacheSE3Offset::setOffsetParam(), and g2o::deprecated::CacheSE3Offset::updateImpl().
 { return _offset;}
const Eigen::Isometry3d& g2o::deprecated::ParameterSE3Offset::offsetMatrix () const inline
rotation of the offset as 3x3 rotation matrix
Definition at line 67 of file parameter_se3_offset.h.
Referenced by g2o::deprecated::EdgeSE3PointXYZDepth::initialEstimate(), g2o::deprecated::EdgeSE3PointXYZ::initialEstimate(), g2o::deprecated::EdgeSE3PointXYZDisparity::initialEstimate(), and g2o::deprecated::CacheCamera::updateImpl().
 { return _offsetMatrix;}
bool g2o::deprecated::ParameterSE3Offset::read (std::istream & is) virtual
read the data from a stream
Implements g2o::Parameter.
Reimplemented in g2o::deprecated::ParameterCamera.
Definition at line 48 of file parameter_se3_offset.cpp.
{
     Vector7d off;
     for (int i=0; i<7; i++) {
       is >> off[i];
       std::cerr << off[i] << " " ;
     }
     std::cerr <<  std::endl;
     setOffset(SE3Quat(off));
     return is.good();
   }
void g2o::deprecated::ParameterSE3Offset::setOffset (const SE3Quat & offset_ = SE3Quat())
update the offset to a new value. re-calculates the different representations, e.g., the rotation matrix
Definition at line 41 of file parameter_se3_offset.cpp.
References g2o::SE3Quat::rotation().
{
     _offset = offset_;
     _offsetMatrix= _offset.rotation().toRotationMatrix();
     _offsetMatrix.translation() = _offset.translation();
     _inverseOffsetMatrix = _offsetMatrix.inverse();
   }
bool g2o::deprecated::ParameterSE3Offset::write (std::ostream & os) const virtual
write the data to a stream
Implements g2o::Parameter.
Reimplemented in g2o::deprecated::ParameterCamera.
Definition at line 59 of file parameter_se3_offset.cpp.
{
     Vector7d off = _offset.toVector();
     for (int i=0; i<7; i++)
       os << off[i] << " ";
     return os.good();
   }
Member Data Documentation
Eigen::Isometry3d g2o::deprecated::ParameterSE3Offset::_inverseOffsetMatrix protected
Definition at line 75 of file parameter_se3_offset.h.
SE3Quat g2o::deprecated::ParameterSE3Offset::_offset protected
Definition at line 73 of file parameter_se3_offset.h.
Eigen::Isometry3d g2o::deprecated::ParameterSE3Offset::_offsetMatrix protected
Definition at line 74 of file parameter_se3_offset.h.
g2o::deprecated::ParameterSE3Offset::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 51 of file parameter_se3_offset.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/deprecated/slam3d/parameter_se3_offset.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/deprecated/slam3d/parameter_se3_offset.cpp