g2o: g2o::SE2 Class Reference
g2o::SE2 Class Reference
represent SE2
#include <se2.h>
Public Member Functions
SE2 ()
SE2 (const Isometry2D &iso)
SE2 (const Vector3D &v)
SE2 (double x, double y, double theta)
const Vector2D & translation () const
translational component
void setTranslation (const Vector2D &t_)
const Eigen::Rotation2Dd & rotation () const
rotational component
void setRotation (const Eigen::Rotation2Dd &R_)
SE2 operator* (const SE2 &tr2) const
concatenate two SE2 elements (motion composition)
SE2 & operator*= (const SE2 &tr2)
motion composition operator
Vector2D operator* (const Vector2D &v) const
project a 2D vector
SE2 inverse () const
invert :-)
double operator[] (int i) const
void fromVector (const Vector3D &v)
assign from a 3D vector (x, y, theta)
Vector3D toVector () const
convert to a 3D vector (x, y, theta)
Isometry2D toIsometry () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Attributes
Eigen::Rotation2Dd _R
Vector2D _t
Detailed Description
represent SE2
Definition at line 40 of file se2.h.
Constructor & Destructor Documentation
g2o::SE2::SE2 () inline
Definition at line 43 of file se2.h.
 :_R(0),_t(0,0){}
g2o::SE2::SE2 (const Isometry2D & iso) inline
Definition at line 45 of file se2.h.
                                 : _R(0), _t(iso.translation()){
         _R.fromRotationMatrix(iso.linear());
       }
g2o::SE2::SE2 (const Vector3D & v) inline
Definition at line 49 of file se2.h.
 :_R(v[2]),_t(v[0],v[1]){}
g2o::SE2::SE2 (double x, double y, double theta) inline
Definition at line 51 of file se2.h.
 :_R(theta),_t(x,y){}
Member Function Documentation
void g2o::SE2::fromVector (const Vector3D & v) inline
assign from a 3D vector (x, y, theta)
Definition at line 103 of file se2.h.
Referenced by g2o::EdgeSE2OdomDifferentialCalib::computeError(), g2o::EdgeSE2PureCalib::computeError(), EdgeCalib::computeError(), main(), g2o::tutorial::VertexSE2::read(), g2o::tutorial::EdgeSE2::read(), g2o::EdgeSE2SensorCalib::read(), and g2o::Gm2dlIO::readGm2dl().
{
         *this=SE2(v[0], v[1], v[2]);
       }
SE2 g2o::SE2::inverse () const inline
invert :-)
Definition at line 82 of file se2.h.
References _R, _t, and g2o::normalize_theta().
Referenced by g2o::addOdometryCalibLinksDifferential(), g2o::OnlineEdgeSE2::chi2(), g2o::EdgeSE2TwoPointsXY::computeError(), g2o::EdgeSE2LotsOfXY::computeError(), g2o::EdgeSE2PointXYBearing::computeError(), g2o::EdgeSE2PointXY::computeError(), g2o::EdgeSE2Line2D::computeError(), g2o::EdgeSE2OdomDifferentialCalib::computeError(), g2o::EdgeSE2::computeError(), g2o::tutorial::EdgeSE2::computeError(), g2o::EdgeSE2Segment2D::computeError(), g2o::EdgeSE2Segment2DLine::computeError(), g2o::EdgeSE2Segment2DPointLine::computeError(), g2o::EdgeSE2PureCalib::computeError(), EdgeCalib::computeError(), g2o::EdgeSE2SensorCalib::initialEstimate(), g2o::EdgeSE2Offset::initialEstimate(), main(), g2o::EdgeSE2WriteGnuplotAction::operator()(), g2o::RobotLaser::read(), g2o::EdgeSE2::read(), g2o::tutorial::EdgeSE2::read(), g2o::EdgeSE2SensorCalib::read(), g2o::EdgeSE2Prior::read(), g2o::Gm2dlIO::readGm2dl(), g2o::EdgeSE2SensorCalib::setMeasurement(), g2o::EdgeSE2::setMeasurement(), g2o::EdgeSE2Offset::setMeasurement(), g2o::EdgeSE2Prior::setMeasurement(), g2o::EdgeSE2Prior::setMeasurementData(), g2o::EdgeSE2TwoPointsXY::setMeasurementFromState(), g2o::EdgeSE2LotsOfXY::setMeasurementFromState(), g2o::EdgeSE2PointXYBearing::setMeasurementFromState(), g2o::EdgeSE2PointXY::setMeasurementFromState(), g2o::EdgeSE2Line2D::setMeasurementFromState(), g2o::EdgeSE2Segment2D::setMeasurementFromState(), g2o::EdgeSE2::setMeasurementFromState(), g2o::EdgeSE2Segment2DLine::setMeasurementFromState(), g2o::EdgeSE2Segment2DPointLine::setMeasurementFromState(), g2o::tutorial::CacheSE2Offset::updateImpl(), and g2o::CacheSE2Offset::updateImpl().
{
         SE2 ret;
         ret._R=_R.inverse();
         ret._R.angle()=normalize_theta(ret._R.angle());
 #ifdef _MSC_VER
         ret._t=ret._R*(Vector2D(_t*-1.));
 #else
         ret._t=ret._R*(_t*-1.);
 #endif
         return ret;
       }
SE2 g2o::SE2::operator* (const SE2 & tr2) const inline
concatenate two SE2 elements (motion composition)
Definition at line 62 of file se2.h.
{
         SE2 result(*this);
         result *= tr2;
         return result;
       }
Vector2D g2o::SE2::operator* (const Vector2D & v) const inline
project a 2D vector
Definition at line 77 of file se2.h.
{
         return _t+_R*v;
       }
SE2& g2o::SE2::operator*= (const SE2 & tr2) inline
motion composition operator
Definition at line 69 of file se2.h.
References _R, _t, and g2o::normalize_theta().
{
         _t+=_R*tr2._t;
         _R.angle()+=tr2._R.angle();
         _R.angle()=normalize_theta(_R.angle());
         return *this;
       }
double g2o::SE2::operator[] (int i) const inline
Definition at line 94 of file se2.h.
{
         assert (i>=0 && i<3);
         if (i<2)
           return _t(i);
         return _R.angle();
       }
const Eigen::Rotation2Dd& g2o::SE2::rotation () const inline
rotational component
Definition at line 58 of file se2.h.
Referenced by g2o::addOdometryCalibLinksDifferential(), g2o::ClosedFormCalibration::calibrate(), g2o::EdgeSE2Line2D::computeError(), g2o::EdgeSE2Offset::computeError(), g2o::EdgeSE2PointXYBearing::initialEstimate(), g2o::EdgeSE2Line2D::initialEstimate(), g2o::EdgeSE2LotsOfXY::linearizeOplus(), g2o::EdgeSE2PointXY::linearizeOplus(), g2o::EdgeSE2::linearizeOplus(), main(), g2o::EdgeSE2PointXYBearingWriteGnuplotAction::operator()(), g2o::EdgeSE2PointXYWriteGnuplotAction::operator()(), g2o::VertexSE2WriteGnuplotAction::operator()(), g2o::EdgeSE2WriteGnuplotAction::operator()(), g2o::operator*(), g2o::ThetaTreeAction::perform(), g2o::G2oSlamInterface::printVertex(), g2o::EdgeSE2Line2D::setMeasurementFromState(), g2o::RobotLaser::setOdomPose(), g2o::ParameterSE2Offset::setOffset(), g2o::SolverSLAM2DLinear::solveOrientation(), updateDisplay(), and g2o::CacheSE2Offset::updateImpl().
 {return _R;}
void g2o::SE2::setRotation (const Eigen::Rotation2Dd & R_) inline
Definition at line 59 of file se2.h.
Referenced by g2o::EdgeSE2PointXYBearing::initialEstimate(), and main().
 {_R=R_;}
void g2o::SE2::setTranslation (const Vector2D & t_) inline
Definition at line 55 of file se2.h.
Referenced by main().
 {_t=t_;}
Isometry2D g2o::SE2::toIsometry () const inline
Definition at line 112 of file se2.h.
{
         Isometry2D iso = Isometry2D::Identity();
         iso.linear() = _R.toRotationMatrix();
         iso.translation() = _t;
         return iso;
       }
Vector3D g2o::SE2::toVector () const inline
convert to a 3D vector (x, y, theta)
Definition at line 108 of file se2.h.
Referenced by g2o::OnlineEdgeSE2::chi2(), g2o::EdgeSE2SensorCalib::computeError(), g2o::EdgeSE2Prior::computeError(), g2o::EdgeSE2OdomDifferentialCalib::computeError(), g2o::EdgeSE2::computeError(), g2o::EdgeSE2PureCalib::computeError(), EdgeCalib::computeError(), gnudump_edges(), main(), g2o::RobotLaser::write(), g2o::ParameterSE2Offset::write(), g2o::EdgeSE2::write(), g2o::tutorial::VertexSE2::write(), g2o::tutorial::EdgeSE2::write(), g2o::EdgeSE2Prior::write(), g2o::EdgeSE2SensorCalib::write(), g2o::VertexSE2::write(), and g2o::Gm2dlIO::writeGm2dl().
{
         return Vector3D(_t.x(), _t.y(), _R.angle());
       }
const Vector2D& g2o::SE2::translation () const inline
translational component
Definition at line 54 of file se2.h.
Referenced by g2o::addOdometryCalibLinksDifferential(), g2o::ClosedFormCalibration::calibrate(), g2o::EdgeSE2Line2D::computeError(), g2o::EdgeSE2Offset::computeError(), g2o::EdgeSE2XYPrior::computeError(), g2o::SparseOptimizerOnline::gnuplotVisualization(), g2o::EdgeSE2Line2D::initialEstimate(), g2o::EdgeSE2LotsOfXY::linearizeOplus(), g2o::EdgeSE2PointXYOffset::linearizeOplus(), g2o::EdgeSE2PointXY::linearizeOplus(), g2o::EdgeSE2::linearizeOplus(), main(), g2o::EdgeSE2PointXYBearingWriteGnuplotAction::operator()(), g2o::EdgeSE2PointXYWriteGnuplotAction::operator()(), g2o::VertexSE2WriteGnuplotAction::operator()(), g2o::EdgeSE2WriteGnuplotAction::operator()(), g2o::operator*(), g2o::G2oSlamInterface::printVertex(), g2o::EdgeSE2Line2D::setMeasurementFromState(), g2o::RobotLaser::setOdomPose(), g2o::ParameterSE2Offset::setOffset(), updateDisplay(), g2o::CacheSE2Offset::updateImpl(), g2o::EdgeSE2OdomDifferentialCalib::write(), and g2o::EdgeSE2SensorCalib::write().
 {return _t;}
Member Data Documentation
Eigen::Rotation2Dd g2o::SE2::_R protected
Definition at line 120 of file se2.h.
Referenced by inverse(), and operator*=().
Vector2D g2o::SE2::_t protected
Definition at line 121 of file se2.h.
Referenced by inverse(), and operator*=().
g2o::SE2::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 42 of file se2.h.
The documentation for this class was generated from the following file:
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam2d/se2.h