g2o: g2o::AbstractOptimizationAlgorithmCreator Class Reference
g2o::AbstractOptimizationAlgorithmCreator Class Reference abstract
base for allocating an optimization algorithm
#include <optimization_algorithm_factory.h>
Public Member Functions
AbstractOptimizationAlgorithmCreator (const OptimizationAlgorithmProperty &p)
virtual ~AbstractOptimizationAlgorithmCreator ()
virtual OptimizationAlgorithm * construct ()=0
allocate a solver operating on optimizer, re-implement for your creator
const OptimizationAlgorithmProperty & property () const
return the properties of the solver
Protected Attributes
OptimizationAlgorithmProperty _property
Detailed Description
base for allocating an optimization algorithm
Allocating a solver for a given optimizer. The method construct() has to be implemented in your derived class to allocate the desired solver.
Definition at line 55 of file optimization_algorithm_factory.h.
Constructor & Destructor Documentation
g2o::AbstractOptimizationAlgorithmCreator::AbstractOptimizationAlgorithmCreator (const OptimizationAlgorithmProperty & p)
Definition at line 37 of file optimization_algorithm_factory.cpp.
References g2o::OptimizationAlgorithmFactory::factoryInstance.
                                                                                                                    :
     _property(p)
   {
   }
virtual g2o::AbstractOptimizationAlgorithmCreator::~AbstractOptimizationAlgorithmCreator () inline virtual
Definition at line 59 of file optimization_algorithm_factory.h.
 { }
Member Function Documentation
virtual OptimizationAlgorithm* g2o::AbstractOptimizationAlgorithmCreator::construct () pure virtual
allocate a solver operating on optimizer, re-implement for your creator
Implemented in g2o::CholmodSolverCreator, g2o::CSparseSolverCreator, g2o::EigenSolverCreator, g2o::DenseSolverCreator, g2o::PCGSolverCreator, g2o::SLAM2DLinearSolverCreator, and g2o::StructureOnlyCreator.
const OptimizationAlgorithmProperty& g2o::AbstractOptimizationAlgorithmCreator::property () const inline
return the properties of the solver
Definition at line 63 of file optimization_algorithm_factory.h.
Referenced by g2o::StructureOnlyCreator::construct(), g2o::SLAM2DLinearSolverCreator::construct(), g2o::RegisterOptimizationAlgorithmProxy::RegisterOptimizationAlgorithmProxy(), g2o::OptimizationAlgorithmFactory::registerSolver(), and g2o::OptimizationAlgorithmFactory::unregisterSolver().
 { return _property;}
Member Data Documentation
OptimizationAlgorithmProperty g2o::AbstractOptimizationAlgorithmCreator::_property protected
Definition at line 65 of file optimization_algorithm_factory.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/core/optimization_algorithm_factory.h
/home/xuezhisd/CLionProjects/g2o/g2o/core/optimization_algorithm_factory.cpp