g2o: g2o::VertexCam Class Reference
g2o::VertexCam Class Reference
SBACam Vertex, (x,y,z,qw,qx,qy,qz) the parameterization for the increments constructed is a 6d vector (x,y,z,qx,qy,qz) (note that we leave out the w part of the quaternion. qw is assumed to be positive, otherwise there is an ambiguity in qx,qy,qz as a rotation.
#include <types_sba.h>
Public Member Functions
VertexCam ()
virtual bool read (std::istream &is)
read the vertex from a stream, i.e., the internal state of the vertex
virtual bool write (std::ostream &os) const
write the vertex to a stream
virtual void setToOriginImpl ()
sets the node to the origin (used in the multilevel stuff)
virtual void setEstimate (const SBACam &cam)
virtual void oplusImpl (const double *update)
virtual bool setEstimateDataImpl (const double *est)
virtual bool getEstimateData (double *est) const
virtual int estimateDimension () const
virtual bool setMinimalEstimateDataImpl (const double *est)
virtual bool getMinimalEstimateData (double *est) const
virtual int minimalEstimateDimension () const
Public Member Functions inherited from g2o::BaseVertex< 6, SBACam >
BaseVertex ()
virtual const double & hessian (int i, int j) const
get the element from the hessian matrix
virtual double & hessian (int i, int j)
virtual double hessianDeterminant () const
virtual double * hessianData ()
virtual void mapHessianMemory (double *d)
virtual int copyB (double *b_) const
virtual const double & b (int i) const
get the b vector element
virtual double & b (int i)
Eigen::Matrix< double, D, 1, Eigen::ColMajor > & b ()
return right hand side b of the constructed linear system
const Eigen::Matrix< double, D, 1, Eigen::ColMajor > & b () const
virtual double * bData ()
return a pointer to the b vector associated with this vertex
virtual void clearQuadraticForm ()
virtual double solveDirect (double lambda=0)
HessianBlockType & A ()
return the hessian block associated with the vertex
const HessianBlockType & A () const
virtual void push ()
backup the position of the vertex to a stack
virtual void pop ()
restore the position of the vertex by retrieving the position from the stack
virtual void discardTop ()
pop the last element from the stack, without restoring the current estimate
virtual int stackSize () const
return the stack size
const EstimateType & estimate () const
return the current estimate of the vertex
void setEstimate (const EstimateType &et)
set the estimate for the vertex also calls updateCache()
Public Member Functions inherited from g2o::OptimizableGraph::Vertex
Vertex ()
virtual Vertex * clone () const
returns a deep copy of the current vertex
virtual ~Vertex ()
void setToOrigin ()
sets the node to the origin (used in the multilevel stuff)
bool setEstimateData (const double *estimate)
bool setEstimateData (const std::vector< double > &estimate)
virtual bool getEstimateData (std::vector< double > &estimate) const
bool setMinimalEstimateData (const double *estimate)
bool setMinimalEstimateData (const std::vector< double > &estimate)
virtual bool getMinimalEstimateData (std::vector< double > &estimate) const
void oplus (const double *v)
int hessianIndex () const
temporary index of this node in the parameter vector obtained from linearization
int G2O_ATTRIBUTE_DEPRECATED (tempIndex() const)
void setHessianIndex (int ti)
set the temporary index of the vertex in the parameter blocks
void G2O_ATTRIBUTE_DEPRECATED (setTempIndex(int ti))
bool fixed () const
true => this node is fixed during the optimization
void setFixed (bool fixed)
true => this node should be considered fixed during the optimization
bool marginalized () const
true => this node is marginalized out during the optimization
void setMarginalized (bool marginalized)
true => this node should be marginalized out during the optimization
int dimension () const
dimension of the estimated state belonging to this node
virtual void setId (int id)
sets the id of the node in the graph be sure that the graph keeps consistent after changing the id
void setColInHessian (int c)
set the row of this vertex in the Hessian
int colInHessian () const
get the row of this vertex in the Hessian
const OptimizableGraph * graph () const
OptimizableGraph * graph ()
void lockQuadraticForm ()
void unlockQuadraticForm ()
virtual void updateCache ()
CacheContainer * cacheContainer ()
Public Member Functions inherited from g2o::HyperGraph::Vertex
Vertex (int id=InvalidId)
creates a vertex having an ID specified by the argument
int id () const
returns the id
const EdgeSet & edges () const
returns the set of hyper-edges that are leaving/entering in this vertex
EdgeSet & edges ()
returns the set of hyper-edges that are leaving/entering in this vertex
virtual HyperGraphElementType elementType () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Member Functions inherited from g2o::HyperGraph::DataContainer
DataContainer ()
virtual ~DataContainer ()
const Data * userData () const
the user data associated with this vertex
Data * userData ()
void setUserData (Data *obs)
void addUserData (Data *obs)
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Additional Inherited Members
Public Types inherited from g2o::BaseVertex< 6, SBACam >
typedef SBACam EstimateType
typedef std::stack< EstimateType, std::vector< EstimateType, Eigen::aligned_allocator< EstimateType > > > BackupStackType
typedef Eigen::Map< Eigen::Matrix< double, D, D, Eigen::ColMajor >, Eigen::Matrix< double, D, D, Eigen::ColMajor >::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockType
Static Public Attributes inherited from g2o::BaseVertex< 6, SBACam >
static const int Dimension
dimension of the estimate (minimal) in the manifold space
Protected Attributes inherited from g2o::BaseVertex< 6, SBACam >
HessianBlockType _hessian
Eigen::Matrix< double, D, 1, Eigen::ColMajor > _b
EstimateType _estimate
BackupStackType _backup
Protected Attributes inherited from g2o::OptimizableGraph::Vertex
OptimizableGraph * _graph
Data * _userData
int _hessianIndex
bool _fixed
bool _marginalized
int _dimension
int _colInHessian
OpenMPMutex _quadraticFormMutex
CacheContainer * _cacheContainer
Protected Attributes inherited from g2o::HyperGraph::Vertex
int _id
EdgeSet _edges
Protected Attributes inherited from g2o::HyperGraph::DataContainer
Data * _userData
Detailed Description
SBACam Vertex, (x,y,z,qw,qx,qy,qz) the parameterization for the increments constructed is a 6d vector (x,y,z,qx,qy,qz) (note that we leave out the w part of the quaternion. qw is assumed to be positive, otherwise there is an ambiguity in qx,qy,qz as a rotation.
Definition at line 71 of file types_sba.h.
Constructor & Destructor Documentation
g2o::VertexCam::VertexCam ()
Definition at line 71 of file types_sba.cpp.
   {
   }
Member Function Documentation
virtual int g2o::VertexCam::estimateDimension () const inline virtual
returns the dimension of the extended representation used by get/setEstimate(double*) -1 if it is not supported
Reimplemented from g2o::OptimizableGraph::Vertex.
Definition at line 113 of file types_sba.h.
{
       return 7;
     }
virtual bool g2o::VertexCam::getEstimateData (double * estimate) const inline virtual
writes the estimater to an array of double
Returns
true on success
Reimplemented from g2o::OptimizableGraph::Vertex.
Definition at line 107 of file types_sba.h.
{
       Eigen::Map <Vector7d> v(est);
       v = estimate().toVector();
       return true;
     }
virtual bool g2o::VertexCam::getMinimalEstimateData (double * estimate) const inline virtual
writes the estimate to an array of double
Returns
true on success
Reimplemented from g2o::OptimizableGraph::Vertex.
Definition at line 123 of file types_sba.h.
{
       Eigen::Map<Vector6d> v(est);
       v = _estimate.toMinimalVector();
       return true;
     }
virtual int g2o::VertexCam::minimalEstimateDimension () const inline virtual
returns the dimension of the extended representation used by get/setEstimate(double*) -1 if it is not supported
Reimplemented from g2o::OptimizableGraph::Vertex.
Definition at line 129 of file types_sba.h.
{
       return 6;
     }
virtual void g2o::VertexCam::oplusImpl (const double * v) inline virtual
update the position of the node from the parameters in v. Implement in your class!
Implements g2o::OptimizableGraph::Vertex.
Definition at line 91 of file types_sba.h.
     {
       Eigen::Map<const Vector6d> v(update);
       _estimate.update(v);
       _estimate.setTransform();
       _estimate.setProjection();
       _estimate.setDr();
     }
bool g2o::VertexCam::read (std::istream & is) virtual
read the vertex from a stream, i.e., the internal state of the vertex
Implements g2o::OptimizableGraph::Vertex.
Definition at line 75 of file types_sba.cpp.
References g2o::SBACam::setKcam().
   {
     // first the position and orientation (vector3 and quaternion)
     Vector3D t;
     for (int i=0; i<3; i++){
       is >> t[i];
     }
     Vector4D rc;
     for (int i=0; i<4; i++) {
       is >> rc[i];
     }
     Quaterniond r;
     r.coeffs() = rc;
     r.normalize();
     // form the camera object
     SBACam cam(r,t);
     // now fx, fy, cx, cy, baseline
     double fx, fy, cx, cy, tx;
     // try to read one value
     is >>  fx;
     if (is.good()) {
       is >>  fy >> cx >> cy >> tx;
       cam.setKcam(fx,fy,cx,cy,tx);
     } else{
       is.clear();
       std::cerr << "cam not defined, using defaults" << std::endl;
       cam.setKcam(300,300,320,320,0.1);
     }
     // set the object
     setEstimate(cam);
     //    std::cout << cam << std::endl;
     return true;
   }
virtual void g2o::VertexCam::setEstimate (const SBACam & cam) inline virtual
Definition at line 84 of file types_sba.h.
References g2o::BaseVertex< D, T >::setEstimate().
Referenced by g2o::EdgeSBACam::initialEstimate(), and g2o::EdgeSBAScale::initialEstimate().
{
       BaseVertex<6, SBACam>::setEstimate(cam);
       _estimate.setTransform();
       _estimate.setProjection();
       _estimate.setDr();
     }
virtual bool g2o::VertexCam::setEstimateDataImpl (const double *) inline virtual
writes the estimater to an array of double
Returns
true on success
Reimplemented from g2o::OptimizableGraph::Vertex.
Definition at line 101 of file types_sba.h.
{
       Eigen::Map <const Vector7d> v(est);
       _estimate.fromVector(v);
       return true;
     }
virtual bool g2o::VertexCam::setMinimalEstimateDataImpl (const double *) inline virtual
sets the initial estimate from an array of double
Returns
true on success
Reimplemented from g2o::OptimizableGraph::Vertex.
Definition at line 117 of file types_sba.h.
{
       Eigen::Map<const Vector6d> v(est);
       _estimate.fromMinimalVector(v);
       return true;
     }
virtual void g2o::VertexCam::setToOriginImpl () inline virtual
sets the node to the origin (used in the multilevel stuff)
Implements g2o::OptimizableGraph::Vertex.
Definition at line 80 of file types_sba.h.
{
       _estimate = SBACam();
     }
bool g2o::VertexCam::write (std::ostream & os) const virtual
write the vertex to a stream
Implements g2o::OptimizableGraph::Vertex.
Definition at line 115 of file types_sba.cpp.
References g2o::SBACam::baseline, g2o::SBACam::Kcam, g2o::SE3Quat::rotation(), and g2o::SE3Quat::translation().
   {
     const SBACam &cam = estimate();
     // first the position and orientation (vector3 and quaternion)
     for (int i=0; i<3; i++)
       os << cam.translation()[i] << " ";
     for (int i=0; i<4; i++)
       os << cam.rotation().coeffs()[i] << " ";
     // now fx, fy, cx, cy, baseline
     os << cam.Kcam(0,0) << " ";
     os << cam.Kcam(1,1) << " ";
     os << cam.Kcam(0,2) << " ";
     os << cam.Kcam(1,2) << " ";
     os << cam.baseline << " ";
     return os.good();
   }
Member Data Documentation
g2o::VertexCam::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 74 of file types_sba.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/sba/types_sba.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/sba/types_sba.cpp