g2o: Sample Class Reference
Sample Class Reference
Static Public Member Functions
static int uniform (int from, int to)
static double uniform ()
static double gaussian (double sigma)
static int uniform (int from, int to)
static double uniform ()
static double gaussian (double sigma)
static int uniform (int from, int to)
static double uniform ()
static double gaussian (double sigma)
static int uniform (int from, int to)
static double uniform ()
static double gaussian (double sigma)
static int uniform (int from, int to)
static double uniform ()
static double gaussian (double sigma)
Static Private Attributes
static default_random_engine gen_real
static default_random_engine gen_int
Detailed Description
Definition at line 48 of file ba_demo.cpp.
Member Function Documentation
double Sample::gaussian (double sigma) static
Definition at line 77 of file ba_demo.cpp.
References gauss_rand().
Referenced by gauss_rand(), and main().
{
   return gauss_rand(0., sigma);
 }
static double Sample::gaussian (double sigma) static
static double Sample::gaussian (double sigma) static
static double Sample::gaussian (double sigma) static
static double Sample::gaussian (double sigma) static
static int Sample::uniform (int from, int to) static
static int Sample::uniform (int from, int to) static
int Sample::uniform (int from, int to) static
Definition at line 69 of file ba_demo.cpp.
References uniform_rand().
{
   return static_cast<int>(uniform_rand(from, to));
 }
static int Sample::uniform (int from, int to) static
double Sample::uniform () static
Definition at line 73 of file ba_demo.cpp.
References uniform_rand().
Referenced by gauss_rand(), and main().
                       {
   return uniform_rand(0., 1.);
 }
static double Sample::uniform () static
static double Sample::uniform () static
static double Sample::uniform () static
static int Sample::uniform (int from, int to) static
static double Sample::uniform () static
Member Data Documentation
default_random_engine Sample::gen_int static private
Definition at line 48 of file gicp_demo.cpp.
default_random_engine Sample::gen_real static private
Definition at line 47 of file gicp_demo.cpp.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/examples/ba/ba_demo.cpp
/home/xuezhisd/CLionProjects/g2o/g2o/examples/icp/gicp_demo.cpp
/home/xuezhisd/CLionProjects/g2o/g2o/examples/icp/gicp_sba_demo.cpp
/home/xuezhisd/CLionProjects/g2o/g2o/examples/ba_anchored_inverse_depth/ba_anchored_inverse_depth_demo.cpp
/home/xuezhisd/CLionProjects/g2o/g2o/examples/sba/sba_demo.cpp