g2o: g2o::VertexEllipse Class Reference
g2o::VertexEllipse Class Reference
string ellipse to be attached to a vertex
#include <vertex_ellipse.h>
Public Types
typedef std::vector< Vector2F, Eigen::aligned_allocator< Vector2F > > myVector2fVector
Public Member Functions
VertexEllipse ()
~VertexEllipse ()
virtual bool write (std::ostream &os) const
write the data to a stream
virtual bool read (std::istream &is)
read the data from a stream
const Matrix3F & covariance ()
void setCovariance (Matrix3F &c)
const Matrix2F & U ()
const Vector2F & singularValues ()
const myVector2fVector & matchingVertices ()
void addMatchingVertex (float x, float y)
void clearMatchingVertices ()
const std::vector< int > & matchingVerticesIDs ()
void addMatchingVertexID (int id)
void clearMatchingVerticesIDs ()
Public Member Functions inherited from g2o::RobotData
RobotData ()
virtual ~RobotData ()
double timestamp () const
void setTimestamp (double ts)
double loggerTimestamp () const
void setLoggerTimestamp (double ts)
const std::string & tag () const
void setTag (const std::string &tag)
const std::string & hostname () const
void setHostname (const std::string &hostname)
Public Member Functions inherited from g2o::HyperGraph::Data
Data ()
~Data ()
virtual HyperGraph::HyperGraphElementType elementType () const
const Data * next () const
Data * next ()
void setNext (Data *next_)
DataContainer * dataContainer ()
const DataContainer * dataContainer () const
void setDataContainer (DataContainer *dataContainer_)
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Member Functions
void _updateSVD () const
Protected Attributes
Matrix3F _covariance
Matrix2F _UMatrix
Vector2F _singularValues
std::vector< int > _matchingVerticesIDs
myVector2fVector _matchingVertices
Protected Attributes inherited from g2o::RobotData
double _timestamp
timestamp when the measurement was generated
double _loggerTimestamp
timestamp when the measurement was recorded
std::string _tag
string tag (FLASER, ROBOTLASER, ODOM..) of the line in the log
std::string _hostname
name of the computer/robot generating the data
Protected Attributes inherited from g2o::HyperGraph::Data
Data * _next
DataContainer * _dataContainer
Detailed Description
string ellipse to be attached to a vertex
Definition at line 39 of file vertex_ellipse.h.
Member Typedef Documentation
typedef std::vector<Vector2F, Eigen::aligned_allocator<Vector2F> > g2o::VertexEllipse::myVector2fVector
Definition at line 42 of file vertex_ellipse.h.
Constructor & Destructor Documentation
g2o::VertexEllipse::VertexEllipse ()
Definition at line 45 of file vertex_ellipse.cpp.
References _covariance, _singularValues, and _UMatrix.
                                : RobotData()
   {
     _covariance = Matrix3F::Zero();
     _UMatrix = Matrix2F::Zero();
     _singularValues = Vector2F::Zero();
   }
g2o::VertexEllipse::~VertexEllipse ()
Definition at line 52 of file vertex_ellipse.cpp.
   {
   }
Member Function Documentation
void g2o::VertexEllipse::_updateSVD () const protected
Definition at line 56 of file vertex_ellipse.cpp.
References _covariance, _singularValues, and _UMatrix.
Referenced by read().
{
     Eigen::SelfAdjointEigenSolver<Matrix2F> eigenSolver(_covariance.block<2,2>(0,0));
     _UMatrix = eigenSolver.eigenvectors();
     _singularValues = eigenSolver.eigenvalues();
   }
void g2o::VertexEllipse::addMatchingVertex (float x, float y) inline
Definition at line 57 of file vertex_ellipse.h.
Referenced by read().
{
         Vector2F v(x,y);
         _matchingVertices.push_back(v);
       }
void g2o::VertexEllipse::addMatchingVertexID (int id) inline
Definition at line 65 of file vertex_ellipse.h.
{
         _matchingVerticesIDs.push_back(id);
       }
void g2o::VertexEllipse::clearMatchingVertices () inline
Definition at line 62 of file vertex_ellipse.h.
 {_matchingVertices.clear();}
void g2o::VertexEllipse::clearMatchingVerticesIDs () inline
Definition at line 68 of file vertex_ellipse.h.
 {_matchingVerticesIDs.clear();}
const Matrix3F& g2o::VertexEllipse::covariance () inline
Definition at line 51 of file vertex_ellipse.h.
Referenced by write().
 {return _covariance;}
const myVector2fVector& g2o::VertexEllipse::matchingVertices () inline
Definition at line 56 of file vertex_ellipse.h.
Referenced by write().
 {return _matchingVertices;}
const std::vector<int>& g2o::VertexEllipse::matchingVerticesIDs () inline
Definition at line 64 of file vertex_ellipse.h.
 {return _matchingVerticesIDs;}
bool g2o::VertexEllipse::read (std::istream & is) virtual
read the data from a stream
Implements g2o::HyperGraph::Data.
Definition at line 63 of file vertex_ellipse.cpp.
References _covariance, _updateSVD(), and addMatchingVertex().
   {
     float cxx, cxy, cxt, cyy, cyt, ctt;
     is >> cxx >> cxy >> cxt >> cyy >> cyt >> ctt;
     _covariance(0,0) = cxx;
     _covariance(0,1) = cxy;
     _covariance(0,2) = cxt;
     _covariance(1,0) = cxy;
     _covariance(1,1) = cyy;
     _covariance(1,2) = cyt;
     _covariance(2,0) = cxt;
     _covariance(2,1) = cyt;
     _covariance(2,2) = ctt;
     _updateSVD();
     int size;
     is >> size;
     for (int i =0; i<size; i++){
       float x, y;
       is >> x >> y;
       addMatchingVertex(x,y);
     }
     return true;
   }
void g2o::VertexEllipse::setCovariance (Matrix3F & c) inline
Definition at line 52 of file vertex_ellipse.h.
 { _covariance = c; _updateSVD();}
const Vector2F& g2o::VertexEllipse::singularValues () inline
Definition at line 54 of file vertex_ellipse.h.
Referenced by write().
 {return _singularValues;}
const Matrix2F& g2o::VertexEllipse::U () inline
Definition at line 53 of file vertex_ellipse.h.
Referenced by write().
 {return _UMatrix;}
bool g2o::VertexEllipse::write (std::ostream & os) const virtual
write the data to a stream
Implements g2o::HyperGraph::Data.
Definition at line 90 of file vertex_ellipse.cpp.
References _covariance, _matchingVertices, covariance(), M_PI, matchingVertices(), g2o::DrawAction::refreshPropertyPtrs(), singularValues(), and U().
   {
     os << _covariance(0,0) << " " << _covariance(0,1) << " " << _covariance(0,2) << " "
        << _covariance(1,1) << " " << _covariance(1,2) << " " << _covariance(2,2) << " ";
     os << _matchingVertices.size() << " " ;
     for (size_t i=0 ; i< _matchingVertices.size(); i++){
       os << _matchingVertices[i].x() << " " << _matchingVertices[i].y() << " ";
     }
     return os.good();
   }
Member Data Documentation
Matrix3F g2o::VertexEllipse::_covariance protected
Definition at line 72 of file vertex_ellipse.h.
Referenced by _updateSVD(), read(), VertexEllipse(), and write().
myVector2fVector g2o::VertexEllipse::_matchingVertices protected
Definition at line 76 of file vertex_ellipse.h.
Referenced by write().
std::vector<int> g2o::VertexEllipse::_matchingVerticesIDs protected
Definition at line 75 of file vertex_ellipse.h.
Vector2F g2o::VertexEllipse::_singularValues mutable protected
Definition at line 74 of file vertex_ellipse.h.
Referenced by _updateSVD(), and VertexEllipse().
Matrix2F g2o::VertexEllipse::_UMatrix mutable protected
Definition at line 73 of file vertex_ellipse.h.
Referenced by _updateSVD(), and VertexEllipse().
g2o::VertexEllipse::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 44 of file vertex_ellipse.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/data/vertex_ellipse.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/data/vertex_ellipse.cpp