g2o: g2o::ParameterSE2Offset Class Reference
g2o::ParameterSE2Offset Class Reference
offset for an SE2
#include <parameter_se2_offset.h>
Public Member Functions
ParameterSE2Offset ()
virtual bool read (std::istream &is)
read the data from a stream
virtual bool write (std::ostream &os) const
write the data to a stream
void setOffset (const SE2 &offset_=SE2())
const SE2 & offset () const
const Isometry2D & offsetMatrix () const
rotation of the offset as 2x2 rotation matrix
const Isometry2D & inverseOffsetMatrix () const
rotation of the inverse offset as 2x2 rotation matrix
Public Member Functions inherited from g2o::Parameter
Parameter ()
virtual ~Parameter ()
int id () const
void setId (int id_)
virtual HyperGraph::HyperGraphElementType elementType () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Attributes
SE2 _offset
Isometry2D _offsetMatrix
Isometry2D _inverseOffsetMatrix
Protected Attributes inherited from g2o::Parameter
int _id
Detailed Description
offset for an SE2
Definition at line 46 of file parameter_se2_offset.h.
Constructor & Destructor Documentation
g2o::ParameterSE2Offset::ParameterSE2Offset ()
Definition at line 36 of file parameter_se2_offset.cpp.
References setOffset().
{
     setOffset();
   }
Member Function Documentation
const Isometry2D& g2o::ParameterSE2Offset::inverseOffsetMatrix () const inline
rotation of the inverse offset as 2x2 rotation matrix
Definition at line 67 of file parameter_se2_offset.h.
 { return _inverseOffsetMatrix;}
const SE2& g2o::ParameterSE2Offset::offset () const inline
Definition at line 61 of file parameter_se2_offset.h.
Referenced by g2o::EdgeSE2Offset::initialEstimate(), g2o::SensorPointXYOffset::sense(), and g2o::CacheSE2Offset::updateImpl().
 { return _offset;}
const Isometry2D& g2o::ParameterSE2Offset::offsetMatrix () const inline
rotation of the offset as 2x2 rotation matrix
Definition at line 64 of file parameter_se2_offset.h.
Referenced by g2o::EdgeSE2PointXYOffset::initialEstimate().
 { return _offsetMatrix;}
bool g2o::ParameterSE2Offset::read (std::istream & is) virtual
read the data from a stream
Implements g2o::Parameter.
Definition at line 47 of file parameter_se2_offset.cpp.
References setOffset().
{
     Vector3D off;
     for (int i=0; i<3; i++) {
       is >> off[i];
       std::cerr << off[i] << " " ;
     }
     std::cerr <<  std::endl;
     setOffset(SE2(off));
     return is.good() || is.eof();
   }
void g2o::ParameterSE2Offset::setOffset (const SE2 & offset_ = SE2())
update the offset to a new value. re-calculates the different representations, e.g., the rotation matrix
Definition at line 40 of file parameter_se2_offset.cpp.
References _inverseOffsetMatrix, _offset, _offsetMatrix, g2o::SE2::rotation(), and g2o::SE2::translation().
Referenced by ParameterSE2Offset(), and read().
{
     _offset = offset_;
     _offsetMatrix= _offset.rotation().toRotationMatrix();
     _offsetMatrix.translation() = _offset.translation();
     _inverseOffsetMatrix = _offsetMatrix.inverse();
   }
bool g2o::ParameterSE2Offset::write (std::ostream & os) const virtual
write the data to a stream
Implements g2o::Parameter.
Definition at line 58 of file parameter_se2_offset.cpp.
References _offset, and g2o::SE2::toVector().
{
     Vector3D off = _offset.toVector();
     for (int i=0; i<3; i++)
       os << off[i] << " ";
     return os.good();
   }
Member Data Documentation
Isometry2D g2o::ParameterSE2Offset::_inverseOffsetMatrix protected
Definition at line 72 of file parameter_se2_offset.h.
Referenced by setOffset().
SE2 g2o::ParameterSE2Offset::_offset protected
Definition at line 70 of file parameter_se2_offset.h.
Referenced by setOffset(), and write().
Isometry2D g2o::ParameterSE2Offset::_offsetMatrix protected
Definition at line 71 of file parameter_se2_offset.h.
Referenced by setOffset().
g2o::ParameterSE2Offset::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 49 of file parameter_se2_offset.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam2d/parameter_se2_offset.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam2d/parameter_se2_offset.cpp