g2o: g2o::World Class Reference
g2o::World Class Reference
#include <simulator.h>
Public Member Functions
World (OptimizableGraph *graph_)
OptimizableGraph * graph ()
bool addRobot (BaseRobot *robot)
bool addWorldObject (BaseWorldObject *worldObject)
bool addParameter (Parameter *p)
std::set< BaseWorldObject * > & objects ()
std::set< BaseRobot * > & robots ()
Protected Attributes
std::set< BaseWorldObject * > _objects
std::set< BaseRobot * > _robots
OptimizableGraph * _graph
int _runningId
int _paramId
Detailed Description
Definition at line 275 of file simulator.h.
Constructor & Destructor Documentation
g2o::World::World (OptimizableGraph * graph_) inline
Definition at line 278 of file simulator.h.
 {_graph = graph_; _runningId=0; _paramId=0;}
Member Function Documentation
bool g2o::World::addParameter (Parameter * p)
Definition at line 102 of file simulator.cpp.
References graph, and g2o::Parameter::setId().
Referenced by g2o::SensorPointXYZ::addParameters(), g2o::SensorSE3Prior::addParameters(), g2o::SensorPointXYZDepth::addParameters(), g2o::SensorPointXYZDisparity::addParameters(), g2o::SensorPose3DOffset::addParameters(), and g2o::SensorPointXYOffset::addParameters().
{
     if ( !graph())
       return false;
     param->setId(_paramId);
     graph()->addParameter(param);
     _paramId++;
     return true;
   }
bool g2o::World::addRobot (BaseRobot * robot)
Definition at line 82 of file simulator.cpp.
References g2o::BaseRobot::setWorld().
Referenced by main().
{
     std::pair<std::set<BaseRobot*>::iterator, bool> result=_robots.insert(robot);
     if (result.second){
       robot->setWorld(this);
     }
     return result.second;
   }
bool g2o::World::addWorldObject (BaseWorldObject * worldObject)
Definition at line 90 of file simulator.cpp.
References graph, and g2o::BaseWorldObject::vertex().
Referenced by main().
{
     std::pair<std::set<BaseWorldObject*>::iterator, bool> result=_objects.insert(object);
     if (result.second){
       object->setWorld(this);
     }
     if (graph() && object->vertex()){
       object->vertex()->setId(_runningId++);
       graph()->addVertex(object->vertex());
     }
     return result.second;
   }
OptimizableGraph* g2o::World::graph () inline
Definition at line 279 of file simulator.h.
 {return _graph;}
std::set<BaseWorldObject*>& g2o::World::objects () inline
Definition at line 284 of file simulator.h.
Referenced by g2o::SensorPose3DOffset::sense(), g2o::SensorPose3D::sense(), g2o::SensorPointXY::sense(), g2o::SensorPointXYZ::sense(), g2o::SensorPointXYZDepth::sense(), g2o::SensorPose2D::sense(), g2o::SensorPointXYOffset::sense(), g2o::SensorPointXYZDisparity::sense(), g2o::SensorSegment2D::sense(), g2o::SensorSegment2DLine::sense(), g2o::SensorPointXYBearing::sense(), and g2o::SensorSegment2DPointLine::sense().
 {return _objects;}
std::set<BaseRobot*>& g2o::World::robots () inline
Definition at line 285 of file simulator.h.
 {return _robots; }
Member Data Documentation
OptimizableGraph* g2o::World::_graph protected
Definition at line 289 of file simulator.h.
std::set<BaseWorldObject*> g2o::World::_objects protected
Definition at line 287 of file simulator.h.
int g2o::World::_paramId protected
Definition at line 291 of file simulator.h.
std::set<BaseRobot*> g2o::World::_robots protected
Definition at line 288 of file simulator.h.
int g2o::World::_runningId protected
Definition at line 290 of file simulator.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_simulator/simulator.h
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_simulator/simulator.cpp