g2o: SlamParser::AbstractSlamInterface Class Reference
SlamParser::AbstractSlamInterface Class Reference abstract
interface for communicating with the SLAM algorithm
#include <abstract_slam_interface.h>
Public Member Functions
virtual bool addNode (const std::string &tag, int id, int dimension, const std::vector< double > &values)=0
virtual bool addEdge (const std::string &tag, int id, int dimension, int v1, int v2, const std::vector< double > &measurement, const std::vector< double > &information)=0
virtual bool fixNode (const std::vector< int > &nodes)=0
virtual bool queryState (const std::vector< int > &nodes)=0
virtual bool solveState ()=0
Detailed Description
interface for communicating with the SLAM algorithm
This interface allows the parser to communicate with the SLAM algorithm.
Definition at line 40 of file abstract_slam_interface.h.
Member Function Documentation
virtual bool SlamParser::AbstractSlamInterface::addEdge (const std::string & tag, int id, int dimension, int v1, int v2, const std::vector< double > & measurement, const std::vector< double > & information) pure virtual
adding an edge to the SLAM engine.
Parameters
tag the tag specifying the type of the vertex
id the unique id of the edge.
dimension the dimension of the edge.
v1 the unique id of the edge of the first vertex
v2 the unique id of the edge of the second vertex
measurement the measurement of the constraint
information the information matrix (inverse of the covariance) representing the uncertainty of the measurement (row-major upper triangular and diagonal)
Returns
true, if adding was successful
Implemented in g2o::G2oSlamInterface, and ExampleSlamInterface.
Referenced by SlamParser::SlamContextInterface::process().
virtual bool SlamParser::AbstractSlamInterface::addNode (const std::string & tag, int id, int dimension, const std::vector< double > & values) pure virtual
adding a node to the SLAM engine.
Parameters
tag the tag specifying the type of the vertex
id the unique id of the node.
dimension the dimension of the node.
values the pose of the node, may be empty (i.e., the engine should initialize the node itself)
Returns
true, if adding was successful
Implemented in g2o::G2oSlamInterface, and ExampleSlamInterface.
Referenced by SlamParser::SlamContextInterface::process().
virtual bool SlamParser::AbstractSlamInterface::fixNode (const std::vector< int > & nodes) pure virtual
set some nodes to a fixed position
Parameters
nodes the list of vertex IDs to fix
Returns
true, if successful
Implemented in g2o::G2oSlamInterface, and ExampleSlamInterface.
Referenced by SlamParser::SlamContextInterface::process().
virtual bool SlamParser::AbstractSlamInterface::queryState (const std::vector< int > & nodes) pure virtual
Ask the SLAM engine to print the current estimate of the variables
Parameters
nodes the list of vertex IDs to print, if empty print all variables
Returns
true, if successful
Implemented in g2o::G2oSlamInterface, and ExampleSlamInterface.
Referenced by SlamParser::SlamContextInterface::process().
virtual bool SlamParser::AbstractSlamInterface::solveState () pure virtual
ask the engine to solve
Returns
true, if successful
Implemented in g2o::G2oSlamInterface, and ExampleSlamInterface.
Referenced by SlamParser::SlamContextInterface::process().
The documentation for this class was generated from the following file:
/home/xuezhisd/CLionProjects/g2o/g2o/examples/interactive_slam/slam_parser/interface/abstract_slam_interface.h