g2o: g2o::VertexSegment2D Class Reference
g2o::VertexSegment2D Class Reference
#include <vertex_segment2d.h>
Public Member Functions
VertexSegment2D ()
Vector2D estimateP1 () const
Vector2D estimateP2 () const
void setEstimateP1 (const Vector2D &p1)
void setEstimateP2 (const Vector2D &p2)
virtual void setToOriginImpl ()
sets the node to the origin (used in the multilevel stuff)
virtual bool setEstimateDataImpl (const double *est)
virtual bool getEstimateData (double *est) const
virtual int estimateDimension () const
virtual bool setMinimalEstimateDataImpl (const double *est)
virtual bool getMinimalEstimateData (double *est) const
virtual int minimalEstimateDimension () const
virtual void oplusImpl (const double *update)
virtual bool read (std::istream &is)
read the vertex from a stream, i.e., the internal state of the vertex
virtual bool write (std::ostream &os) const
write the vertex to a stream
Public Member Functions inherited from g2o::BaseVertex< 4, Vector4D >
BaseVertex ()
virtual const double & hessian (int i, int j) const
get the element from the hessian matrix
virtual double & hessian (int i, int j)
virtual double hessianDeterminant () const
virtual double * hessianData ()
virtual void mapHessianMemory (double *d)
virtual int copyB (double *b_) const
virtual const double & b (int i) const
get the b vector element
virtual double & b (int i)
Eigen::Matrix< double, D, 1, Eigen::ColMajor > & b ()
return right hand side b of the constructed linear system
const Eigen::Matrix< double, D, 1, Eigen::ColMajor > & b () const
virtual double * bData ()
return a pointer to the b vector associated with this vertex
virtual void clearQuadraticForm ()
virtual double solveDirect (double lambda=0)
HessianBlockType & A ()
return the hessian block associated with the vertex
const HessianBlockType & A () const
virtual void push ()
backup the position of the vertex to a stack
virtual void pop ()
restore the position of the vertex by retrieving the position from the stack
virtual void discardTop ()
pop the last element from the stack, without restoring the current estimate
virtual int stackSize () const
return the stack size
const EstimateType & estimate () const
return the current estimate of the vertex
void setEstimate (const EstimateType &et)
set the estimate for the vertex also calls updateCache()
Public Member Functions inherited from g2o::OptimizableGraph::Vertex
Vertex ()
virtual Vertex * clone () const
returns a deep copy of the current vertex
virtual ~Vertex ()
void setToOrigin ()
sets the node to the origin (used in the multilevel stuff)
bool setEstimateData (const double *estimate)
bool setEstimateData (const std::vector< double > &estimate)
virtual bool getEstimateData (std::vector< double > &estimate) const
bool setMinimalEstimateData (const double *estimate)
bool setMinimalEstimateData (const std::vector< double > &estimate)
virtual bool getMinimalEstimateData (std::vector< double > &estimate) const
void oplus (const double *v)
int hessianIndex () const
temporary index of this node in the parameter vector obtained from linearization
int G2O_ATTRIBUTE_DEPRECATED (tempIndex() const)
void setHessianIndex (int ti)
set the temporary index of the vertex in the parameter blocks
void G2O_ATTRIBUTE_DEPRECATED (setTempIndex(int ti))
bool fixed () const
true => this node is fixed during the optimization
void setFixed (bool fixed)
true => this node should be considered fixed during the optimization
bool marginalized () const
true => this node is marginalized out during the optimization
void setMarginalized (bool marginalized)
true => this node should be marginalized out during the optimization
int dimension () const
dimension of the estimated state belonging to this node
virtual void setId (int id)
sets the id of the node in the graph be sure that the graph keeps consistent after changing the id
void setColInHessian (int c)
set the row of this vertex in the Hessian
int colInHessian () const
get the row of this vertex in the Hessian
const OptimizableGraph * graph () const
OptimizableGraph * graph ()
void lockQuadraticForm ()
void unlockQuadraticForm ()
virtual void updateCache ()
CacheContainer * cacheContainer ()
Public Member Functions inherited from g2o::HyperGraph::Vertex
Vertex (int id=InvalidId)
creates a vertex having an ID specified by the argument
int id () const
returns the id
const EdgeSet & edges () const
returns the set of hyper-edges that are leaving/entering in this vertex
EdgeSet & edges ()
returns the set of hyper-edges that are leaving/entering in this vertex
virtual HyperGraphElementType elementType () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Member Functions inherited from g2o::HyperGraph::DataContainer
DataContainer ()
virtual ~DataContainer ()
const Data * userData () const
the user data associated with this vertex
Data * userData ()
void setUserData (Data *obs)
void addUserData (Data *obs)
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Additional Inherited Members
Public Types inherited from g2o::BaseVertex< 4, Vector4D >
typedef Vector4D EstimateType
typedef std::stack< EstimateType, std::vector< EstimateType, Eigen::aligned_allocator< EstimateType > > > BackupStackType
typedef Eigen::Map< Eigen::Matrix< double, D, D, Eigen::ColMajor >, Eigen::Matrix< double, D, D, Eigen::ColMajor >::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockType
Static Public Attributes inherited from g2o::BaseVertex< 4, Vector4D >
static const int Dimension
dimension of the estimate (minimal) in the manifold space
Protected Attributes inherited from g2o::BaseVertex< 4, Vector4D >
HessianBlockType _hessian
Eigen::Matrix< double, D, 1, Eigen::ColMajor > _b
EstimateType _estimate
BackupStackType _backup
Protected Attributes inherited from g2o::OptimizableGraph::Vertex
OptimizableGraph * _graph
Data * _userData
int _hessianIndex
bool _fixed
bool _marginalized
int _dimension
int _colInHessian
OpenMPMutex _quadraticFormMutex
CacheContainer * _cacheContainer
Protected Attributes inherited from g2o::HyperGraph::Vertex
int _id
EdgeSet _edges
Protected Attributes inherited from g2o::HyperGraph::DataContainer
Data * _userData
Detailed Description
Definition at line 39 of file vertex_segment2d.h.
Constructor & Destructor Documentation
g2o::VertexSegment2D::VertexSegment2D ()
Definition at line 43 of file vertex_segment2d.cpp.
References g2o::BaseVertex< 4, Vector4D >::_estimate.
                                    :
     BaseVertex<4, Vector4D>()
   {
     _estimate.setZero();
   }
Member Function Documentation
virtual int g2o::VertexSegment2D::estimateDimension () const inline virtual
returns the dimension of the extended representation used by get/setEstimate(double*) -1 if it is not supported
Reimplemented from g2o::OptimizableGraph::Vertex.
Definition at line 66 of file vertex_segment2d.h.
{
         return 4;
       }
Vector2D g2o::VertexSegment2D::estimateP1 () const inline
Definition at line 45 of file vertex_segment2d.h.
Referenced by g2o::EdgeSE2Segment2D::computeError(), g2o::EdgeSE2Segment2DLine::computeError(), g2o::EdgeSE2Segment2DPointLine::computeError(), LineInfo::LineInfo(), main(), g2o::VertexSegment2DWriteGnuplotAction::operator()(), g2o::EdgeSE2Segment2D::setMeasurementFromState(), g2o::EdgeSE2Segment2DLine::setMeasurementFromState(), and g2o::EdgeSE2Segment2DPointLine::setMeasurementFromState().
 { return Eigen::Map<const Vector2D>(&(_estimate[0])); }
Vector2D g2o::VertexSegment2D::estimateP2 () const inline
Definition at line 46 of file vertex_segment2d.h.
Referenced by g2o::EdgeSE2Segment2D::computeError(), g2o::EdgeSE2Segment2DLine::computeError(), g2o::EdgeSE2Segment2DPointLine::computeError(), LineInfo::LineInfo(), main(), g2o::VertexSegment2DWriteGnuplotAction::operator()(), g2o::EdgeSE2Segment2D::setMeasurementFromState(), g2o::EdgeSE2Segment2DLine::setMeasurementFromState(), and g2o::EdgeSE2Segment2DPointLine::setMeasurementFromState().
 { return Eigen::Map<const Vector2D>(&(_estimate[2])); }
virtual bool g2o::VertexSegment2D::getEstimateData (double * estimate) const inline virtual
writes the estimater to an array of double
Returns
true on success
Reimplemented from g2o::OptimizableGraph::Vertex.
Definition at line 60 of file vertex_segment2d.h.
{
         Eigen::Map<Vector4D> v(est);
         v = _estimate;
         return true;
       }
virtual bool g2o::VertexSegment2D::getMinimalEstimateData (double * estimate) const inline virtual
writes the estimate to an array of double
Returns
true on success
Reimplemented from g2o::OptimizableGraph::Vertex.
Definition at line 74 of file vertex_segment2d.h.
{
         return getEstimateData(est);
       }
virtual int g2o::VertexSegment2D::minimalEstimateDimension () const inline virtual
returns the dimension of the extended representation used by get/setEstimate(double*) -1 if it is not supported
Reimplemented from g2o::OptimizableGraph::Vertex.
Definition at line 78 of file vertex_segment2d.h.
{
         return 4;
       }
virtual void g2o::VertexSegment2D::oplusImpl (const double * v) inline virtual
update the position of the node from the parameters in v. Implement in your class!
Implements g2o::OptimizableGraph::Vertex.
Definition at line 82 of file vertex_segment2d.h.
       {
         Eigen::Map<const Vector4D> upd(update);
         _estimate += upd;
       }
bool g2o::VertexSegment2D::read (std::istream & is) virtual
read the vertex from a stream, i.e., the internal state of the vertex
Implements g2o::OptimizableGraph::Vertex.
Definition at line 49 of file vertex_segment2d.cpp.
References g2o::BaseVertex< 4, Vector4D >::_estimate.
   {
     for (size_t i=0; i<4; i++)
       is >> _estimate[i];
     return true;
   }
virtual bool g2o::VertexSegment2D::setEstimateDataImpl (const double *) inline virtual
writes the estimater to an array of double
Returns
true on success
Reimplemented from g2o::OptimizableGraph::Vertex.
Definition at line 54 of file vertex_segment2d.h.
{
         Eigen::Map<const Vector4D> v(est);
         _estimate = v;
         return true;
       }
void g2o::VertexSegment2D::setEstimateP1 (const Vector2D & p1) inline
Definition at line 47 of file vertex_segment2d.h.
Referenced by g2o::EdgeSE2Segment2D::initialEstimate().
 { Eigen::Map<Vector2D> v(&_estimate[0]); v=p1; }
void g2o::VertexSegment2D::setEstimateP2 (const Vector2D & p2) inline
Definition at line 48 of file vertex_segment2d.h.
Referenced by g2o::EdgeSE2Segment2D::initialEstimate().
 { Eigen::Map<Vector2D> v(&_estimate[2]); v=p2; }
virtual bool g2o::VertexSegment2D::setMinimalEstimateDataImpl (const double *) inline virtual
sets the initial estimate from an array of double
Returns
true on success
Reimplemented from g2o::OptimizableGraph::Vertex.
Definition at line 70 of file vertex_segment2d.h.
{
         return setEstimateData(est);
       }
virtual void g2o::VertexSegment2D::setToOriginImpl () inline virtual
sets the node to the origin (used in the multilevel stuff)
Implements g2o::OptimizableGraph::Vertex.
Definition at line 50 of file vertex_segment2d.h.
{
         _estimate.setZero();
       }
bool g2o::VertexSegment2D::write (std::ostream & os) const virtual
write the vertex to a stream
Implements g2o::OptimizableGraph::Vertex.
Definition at line 56 of file vertex_segment2d.cpp.
References g2o::BaseVertex< 4, Vector4D >::_estimate.
   {
     for (size_t i=0; i<4; i++)
       os << _estimate[i] << " ";
     return os.good();
   }
Member Data Documentation
g2o::VertexSegment2D::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 42 of file vertex_segment2d.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam2d_addons/vertex_segment2d.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam2d_addons/vertex_segment2d.cpp