g2o: g2o::WorldObject< VertexType_ > Class Template Reference
g2o::WorldObject< VertexType_ > Class Template Reference
#include <simulator.h>
Public Types
typedef VertexType_ VertexType
typedef VertexType_::EstimateType EstimateType
Public Member Functions
WorldObject (World *world_=0)
virtual void setVertex (OptimizableGraph::Vertex *vertex_)
VertexType * vertex ()
Public Member Functions inherited from g2o::BaseWorldObject
BaseWorldObject (World *world_=0)
virtual ~BaseWorldObject ()
void setWorld (World *world_)
World * world ()
OptimizableGraph * graph ()
OptimizableGraph::Vertex * vertex ()
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Additional Inherited Members
Protected Attributes inherited from g2o::BaseWorldObject
OptimizableGraph * _graph
OptimizableGraph::Vertex * _vertex
World * _world
Detailed Description
template<class VertexType_>
class g2o::WorldObject< VertexType_ >
Definition at line 58 of file simulator.h.
Member Typedef Documentation
template<class VertexType_ > typedef VertexType_::EstimateType g2o::WorldObject< VertexType_ >::EstimateType
Definition at line 62 of file simulator.h.
template<class VertexType_ > typedef VertexType_ g2o::WorldObject< VertexType_ >::VertexType
Definition at line 61 of file simulator.h.
Constructor & Destructor Documentation
template<class VertexType_ > g2o::WorldObject< VertexType_ >::WorldObject (World * world_ = 0) inline
Definition at line 63 of file simulator.h.
                                 : BaseWorldObject(world_){
       _vertex = new VertexType();
     }
Member Function Documentation
template<class VertexType_ > virtual void g2o::WorldObject< VertexType_ >::setVertex (OptimizableGraph::Vertex * vertex_) inline virtual
Reimplemented from g2o::BaseWorldObject.
Definition at line 66 of file simulator.h.
{
       if(! dynamic_cast<VertexType*>(vertex_))
         return;
       _vertex = vertex_;
     }
template<class VertexType_ > VertexType* g2o::WorldObject< VertexType_ >::vertex () inline
Definition at line 72 of file simulator.h.
Referenced by g2o::SensorPointXY::isVisible(), g2o::SensorPointXYBearing::isVisible(), g2o::SensorSegment2D::isVisible(), g2o::SensorSegment2DLine::isVisible(), g2o::SensorSegment2DPointLine::isVisible(), g2o::SensorPointXYZ::isVisible(), g2o::SensorPointXYZDepth::isVisible(), g2o::SensorPointXYOffset::isVisible(), g2o::SensorPointXYZDisparity::isVisible(), g2o::SensorPose3D::isVisible(), g2o::SensorPose2D::isVisible(), g2o::SensorPose3DOffset::isVisible(), and main().
{
       if (! _vertex) return 0;
       return dynamic_cast<VertexType*>(_vertex);
     }
Member Data Documentation
template<class VertexType_ > g2o::WorldObject< VertexType_ >::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 60 of file simulator.h.
The documentation for this class was generated from the following file:
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_simulator/simulator.h