g2o: g2o::EdgeSE2Segment2D Class Reference
g2o::EdgeSE2Segment2D Class Reference
#include <edge_se2_segment2d.h>
Public Member Functions
G2O_TYPES_SLAM2D_ADDONS_API EIGEN_MAKE_ALIGNED_OPERATOR_NEW G2O_TYPES_SLAM2D_ADDONS_API EdgeSE2Segment2D ()
G2O_TYPES_SLAM2D_ADDONS_API Vector2D measurementP1 ()
G2O_TYPES_SLAM2D_ADDONS_API Vector2D measurementP2 ()
G2O_TYPES_SLAM2D_ADDONS_API void setMeasurementP1 (const Vector2D &p1)
G2O_TYPES_SLAM2D_ADDONS_API void setMeasurementP2 (const Vector2D &p2)
G2O_TYPES_SLAM2D_ADDONS_API void computeError ()
virtual G2O_TYPES_SLAM2D_ADDONS_API bool setMeasurementData (const double *d)
virtual G2O_TYPES_SLAM2D_ADDONS_API bool getMeasurementData (double *d) const
virtual G2O_TYPES_SLAM2D_ADDONS_API int measurementDimension () const
virtual G2O_TYPES_SLAM2D_ADDONS_API bool setMeasurementFromState ()
virtual G2O_TYPES_SLAM2D_ADDONS_API bool read (std::istream &is)
read the vertex from a stream, i.e., the internal state of the vertex
virtual G2O_TYPES_SLAM2D_ADDONS_API bool write (std::ostream &os) const
write the vertex to a stream
virtual G2O_TYPES_SLAM2D_ADDONS_API void initialEstimate (const OptimizableGraph::VertexSet &from, OptimizableGraph::Vertex *to)
virtual G2O_TYPES_SLAM2D_ADDONS_API double initialEstimatePossible (const OptimizableGraph::VertexSet &from, OptimizableGraph::Vertex *to)
Public Member Functions inherited from g2o::BaseBinaryEdge< 4, Vector4D, VertexSE2, VertexSegment2D >
BaseBinaryEdge ()
virtual OptimizableGraph::Vertex * createFrom ()
virtual OptimizableGraph::Vertex * createTo ()
virtual OptimizableGraph::Vertex * createVertex (int i)
virtual void resize (size_t size)
virtual bool allVerticesFixed () const
virtual void linearizeOplus (JacobianWorkspace &jacobianWorkspace)
virtual void linearizeOplus ()
const JacobianXiOplusType & jacobianOplusXi () const
returns the result of the linearization in the manifold space for the node xi
const JacobianXjOplusType & jacobianOplusXj () const
returns the result of the linearization in the manifold space for the node xj
virtual void constructQuadraticForm ()
virtual void mapHessianMemory (double *d, int i, int j, bool rowMajor)
Public Member Functions inherited from g2o::BaseEdge< D, Vector4D >
BaseEdge ()
virtual ~BaseEdge ()
virtual double chi2 () const
computes the chi2 based on the cached error value, only valid after computeError has been called.
virtual const double * errorData () const
returns the error vector cached after calling the computeError;
virtual double * errorData ()
const ErrorVector & error () const
ErrorVector & error ()
EIGEN_STRONG_INLINE const InformationType & information () const
information matrix of the constraint
EIGEN_STRONG_INLINE InformationType & information ()
EIGEN_STRONG_INLINE void setInformation (const InformationType &information)
virtual const double * informationData () const
returns the memory of the information matrix, usable for example with a Eigen::Map<MatrixXD>
virtual double * informationData ()
EIGEN_STRONG_INLINE const Measurement & measurement () const
accessor functions for the measurement represented by the edge
virtual void setMeasurement (const Measurement &m)
virtual int rank () const
Public Member Functions inherited from g2o::OptimizableGraph::Edge
Edge ()
virtual ~Edge ()
virtual Edge * clone () const
RobustKernel * robustKernel () const
if NOT NULL, error of this edge will be robustifed with the kernel
void setRobustKernel (RobustKernel *ptr)
int level () const
returns the level of the edge
void setLevel (int l)
sets the level of the edge
int dimension () const
returns the dimensions of the error function
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createFrom())
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createTo())
long long internalId () const
the internal ID of the edge
OptimizableGraph * graph ()
const OptimizableGraph * graph () const
bool setParameterId (int argNum, int paramId)
const Parameter * parameter (int argNo) const
size_t numParameters () const
void resizeParameters (size_t newSize)
Public Member Functions inherited from g2o::HyperGraph::Edge
Edge (int id=InvalidId)
creates and empty edge with no vertices
const VertexContainer & vertices () const
VertexContainer & vertices ()
const Vertex * vertex (size_t i) const
Vertex * vertex (size_t i)
void setVertex (size_t i, Vertex *v)
int id () const
void setId (int id)
virtual HyperGraphElementType elementType () const
int numUndefinedVertices () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Member Functions inherited from g2o::HyperGraph::DataContainer
DataContainer ()
virtual ~DataContainer ()
const Data * userData () const
the user data associated with this vertex
Data * userData ()
void setUserData (Data *obs)
void addUserData (Data *obs)
Additional Inherited Members
Public Types inherited from g2o::BaseBinaryEdge< 4, Vector4D, VertexSE2, VertexSegment2D >
typedef VertexSE2 VertexXiType
typedef VertexSegment2D VertexXjType
typedef BaseEdge< D, Vector4D >::Measurement Measurement
typedef Eigen::Matrix< double, D, Di, D==1?Eigen::RowMajor:Eigen::ColMajor >::AlignedMapType JacobianXiOplusType
typedef Eigen::Matrix< double, D, Dj, D==1?Eigen::RowMajor:Eigen::ColMajor >::AlignedMapType JacobianXjOplusType
typedef BaseEdge< D, Vector4D >::ErrorVector ErrorVector
typedef BaseEdge< D, Vector4D >::InformationType InformationType
typedef Eigen::Map< Eigen::Matrix< double, Di, Dj, Di==1?Eigen::RowMajor:Eigen::ColMajor >, Eigen::Matrix< double, Di, Dj, Di==1?Eigen::RowMajor:Eigen::ColMajor >::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockType
typedef Eigen::Map< Eigen::Matrix< double, Dj, Di, Dj==1?Eigen::RowMajor:Eigen::ColMajor >, Eigen::Matrix< double, Dj, Di, Dj==1?Eigen::RowMajor:Eigen::ColMajor >::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockTransposedType
Public Types inherited from g2o::BaseEdge< D, Vector4D >
typedef Vector4D Measurement
typedef Eigen::Matrix< double, D, 1, Eigen::ColMajor > ErrorVector
typedef Eigen::Matrix< double, D, D, Eigen::ColMajor > InformationType
Static Public Attributes inherited from g2o::BaseBinaryEdge< 4, Vector4D, VertexSE2, VertexSegment2D >
static const int Di
static const int Dj
static const int Dimension
Static Public Attributes inherited from g2o::BaseEdge< D, Vector4D >
static const int Dimension
Protected Member Functions inherited from g2o::BaseEdge< D, Vector4D >
InformationType robustInformation (const Vector3D &rho)
Protected Member Functions inherited from g2o::OptimizableGraph::Edge
template<typename ParameterType >
bool installParameter (ParameterType *&p, size_t argNo, int paramId=-1)
template<typename CacheType >
void resolveCache (CacheType *&cache, OptimizableGraph::Vertex *, const std::string &_type, const ParameterVector &parameters)
bool resolveParameters ()
virtual bool resolveCaches ()
Protected Attributes inherited from g2o::BaseBinaryEdge< 4, Vector4D, VertexSE2, VertexSegment2D >
bool _hessianRowMajor
HessianBlockType _hessian
HessianBlockTransposedType _hessianTransposed
JacobianXiOplusType _jacobianOplusXi
JacobianXjOplusType _jacobianOplusXj
Protected Attributes inherited from g2o::BaseEdge< D, Vector4D >
Measurement _measurement
InformationType _information
ErrorVector _error
Protected Attributes inherited from g2o::OptimizableGraph::Edge
int _dimension
int _level
RobustKernel * _robustKernel
long long _internalId
std::vector< int > _cacheIds
std::vector< std::string > _parameterTypes
std::vector< Parameter ** > _parameters
std::vector< int > _parameterIds
Protected Attributes inherited from g2o::HyperGraph::Edge
VertexContainer _vertices
int _id
unique id
Protected Attributes inherited from g2o::HyperGraph::DataContainer
Data * _userData
Detailed Description
Definition at line 38 of file edge_se2_segment2d.h.
Constructor & Destructor Documentation
g2o::EdgeSE2Segment2D::EdgeSE2Segment2D ()
Definition at line 43 of file edge_se2_segment2d.cpp.
                                      :
     BaseBinaryEdge<4, Vector4D, VertexSE2, VertexSegment2D>()
   {
   }
Member Function Documentation
G2O_TYPES_SLAM2D_ADDONS_API void g2o::EdgeSE2Segment2D::computeError () inline virtual
Implements g2o::OptimizableGraph::Edge.
Definition at line 49 of file edge_se2_segment2d.h.
References g2o::BaseEdge< D, Vector4D >::_error, g2o::BaseEdge< D, Vector4D >::_measurement, g2o::HyperGraph::Edge::_vertices, g2o::BaseVertex< D, T >::estimate(), g2o::VertexSegment2D::estimateP1(), g2o::VertexSegment2D::estimateP2(), and g2o::SE2::inverse().
       {
         const VertexSE2* v1 = static_cast<const VertexSE2*>(_vertices[0]);
         const VertexSegment2D* l2 = static_cast<const VertexSegment2D*>(_vertices[1]);
         Eigen::Map<Vector2D> error1(&_error(0));
         Eigen::Map<Vector2D> error2(&_error(2));
         SE2 iEst=v1->estimate().inverse();
         error1 = (iEst * l2->estimateP1());
         error2 = (iEst * l2->estimateP2());
         _error = _error - _measurement;
       }
virtual G2O_TYPES_SLAM2D_ADDONS_API bool g2o::EdgeSE2Segment2D::getMeasurementData (double * m) const inline virtual
writes the measurement to an array of double
Returns
true on success
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 67 of file edge_se2_segment2d.h.
References g2o::BaseEdge< D, Vector4D >::_measurement.
{
         Eigen::Map<Vector4D> data(d);
         data = _measurement;
         return true;
       }
void g2o::EdgeSE2Segment2D::initialEstimate (const OptimizableGraph::VertexSet & , OptimizableGraph::Vertex *) virtual
set the estimate of the to vertex, based on the estimate of the from vertices in the edge.
Reimplemented from g2o::BaseEdge< D, Vector4D >.
Definition at line 71 of file edge_se2_segment2d.cpp.
References g2o::HyperGraph::Edge::_vertices, measurementP1(), measurementP2(), g2o::VertexSegment2D::setEstimateP1(), and g2o::VertexSegment2D::setEstimateP2().
Referenced by setMeasurementFromState().
   {
     assert(from.size() == 1 && from.count(_vertices[0]) == 1 && "Can not initialize VertexSE2 position by VertexSegment2D. I could if i wanted. Not now");
     VertexSE2* vi     = static_cast<VertexSE2*>(_vertices[0]);
     VertexSegment2D* vj = static_cast<VertexSegment2D*>(_vertices[1]);
     if (from.count(vi) > 0 && to == vj) {
       vj->setEstimateP1(vi->estimate() * measurementP1());
       vj->setEstimateP2(vi->estimate() * measurementP2());
     }
   }
virtual G2O_TYPES_SLAM2D_ADDONS_API double g2o::EdgeSE2Segment2D::initialEstimatePossible (const OptimizableGraph::VertexSet & from, OptimizableGraph::Vertex * to) inline virtual
override in your class if it's possible to initialize the vertices in certain combinations. The return value may correspond to the cost for initiliaizng the vertex but should be positive if the initialization is possible and negative if not possible.
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 88 of file edge_se2_segment2d.h.
References g2o::HyperGraph::Edge::_vertices.
 { (void) to; return (from.count(_vertices[0]) == 1 ? 1.0 : -1.0);}
virtual G2O_TYPES_SLAM2D_ADDONS_API int g2o::EdgeSE2Segment2D::measurementDimension () const inline virtual
returns the dimension of the measurement in the extended representation which is used by get/setMeasurement;
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 73 of file edge_se2_segment2d.h.
 {return 4;}
G2O_TYPES_SLAM2D_ADDONS_API Vector2D g2o::EdgeSE2Segment2D::measurementP1 () inline
Definition at line 44 of file edge_se2_segment2d.h.
References g2o::BaseEdge< D, Vector4D >::_measurement.
Referenced by initialEstimate(), and main().
 { return Eigen::Map<const Vector2D>(&(_measurement[0])); }
G2O_TYPES_SLAM2D_ADDONS_API Vector2D g2o::EdgeSE2Segment2D::measurementP2 () inline
Definition at line 45 of file edge_se2_segment2d.h.
References g2o::BaseEdge< D, Vector4D >::_measurement.
Referenced by initialEstimate(), and main().
 { return Eigen::Map<const Vector2D>(&(_measurement[2])); }
bool g2o::EdgeSE2Segment2D::read (std::istream & is) virtual
read the vertex from a stream, i.e., the internal state of the vertex
Implements g2o::OptimizableGraph::Edge.
Definition at line 48 of file edge_se2_segment2d.cpp.
References g2o::BaseEdge< D, Vector4D >::_information, and g2o::BaseEdge< D, Vector4D >::_measurement.
Referenced by setMeasurementFromState().
   {
     for (size_t i = 0; i < 4 ; i++)
       is >> _measurement[i];
     for (size_t i = 0; i < 4 ; i++)
       for (size_t j = i; j < 4 ; j++) {
         is >> _information (i,j);
         _information (j,i) = _information (i,j);
       }
     return true;
   }
virtual G2O_TYPES_SLAM2D_ADDONS_API bool g2o::EdgeSE2Segment2D::setMeasurementData (const double * m) inline virtual
sets the measurement from an array of double
Returns
true on success
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 61 of file edge_se2_segment2d.h.
References g2o::BaseEdge< D, Vector4D >::_measurement.
{
         Eigen::Map<const Vector4D> data(d);
         _measurement = data;
         return true;
       }
virtual G2O_TYPES_SLAM2D_ADDONS_API bool g2o::EdgeSE2Segment2D::setMeasurementFromState () inline virtual
sets the estimate to have a zero error, based on the current value of the state variables returns false if not supported.
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 75 of file edge_se2_segment2d.h.
References g2o::HyperGraph::Edge::_vertices, g2o::BaseVertex< D, T >::estimate(), g2o::VertexSegment2D::estimateP1(), g2o::VertexSegment2D::estimateP2(), G2O_TYPES_SLAM2D_ADDONS_API, initialEstimate(), g2o::SE2::inverse(), read(), setMeasurementP1(), setMeasurementP2(), and write().
Referenced by g2o::SensorSegment2D::sense().
{
         const VertexSE2* v1 = static_cast<const VertexSE2*>(_vertices[0]);
         const VertexSegment2D* l2 = static_cast<const VertexSegment2D*>(_vertices[1]);
         SE2 iEst=v1->estimate().inverse();
         setMeasurementP1(iEst*l2->estimateP1());
         setMeasurementP2(iEst*l2->estimateP2());
         return true;
       }
G2O_TYPES_SLAM2D_ADDONS_API void g2o::EdgeSE2Segment2D::setMeasurementP1 (const Vector2D & p1) inline
Definition at line 46 of file edge_se2_segment2d.h.
References g2o::BaseEdge< D, Vector4D >::_measurement.
Referenced by setMeasurementFromState().
 { Eigen::Map<Vector2D> v(&_measurement[0]); v=p1; }
G2O_TYPES_SLAM2D_ADDONS_API void g2o::EdgeSE2Segment2D::setMeasurementP2 (const Vector2D & p2) inline
Definition at line 47 of file edge_se2_segment2d.h.
References g2o::BaseEdge< D, Vector4D >::_measurement.
Referenced by setMeasurementFromState().
 { Eigen::Map<Vector2D> v(&_measurement[2]); v=p2; }
bool g2o::EdgeSE2Segment2D::write (std::ostream & os) const virtual
write the vertex to a stream
Implements g2o::OptimizableGraph::Edge.
Definition at line 60 of file edge_se2_segment2d.cpp.
References g2o::BaseEdge< D, Vector4D >::_information, and g2o::BaseEdge< D, Vector4D >::_measurement.
Referenced by setMeasurementFromState().
   {
     for (size_t i = 0; i < 4 ; i++)
       os << _measurement[i] << " ";
     for (size_t i = 0; i < 4 ; i++)
       for (size_t j = i; j < 4 ; j++) {
         os << _information (i,j) << " ";
       }
     return os.good();
   }
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam2d_addons/edge_se2_segment2d.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam2d_addons/edge_se2_segment2d.cpp