g2o: g2o::EdgeSE2Prior Class Reference
g2o::EdgeSE2Prior Class Reference
Prior for a two D pose.
#include <edge_se2_prior.h>
Public Member Functions
EdgeSE2Prior ()
void computeError ()
virtual void setMeasurement (const SE2 &m)
virtual bool setMeasurementData (const double *d)
virtual bool getMeasurementData (double *d) const
int measurementDimension () const
virtual bool read (std::istream &is)
read the vertex from a stream, i.e., the internal state of the vertex
virtual bool write (std::ostream &os) const
write the vertex to a stream
virtual double initialEstimatePossible (const OptimizableGraph::VertexSet &, OptimizableGraph::Vertex *)
virtual void initialEstimate (const OptimizableGraph::VertexSet &from, OptimizableGraph::Vertex *to)
Public Member Functions inherited from g2o::BaseUnaryEdge< 3, SE2, VertexSE2 >
BaseUnaryEdge ()
virtual void resize (size_t size)
virtual bool allVerticesFixed () const
virtual void linearizeOplus (JacobianWorkspace &jacobianWorkspace)
virtual void linearizeOplus ()
virtual OptimizableGraph::Vertex * createVertex (int i)
const JacobianXiOplusType & jacobianOplusXi () const
returns the result of the linearization in the manifold space for the node xi
virtual void constructQuadraticForm ()
virtual void mapHessianMemory (double *, int, int, bool)
Public Member Functions inherited from g2o::BaseEdge< D, SE2 >
BaseEdge ()
virtual ~BaseEdge ()
virtual double chi2 () const
computes the chi2 based on the cached error value, only valid after computeError has been called.
virtual const double * errorData () const
returns the error vector cached after calling the computeError;
virtual double * errorData ()
const ErrorVector & error () const
ErrorVector & error ()
EIGEN_STRONG_INLINE const InformationType & information () const
information matrix of the constraint
EIGEN_STRONG_INLINE InformationType & information ()
EIGEN_STRONG_INLINE void setInformation (const InformationType &information)
virtual const double * informationData () const
returns the memory of the information matrix, usable for example with a Eigen::Map<MatrixXD>
virtual double * informationData ()
EIGEN_STRONG_INLINE const Measurement & measurement () const
accessor functions for the measurement represented by the edge
virtual int rank () const
Public Member Functions inherited from g2o::OptimizableGraph::Edge
Edge ()
virtual ~Edge ()
virtual Edge * clone () const
virtual bool setMeasurementFromState ()
RobustKernel * robustKernel () const
if NOT NULL, error of this edge will be robustifed with the kernel
void setRobustKernel (RobustKernel *ptr)
int level () const
returns the level of the edge
void setLevel (int l)
sets the level of the edge
int dimension () const
returns the dimensions of the error function
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createFrom())
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createTo())
long long internalId () const
the internal ID of the edge
OptimizableGraph * graph ()
const OptimizableGraph * graph () const
bool setParameterId (int argNum, int paramId)
const Parameter * parameter (int argNo) const
size_t numParameters () const
void resizeParameters (size_t newSize)
Public Member Functions inherited from g2o::HyperGraph::Edge
Edge (int id=InvalidId)
creates and empty edge with no vertices
const VertexContainer & vertices () const
VertexContainer & vertices ()
const Vertex * vertex (size_t i) const
Vertex * vertex (size_t i)
void setVertex (size_t i, Vertex *v)
int id () const
void setId (int id)
virtual HyperGraphElementType elementType () const
int numUndefinedVertices () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Member Functions inherited from g2o::HyperGraph::DataContainer
DataContainer ()
virtual ~DataContainer ()
const Data * userData () const
the user data associated with this vertex
Data * userData ()
void setUserData (Data *obs)
void addUserData (Data *obs)
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Attributes
SE2 _inverseMeasurement
Protected Attributes inherited from g2o::BaseUnaryEdge< 3, SE2, VertexSE2 >
JacobianXiOplusType _jacobianOplusXi
Protected Attributes inherited from g2o::BaseEdge< D, SE2 >
Measurement _measurement
InformationType _information
ErrorVector _error
Protected Attributes inherited from g2o::OptimizableGraph::Edge
int _dimension
int _level
RobustKernel * _robustKernel
long long _internalId
std::vector< int > _cacheIds
std::vector< std::string > _parameterTypes
std::vector< Parameter ** > _parameters
std::vector< int > _parameterIds
Protected Attributes inherited from g2o::HyperGraph::Edge
VertexContainer _vertices
int _id
unique id
Protected Attributes inherited from g2o::HyperGraph::DataContainer
Data * _userData
Additional Inherited Members
Public Types inherited from g2o::BaseUnaryEdge< 3, SE2, VertexSE2 >
typedef BaseEdge< D, SE2 >::Measurement Measurement
typedef VertexSE2 VertexXiType
typedef Eigen::Matrix< double, D, VertexXiType::Dimension, D==1?Eigen::RowMajor:Eigen::ColMajor >::AlignedMapType JacobianXiOplusType
typedef BaseEdge< D, SE2 >::ErrorVector ErrorVector
typedef BaseEdge< D, SE2 >::InformationType InformationType
Public Types inherited from g2o::BaseEdge< D, SE2 >
typedef SE2 Measurement
typedef Eigen::Matrix< double, D, 1, Eigen::ColMajor > ErrorVector
typedef Eigen::Matrix< double, D, D, Eigen::ColMajor > InformationType
Static Public Attributes inherited from g2o::BaseUnaryEdge< 3, SE2, VertexSE2 >
static const int Dimension
Static Public Attributes inherited from g2o::BaseEdge< D, SE2 >
static const int Dimension
Protected Member Functions inherited from g2o::BaseEdge< D, SE2 >
InformationType robustInformation (const Vector3D &rho)
Protected Member Functions inherited from g2o::OptimizableGraph::Edge
template<typename ParameterType >
bool installParameter (ParameterType *&p, size_t argNo, int paramId=-1)
template<typename CacheType >
void resolveCache (CacheType *&cache, OptimizableGraph::Vertex *, const std::string &_type, const ParameterVector &parameters)
bool resolveParameters ()
virtual bool resolveCaches ()
Detailed Description
Prior for a two D pose.
Definition at line 39 of file edge_se2_prior.h.
Constructor & Destructor Documentation
g2o::EdgeSE2Prior::EdgeSE2Prior ()
Definition at line 31 of file edge_se2_prior.cpp.
                              : BaseUnaryEdge<3, SE2, VertexSE2>()
   {
   }
Member Function Documentation
void g2o::EdgeSE2Prior::computeError () inline virtual
Implements g2o::OptimizableGraph::Edge.
Definition at line 45 of file edge_se2_prior.h.
References g2o::BaseVertex< D, T >::estimate(), and g2o::SE2::toVector().
       {
         const VertexSE2* v1 = static_cast<const VertexSE2*>(_vertices[0]);
         SE2 delta = _inverseMeasurement * v1->estimate();
         _error = delta.toVector();
       }
virtual bool g2o::EdgeSE2Prior::getMeasurementData (double * m) const inline virtual
writes the measurement to an array of double
Returns
true on success
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 63 of file edge_se2_prior.h.
{
         Eigen::Map<Vector3D> v(d);
         v = _measurement.toVector();
         return true;
       }
void g2o::EdgeSE2Prior::initialEstimate (const OptimizableGraph::VertexSet & from, OptimizableGraph::Vertex * to) virtual
set the estimate of the to vertex, based on the estimate of the from vertices in the edge.
Reimplemented from g2o::BaseUnaryEdge< 3, SE2, VertexSE2 >.
Definition at line 35 of file edge_se2_prior.cpp.
References g2o::BaseEdge< D, SE2 >::_measurement, g2o::HyperGraph::Edge::_vertices, and g2o::BaseVertex< D, T >::setEstimate().
   {
     assert(from.size() == 0); (void) from; (void) to;
     VertexSE2* v1 = static_cast<VertexSE2*>(_vertices[0]);
     v1->setEstimate(_measurement);
   }
virtual double g2o::EdgeSE2Prior::initialEstimatePossible (const OptimizableGraph::VertexSet & from, OptimizableGraph::Vertex * to) inline virtual
override in your class if it's possible to initialize the vertices in certain combinations. The return value may correspond to the cost for initiliaizng the vertex but should be positive if the initialization is possible and negative if not possible.
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 74 of file edge_se2_prior.h.
 { return 1.;}
int g2o::EdgeSE2Prior::measurementDimension () const inline virtual
returns the dimension of the measurement in the extended representation which is used by get/setMeasurement;
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 69 of file edge_se2_prior.h.
 {return 3;}
bool g2o::EdgeSE2Prior::read (std::istream & is) virtual
read the vertex from a stream, i.e., the internal state of the vertex
Implements g2o::OptimizableGraph::Edge.
Definition at line 42 of file edge_se2_prior.cpp.
References _inverseMeasurement, g2o::BaseEdge< D, SE2 >::_measurement, g2o::BaseEdge< D, SE2 >::information(), g2o::SE2::inverse(), and setMeasurement().
   {
     Vector3D p;
     is >> p[0] >> p[1] >> p[2];
     setMeasurement(p);
     _inverseMeasurement= _measurement.inverse();
     for (int i = 0; i < 3; ++i)
       for (int j = i; j < 3; ++j) {
         is >> information()(i, j);
         if (i != j)
           information()(j, i) = information()(i, j);
       }
     return true;
   }
void g2o::EdgeSE2Prior::setMeasurement (const SE2 & m) virtual
Reimplemented from g2o::BaseEdge< D, SE2 >.
Definition at line 67 of file edge_se2_prior.cpp.
References _inverseMeasurement, g2o::BaseEdge< D, SE2 >::_measurement, and g2o::SE2::inverse().
Referenced by read().
   {
     _measurement = m;
     _inverseMeasurement = m.inverse();
   }
bool g2o::EdgeSE2Prior::setMeasurementData (const double * m) virtual
sets the measurement from an array of double
Returns
true on success
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 73 of file edge_se2_prior.cpp.
References _inverseMeasurement, g2o::BaseEdge< D, SE2 >::_measurement, and g2o::SE2::inverse().
{
     _measurement=SE2(d[0], d[1], d[2]);
     _inverseMeasurement = _measurement.inverse();
     return true;
   }
bool g2o::EdgeSE2Prior::write (std::ostream & os) const virtual
write the vertex to a stream
Implements g2o::OptimizableGraph::Edge.
Definition at line 57 of file edge_se2_prior.cpp.
References g2o::BaseEdge< D, SE2 >::information(), g2o::BaseEdge< D, SE2 >::measurement(), and g2o::SE2::toVector().
   {
     Vector3D p = measurement().toVector();
     os << p.x() << " " << p.y() << " " << p.z();
     for (int i = 0; i < 3; ++i)
       for (int j = i; j < 3; ++j)
         os << " " << information()(i, j);
     return os.good();
   }
Member Data Documentation
SE2 g2o::EdgeSE2Prior::_inverseMeasurement protected
Definition at line 78 of file edge_se2_prior.h.
Referenced by read(), setMeasurement(), and setMeasurementData().
g2o::EdgeSE2Prior::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 42 of file edge_se2_prior.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam2d/edge_se2_prior.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam2d/edge_se2_prior.cpp