g2o: g2o::VertexSCam Class Reference
g2o::VertexSCam Class Reference
Stereo camera vertex, derived from SE3 class. Note that we use the actual pose of the vertex as its parameterization, rather than the transform from RW to camera coords. Uses static vars for camera params, so there is a single camera setup.
#include <types_icp.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW VertexSCam ()
virtual bool read (std::istream &is)
read the vertex from a stream, i.e., the internal state of the vertex
virtual bool write (std::ostream &os) const
write the vertex to a stream
virtual void oplusImpl (const double *update)
void setTransform ()
void setProjection ()
void setDr ()
void setAll ()
void mapPoint (Vector3D &res, const Vector3D &pt3)
Public Member Functions inherited from g2o::VertexSE3
VertexSE3 ()
virtual void setToOriginImpl ()
sets the node to the origin (used in the multilevel stuff)
virtual bool setEstimateDataImpl (const double *est)
virtual bool getEstimateData (double *est) const
virtual int estimateDimension () const
virtual bool setMinimalEstimateDataImpl (const double *est)
virtual bool getMinimalEstimateData (double *est) const
virtual int minimalEstimateDimension () const
SE3Quat G2O_ATTRIBUTE_DEPRECATED (estimateAsSE3Quat() const)
wrapper function to use the old SE3 type
void G2O_ATTRIBUTE_DEPRECATED (setEstimateFromSE3Quat(const SE3Quat &se3))
wrapper function to use the old SE3 type
Public Member Functions inherited from g2o::BaseVertex< 6, Isometry3D >
BaseVertex ()
virtual const double & hessian (int i, int j) const
get the element from the hessian matrix
virtual double & hessian (int i, int j)
virtual double hessianDeterminant () const
virtual double * hessianData ()
virtual void mapHessianMemory (double *d)
virtual int copyB (double *b_) const
virtual const double & b (int i) const
get the b vector element
virtual double & b (int i)
Eigen::Matrix< double, D, 1, Eigen::ColMajor > & b ()
return right hand side b of the constructed linear system
const Eigen::Matrix< double, D, 1, Eigen::ColMajor > & b () const
virtual double * bData ()
return a pointer to the b vector associated with this vertex
virtual void clearQuadraticForm ()
virtual double solveDirect (double lambda=0)
HessianBlockType & A ()
return the hessian block associated with the vertex
const HessianBlockType & A () const
virtual void push ()
backup the position of the vertex to a stack
virtual void pop ()
restore the position of the vertex by retrieving the position from the stack
virtual void discardTop ()
pop the last element from the stack, without restoring the current estimate
virtual int stackSize () const
return the stack size
const EstimateType & estimate () const
return the current estimate of the vertex
void setEstimate (const EstimateType &et)
set the estimate for the vertex also calls updateCache()
Public Member Functions inherited from g2o::OptimizableGraph::Vertex
Vertex ()
virtual Vertex * clone () const
returns a deep copy of the current vertex
virtual ~Vertex ()
void setToOrigin ()
sets the node to the origin (used in the multilevel stuff)
bool setEstimateData (const double *estimate)
bool setEstimateData (const std::vector< double > &estimate)
virtual bool getEstimateData (std::vector< double > &estimate) const
bool setMinimalEstimateData (const double *estimate)
bool setMinimalEstimateData (const std::vector< double > &estimate)
virtual bool getMinimalEstimateData (std::vector< double > &estimate) const
void oplus (const double *v)
int hessianIndex () const
temporary index of this node in the parameter vector obtained from linearization
int G2O_ATTRIBUTE_DEPRECATED (tempIndex() const)
void setHessianIndex (int ti)
set the temporary index of the vertex in the parameter blocks
void G2O_ATTRIBUTE_DEPRECATED (setTempIndex(int ti))
bool fixed () const
true => this node is fixed during the optimization
void setFixed (bool fixed)
true => this node should be considered fixed during the optimization
bool marginalized () const
true => this node is marginalized out during the optimization
void setMarginalized (bool marginalized)
true => this node should be marginalized out during the optimization
int dimension () const
dimension of the estimated state belonging to this node
virtual void setId (int id)
sets the id of the node in the graph be sure that the graph keeps consistent after changing the id
void setColInHessian (int c)
set the row of this vertex in the Hessian
int colInHessian () const
get the row of this vertex in the Hessian
const OptimizableGraph * graph () const
OptimizableGraph * graph ()
void lockQuadraticForm ()
void unlockQuadraticForm ()
virtual void updateCache ()
CacheContainer * cacheContainer ()
Public Member Functions inherited from g2o::HyperGraph::Vertex
Vertex (int id=InvalidId)
creates a vertex having an ID specified by the argument
int id () const
returns the id
const EdgeSet & edges () const
returns the set of hyper-edges that are leaving/entering in this vertex
EdgeSet & edges ()
returns the set of hyper-edges that are leaving/entering in this vertex
virtual HyperGraphElementType elementType () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Member Functions inherited from g2o::HyperGraph::DataContainer
DataContainer ()
virtual ~DataContainer ()
const Data * userData () const
the user data associated with this vertex
Data * userData ()
void setUserData (Data *obs)
void addUserData (Data *obs)
Static Public Member Functions
static void transformW2F (Eigen::Matrix< double, 3, 4, Eigen::ColMajor > &m, const Vector3D &trans, const Eigen::Quaterniond &qrot)
static void transformF2W (Eigen::Matrix< double, 3, 4, Eigen::ColMajor > &m, const Vector3D &trans, const Eigen::Quaterniond &qrot)
static void setKcam (double fx, double fy, double cx, double cy, double tx)
Public Attributes
Eigen::Matrix< double, 3, 4, Eigen::ColMajor > w2n
Eigen::Matrix< double, 3, 4, Eigen::ColMajor > w2i
Matrix3D dRdx
Matrix3D dRdy
Matrix3D dRdz
Public Attributes inherited from g2o::VertexSE3
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Static Public Attributes
static Matrix3D Kcam
static double baseline
static Matrix3D dRidx
static Matrix3D dRidy
static Matrix3D dRidz
Static Public Attributes inherited from g2o::VertexSE3
static const int orthogonalizeAfter = 1000
Static Public Attributes inherited from g2o::BaseVertex< 6, Isometry3D >
static const int Dimension
dimension of the estimate (minimal) in the manifold space
Additional Inherited Members
Public Types inherited from g2o::BaseVertex< 6, Isometry3D >
typedef Isometry3D EstimateType
typedef std::stack< EstimateType, std::vector< EstimateType, Eigen::aligned_allocator< EstimateType > > > BackupStackType
typedef Eigen::Map< Eigen::Matrix< double, D, D, Eigen::ColMajor >, Eigen::Matrix< double, D, D, Eigen::ColMajor >::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockType
Protected Attributes inherited from g2o::VertexSE3
int _numOplusCalls
store how often opluse was called to trigger orthogonaliation of the rotation matrix
Protected Attributes inherited from g2o::BaseVertex< 6, Isometry3D >
HessianBlockType _hessian
Eigen::Matrix< double, D, 1, Eigen::ColMajor > _b
EstimateType _estimate
BackupStackType _backup
Protected Attributes inherited from g2o::OptimizableGraph::Vertex
OptimizableGraph * _graph
Data * _userData
int _hessianIndex
bool _fixed
bool _marginalized
int _dimension
int _colInHessian
OpenMPMutex _quadraticFormMutex
CacheContainer * _cacheContainer
Protected Attributes inherited from g2o::HyperGraph::Vertex
int _id
EdgeSet _edges
Protected Attributes inherited from g2o::HyperGraph::DataContainer
Data * _userData
Detailed Description
Stereo camera vertex, derived from SE3 class. Note that we use the actual pose of the vertex as its parameterization, rather than the transform from RW to camera coords. Uses static vars for camera params, so there is a single camera setup.
Definition at line 250 of file types_icp.h.
Constructor & Destructor Documentation
g2o::VertexSCam::VertexSCam ()
Definition at line 232 of file types_icp.cpp.
                          :
     VertexSE3()
   {}
Member Function Documentation
void g2o::VertexSCam::mapPoint (Vector3D & res, const Vector3D & pt3) inline
Definition at line 343 of file types_icp.h.
Referenced by g2o::Edge_XYZ_VSC::computeError().
       {
         Vector4D pt;
         pt.head<3>() = pt3;
         pt(3) = 1.0;
         Vector3D p1 = w2i * pt;
         Vector3D p2 = w2n * pt;
         Vector3D pb(baseline,0,0);
         double invp1 = 1.0/p1(2);
         res.head<2>() = p1.head<2>()*invp1;
         // right camera px
         p2 = Kcam*(p2-pb);
         res(2) = p2(0)/p2(2);
       }
virtual void g2o::VertexSCam::oplusImpl (const double * update) inline virtual
update the position of this vertex. The update is in the form (x,y,z,qx,qy,qz) whereas (x,y,z) represents the translational update and (qx,qy,qz) corresponds to the respective elements. The missing element qw of the quaternion is recovred by || (qw,qx,qy,qz) || == 1 => qw = sqrt(1 - || (qx,qy,qz) ||
Reimplemented from g2o::VertexSE3.
Definition at line 262 of file types_icp.h.
References g2o::VertexSE3::oplusImpl().
       {
         VertexSE3::oplusImpl(update);
         setAll();
       }
bool g2o::VertexSCam::read (std::istream & is) virtual
read the vertex from a stream, i.e., the internal state of the vertex
Reimplemented from g2o::VertexSE3.
Definition at line 331 of file types_icp.cpp.
   { return false; }
void g2o::VertexSCam::setAll () inline
Definition at line 335 of file types_icp.h.
Referenced by main().
       {
         setTransform();
         setProjection();
         setDr();
       }
void g2o::VertexSCam::setDr () inline
Definition at line 324 of file types_icp.h.
       {
         // inefficient, just for testing
         // use simple multiplications and additions for production code in calculating dRdx,y,z
         // for dS'*R', with dS the incremental change
         dRdx = dRidx * w2n.block<3,3>(0,0);
         dRdy = dRidy * w2n.block<3,3>(0,0);
         dRdz = dRidz * w2n.block<3,3>(0,0);
       }
static void g2o::VertexSCam::setKcam (double fx, double fy, double cx, double cy, double tx) inline static
Definition at line 302 of file types_icp.h.
Referenced by main().
       {
         Kcam.setZero();
         Kcam(0,0) = fx;
         Kcam(1,1) = fy;
         Kcam(0,2) = cx;
         Kcam(1,2) = cy;
         Kcam(2,2) = 1.0;
         baseline = tx;
       }
void g2o::VertexSCam::setProjection () inline
Definition at line 321 of file types_icp.h.
 { w2i = Kcam * w2n; }
void g2o::VertexSCam::setTransform () inline
Definition at line 314 of file types_icp.h.
{
         w2n = estimate().inverse().matrix().block<3,4>(0, 0);
         //transformW2F(w2n,estimate().translation(), estimate().rotation());
       }
static void g2o::VertexSCam::transformF2W (Eigen::Matrix< double, 3, 4, Eigen::ColMajor > & m, const Vector3D & trans, const Eigen::Quaterniond & qrot) inline static
Definition at line 293 of file types_icp.h.
         {
           m.block<3,3>(0,0) = qrot.toRotationMatrix();
           m.col(3) = trans;
         }
static void g2o::VertexSCam::transformW2F (Eigen::Matrix< double, 3, 4, Eigen::ColMajor > & m, const Vector3D & trans, const Eigen::Quaterniond & qrot) inline static
Definition at line 281 of file types_icp.h.
         {
           m.block<3,3>(0,0) = qrot.toRotationMatrix().transpose();
           m.col(3).setZero();         // make sure there's no translation
           Vector4D tt;
           tt.head(3) = trans;
           tt[3] = 1.0;
           m.col(3) = -m*tt;
         }
bool g2o::VertexSCam::write (std::ostream & os) const virtual
write the vertex to a stream
Reimplemented from g2o::VertexSE3.
Definition at line 334 of file types_icp.cpp.
   { return false; }
Member Data Documentation
double g2o::VertexSCam::baseline static
Definition at line 270 of file types_icp.h.
Referenced by g2o::Edge_XYZ_VSC::Edge_XYZ_VSC().
Matrix3D g2o::VertexSCam::dRdx
Definition at line 278 of file types_icp.h.
Referenced by g2o::Edge_XYZ_VSC::Edge_XYZ_VSC().
Matrix3D g2o::VertexSCam::dRdy
Definition at line 278 of file types_icp.h.
Referenced by g2o::Edge_XYZ_VSC::Edge_XYZ_VSC().
Matrix3D g2o::VertexSCam::dRdz
Definition at line 278 of file types_icp.h.
Referenced by g2o::Edge_XYZ_VSC::Edge_XYZ_VSC().
Matrix3D g2o::VertexSCam::dRidx static
Definition at line 360 of file types_icp.h.
Matrix3D g2o::VertexSCam::dRidy static
Definition at line 361 of file types_icp.h.
Matrix3D g2o::VertexSCam::dRidz static
Definition at line 362 of file types_icp.h.
Matrix3D g2o::VertexSCam::Kcam static
Definition at line 269 of file types_icp.h.
Referenced by g2o::Edge_XYZ_VSC::Edge_XYZ_VSC().
Eigen::Matrix<double,3,4,Eigen::ColMajor> g2o::VertexSCam::w2i
Definition at line 274 of file types_icp.h.
Eigen::Matrix<double,3,4,Eigen::ColMajor> g2o::VertexSCam::w2n
Definition at line 273 of file types_icp.h.
Referenced by g2o::Edge_XYZ_VSC::Edge_XYZ_VSC().
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/icp/types_icp.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/icp/types_icp.cpp