g2o: g2o::HyperGraph::Data Class Reference
g2o::HyperGraph::Data Class Reference abstract
data packet for a vertex. Extend this class to store in the vertices the potential additional information you need (e.g. images, laser scans, ...).
#include <hyper_graph.h>
Public Member Functions
Data ()
~Data ()
virtual bool read (std::istream &is)=0
read the data from a stream
virtual bool write (std::ostream &os) const =0
write the data to a stream
virtual HyperGraph::HyperGraphElementType elementType () const
const Data * next () const
Data * next ()
void setNext (Data *next_)
DataContainer * dataContainer ()
const DataContainer * dataContainer () const
void setDataContainer (DataContainer *dataContainer_)
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Protected Attributes
Data * _next
DataContainer * _dataContainer
Detailed Description
data packet for a vertex. Extend this class to store in the vertices the potential additional information you need (e.g. images, laser scans, ...).
Definition at line 97 of file hyper_graph.h.
Constructor & Destructor Documentation
g2o::HyperGraph::Data::Data ()
Definition at line 34 of file hyper_graph.cpp.
References _dataContainer, and _next.
{
     _next = 0;
     _dataContainer = 0;
   }
g2o::HyperGraph::Data::~Data ()
Definition at line 39 of file hyper_graph.cpp.
References _next.
{
     delete _next;
   }
Member Function Documentation
DataContainer* g2o::HyperGraph::Data::dataContainer () inline
Definition at line 109 of file hyper_graph.h.
Referenced by g2o::OptimizableGraph::setFixed().
 { return _dataContainer;}
const DataContainer* g2o::HyperGraph::Data::dataContainer () const inline
Definition at line 110 of file hyper_graph.h.
 { return _dataContainer;}
virtual HyperGraph::HyperGraphElementType g2o::HyperGraph::Data::elementType () const inline virtual
returns the type of the graph element, see HyperGraphElementType
Implements g2o::HyperGraph::HyperGraphElement.
Definition at line 105 of file hyper_graph.h.
References HGET_DATA.
 { return HyperGraph::HGET_DATA;}
const Data* g2o::HyperGraph::Data::next () const inline
Definition at line 106 of file hyper_graph.h.
Referenced by g2o::deprecated::VertexSE3WriteGnuplotAction::operator()(), and g2o::OptimizableGraph::saveUserData().
 {return _next;}
Data* g2o::HyperGraph::Data::next () inline
Definition at line 107 of file hyper_graph.h.
 {return _next;}
virtual bool g2o::HyperGraph::Data::read (std::istream & is) pure virtual
read the data from a stream
Implemented in g2o::RawLaser, g2o::RobotLaser, g2o::VertexTag, and g2o::VertexEllipse.
Referenced by g2o::OptimizableGraph::setFixed().
void g2o::HyperGraph::Data::setDataContainer (DataContainer * dataContainer_) inline
Definition at line 111 of file hyper_graph.h.
Referenced by g2o::OptimizableGraph::setFixed().
 { _dataContainer = dataContainer_;}
void g2o::HyperGraph::Data::setNext (Data * next_) inline
Definition at line 108 of file hyper_graph.h.
Referenced by g2o::HyperGraph::DataContainer::addUserData(), and g2o::OptimizableGraph::setFixed().
 { _next = next_; }
virtual bool g2o::HyperGraph::Data::write (std::ostream & os) const pure virtual
write the data to a stream
Implemented in g2o::RawLaser, g2o::RobotLaser, g2o::VertexTag, and g2o::VertexEllipse.
Referenced by g2o::OptimizableGraph::saveUserData(), and g2o::Gm2dlIO::writeGm2dl().
Member Data Documentation
DataContainer* g2o::HyperGraph::Data::_dataContainer protected
Definition at line 114 of file hyper_graph.h.
Referenced by Data().
Data* g2o::HyperGraph::Data::_next protected
Definition at line 113 of file hyper_graph.h.
Referenced by Data(), and ~Data().
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/core/hyper_graph.h
/home/xuezhisd/CLionProjects/g2o/g2o/core/hyper_graph.cpp