g2o: g2o::EdgeProjectP2SC Class Reference
g2o::EdgeProjectP2SC Class Reference
#include <types_sba.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW EdgeProjectP2SC ()
virtual bool read (std::istream &is)
read the vertex from a stream, i.e., the internal state of the vertex
virtual bool write (std::ostream &os) const
write the vertex to a stream
void computeError ()
virtual void linearizeOplus ()
Jacobian for stereo projection.
Public Member Functions inherited from g2o::BaseBinaryEdge< 3, Vector3D, VertexSBAPointXYZ, VertexCam >
BaseBinaryEdge ()
virtual OptimizableGraph::Vertex * createFrom ()
virtual OptimizableGraph::Vertex * createTo ()
virtual OptimizableGraph::Vertex * createVertex (int i)
virtual void resize (size_t size)
virtual bool allVerticesFixed () const
virtual void linearizeOplus (JacobianWorkspace &jacobianWorkspace)
const JacobianXiOplusType & jacobianOplusXi () const
returns the result of the linearization in the manifold space for the node xi
const JacobianXjOplusType & jacobianOplusXj () const
returns the result of the linearization in the manifold space for the node xj
virtual void constructQuadraticForm ()
virtual void mapHessianMemory (double *d, int i, int j, bool rowMajor)
Public Member Functions inherited from g2o::BaseEdge< D, Vector3D >
BaseEdge ()
virtual ~BaseEdge ()
virtual double chi2 () const
computes the chi2 based on the cached error value, only valid after computeError has been called.
virtual const double * errorData () const
returns the error vector cached after calling the computeError;
virtual double * errorData ()
const ErrorVector & error () const
ErrorVector & error ()
EIGEN_STRONG_INLINE const InformationType & information () const
information matrix of the constraint
EIGEN_STRONG_INLINE InformationType & information ()
EIGEN_STRONG_INLINE void setInformation (const InformationType &information)
virtual const double * informationData () const
returns the memory of the information matrix, usable for example with a Eigen::Map<MatrixXD>
virtual double * informationData ()
EIGEN_STRONG_INLINE const Measurement & measurement () const
accessor functions for the measurement represented by the edge
virtual void setMeasurement (const Measurement &m)
virtual int rank () const
virtual void initialEstimate (const OptimizableGraph::VertexSet &, OptimizableGraph::Vertex *)
Public Member Functions inherited from g2o::OptimizableGraph::Edge
Edge ()
virtual ~Edge ()
virtual Edge * clone () const
virtual bool setMeasurementData (const double *m)
virtual bool getMeasurementData (double *m) const
virtual int measurementDimension () const
virtual bool setMeasurementFromState ()
RobustKernel * robustKernel () const
if NOT NULL, error of this edge will be robustifed with the kernel
void setRobustKernel (RobustKernel *ptr)
virtual double initialEstimatePossible (const OptimizableGraph::VertexSet &from, OptimizableGraph::Vertex *to)
int level () const
returns the level of the edge
void setLevel (int l)
sets the level of the edge
int dimension () const
returns the dimensions of the error function
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createFrom())
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createTo())
long long internalId () const
the internal ID of the edge
OptimizableGraph * graph ()
const OptimizableGraph * graph () const
bool setParameterId (int argNum, int paramId)
const Parameter * parameter (int argNo) const
size_t numParameters () const
void resizeParameters (size_t newSize)
Public Member Functions inherited from g2o::HyperGraph::Edge
Edge (int id=InvalidId)
creates and empty edge with no vertices
const VertexContainer & vertices () const
VertexContainer & vertices ()
const Vertex * vertex (size_t i) const
Vertex * vertex (size_t i)
void setVertex (size_t i, Vertex *v)
int id () const
void setId (int id)
virtual HyperGraphElementType elementType () const
int numUndefinedVertices () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Member Functions inherited from g2o::HyperGraph::DataContainer
DataContainer ()
virtual ~DataContainer ()
const Data * userData () const
the user data associated with this vertex
Data * userData ()
void setUserData (Data *obs)
void addUserData (Data *obs)
Additional Inherited Members
Public Types inherited from g2o::BaseBinaryEdge< 3, Vector3D, VertexSBAPointXYZ, VertexCam >
typedef VertexSBAPointXYZ VertexXiType
typedef VertexCam VertexXjType
typedef BaseEdge< D, Vector3D >::Measurement Measurement
typedef Eigen::Matrix< double, D, Di, D==1?Eigen::RowMajor:Eigen::ColMajor >::AlignedMapType JacobianXiOplusType
typedef Eigen::Matrix< double, D, Dj, D==1?Eigen::RowMajor:Eigen::ColMajor >::AlignedMapType JacobianXjOplusType
typedef BaseEdge< D, Vector3D >::ErrorVector ErrorVector
typedef BaseEdge< D, Vector3D >::InformationType InformationType
typedef Eigen::Map< Eigen::Matrix< double, Di, Dj, Di==1?Eigen::RowMajor:Eigen::ColMajor >, Eigen::Matrix< double, Di, Dj, Di==1?Eigen::RowMajor:Eigen::ColMajor >::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockType
typedef Eigen::Map< Eigen::Matrix< double, Dj, Di, Dj==1?Eigen::RowMajor:Eigen::ColMajor >, Eigen::Matrix< double, Dj, Di, Dj==1?Eigen::RowMajor:Eigen::ColMajor >::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockTransposedType
Public Types inherited from g2o::BaseEdge< D, Vector3D >
typedef Vector3D Measurement
typedef Eigen::Matrix< double, D, 1, Eigen::ColMajor > ErrorVector
typedef Eigen::Matrix< double, D, D, Eigen::ColMajor > InformationType
Static Public Attributes inherited from g2o::BaseBinaryEdge< 3, Vector3D, VertexSBAPointXYZ, VertexCam >
static const int Di
static const int Dj
static const int Dimension
Static Public Attributes inherited from g2o::BaseEdge< D, Vector3D >
static const int Dimension
Protected Member Functions inherited from g2o::BaseEdge< D, Vector3D >
InformationType robustInformation (const Vector3D &rho)
Protected Member Functions inherited from g2o::OptimizableGraph::Edge
template<typename ParameterType >
bool installParameter (ParameterType *&p, size_t argNo, int paramId=-1)
template<typename CacheType >
void resolveCache (CacheType *&cache, OptimizableGraph::Vertex *, const std::string &_type, const ParameterVector &parameters)
bool resolveParameters ()
virtual bool resolveCaches ()
Protected Attributes inherited from g2o::BaseBinaryEdge< 3, Vector3D, VertexSBAPointXYZ, VertexCam >
bool _hessianRowMajor
HessianBlockType _hessian
HessianBlockTransposedType _hessianTransposed
JacobianXiOplusType _jacobianOplusXi
JacobianXjOplusType _jacobianOplusXj
Protected Attributes inherited from g2o::BaseEdge< D, Vector3D >
Measurement _measurement
InformationType _information
ErrorVector _error
Protected Attributes inherited from g2o::OptimizableGraph::Edge
int _dimension
int _level
RobustKernel * _robustKernel
long long _internalId
std::vector< int > _cacheIds
std::vector< std::string > _parameterTypes
std::vector< Parameter ** > _parameters
std::vector< int > _parameterIds
Protected Attributes inherited from g2o::HyperGraph::Edge
VertexContainer _vertices
int _id
unique id
Protected Attributes inherited from g2o::HyperGraph::DataContainer
Data * _userData
Detailed Description
Definition at line 198 of file types_sba.h.
Constructor & Destructor Documentation
g2o::EdgeProjectP2SC::EdgeProjectP2SC ()
Definition at line 224 of file types_sba.cpp.
                                    :
     BaseBinaryEdge<3, Vector3D, VertexSBAPointXYZ, VertexCam>()
   {
   }
Member Function Documentation
void g2o::EdgeProjectP2SC::computeError () inline virtual
Implements g2o::OptimizableGraph::Edge.
Definition at line 207 of file types_sba.h.
References g2o::SBACam::baseline, g2o::BaseVertex< D, T >::estimate(), g2o::SBACam::Kcam, g2o::SBACam::w2i, and g2o::SBACam::w2n.
     {
       // from <Point> to <Cam>
       const VertexSBAPointXYZ *point = static_cast<const VertexSBAPointXYZ*>(_vertices[0]);
       VertexCam *cam = static_cast<VertexCam*>(_vertices[1]);
       // calculate the projection
       Vector3D kp;
       Vector4D pt;
       pt.head<3>() = point->estimate();
       pt(3) = 1.0;
       const SBACam& nd = cam->estimate();
       // these should be already ok
       /* nd.setTransform(); */
       /* nd.setProjection(); */
       /* nd.setDr(); */
       Vector3D p1 = nd.w2i * pt;
       Vector3D p2 = nd.w2n * pt;
       Vector3D pb(nd.baseline,0,0);
       double invp1 = 1.0/p1(2);
       kp.head<2>() = p1.head<2>()*invp1;
       // right camera px
       p2 = nd.Kcam*(p2-pb);
       kp(2) = p2(0)/p2(2);
       // std::cout << std::endl << "CAM   " << cam->estimate() << std::endl;
       // std::cout << "POINT " << pt.transpose() << std::endl;
       // std::cout << "PROJ  " << p1.transpose() << std::endl;
       // std::cout << "PROJ  " << p2.transpose() << std::endl;
       // std::cout << "CPROJ " << kp.transpose() << std::endl;
       // std::cout << "MEAS  " << _measurement.transpose() << std::endl;
       // error, which is backwards from the normal observed - calculated
       // _measurement is the measured projection
       _error = kp - _measurement;
     }
void g2o::EdgeProjectP2SC::linearizeOplus () virtual
Jacobian for stereo projection.
Reimplemented from g2o::BaseBinaryEdge< 3, Vector3D, VertexSBAPointXYZ, VertexCam >.
Definition at line 250 of file types_sba.cpp.
References g2o::BaseBinaryEdge< 3, Vector3D, VertexSBAPointXYZ, VertexCam >::_jacobianOplusXi, g2o::BaseBinaryEdge< 3, Vector3D, VertexSBAPointXYZ, VertexCam >::_jacobianOplusXj, g2o::HyperGraph::Edge::_vertices, g2o::SBACam::baseline, g2o::SBACam::dRdx, g2o::SBACam::dRdy, g2o::SBACam::dRdz, g2o::BaseVertex< D, T >::estimate(), g2o_isnan, g2o::SBACam::Kcam, g2o::SE3Quat::translation(), and g2o::SBACam::w2n.
   {
     VertexCam *vc = static_cast<VertexCam *>(_vertices[1]);
     const SBACam &cam = vc->estimate();
     VertexSBAPointXYZ *vp = static_cast<VertexSBAPointXYZ *>(_vertices[0]);
     Vector4D pt, trans;
     pt.head<3>() = vp->estimate();
     pt(3) = 1.0;
     trans.head<3>() = cam.translation();
     trans(3) = 1.0;
     // first get the world point in camera coords
     Eigen::Matrix<double,3,1,Eigen::ColMajor> pc = cam.w2n * pt;
     // Jacobians wrt camera parameters
     // set d(quat-x) values [ pz*dpx/dx - px*dpz/dx ] / pz^2
     double px = pc(0);
     double py = pc(1);
     double pz = pc(2);
     double ipz2 = 1.0/(pz*pz);
     if (g2o_isnan(ipz2) ) {
       std::cout << "[SetJac] infinite jac" << std::endl;
       abort();
     }
     double ipz2fx = ipz2*cam.Kcam(0,0); // Fx
     double ipz2fy = ipz2*cam.Kcam(1,1); // Fy
     double b      = cam.baseline; // stereo baseline
     Eigen::Matrix<double,3,1,Eigen::ColMajor> pwt;
     // check for local vars
     pwt = (pt-trans).head<3>(); // transform translations, use differential rotation
     // dx
     Eigen::Matrix<double,3,1,Eigen::ColMajor> dp = cam.dRdx * pwt; // dR'/dq * [pw - t]
     _jacobianOplusXj(0,3) = (pz*dp(0) - px*dp(2))*ipz2fx;
     _jacobianOplusXj(1,3) = (pz*dp(1) - py*dp(2))*ipz2fy;
     _jacobianOplusXj(2,3) = (pz*dp(0) - (px-b)*dp(2))*ipz2fx; // right image px
     // dy
     dp = cam.dRdy * pwt; // dR'/dq * [pw - t]
     _jacobianOplusXj(0,4) = (pz*dp(0) - px*dp(2))*ipz2fx;
     _jacobianOplusXj(1,4) = (pz*dp(1) - py*dp(2))*ipz2fy;
     _jacobianOplusXj(2,4) = (pz*dp(0) - (px-b)*dp(2))*ipz2fx; // right image px
     // dz
     dp = cam.dRdz * pwt; // dR'/dq * [pw - t]
     _jacobianOplusXj(0,5) = (pz*dp(0) - px*dp(2))*ipz2fx;
     _jacobianOplusXj(1,5) = (pz*dp(1) - py*dp(2))*ipz2fy;
     _jacobianOplusXj(2,5) = (pz*dp(0) - (px-b)*dp(2))*ipz2fx; // right image px
     // set d(t) values [ pz*dpx/dx - px*dpz/dx ] / pz^2
     dp = -cam.w2n.col(0);        // dpc / dx
     _jacobianOplusXj(0,0) = (pz*dp(0) - px*dp(2))*ipz2fx;
     _jacobianOplusXj(1,0) = (pz*dp(1) - py*dp(2))*ipz2fy;
     _jacobianOplusXj(2,0) = (pz*dp(0) - (px-b)*dp(2))*ipz2fx; // right image px
     dp = -cam.w2n.col(1);        // dpc / dy
     _jacobianOplusXj(0,1) = (pz*dp(0) - px*dp(2))*ipz2fx;
     _jacobianOplusXj(1,1) = (pz*dp(1) - py*dp(2))*ipz2fy;
     _jacobianOplusXj(2,1) = (pz*dp(0) - (px-b)*dp(2))*ipz2fx; // right image px
     dp = -cam.w2n.col(2);        // dpc / dz
     _jacobianOplusXj(0,2) = (pz*dp(0) - px*dp(2))*ipz2fx;
     _jacobianOplusXj(1,2) = (pz*dp(1) - py*dp(2))*ipz2fy;
     _jacobianOplusXj(2,2) = (pz*dp(0) - (px-b)*dp(2))*ipz2fx; // right image px
     // Jacobians wrt point parameters
     // set d(t) values [ pz*dpx/dx - px*dpz/dx ] / pz^2
     dp = cam.w2n.col(0); // dpc / dx
     _jacobianOplusXi(0,0) = (pz*dp(0) - px*dp(2))*ipz2fx;
     _jacobianOplusXi(1,0) = (pz*dp(1) - py*dp(2))*ipz2fy;
     _jacobianOplusXi(2,0) = (pz*dp(0) - (px-b)*dp(2))*ipz2fx; // right image px
     dp = cam.w2n.col(1); // dpc / dy
     _jacobianOplusXi(0,1) = (pz*dp(0) - px*dp(2))*ipz2fx;
     _jacobianOplusXi(1,1) = (pz*dp(1) - py*dp(2))*ipz2fy;
     _jacobianOplusXi(2,1) = (pz*dp(0) - (px-b)*dp(2))*ipz2fx; // right image px
     dp = cam.w2n.col(2); // dpc / dz
     _jacobianOplusXi(0,2) = (pz*dp(0) - px*dp(2))*ipz2fx;
     _jacobianOplusXi(1,2) = (pz*dp(1) - py*dp(2))*ipz2fy;
     _jacobianOplusXi(2,2) = (pz*dp(0) - (px-b)*dp(2))*ipz2fx; // right image px
   }
bool g2o::EdgeProjectP2SC::read (std::istream & is) virtual
read the vertex from a stream, i.e., the internal state of the vertex
Implements g2o::OptimizableGraph::Edge.
Definition at line 229 of file types_sba.cpp.
References g2o::BaseEdge< D, Vector3D >::information(), and g2o::BaseEdge< D, Vector3D >::setMeasurement().
   {
     Vector3D meas;
     for (int i=0; i<3; i++)
       is >> meas[i];
     setMeasurement(meas);
     // information matrix is the identity for features, could be changed to allow arbitrary covariances
     information().setIdentity();
     return true;
   }
bool g2o::EdgeProjectP2SC::write (std::ostream & os) const virtual
write the vertex to a stream
Implements g2o::OptimizableGraph::Edge.
Definition at line 240 of file types_sba.cpp.
References g2o::BaseEdge< D, Vector3D >::measurement().
   {
     for (int i=0; i<3; i++)
       os  << measurement()[i] << " ";
     return os.good();
   }
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/sba/types_sba.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/sba/types_sba.cpp