g2o: g2o::EdgeProjectPSI2UV Class Reference
g2o::EdgeProjectPSI2UV Class Reference
#include <types_six_dof_expmap.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW EdgeProjectPSI2UV ()
virtual bool read (std::istream &is)
read the vertex from a stream, i.e., the internal state of the vertex
virtual bool write (std::ostream &os) const
write the vertex to a stream
void computeError ()
virtual void linearizeOplus ()
Public Member Functions inherited from g2o::BaseMultiEdge< 2, Vector2D >
BaseMultiEdge ()
virtual void linearizeOplus (JacobianWorkspace &jacobianWorkspace)
virtual void resize (size_t size)
virtual bool allVerticesFixed () const
virtual void constructQuadraticForm ()
virtual void mapHessianMemory (double *d, int i, int j, bool rowMajor)
Public Member Functions inherited from g2o::BaseEdge< D, Vector2D >
BaseEdge ()
virtual ~BaseEdge ()
virtual double chi2 () const
computes the chi2 based on the cached error value, only valid after computeError has been called.
virtual const double * errorData () const
returns the error vector cached after calling the computeError;
virtual double * errorData ()
const ErrorVector & error () const
ErrorVector & error ()
EIGEN_STRONG_INLINE const InformationType & information () const
information matrix of the constraint
EIGEN_STRONG_INLINE InformationType & information ()
EIGEN_STRONG_INLINE void setInformation (const InformationType &information)
virtual const double * informationData () const
returns the memory of the information matrix, usable for example with a Eigen::Map<MatrixXD>
virtual double * informationData ()
EIGEN_STRONG_INLINE const Measurement & measurement () const
accessor functions for the measurement represented by the edge
virtual void setMeasurement (const Measurement &m)
virtual int rank () const
virtual void initialEstimate (const OptimizableGraph::VertexSet &, OptimizableGraph::Vertex *)
Public Member Functions inherited from g2o::OptimizableGraph::Edge
Edge ()
virtual ~Edge ()
virtual Edge * clone () const
virtual bool setMeasurementData (const double *m)
virtual bool getMeasurementData (double *m) const
virtual int measurementDimension () const
virtual bool setMeasurementFromState ()
RobustKernel * robustKernel () const
if NOT NULL, error of this edge will be robustifed with the kernel
void setRobustKernel (RobustKernel *ptr)
virtual double initialEstimatePossible (const OptimizableGraph::VertexSet &from, OptimizableGraph::Vertex *to)
int level () const
returns the level of the edge
void setLevel (int l)
sets the level of the edge
int dimension () const
returns the dimensions of the error function
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createFrom())
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createTo())
virtual Vertex * createVertex (int)
long long internalId () const
the internal ID of the edge
OptimizableGraph * graph ()
const OptimizableGraph * graph () const
bool setParameterId (int argNum, int paramId)
const Parameter * parameter (int argNo) const
size_t numParameters () const
void resizeParameters (size_t newSize)
Public Member Functions inherited from g2o::HyperGraph::Edge
Edge (int id=InvalidId)
creates and empty edge with no vertices
const VertexContainer & vertices () const
VertexContainer & vertices ()
const Vertex * vertex (size_t i) const
Vertex * vertex (size_t i)
void setVertex (size_t i, Vertex *v)
int id () const
void setId (int id)
virtual HyperGraphElementType elementType () const
int numUndefinedVertices () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Member Functions inherited from g2o::HyperGraph::DataContainer
DataContainer ()
virtual ~DataContainer ()
const Data * userData () const
the user data associated with this vertex
Data * userData ()
void setUserData (Data *obs)
void addUserData (Data *obs)
Public Attributes
CameraParameters * _cam
Additional Inherited Members
Public Types inherited from g2o::BaseMultiEdge< 2, Vector2D >
typedef BaseEdge< D, Vector2D >::Measurement Measurement
typedef MatrixXD::MapType JacobianType
typedef BaseEdge< D, Vector2D >::ErrorVector ErrorVector
typedef BaseEdge< D, Vector2D >::InformationType InformationType
typedef Eigen::Map< MatrixXD, MatrixXD::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockType
Public Types inherited from g2o::BaseEdge< D, Vector2D >
typedef Vector2D Measurement
typedef Eigen::Matrix< double, D, 1, Eigen::ColMajor > ErrorVector
typedef Eigen::Matrix< double, D, D, Eigen::ColMajor > InformationType
Static Public Attributes inherited from g2o::BaseMultiEdge< 2, Vector2D >
static const int Dimension
Static Public Attributes inherited from g2o::BaseEdge< D, Vector2D >
static const int Dimension
Protected Member Functions inherited from g2o::BaseMultiEdge< 2, Vector2D >
void computeQuadraticForm (const InformationType &omega, const ErrorVector &weightedError)
Protected Member Functions inherited from g2o::BaseEdge< D, Vector2D >
InformationType robustInformation (const Vector3D &rho)
Protected Member Functions inherited from g2o::OptimizableGraph::Edge
template<typename ParameterType >
bool installParameter (ParameterType *&p, size_t argNo, int paramId=-1)
template<typename CacheType >
void resolveCache (CacheType *&cache, OptimizableGraph::Vertex *, const std::string &_type, const ParameterVector &parameters)
bool resolveParameters ()
virtual bool resolveCaches ()
Protected Attributes inherited from g2o::BaseMultiEdge< 2, Vector2D >
std::vector< HessianHelper > _hessian
std::vector< JacobianType, Eigen::aligned_allocator< JacobianType > > _jacobianOplus
jacobians of the edge (w.r.t. oplus)
Protected Attributes inherited from g2o::BaseEdge< D, Vector2D >
Measurement _measurement
InformationType _information
ErrorVector _error
Protected Attributes inherited from g2o::OptimizableGraph::Edge
int _dimension
int _level
RobustKernel * _robustKernel
long long _internalId
std::vector< int > _cacheIds
std::vector< std::string > _parameterTypes
std::vector< Parameter ** > _parameters
std::vector< int > _parameterIds
Protected Attributes inherited from g2o::HyperGraph::Edge
VertexContainer _vertices
int _id
unique id
Protected Attributes inherited from g2o::HyperGraph::DataContainer
Data * _userData
Detailed Description
Definition at line 156 of file types_six_dof_expmap.h.
Constructor & Destructor Documentation
EIGEN_MAKE_ALIGNED_OPERATOR_NEW g2o::EdgeProjectPSI2UV::EdgeProjectPSI2UV () inline
Definition at line 161 of file types_six_dof_expmap.h.
{
     resizeParameters(1);
     installParameter(_cam, 0);
   }
Member Function Documentation
void g2o::EdgeProjectPSI2UV::computeError () virtual
Implements g2o::OptimizableGraph::Edge.
Definition at line 174 of file types_six_dof_expmap.cpp.
References g2o::BaseEdge< D, Vector2D >::_error, g2o::BaseEdge< D, Vector2D >::_measurement, g2o::HyperGraph::Edge::_vertices, g2o::CameraParameters::cam_map(), g2o::BaseVertex< D, T >::estimate(), g2o::SE3Quat::inverse(), g2o::invert_depth(), and g2o::OptimizableGraph::Edge::parameter().
{
   const VertexSBAPointXYZ * psi = static_cast<const VertexSBAPointXYZ*>(_vertices[0]);
   const VertexSE3Expmap * T_p_from_world = static_cast<const VertexSE3Expmap*>(_vertices[1]);
   const VertexSE3Expmap * T_anchor_from_world = static_cast<const VertexSE3Expmap*>(_vertices[2]);
   const CameraParameters * cam = static_cast<const CameraParameters *>(parameter(0));
   Vector2D obs(_measurement);
   _error = obs - cam->cam_map(T_p_from_world->estimate()
         *T_anchor_from_world->estimate().inverse()
         *invert_depth(psi->estimate()));
 }
void g2o::EdgeProjectPSI2UV::linearizeOplus () virtual
Linearizes the oplus operator in the vertex, and stores the result in temporary variable vector _jacobianOplus
Reimplemented from g2o::BaseMultiEdge< 2, Vector2D >.
Definition at line 215 of file types_six_dof_expmap.cpp.
References g2o::HyperGraph::Edge::_vertices, g2o::d_expy_d_y(), g2o::d_proj_d_y(), g2o::d_Tinvpsi_d_psi(), g2o::BaseVertex< D, T >::estimate(), g2o::CameraParameters::focal_length, g2o::SE3Quat::inverse(), g2o::invert_depth(), g2o::OptimizableGraph::Edge::parameter(), and g2o::SE3Quat::rotation().
{
   VertexSBAPointXYZ* vpoint = static_cast<VertexSBAPointXYZ*>(_vertices[0]);
   Vector3D psi_a = vpoint->estimate();
   VertexSE3Expmap * vpose = static_cast<VertexSE3Expmap *>(_vertices[1]);
   SE3Quat T_cw = vpose->estimate();
   VertexSE3Expmap * vanchor = static_cast<VertexSE3Expmap *>(_vertices[2]);
   const CameraParameters * cam
       = static_cast<const CameraParameters *>(parameter(0));
   SE3Quat A_aw = vanchor->estimate();
   SE3Quat T_ca = T_cw*A_aw.inverse();
   Vector3D x_a = invert_depth(psi_a);
   Vector3D y = T_ca*x_a;
   Matrix<double,2,3,Eigen::ColMajor> Jcam
       = d_proj_d_y(cam->focal_length, y);
   _jacobianOplus[0] = -Jcam*d_Tinvpsi_d_psi(T_ca, psi_a);
   _jacobianOplus[1] = -Jcam*d_expy_d_y(y);
   _jacobianOplus[2] = Jcam*T_ca.rotation().toRotationMatrix()*d_expy_d_y(x_a);
 }
bool g2o::EdgeProjectPSI2UV::read (std::istream & is) virtual
read the vertex from a stream, i.e., the internal state of the vertex
Implements g2o::OptimizableGraph::Edge.
Definition at line 157 of file types_six_dof_expmap.cpp.
References g2o::BaseEdge< D, Vector2D >::_measurement, g2o::BaseEdge< D, Vector2D >::information(), and g2o::OptimizableGraph::Edge::setParameterId().
{
   int paramId;
   is >> paramId;
   setParameterId(0, paramId);
   for (int i=0; i<2; i++){
     is >> _measurement[i];
   }
   for (int i=0; i<2; i++)
     for (int j=i; j<2; j++) {
       is >> information()(i,j);
       if (i!=j)
         information()(j,i)=information()(i,j);
     }
   return true;
 }
bool g2o::EdgeProjectPSI2UV::write (std::ostream & os) const virtual
write the vertex to a stream
Implements g2o::OptimizableGraph::Edge.
Definition at line 144 of file types_six_dof_expmap.cpp.
References g2o::EdgeProjectXYZ2UV::_cam, g2o::Parameter::id(), g2o::BaseEdge< D, Vector2D >::information(), and g2o::BaseEdge< D, Vector2D >::measurement().
{
   os << _cam->id() << " ";
   for (int i=0; i<2; i++){
     os << measurement()[i] << " ";
   }
   for (int i=0; i<2; i++)
     for (int j=i; j<2; j++){
       os << " " <<  information()(i,j);
     }
   return os.good();
 }
Member Data Documentation
CameraParameters* g2o::EdgeProjectPSI2UV::_cam
Definition at line 170 of file types_six_dof_expmap.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/sba/types_six_dof_expmap.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/sba/types_six_dof_expmap.cpp