g2o: g2o::BaseSensor Class Reference
g2o::BaseSensor Class Reference abstract
#include <simulator.h>
Public Member Functions
BaseSensor (const std::string &name_)
BaseRobot * robot ()
void setRobot (BaseRobot *robot_)
World * world ()
OptimizableGraph * graph ()
std::vector< Parameter * > parameters ()
virtual void sense ()=0
virtual void addParameters ()
Protected Attributes
std::string _name
std::vector< Parameter * > _parameters
BaseRobot * _robot
Detailed Description
Definition at line 126 of file simulator.h.
Constructor & Destructor Documentation
g2o::BaseSensor::BaseSensor (const std::string & name_) inline
Definition at line 128 of file simulator.h.
 { _name = name_;}
Member Function Documentation
virtual void g2o::BaseSensor::addParameters () inline virtual
Reimplemented in g2o::SensorPointXYOffset, g2o::SensorPointXYZDisparity, g2o::SensorPose3DOffset, g2o::SensorPointLine3D, g2o::SensorPointXYZ, g2o::SensorPointXYZDepth, and g2o::SensorSE3Prior.
Definition at line 135 of file simulator.h.
Referenced by g2o::BaseRobot::addSensor().
 {}
OptimizableGraph * g2o::BaseSensor::graph ()
Definition at line 75 of file simulator.cpp.
Referenced by g2o::SensorOdometry< R, E, O >::sense(), g2o::SensorPose3DOffset::sense(), g2o::SensorOdometry2D::sense(), g2o::SensorPose3D::sense(), g2o::SensorOdometry3D::sense(), g2o::SensorPointXY::sense(), g2o::SensorPointXYZDepth::sense(), g2o::SensorPose2D::sense(), g2o::SensorSE3Prior::sense(), g2o::SensorPointXYZ::sense(), g2o::SensorPointXYZDisparity::sense(), g2o::SensorSegment2DPointLine::sense(), g2o::SensorSegment2DLine::sense(), g2o::SensorPointXYOffset::sense(), g2o::SensorSegment2D::sense(), and g2o::SensorPointXYBearing::sense().
{
     if (!_robot)
       return 0;
     return _robot->graph();
   }
std::vector<Parameter*> g2o::BaseSensor::parameters () inline
Definition at line 133 of file simulator.h.
 {return _parameters;}
BaseRobot* g2o::BaseSensor::robot () inline
Definition at line 129 of file simulator.h.
Referenced by g2o::SensorOdometry< R, E, O >::sense(), g2o::SensorPose3DOffset::sense(), g2o::SensorOdometry2D::sense(), g2o::SensorPose3D::sense(), g2o::SensorOdometry3D::sense(), g2o::SensorPointXY::sense(), g2o::SensorPointXYZDepth::sense(), g2o::SensorPose2D::sense(), g2o::SensorSE3Prior::sense(), g2o::SensorPointXYZ::sense(), g2o::SensorPointXYZDisparity::sense(), g2o::SensorSegment2DPointLine::sense(), g2o::SensorSegment2DLine::sense(), g2o::SensorPointXYOffset::sense(), g2o::SensorSegment2D::sense(), and g2o::SensorPointXYBearing::sense().
 {return _robot;}
virtual void g2o::BaseSensor::sense () pure virtual
Implemented in g2o::BinarySensor< RobotType_, EdgeType_, WorldObjectType_ >, g2o::BinarySensor< Robot3D, EdgeSE3PointXYZDisparity, WorldObjectTrackXYZ >, g2o::BinarySensor< Robot3D, EdgeSE3Offset, WorldObjectSE3 >, g2o::BinarySensor< Robot2D, EdgeSE2PointXYBearing, WorldObjectPointXY >, g2o::BinarySensor< R, E, O >, g2o::BinarySensor< Robot2D, EdgeSE2Segment2DPointLine, WorldObjectSegment2D >, g2o::BinarySensor< Robot2D, EdgeSE2Segment2DLine, WorldObjectSegment2D >, g2o::BinarySensor< Robot3D, EdgeSE3PointXYZ, WorldObjectTrackXYZ >, g2o::BinarySensor< Robot2D, EdgeSE2, WorldObjectSE2 >, g2o::BinarySensor< Robot3D, EdgeSE3, WorldObjectSE3 >, g2o::BinarySensor< Robot2D, EdgeSE2Segment2D, WorldObjectSegment2D >, g2o::BinarySensor< Robot3D, EdgeSE3Line WorldObjectLine3D >, g2o::BinarySensor< Robot3D, EdgeSE3PointXYZDepth, WorldObjectTrackXYZ >, g2o::BinarySensor< Robot2D, EdgeSE2PointXYOffset, WorldObjectPointXY >, g2o::BinarySensor< Robot2D, EdgeSE2PointXY, WorldObjectPointXY >, g2o::UnarySensor< RobotType_, EdgeType_ >, g2o::UnarySensor< Robot3D, EdgeSE3Prior >, g2o::SensorPointXYBearing, g2o::SensorPointXYOffset, g2o::SensorPointXYZDisparity, g2o::SensorSegment2D, g2o::SensorSegment2DLine, g2o::SensorSegment2DPointLine, g2o::SensorPointLine3D, g2o::SensorPointXY, g2o::SensorPointXYZ, g2o::SensorPointXYZDepth, g2o::SensorPose2D, g2o::SensorSE3Prior, g2o::SensorOdometry2D, g2o::SensorOdometry3D, g2o::SensorPose3D, g2o::SensorOdometry< R, E, O >, and g2o::SensorPose3DOffset.
Referenced by g2o::BaseRobot::sense().
void g2o::BaseSensor::setRobot (BaseRobot * robot_) inline
Definition at line 130 of file simulator.h.
References graph.
Referenced by g2o::BaseRobot::addSensor().
 {_robot = robot_;}
World * g2o::BaseSensor::world ()
Definition at line 69 of file simulator.cpp.
Referenced by g2o::SensorPointXYZ::addParameters(), g2o::SensorPointXYZDepth::addParameters(), g2o::SensorSE3Prior::addParameters(), g2o::SensorPointXYZDisparity::addParameters(), g2o::SensorPose3DOffset::addParameters(), g2o::SensorPointXYOffset::addParameters(), g2o::SensorPose3DOffset::sense(), g2o::SensorPose3D::sense(), g2o::SensorPointXYZDepth::sense(), g2o::SensorPose2D::sense(), g2o::SensorPointXYZ::sense(), g2o::SensorPointXY::sense(), g2o::SensorSegment2D::sense(), g2o::SensorSegment2DLine::sense(), g2o::SensorPointXYBearing::sense(), g2o::SensorSegment2DPointLine::sense(), g2o::SensorPointXYOffset::sense(), and g2o::SensorPointXYZDisparity::sense().
{
     if (!_robot)
       return 0;
     return _robot->world();
   }
Member Data Documentation
std::string g2o::BaseSensor::_name protected
Definition at line 137 of file simulator.h.
std::vector<Parameter*> g2o::BaseSensor::_parameters protected
Definition at line 138 of file simulator.h.
BaseRobot* g2o::BaseSensor::_robot protected
Definition at line 139 of file simulator.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_simulator/simulator.h
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_simulator/simulator.cpp