g2o: SlamParser::SlamContextInterface Class Reference
SlamParser::SlamContextInterface Class Reference
#include <slam_context_interface.h>
Public Member Functions
SlamContextInterface (AbstractSlamInterface *slam)
~SlamContextInterface ()
bool process (CommandNode *commandNode)
Public Member Functions inherited from SlamParser::SlamContext
SlamContext ()
virtual ~SlamContext ()
Protected Attributes
AbstractSlamInterface * _slam
Detailed Description
Definition at line 36 of file slam_context_interface.h.
Constructor & Destructor Documentation
SlamParser::SlamContextInterface::SlamContextInterface (AbstractSlamInterface * slam)
Definition at line 37 of file slam_context_interface.cpp.
                                                                         :
     SlamContext(),
     _slam(slam)
   {
   }
SlamParser::SlamContextInterface::~SlamContextInterface ()
Definition at line 43 of file slam_context_interface.cpp.
   {
   }
Member Function Documentation
bool SlamParser::SlamContextInterface::process (CommandNode * commandNode) virtual
Reimplemented from SlamParser::SlamContext.
Definition at line 47 of file slam_context_interface.cpp.
References _slam, SlamParser::AbstractSlamInterface::addEdge(), SlamParser::AbstractSlamInterface::addNode(), SlamParser::CommandNode::commandType(), SlamParser::CT_ADD_EDGE, SlamParser::CT_ADD_NODE, SlamParser::CT_FIX, SlamParser::CT_QUERY_STATE, SlamParser::CT_SOLVE_STATE, SlamParser::AddNode::dimension(), SlamParser::AddEdge::dimension(), SlamParser::AbstractSlamInterface::fixNode(), SlamParser::AddNode::id(), SlamParser::AddEdge::id(), SlamParser::AddEdge::id1(), SlamParser::AddEdge::id2(), SlamParser::QueryState::ids(), SlamParser::FixNode::ids(), SlamParser::AddEdge::information(), SlamParser::AbstractSlamInterface::queryState(), SlamParser::AbstractSlamInterface::solveState(), SlamParser::CommandNode::tag(), SlamParser::AddNode::values(), and SlamParser::AddEdge::values().
   {
     if (! _slam) {
       return true;
     }
     switch (commandNode->commandType()) {
       case CT_ADD_NODE:
         {
           AddNode* c = static_cast<AddNode*>(commandNode);
           return _slam->addNode(c->tag(), c->id(), c->dimension(), c->values());
         }
       case CT_ADD_EDGE:
         {
           AddEdge* c = static_cast<AddEdge*>(commandNode);
           return _slam->addEdge(c->tag(), c->id(), c->dimension(), c->id1(), c->id2(), c->values(), c->information());
         }
       case CT_SOLVE_STATE:
         {
           //SolveState* c = static_cast<SolveState*>(commandNode);
           return _slam->solveState();
         }
       case CT_QUERY_STATE:
         {
           QueryState* c = static_cast<QueryState*>(commandNode);
           return _slam->queryState(c->ids());
         }
       case CT_FIX:
         {
           FixNode* c = static_cast<FixNode*>(commandNode);
           return _slam->fixNode(c->ids());
         }
     }
     cerr << "SlamContextInterface::process: Unknown command type" << endl;
     return false;
   }
Member Data Documentation
AbstractSlamInterface* SlamParser::SlamContextInterface::_slam protected
Definition at line 45 of file slam_context_interface.h.
Referenced by process().
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/examples/interactive_slam/slam_parser/interface/slam_context_interface.h
/home/xuezhisd/CLionProjects/g2o/g2o/examples/interactive_slam/slam_parser/interface/slam_context_interface.cpp