g2o: g2o::SensorOdometry< R, E, O > Class Template Reference
g2o::SensorOdometry< R, E, O > Class Template Reference
#include <sensor_odometry.h>
Public Member Functions
SensorOdometry (const std::string name_)
virtual EIGEN_MAKE_ALIGNED_OPERATOR_NEW void sense ()
Public Member Functions inherited from g2o::BinarySensor< R, E, O >
BinarySensor (const std::string &name)
void setInformation (const InformationType &information_)
const InformationType & information ()
Public Member Functions inherited from g2o::BaseSensor
BaseSensor (const std::string &name_)
BaseRobot * robot ()
void setRobot (BaseRobot *robot_)
World * world ()
OptimizableGraph * graph ()
std::vector< Parameter * > parameters ()
virtual void addParameters ()
Additional Inherited Members
Public Types inherited from g2o::BinarySensor< R, E, O >
typedef R RobotType
typedef RobotType::PoseObject PoseObject
typedef RobotType::TrajectoryType TrajectoryType
typedef RobotType::PoseObject::VertexType PoseVertexType
typedef E EdgeType
typedef O WorldObjectType
typedef WorldObjectType::VertexType VertexType
typedef EdgeType::InformationType InformationType
Public Attributes inherited from g2o::BinarySensor< R, E, O >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Member Functions inherited from g2o::BinarySensor< R, E, O >
EdgeType * mkEdge (WorldObjectType *object)
virtual void addNoise (EdgeType *)
Protected Attributes inherited from g2o::BinarySensor< R, E, O >
PoseObject * _robotPoseObject
InformationType _information
GaussianSampler< typename EdgeType::ErrorVector, InformationType > _sampler
Protected Attributes inherited from g2o::BaseSensor
std::string _name
std::vector< Parameter * > _parameters
BaseRobot * _robot
Detailed Description
template<class R, class E, class O>
class g2o::SensorOdometry< R, E, O >
Definition at line 34 of file sensor_odometry.h.
Constructor & Destructor Documentation
template<class R , class E , class O > g2o::SensorOdometry< R, E, O >::SensorOdometry (const std::string name_) inline
Definition at line 36 of file sensor_odometry.h.
References g2o::BinarySensor< R, E, O >::EIGEN_MAKE_ALIGNED_OPERATOR_NEW.
 : BinarySensor<R, E, O> (name_){};
Member Function Documentation
template<class R , class E , class O > virtual EIGEN_MAKE_ALIGNED_OPERATOR_NEW void g2o::SensorOdometry< R, E, O >::sense () inline virtual
Reimplemented from g2o::BinarySensor< R, E, O >.
Definition at line 38 of file sensor_odometry.h.
References __PRETTY_FUNCTION__, g2o::BinarySensor< R, E, O >::_robotPoseObject, g2o::OptimizableGraph::addEdge(), g2o::BinarySensor< R, E, O >::addNoise(), g2o::BaseSensor::graph(), g2o::BinarySensor< R, E, O >::mkEdge(), and g2o::BaseSensor::robot().
{
       if (!  BinarySensor<R, E, O>::robot())
   return;
       typename BinarySensor<R, E, O>::RobotType* r =dynamic_cast<typename BinarySensor<R, E, O>::RobotType*>(robot());
       if (!r)
   return;
       PoseObject* pprev=0, *pcurr=0;
       std::list<PoseObject*>::reverse_iterator it=r->trajectory().rbegin();
       if (it!=r->trajectory().rend()){
   pcurr = *it;
   it++;
       }
       if (it!=r->trajectory().rend()){
   pprev = *it;
   it++;
       }
       if (!(pcurr&&pprev)) {
   cerr << __PRETTY_FUNCTION__ << ": fatal, trajectory empty" << endl;
   return;
       }
       _robotPoseObject = pprev;
       EdgeType* e=mkEdge(pcurr);
       if (e){
   addNoise(e);
   if (graph())
     graph()->addEdge(e);
       }
     _robotPoseObject = pcurr;
     }
The documentation for this class was generated from the following file:
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_simulator/sensor_odometry.h