g2o: g2o::OnlineVertexSE3 Class Reference
g2o::OnlineVertexSE3 Class Reference
#include <types_slam3d_online.h>
Public Member Functions
OnlineVertexSE3 ()
virtual void oplusImpl (const double *update)
void oplusUpdatedEstimate (double *update)
Public Member Functions inherited from g2o::VertexSE3
VertexSE3 ()
virtual void setToOriginImpl ()
sets the node to the origin (used in the multilevel stuff)
virtual bool read (std::istream &is)
read the vertex from a stream, i.e., the internal state of the vertex
virtual bool write (std::ostream &os) const
write the vertex to a stream
virtual bool setEstimateDataImpl (const double *est)
virtual bool getEstimateData (double *est) const
virtual int estimateDimension () const
virtual bool setMinimalEstimateDataImpl (const double *est)
virtual bool getMinimalEstimateData (double *est) const
virtual int minimalEstimateDimension () const
SE3Quat G2O_ATTRIBUTE_DEPRECATED (estimateAsSE3Quat() const)
wrapper function to use the old SE3 type
void G2O_ATTRIBUTE_DEPRECATED (setEstimateFromSE3Quat(const SE3Quat &se3))
wrapper function to use the old SE3 type
Public Member Functions inherited from g2o::BaseVertex< 6, Isometry3D >
BaseVertex ()
virtual const double & hessian (int i, int j) const
get the element from the hessian matrix
virtual double & hessian (int i, int j)
virtual double hessianDeterminant () const
virtual double * hessianData ()
virtual void mapHessianMemory (double *d)
virtual int copyB (double *b_) const
virtual const double & b (int i) const
get the b vector element
virtual double & b (int i)
Eigen::Matrix< double, D, 1, Eigen::ColMajor > & b ()
return right hand side b of the constructed linear system
const Eigen::Matrix< double, D, 1, Eigen::ColMajor > & b () const
virtual double * bData ()
return a pointer to the b vector associated with this vertex
virtual void clearQuadraticForm ()
virtual double solveDirect (double lambda=0)
HessianBlockType & A ()
return the hessian block associated with the vertex
const HessianBlockType & A () const
virtual void push ()
backup the position of the vertex to a stack
virtual void pop ()
restore the position of the vertex by retrieving the position from the stack
virtual void discardTop ()
pop the last element from the stack, without restoring the current estimate
virtual int stackSize () const
return the stack size
const EstimateType & estimate () const
return the current estimate of the vertex
void setEstimate (const EstimateType &et)
set the estimate for the vertex also calls updateCache()
Public Member Functions inherited from g2o::OptimizableGraph::Vertex
Vertex ()
virtual Vertex * clone () const
returns a deep copy of the current vertex
virtual ~Vertex ()
void setToOrigin ()
sets the node to the origin (used in the multilevel stuff)
bool setEstimateData (const double *estimate)
bool setEstimateData (const std::vector< double > &estimate)
virtual bool getEstimateData (std::vector< double > &estimate) const
bool setMinimalEstimateData (const double *estimate)
bool setMinimalEstimateData (const std::vector< double > &estimate)
virtual bool getMinimalEstimateData (std::vector< double > &estimate) const
void oplus (const double *v)
int hessianIndex () const
temporary index of this node in the parameter vector obtained from linearization
int G2O_ATTRIBUTE_DEPRECATED (tempIndex() const)
void setHessianIndex (int ti)
set the temporary index of the vertex in the parameter blocks
void G2O_ATTRIBUTE_DEPRECATED (setTempIndex(int ti))
bool fixed () const
true => this node is fixed during the optimization
void setFixed (bool fixed)
true => this node should be considered fixed during the optimization
bool marginalized () const
true => this node is marginalized out during the optimization
void setMarginalized (bool marginalized)
true => this node should be marginalized out during the optimization
int dimension () const
dimension of the estimated state belonging to this node
virtual void setId (int id)
sets the id of the node in the graph be sure that the graph keeps consistent after changing the id
void setColInHessian (int c)
set the row of this vertex in the Hessian
int colInHessian () const
get the row of this vertex in the Hessian
const OptimizableGraph * graph () const
OptimizableGraph * graph ()
void lockQuadraticForm ()
void unlockQuadraticForm ()
virtual void updateCache ()
CacheContainer * cacheContainer ()
Public Member Functions inherited from g2o::HyperGraph::Vertex
Vertex (int id=InvalidId)
creates a vertex having an ID specified by the argument
int id () const
returns the id
const EdgeSet & edges () const
returns the set of hyper-edges that are leaving/entering in this vertex
EdgeSet & edges ()
returns the set of hyper-edges that are leaving/entering in this vertex
virtual HyperGraphElementType elementType () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Member Functions inherited from g2o::HyperGraph::DataContainer
DataContainer ()
virtual ~DataContainer ()
const Data * userData () const
the user data associated with this vertex
Data * userData ()
void setUserData (Data *obs)
void addUserData (Data *obs)
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
VertexSE3::EstimateType updatedEstimate
Public Attributes inherited from g2o::VertexSE3
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Additional Inherited Members
Public Types inherited from g2o::BaseVertex< 6, Isometry3D >
typedef Isometry3D EstimateType
typedef std::stack< EstimateType, std::vector< EstimateType, Eigen::aligned_allocator< EstimateType > > > BackupStackType
typedef Eigen::Map< Eigen::Matrix< double, D, D, Eigen::ColMajor >, Eigen::Matrix< double, D, D, Eigen::ColMajor >::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockType
Static Public Attributes inherited from g2o::VertexSE3
static const int orthogonalizeAfter = 1000
Static Public Attributes inherited from g2o::BaseVertex< 6, Isometry3D >
static const int Dimension
dimension of the estimate (minimal) in the manifold space
Protected Attributes inherited from g2o::VertexSE3
int _numOplusCalls
store how often opluse was called to trigger orthogonaliation of the rotation matrix
Protected Attributes inherited from g2o::BaseVertex< 6, Isometry3D >
HessianBlockType _hessian
Eigen::Matrix< double, D, 1, Eigen::ColMajor > _b
EstimateType _estimate
BackupStackType _backup
Protected Attributes inherited from g2o::OptimizableGraph::Vertex
OptimizableGraph * _graph
Data * _userData
int _hessianIndex
bool _fixed
bool _marginalized
int _dimension
int _colInHessian
OpenMPMutex _quadraticFormMutex
CacheContainer * _cacheContainer
Protected Attributes inherited from g2o::HyperGraph::Vertex
int _id
EdgeSet _edges
Protected Attributes inherited from g2o::HyperGraph::DataContainer
Data * _userData
Detailed Description
Definition at line 37 of file types_slam3d_online.h.
Constructor & Destructor Documentation
g2o::OnlineVertexSE3::OnlineVertexSE3 () inline
Definition at line 41 of file types_slam3d_online.h.
 : VertexSE3(), updatedEstimate(Eigen::Isometry3d::Identity()) {}
Member Function Documentation
virtual void g2o::OnlineVertexSE3::oplusImpl (const double * update) inline virtual
update the position of this vertex. The update is in the form (x,y,z,qx,qy,qz) whereas (x,y,z) represents the translational update and (qx,qy,qz) corresponds to the respective elements. The missing element qw of the quaternion is recovred by || (qw,qx,qy,qz) || == 1 => qw = sqrt(1 - || (qx,qy,qz) ||
Reimplemented from g2o::VertexSE3.
Definition at line 43 of file types_slam3d_online.h.
References g2o::VertexSE3::oplusImpl().
       {
         VertexSE3::oplusImpl(update);
         updatedEstimate = _estimate;
       }
void g2o::OnlineVertexSE3::oplusUpdatedEstimate (double * update) inline
Definition at line 49 of file types_slam3d_online.h.
References g2o::internal::fromVectorMQT().
Referenced by g2o::SparseOptimizerOnline::update().
       {
         Eigen::Map<const Vector6d> v(update);
         Eigen::Isometry3d increment = internal::fromVectorMQT(v);
         updatedEstimate = _estimate * increment;
       }
Member Data Documentation
g2o::OnlineVertexSE3::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 40 of file types_slam3d_online.h.
VertexSE3::EstimateType g2o::OnlineVertexSE3::updatedEstimate
Definition at line 56 of file types_slam3d_online.h.
Referenced by g2o::SparseOptimizerOnline::gnuplotVisualization(), g2o::OnlineEdgeSE3::initialEstimate(), g2o::SparseOptimizerIncremental::optimize(), g2o::SparseOptimizerOnline::optimize(), and g2o::G2oSlamInterface::printVertex().
The documentation for this class was generated from the following file:
/home/xuezhisd/CLionProjects/g2o/g2o/examples/interactive_slam/g2o_interactive/types_slam3d_online.h