g2o: g2o::RobotData Class Reference
g2o::RobotData Class Reference
data recorded by the robot
#include <robot_data.h>
Public Member Functions
RobotData ()
virtual ~RobotData ()
double timestamp () const
void setTimestamp (double ts)
double loggerTimestamp () const
void setLoggerTimestamp (double ts)
const std::string & tag () const
void setTag (const std::string &tag)
const std::string & hostname () const
void setHostname (const std::string &hostname)
Public Member Functions inherited from g2o::HyperGraph::Data
Data ()
~Data ()
virtual bool read (std::istream &is)=0
read the data from a stream
virtual bool write (std::ostream &os) const =0
write the data to a stream
virtual HyperGraph::HyperGraphElementType elementType () const
const Data * next () const
Data * next ()
void setNext (Data *next_)
DataContainer * dataContainer ()
const DataContainer * dataContainer () const
void setDataContainer (DataContainer *dataContainer_)
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Protected Attributes
double _timestamp
timestamp when the measurement was generated
double _loggerTimestamp
timestamp when the measurement was recorded
std::string _tag
string tag (FLASER, ROBOTLASER, ODOM..) of the line in the log
std::string _hostname
name of the computer/robot generating the data
Protected Attributes inherited from g2o::HyperGraph::Data
Data * _next
DataContainer * _dataContainer
Detailed Description
data recorded by the robot
Definition at line 41 of file robot_data.h.
Constructor & Destructor Documentation
g2o::RobotData::RobotData ()
Definition at line 31 of file robot_data.cpp.
                        :
     HyperGraph::Data(),
     _timestamp(-1.), _loggerTimestamp(-1.)
   {
   }
g2o::RobotData::~RobotData () virtual
Definition at line 37 of file robot_data.cpp.
   {
   }
Member Function Documentation
const std::string& g2o::RobotData::hostname () const inline
Definition at line 56 of file robot_data.h.
Referenced by setHostname(), g2o::VertexTag::write(), and g2o::RobotLaser::write().
 { return _hostname;}
double g2o::RobotData::loggerTimestamp () const inline
Definition at line 50 of file robot_data.h.
Referenced by g2o::RobotLaser::write(), and g2o::VertexTag::write().
 { return _loggerTimestamp;}
void g2o::RobotData::setHostname (const std::string & hostname)
Definition at line 56 of file robot_data.cpp.
References _hostname, and hostname().
   {
     _hostname = hostname;
   }
void g2o::RobotData::setLoggerTimestamp (double ts)
Definition at line 46 of file robot_data.cpp.
References _loggerTimestamp.
   {
     _loggerTimestamp = ts;
   }
void g2o::RobotData::setTag (const std::string & tag)
Definition at line 51 of file robot_data.cpp.
References _tag, and tag().
   {
     _tag = tag;
   }
void g2o::RobotData::setTimestamp (double ts)
Definition at line 41 of file robot_data.cpp.
References _timestamp.
   {
     _timestamp = ts;
   }
const std::string& g2o::RobotData::tag () const inline
Definition at line 53 of file robot_data.h.
Referenced by setTag().
 { return _tag;}
double g2o::RobotData::timestamp () const inline
Definition at line 47 of file robot_data.h.
Referenced by g2o::DataQueue::add(), g2o::addOdometryCalibLinksDifferential(), main(), g2o::VertexTag::write(), and g2o::RobotLaser::write().
 { return _timestamp;}
Member Data Documentation
std::string g2o::RobotData::_hostname protected
name of the computer/robot generating the data
Definition at line 63 of file robot_data.h.
Referenced by g2o::RobotLaser::read(), g2o::VertexTag::read(), g2o::RawLaser::read(), and setHostname().
double g2o::RobotData::_loggerTimestamp protected
timestamp when the measurement was recorded
Definition at line 61 of file robot_data.h.
Referenced by g2o::RobotLaser::read(), g2o::VertexTag::read(), g2o::RawLaser::read(), and setLoggerTimestamp().
std::string g2o::RobotData::_tag protected
string tag (FLASER, ROBOTLASER, ODOM..) of the line in the log
Definition at line 62 of file robot_data.h.
Referenced by setTag().
double g2o::RobotData::_timestamp protected
timestamp when the measurement was generated
Definition at line 60 of file robot_data.h.
Referenced by g2o::RobotLaser::read(), g2o::VertexTag::read(), g2o::RawLaser::read(), and setTimestamp().
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/data/robot_data.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/data/robot_data.cpp