g2o: SlamParser::CommandNode Class Reference
SlamParser::CommandNode Class Reference
#include <commands.h>
Public Member Functions
CommandNode (CommandType commandType, const std::string &tag)
virtual ~CommandNode ()
CommandType commandType () const
const std::string & tag () const
Protected Attributes
CommandType _commandType
std::string _tag
Detailed Description
Definition at line 44 of file commands.h.
Constructor & Destructor Documentation
SlamParser::CommandNode::CommandNode (CommandType commandType, const std::string & tag) inline
Definition at line 47 of file commands.h.
 : _commandType(commandType), _tag(tag) {}
virtual SlamParser::CommandNode::~CommandNode () inline virtual
Definition at line 48 of file commands.h.
 {}
Member Function Documentation
CommandType SlamParser::CommandNode::commandType () const inline
Definition at line 49 of file commands.h.
References _commandType.
Referenced by SlamParser::SlamContextInterface::process(), and SlamParser::SlamContext::process().
 { return _commandType;}
const std::string& SlamParser::CommandNode::tag () const inline
Definition at line 50 of file commands.h.
References _tag.
Referenced by SlamParser::SlamContextInterface::process().
 { return _tag;}
Member Data Documentation
CommandType SlamParser::CommandNode::_commandType protected
Definition at line 52 of file commands.h.
Referenced by commandType().
std::string SlamParser::CommandNode::_tag protected
Definition at line 53 of file commands.h.
Referenced by tag().
The documentation for this class was generated from the following file:
/home/xuezhisd/CLionProjects/g2o/g2o/examples/interactive_slam/slam_parser/parser/commands.h