g2o: g2o::SensorOdometry2D Class Reference
g2o::SensorOdometry2D Class Reference
#include <sensor_odometry2d.h>
Public Member Functions
SensorOdometry2D (const std::string &name_)
virtual void sense ()
virtual void addNoise (EdgeType *e)
Public Member Functions inherited from g2o::BinarySensor< Robot2D, EdgeSE2, WorldObjectSE2 >
BinarySensor (const std::string &name)
void setInformation (const InformationType &information_)
const InformationType & information ()
Public Member Functions inherited from g2o::BaseSensor
BaseSensor (const std::string &name_)
BaseRobot * robot ()
void setRobot (BaseRobot *robot_)
World * world ()
OptimizableGraph * graph ()
std::vector< Parameter * > parameters ()
virtual void addParameters ()
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef Robot2D::PoseObject PoseObject
Public Attributes inherited from g2o::BinarySensor< Robot2D, EdgeSE2, WorldObjectSE2 >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Additional Inherited Members
Public Types inherited from g2o::BinarySensor< Robot2D, EdgeSE2, WorldObjectSE2 >
typedef Robot2D RobotType
typedef RobotType::PoseObject PoseObject
typedef RobotType::TrajectoryType TrajectoryType
typedef RobotType::PoseObject::VertexType PoseVertexType
typedef EdgeSE2 EdgeType
typedef WorldObjectSE2 WorldObjectType
typedef WorldObjectType::VertexType VertexType
typedef EdgeType::InformationType InformationType
Protected Member Functions inherited from g2o::BinarySensor< Robot2D, EdgeSE2, WorldObjectSE2 >
EdgeType * mkEdge (WorldObjectType *object)
Protected Attributes inherited from g2o::BinarySensor< Robot2D, EdgeSE2, WorldObjectSE2 >
PoseObject * _robotPoseObject
InformationType _information
GaussianSampler< typename EdgeType::ErrorVector, InformationType > _sampler
Protected Attributes inherited from g2o::BaseSensor
std::string _name
std::vector< Parameter * > _parameters
BaseRobot * _robot
Detailed Description
Definition at line 34 of file sensor_odometry2d.h.
Constructor & Destructor Documentation
g2o::SensorOdometry2D::SensorOdometry2D (const std::string & name_)
Definition at line 36 of file sensor_odometry2d.cpp.
                                                           :
     BinarySensor<Robot2D, EdgeSE2, WorldObjectSE2>(name_){}
Member Function Documentation
void g2o::SensorOdometry2D::addNoise (EdgeType * e) virtual
Reimplemented from g2o::BinarySensor< Robot2D, EdgeSE2, WorldObjectSE2 >.
Definition at line 73 of file sensor_odometry2d.cpp.
References g2o::BinarySensor< Robot2D, EdgeSE2, WorldObjectSE2 >::_sampler, g2o::GaussianSampler< SampleType, CovarianceType >::generateSample(), g2o::BinarySensor< Robot2D, EdgeSE2, WorldObjectSE2 >::information(), g2o::BaseEdge< D, E >::measurement(), g2o::BaseEdge< D, E >::setInformation(), and g2o::EdgeSE2::setMeasurement().
Referenced by sense().
{
     EdgeType::ErrorVector noise=_sampler.generateSample();
     EdgeType::Measurement n;
     n.fromVector(noise);
     e->setMeasurement(e->measurement()*n);
     e->setInformation(information());
   }
void g2o::SensorOdometry2D::sense () virtual
Reimplemented from g2o::BinarySensor< Robot2D, EdgeSE2, WorldObjectSE2 >.
Definition at line 39 of file sensor_odometry2d.cpp.
References __PRETTY_FUNCTION__, g2o::BinarySensor< Robot2D, EdgeSE2, WorldObjectSE2 >::_robotPoseObject, g2o::OptimizableGraph::addEdge(), addNoise(), g2o::BaseSensor::graph(), g2o::BinarySensor< Robot2D, EdgeSE2, WorldObjectSE2 >::mkEdge(), g2o::BaseSensor::robot(), g2o::EdgeSE2::setMeasurementFromState(), and g2o::Robot< RobotPoseObject >::trajectory().
{
     if (! robot())
       return;
     RobotType* r =dynamic_cast<RobotType*>(robot());
     if (!r)
       return;
     PoseObject* pprev=0, *pcurr=0;
     std::list<PoseObject*>::reverse_iterator it=r->trajectory().rbegin();
     if (it!=r->trajectory().rend()){
       pcurr = *it;
       it++;
     }
     if (it!=r->trajectory().rend()){
       pprev = *it;
       it++;
     }
     if (!(pcurr&&pprev)) {
       cerr << __PRETTY_FUNCTION__ << ": fatal, trajectory empty" << endl;
       return;
     }
     _robotPoseObject = pprev;
     EdgeType* e=mkEdge(pcurr);
     if (e){
       e->setMeasurementFromState();
       addNoise(e);
       if (graph())
     graph()->addEdge(e);
     }
     _robotPoseObject = pcurr;
   }
Member Data Documentation
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef Robot2D::PoseObject g2o::SensorOdometry2D::PoseObject
Definition at line 37 of file sensor_odometry2d.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_simulator/sensor_odometry2d.h
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_simulator/sensor_odometry2d.cpp