g2o: g2o::VertexTag Class Reference
g2o::VertexTag Class Reference
string tag to be attached to a vertex
#include <vertex_tag.h>
Public Member Functions
VertexTag ()
~VertexTag ()
virtual bool write (std::ostream &os) const
write the data to a stream
virtual bool read (std::istream &is)
read the data from a stream
const std::string name () const
void setName (const std::string &name_)
const Vector3F & position () const
void setPosition (const Vector3F &p)
Public Member Functions inherited from g2o::RobotData
RobotData ()
virtual ~RobotData ()
double timestamp () const
void setTimestamp (double ts)
double loggerTimestamp () const
void setLoggerTimestamp (double ts)
const std::string & tag () const
void setTag (const std::string &tag)
const std::string & hostname () const
void setHostname (const std::string &hostname)
Public Member Functions inherited from g2o::HyperGraph::Data
Data ()
~Data ()
virtual HyperGraph::HyperGraphElementType elementType () const
const Data * next () const
Data * next ()
void setNext (Data *next_)
DataContainer * dataContainer ()
const DataContainer * dataContainer () const
void setDataContainer (DataContainer *dataContainer_)
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Attributes
std::string _name
Vector3F _position
Vector3F _odom2d
Protected Attributes inherited from g2o::RobotData
double _timestamp
timestamp when the measurement was generated
double _loggerTimestamp
timestamp when the measurement was recorded
std::string _tag
string tag (FLASER, ROBOTLASER, ODOM..) of the line in the log
std::string _hostname
name of the computer/robot generating the data
Protected Attributes inherited from g2o::HyperGraph::Data
Data * _next
DataContainer * _dataContainer
Detailed Description
string tag to be attached to a vertex
A laser measurement obtained by a robot. The measurement is equipped with a pose of the robot at which the measurement was taken. The read/write function correspond to the CARMEN logfile format.
Definition at line 42 of file vertex_tag.h.
Constructor & Destructor Documentation
g2o::VertexTag::VertexTag ()
Definition at line 42 of file vertex_tag.cpp.
                        : RobotData()
   {
   }
g2o::VertexTag::~VertexTag ()
Definition at line 46 of file vertex_tag.cpp.
   {
   }
Member Function Documentation
const std::string g2o::VertexTag::name () const inline
Definition at line 52 of file vertex_tag.h.
Referenced by write().
 { return _name;}
const Vector3F& g2o::VertexTag::position () const inline
Definition at line 54 of file vertex_tag.h.
Referenced by write().
 {return _position;}
bool g2o::VertexTag::read (std::istream & is) virtual
read the data from a stream
Implements g2o::HyperGraph::Data.
Definition at line 50 of file vertex_tag.cpp.
References g2o::RobotData::_hostname, g2o::RobotData::_loggerTimestamp, _name, _odom2d, _position, and g2o::RobotData::_timestamp.
   {
     is >> _name;
     is >> _position.x() >> _position.y() >> _position.z();
     is >> _odom2d.x() >> _odom2d.y() >> _odom2d.z();
     is >> _timestamp;
     is >> _hostname;
     is >> _loggerTimestamp;
     return true;
   }
void g2o::VertexTag::setName (const std::string & name_) inline
Definition at line 53 of file vertex_tag.h.
 {_name=name_;}
void g2o::VertexTag::setPosition (const Vector3F & p) inline
Definition at line 55 of file vertex_tag.h.
 {_position = p;}
bool g2o::VertexTag::write (std::ostream & os) const virtual
write the data to a stream
Implements g2o::HyperGraph::Data.
Definition at line 61 of file vertex_tag.cpp.
References _name, _odom2d, _position, g2o::opengl::drawBox(), g2o::RobotData::hostname(), g2o::RobotData::loggerTimestamp(), name(), position(), g2o::DrawAction::refreshPropertyPtrs(), and g2o::RobotData::timestamp().
   {
     os << _name << " ";
     os << FIXED(_position.x() << " " << _position.y() << " " << _position.z() << " ");
     os << FIXED(_odom2d.x() << " " << _odom2d.y() << " " << _odom2d.z() << " ");
     os << FIXED(" " << timestamp() << " " << hostname() << " " << loggerTimestamp());
     return os.good();
   }
Member Data Documentation
std::string g2o::VertexTag::_name protected
Definition at line 57 of file vertex_tag.h.
Referenced by read(), and write().
Vector3F g2o::VertexTag::_odom2d protected
Definition at line 59 of file vertex_tag.h.
Referenced by read(), and write().
Vector3F g2o::VertexTag::_position protected
Definition at line 58 of file vertex_tag.h.
Referenced by read(), and write().
g2o::VertexTag::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 45 of file vertex_tag.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/data/vertex_tag.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/data/vertex_tag.cpp