g2o: g2o::OdomConvert Class Reference
g2o::OdomConvert Class Reference
convert between the different types of odometry measurements
#include <odometry_measurement.h>
Static Public Member Functions
static VelocityMeasurement convertToVelocity (const MotionMeasurement &m)
static MotionMeasurement convertToMotion (const VelocityMeasurement &vi, double l=1.0)
Detailed Description
convert between the different types of odometry measurements
Definition at line 94 of file odometry_measurement.h.
Member Function Documentation
MotionMeasurement g2o::OdomConvert::convertToMotion (const VelocityMeasurement & vi, double l = 1.0) static
Definition at line 95 of file odometry_measurement.cpp.
References g2o::VelocityMeasurement::dt(), g2o::MotionMeasurement::MotionMeasurement(), g2o::MotionMeasurement::theta(), g2o::VelocityMeasurement::vl(), g2o::VelocityMeasurement::vr(), g2o::MotionMeasurement::x(), and g2o::MotionMeasurement::y().
Referenced by g2o::EdgeSE2OdomDifferentialCalib::computeError(), and g2o::EdgeSE2PureCalib::computeError().
   {
     double x, y, theta;
     if (fabs(v.vr() - v.vl()) > 1e-7) {
       double R = l * 0.5 * ((v.vl() + v.vr())  / (v.vr() - v.vl()));
       double w = (v.vr() - v.vl()) / l;
       theta = w * v.dt();
       Eigen::Rotation2Dd rot(theta);
       Vector2D icc(0, R);
       Vector2D motion = (rot * (Vector2D(-1.*icc))) + icc;
       x = motion.x();
       y = motion.y();
     } else {
       double tv = 0.5 * (v.vr() + v.vl());
       theta = 0.;
       x = tv * v.dt();
       y = 0.;
     }
     return MotionMeasurement(x, y, theta, v.dt());
   }
VelocityMeasurement g2o::OdomConvert::convertToVelocity (const MotionMeasurement & m) static
Definition at line 59 of file odometry_measurement.cpp.
References g2o::MotionMeasurement::dt(), g2o::hypot(), g2o::MotionMeasurement::theta(), g2o::MotionMeasurement::x(), and g2o::MotionMeasurement::y().
   {
     Vector2D px2(0, 10);
     if (fabs(m.theta()) > 1e-7) {
       Eigen::Rotation2Dd rot(m.theta());
       Vector2D px3(m.x(), m.y());
       Vector2D px4(rot * px2 + px3);
       const double& y2 = px2.y();
       const double& x3 = px3.x();
       const double& y3 = px3.y();
       const double& x4 = px4.x();
       const double& y4 = px4.y();
       double R = (y2 * (x3*y4 - y3*x4)) / (y2 * (x3 - x4));
       double w;
       if (fabs(m.dt()) > 1e-7)
         w = m.theta() / m.dt();
       else
         w = 0.;
       double vl = (2.*R*w - w) / 2.;
       double vr = w + vl;
       return VelocityMeasurement(vl, vr, m.dt());
     } else {
       double vl, vr;
       if (fabs(m.dt()) > 1e-7)
         vl = vr = hypot(m.x(), m.y()) / m.dt();
       else
         vl = vr = 0.;
       return VelocityMeasurement(vl, vr, m.dt());
     }
   }
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/sclam2d/odometry_measurement.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/sclam2d/odometry_measurement.cpp