g2o: g2o::CacheCamera Class Reference
g2o::CacheCamera Class Reference
#include <parameter_camera.h>
Public Member Functions
const ParameterCamera * camParams () const
parameters of the camera
const Affine3D & w2i () const
return the world to image transform
Public Member Functions inherited from g2o::CacheSE3Offset
CacheSE3Offset ()
const ParameterSE3Offset * offsetParam () const
void setOffsetParam (ParameterSE3Offset *offsetParam)
const Isometry3D & w2n () const
const Isometry3D & n2w () const
const Isometry3D & w2l () const
Public Member Functions inherited from g2o::Cache
Cache (CacheContainer *container_=0, const ParameterVector &parameters_=ParameterVector())
CacheKey key () const
OptimizableGraph::Vertex * vertex ()
OptimizableGraph * graph ()
CacheContainer * container ()
ParameterVector & parameters ()
void update ()
virtual HyperGraph::HyperGraphElementType elementType () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Public Attributes inherited from g2o::CacheSE3Offset
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Member Functions
virtual void updateImpl ()
redefine this to do the update
virtual bool resolveDependancies ()
Protected Member Functions inherited from g2o::Cache
Cache * installDependency (const std::string &type_, const std::vector< int > &parameterIndices)
Protected Attributes
Affine3D _w2i
world to image transform
ParameterCamera * params
Protected Attributes inherited from g2o::CacheSE3Offset
ParameterSE3Offset * _offsetParam
the parameter connected to the cache
Isometry3D _w2n
Isometry3D _n2w
Isometry3D _w2l
Protected Attributes inherited from g2o::Cache
bool _updateNeeded
ParameterVector _parameters
std::vector< Cache * > _parentCaches
CacheContainer * _container
Detailed Description
Definition at line 58 of file parameter_camera.h.
Member Function Documentation
const ParameterCamera* g2o::CacheCamera::camParams () const inline
parameters of the camera
Definition at line 62 of file parameter_camera.h.
Referenced by updateImpl().
 {return params;}
bool g2o::CacheCamera::resolveDependancies () protected virtual
Function to be called from a cache that has dependencies. It just invokes a sequence of installDependency(). Although the caches returned are stored in the _parentCache vector, it is better that you redefine your own cache member variables, for better readability
Reimplemented from g2o::CacheSE3Offset.
Definition at line 87 of file parameter_camera.cpp.
{
     if  (!CacheSE3Offset::resolveDependancies())
       return false;
     params = dynamic_cast<ParameterCamera*>(_parameters[0]);
     return params != 0;
   }
void g2o::CacheCamera::updateImpl () protected virtual
redefine this to do the update
Reimplemented from g2o::CacheSE3Offset.
Definition at line 94 of file parameter_camera.cpp.
References camParams(), g2o::opengl::drawPyramid(), g2o::ParameterSE3Offset::offset(), and POSE_PARAMETER_COLOR.
{
     CacheSE3Offset::updateImpl();
     _w2i.matrix().topLeftCorner<3,4>() = params->Kcam() * w2n().matrix().topLeftCorner<3,4>();
   }
const Affine3D& g2o::CacheCamera::w2i () const inline
return the world to image transform
Definition at line 64 of file parameter_camera.h.
Referenced by g2o::EdgeSE3PointXYZDepth::computeError(), g2o::EdgeSE3PointXYZDisparity::computeError(), g2o::EdgeSE3PointXYZDepth::linearizeOplus(), g2o::EdgeSE3PointXYZDisparity::linearizeOplus(), g2o::EdgeSE3PointXYZDepth::setMeasurementFromState(), and g2o::EdgeSE3PointXYZDisparity::setMeasurementFromState().
 {return _w2i;}
Member Data Documentation
Affine3D g2o::CacheCamera::_w2i protected
world to image transform
Definition at line 69 of file parameter_camera.h.
g2o::CacheCamera::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 60 of file parameter_camera.h.
ParameterCamera* g2o::CacheCamera::params protected
Definition at line 70 of file parameter_camera.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam3d/parameter_camera.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam3d/parameter_camera.cpp