g2o: g2o::DlWrapper Class Reference
g2o::DlWrapper Class Reference
Loading libraries during run-time.
#include <dl_wrapper.h>
Public Member Functions
DlWrapper ()
virtual ~DlWrapper ()
int openLibraries (const std::string &directory, const std::string &pattern="")
bool openLibrary (const std::string &filename)
void clear ()
Protected Attributes
std::vector< std::string > _filenames
Private Member Functions
DlWrapper (const DlWrapper &)
DlWrapper & operator= (const DlWrapper &)
Detailed Description
Loading libraries during run-time.
Definition at line 44 of file dl_wrapper.h.
Constructor & Destructor Documentation
g2o::DlWrapper::DlWrapper ()
Definition at line 56 of file dl_wrapper.cpp.
 {
 }
g2o::DlWrapper::~DlWrapper () virtual
Definition at line 60 of file dl_wrapper.cpp.
 {
   //clear();
 }
g2o::DlWrapper::DlWrapper (const DlWrapper &) private
it's not allowed to draw a copy of the wrapper
Member Function Documentation
void g2o::DlWrapper::clear ()
free all loaded libs, i.e., call dlclose()
Definition at line 100 of file dl_wrapper.cpp.
 {
 # if defined (UNIX) || defined(CYGWIN)
   for (size_t i = 0; i < _handles.size(); ++i) {
     dlclose(_handles[i]);
   }
 #elif defined(WINDOWS)
   for (size_t i = 0; i < _handles.size(); ++i) {
     FreeLibrary(_handles[i]);
   }
 #endif
   _filenames.clear();
   _handles.clear();
 }
int g2o::DlWrapper::openLibraries (const std::string & directory, const std::string & pattern = "")
open all libs from a directory matching a specific pattern.
Returns
number of loaded libs
Definition at line 65 of file dl_wrapper.cpp.
References g2o::getFilesByPattern(), SO_EXT, and SO_EXT_LEN.
Referenced by g2o::loadStandardSolver(), and g2o::loadStandardTypes().
 {
   //cerr << "# loading libraries from " << directory << "\t pattern: " << pattern << endl;
   string searchPattern = directory + "/" + pattern;
   if (pattern == "")
     searchPattern = directory + "/*";
   vector<string> matchingFiles = getFilesByPattern(searchPattern.c_str());
   int numLibs = 0;
   for (size_t i = 0; i < matchingFiles.size(); ++i) {
     const string& filename = matchingFiles[i];
     if (find(_filenames.begin(), _filenames.end(), filename) != _filenames.end())
       continue;
     // If we are doing a release build, the wildcards will pick up the
     // suffixes; unfortunately the "_rd" extension means that we
     // don't seem to be able to filter out the incompatible files using a
     // wildcard expansion to wordexp.
 #ifndef G2O_LIBRARY_POSTFIX
     if ((filename.rfind(string("_d.") + SO_EXT) == filename.length() - 3 - SO_EXT_LEN)
         || (filename.rfind(string("_rd.") + SO_EXT) == filename.length() - 4 - SO_EXT_LEN)
         || (filename.rfind(string("_s.") + SO_EXT) == filename.length() - 3 - SO_EXT_LEN))
         continue;
 #endif
     // open the lib
     //cerr << "loading " << filename << endl;
     if (openLibrary(filename))
       numLibs++;
   }
   return numLibs;
 }
bool g2o::DlWrapper::openLibrary (const std::string & filename)
open a specific library
Definition at line 115 of file dl_wrapper.cpp.
References __PRETTY_FUNCTION__.
Referenced by g2o::loadStandardSolver(), and g2o::loadStandardTypes().
 {
 # if defined (UNIX) || defined(CYGWIN)
   void* handle = dlopen(filename.c_str(), RTLD_LAZY);
   if (! handle) {
     cerr << __PRETTY_FUNCTION__ << " Cannot open library: " << dlerror() << '\n';
     return false;
   }
 # elif defined (WINDOWS)
   HMODULE handle = LoadLibrary(filename.c_str());
   if (! handle) {
     cerr << __PRETTY_FUNCTION__ << " Cannot open library." << endl;
     return false;
   }
 # endif
   //cerr << "loaded " << filename << endl;
   _filenames.push_back(filename);
   _handles.push_back(handle);
   return true;
 }
DlWrapper& g2o::DlWrapper::operator= (const DlWrapper &) private
Member Data Documentation
std::vector<std::string> g2o::DlWrapper::_filenames protected
Definition at line 72 of file dl_wrapper.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_cli/dl_wrapper.h
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_cli/dl_wrapper.cpp