g2o: g2o::deprecated::CacheCamera Class Reference
g2o::deprecated::CacheCamera Class Reference
#include <parameter_camera.h>
Public Member Functions
const ParameterCamera * camParams () const
parameters of the camera
const Eigen::Affine3d & w2i () const
return the world to image transform
Public Member Functions inherited from g2o::deprecated::CacheSE3Offset
CacheSE3Offset ()
const ParameterSE3Offset * offsetParam () const
void setOffsetParam (ParameterSE3Offset *offsetParam)
const SE3Quat & w2n () const
const SE3Quat & n2w () const
const Eigen::Isometry3d & w2nMatrix () const
const Eigen::Isometry3d & n2wMatrix () const
const Eigen::Isometry3d & w2lMatrix () const
Public Member Functions inherited from g2o::Cache
Cache (CacheContainer *container_=0, const ParameterVector &parameters_=ParameterVector())
CacheKey key () const
OptimizableGraph::Vertex * vertex ()
OptimizableGraph * graph ()
CacheContainer * container ()
ParameterVector & parameters ()
void update ()
virtual HyperGraph::HyperGraphElementType elementType () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Public Attributes inherited from g2o::deprecated::CacheSE3Offset
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Member Functions
virtual void updateImpl ()
redefine this to do the update
virtual bool resolveDependancies ()
Protected Member Functions inherited from g2o::Cache
Cache * installDependency (const std::string &type_, const std::vector< int > &parameterIndices)
Protected Attributes
Eigen::Affine3d _w2i
world to image transform
ParameterCamera * params
Protected Attributes inherited from g2o::deprecated::CacheSE3Offset
ParameterSE3Offset * _offsetParam
the parameter connected to the cache
SE3Quat _se3_w2n
SE3Quat _se3_n2w
Eigen::Isometry3d _w2n
world to sensor transform
Eigen::Isometry3d _w2l
world to local
Eigen::Isometry3d _n2w
sensor to world
Protected Attributes inherited from g2o::Cache
bool _updateNeeded
ParameterVector _parameters
std::vector< Cache * > _parentCaches
CacheContainer * _container
Detailed Description
Definition at line 61 of file parameter_camera.h.
Member Function Documentation
const ParameterCamera* g2o::deprecated::CacheCamera::camParams () const inline
parameters of the camera
Definition at line 65 of file parameter_camera.h.
Referenced by updateImpl().
 {return params;}
bool g2o::deprecated::CacheCamera::resolveDependancies () protected virtual
Function to be called from a cache that has dependencies. It just invokes a sequence of installDependency(). Although the caches returned are stored in the _parentCache vector, it is better that you redefine your own cache member variables, for better readability
Reimplemented from g2o::deprecated::CacheSE3Offset.
Definition at line 81 of file parameter_camera.cpp.
{
     if  (!CacheSE3Offset::resolveDependancies())
       return false;
     params = dynamic_cast<ParameterCamera*>(_parameters[0]);
     return params != 0;
   }
void g2o::deprecated::CacheCamera::updateImpl () protected virtual
redefine this to do the update
Reimplemented from g2o::deprecated::CacheSE3Offset.
Definition at line 88 of file parameter_camera.cpp.
References camParams(), and g2o::deprecated::ParameterSE3Offset::offsetMatrix().
{
     CacheSE3Offset::updateImpl();
     _w2i.matrix().topLeftCorner<3,4>() = params->Kcam() * w2nMatrix().matrix().topLeftCorner<3,4>();
   }
const Eigen::Affine3d& g2o::deprecated::CacheCamera::w2i () const inline
return the world to image transform
Definition at line 67 of file parameter_camera.h.
Referenced by g2o::deprecated::EdgeSE3PointXYZDepth::computeError(), g2o::deprecated::EdgeSE3PointXYZDisparity::computeError(), g2o::deprecated::EdgeSE3PointXYZDepth::linearizeOplus(), g2o::deprecated::EdgeSE3PointXYZDisparity::linearizeOplus(), g2o::deprecated::EdgeSE3PointXYZDepth::setMeasurementFromState(), and g2o::deprecated::EdgeSE3PointXYZDisparity::setMeasurementFromState().
 {return _w2i;}
Member Data Documentation
Eigen::Affine3d g2o::deprecated::CacheCamera::_w2i protected
world to image transform
Definition at line 71 of file parameter_camera.h.
g2o::deprecated::CacheCamera::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 63 of file parameter_camera.h.
ParameterCamera* g2o::deprecated::CacheCamera::params protected
Definition at line 72 of file parameter_camera.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/deprecated/slam3d/parameter_camera.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/deprecated/slam3d/parameter_camera.cpp