g2o: g2o::EstimatePropagator::AdjacencyMapEntry Class Reference
g2o::EstimatePropagator::AdjacencyMapEntry Class Reference
data structure for loopuk during Dijkstra
#include <estimate_propagator.h>
Public Member Functions
AdjacencyMapEntry ()
void reset ()
OptimizableGraph::Vertex * child () const
const OptimizableGraph::VertexSet & parent () const
OptimizableGraph::Edge * edge () const
double distance () const
int frontierLevel () const
Protected Attributes
OptimizableGraph::Vertex * _child
OptimizableGraph::VertexSet _parent
OptimizableGraph::Edge * _edge
double _distance
int _frontierLevel
Private Attributes
bool inQueue
PriorityQueue::iterator queueIt
Friends
class EstimatePropagator
class PriorityQueue
Detailed Description
data structure for loopuk during Dijkstra
Definition at line 104 of file estimate_propagator.h.
Constructor & Destructor Documentation
g2o::EstimatePropagator::AdjacencyMapEntry::AdjacencyMapEntry ()
Definition at line 51 of file estimate_propagator.cpp.
   {
     reset();
   }
Member Function Documentation
OptimizableGraph::Vertex* g2o::EstimatePropagator::AdjacencyMapEntry::child () const inline
Definition at line 110 of file estimate_propagator.h.
Referenced by g2o::EstimatePropagator::EstimatePropagator(), and g2o::EstimatePropagator::propagate().
 {return _child;}
double g2o::EstimatePropagator::AdjacencyMapEntry::distance () const inline
Definition at line 113 of file estimate_propagator.h.
Referenced by g2o::EstimatePropagator::propagate(), and g2o::EstimatePropagator::PriorityQueue::push().
 {return _distance;}
OptimizableGraph::Edge* g2o::EstimatePropagator::AdjacencyMapEntry::edge () const inline
Definition at line 112 of file estimate_propagator.h.
Referenced by g2o::EstimatePropagator::propagate().
 {return _edge;}
int g2o::EstimatePropagator::AdjacencyMapEntry::frontierLevel () const inline
Definition at line 114 of file estimate_propagator.h.
 { return _frontierLevel;}
const OptimizableGraph::VertexSet& g2o::EstimatePropagator::AdjacencyMapEntry::parent () const inline
Definition at line 111 of file estimate_propagator.h.
Referenced by g2o::EstimatePropagator::propagate().
 {return _parent;}
void g2o::EstimatePropagator::AdjacencyMapEntry::reset ()
Definition at line 56 of file estimate_propagator.cpp.
   {
     _child = 0;
     _parent.clear();
     _edge = 0;
     _distance = numeric_limits<double>::max();
     _frontierLevel = -1;
     inQueue = false;
   }
Friends And Related Function Documentation
friend class EstimatePropagator friend
Definition at line 106 of file estimate_propagator.h.
friend class PriorityQueue friend
Definition at line 107 of file estimate_propagator.h.
Member Data Documentation
OptimizableGraph::Vertex* g2o::EstimatePropagator::AdjacencyMapEntry::_child protected
Definition at line 117 of file estimate_propagator.h.
Referenced by g2o::EstimatePropagator::EstimatePropagator().
double g2o::EstimatePropagator::AdjacencyMapEntry::_distance protected
Definition at line 120 of file estimate_propagator.h.
OptimizableGraph::Edge* g2o::EstimatePropagator::AdjacencyMapEntry::_edge protected
Definition at line 119 of file estimate_propagator.h.
int g2o::EstimatePropagator::AdjacencyMapEntry::_frontierLevel protected
Definition at line 121 of file estimate_propagator.h.
Referenced by g2o::EstimatePropagator::propagate().
OptimizableGraph::VertexSet g2o::EstimatePropagator::AdjacencyMapEntry::_parent protected
Definition at line 118 of file estimate_propagator.h.
bool g2o::EstimatePropagator::AdjacencyMapEntry::inQueue private
Definition at line 123 of file estimate_propagator.h.
Referenced by g2o::EstimatePropagator::PriorityQueue::pop(), and g2o::EstimatePropagator::PriorityQueue::push().
PriorityQueue::iterator g2o::EstimatePropagator::AdjacencyMapEntry::queueIt private
Definition at line 124 of file estimate_propagator.h.
Referenced by g2o::EstimatePropagator::PriorityQueue::pop(), and g2o::EstimatePropagator::PriorityQueue::push().
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/core/estimate_propagator.h
/home/xuezhisd/CLionProjects/g2o/g2o/core/estimate_propagator.cpp