g2o: g2o::BaseMultiEdge<-1, E > Class Template Reference
g2o::BaseMultiEdge<-1, E > Class Template Reference
#include <base_multi_edge.h>
Classes
struct HessianHelper
helper for mapping the Hessian memory of the upper triangular block
Public Types
typedef BaseEdge<-1, E >::Measurement Measurement
typedef MatrixXD::MapType JacobianType
typedef BaseEdge<-1, E >::ErrorVector ErrorVector
typedef BaseEdge<-1, E >::InformationType InformationType
typedef Eigen::Map< MatrixXD, MatrixXD::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockType
Public Types inherited from g2o::BaseEdge<-1, E >
typedef E Measurement
typedef Eigen::Matrix< double, Eigen::Dynamic, 1, Eigen::ColMajor > ErrorVector
typedef Eigen::Matrix< double, Eigen::Dynamic, Eigen::Dynamic, Eigen::ColMajor > InformationType
Public Member Functions
BaseMultiEdge ()
virtual void linearizeOplus (JacobianWorkspace &jacobianWorkspace)
virtual void linearizeOplus ()
virtual void resize (size_t size)
virtual bool allVerticesFixed () const
virtual void constructQuadraticForm ()
virtual void mapHessianMemory (double *d, int i, int j, bool rowMajor)
Public Member Functions inherited from g2o::BaseEdge<-1, E >
BaseEdge ()
virtual ~BaseEdge ()
virtual double chi2 () const
computes the chi2 based on the cached error value, only valid after computeError has been called.
virtual const double * errorData () const
returns the error vector cached after calling the computeError;
virtual double * errorData ()
const ErrorVector & error () const
ErrorVector & error ()
const InformationType & information () const
information matrix of the constraint
InformationType & information ()
void setInformation (const InformationType &information)
virtual const double * informationData () const
returns the memory of the information matrix, usable for example with a Eigen::Map<MatrixXD>
virtual double * informationData ()
const Measurement & measurement () const
accessor functions for the measurement represented by the edge
virtual void setMeasurement (const Measurement &m)
virtual int rank () const
virtual void initialEstimate (const OptimizableGraph::VertexSet &, OptimizableGraph::Vertex *)
Public Member Functions inherited from g2o::OptimizableGraph::Edge
Edge ()
virtual ~Edge ()
virtual Edge * clone () const
virtual void computeError ()=0
virtual bool setMeasurementData (const double *m)
virtual bool getMeasurementData (double *m) const
virtual int measurementDimension () const
virtual bool setMeasurementFromState ()
RobustKernel * robustKernel () const
if NOT NULL, error of this edge will be robustifed with the kernel
void setRobustKernel (RobustKernel *ptr)
virtual double initialEstimatePossible (const OptimizableGraph::VertexSet &from, OptimizableGraph::Vertex *to)
int level () const
returns the level of the edge
void setLevel (int l)
sets the level of the edge
int dimension () const
returns the dimensions of the error function
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createFrom())
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createTo())
virtual Vertex * createVertex (int)
virtual bool read (std::istream &is)=0
read the vertex from a stream, i.e., the internal state of the vertex
virtual bool write (std::ostream &os) const =0
write the vertex to a stream
long long internalId () const
the internal ID of the edge
OptimizableGraph * graph ()
const OptimizableGraph * graph () const
bool setParameterId (int argNum, int paramId)
const Parameter * parameter (int argNo) const
size_t numParameters () const
void resizeParameters (size_t newSize)
Public Member Functions inherited from g2o::HyperGraph::Edge
Edge (int id=InvalidId)
creates and empty edge with no vertices
const VertexContainer & vertices () const
VertexContainer & vertices ()
const Vertex * vertex (size_t i) const
Vertex * vertex (size_t i)
void setVertex (size_t i, Vertex *v)
int id () const
void setId (int id)
virtual HyperGraphElementType elementType () const
int numUndefinedVertices () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Member Functions inherited from g2o::HyperGraph::DataContainer
DataContainer ()
virtual ~DataContainer ()
const Data * userData () const
the user data associated with this vertex
Data * userData ()
void setUserData (Data *obs)
void addUserData (Data *obs)
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Static Public Attributes
static const int Dimension = BaseEdge<-1,E>::Dimension
Static Public Attributes inherited from g2o::BaseEdge<-1, E >
static const int Dimension = -1
Protected Member Functions
void computeQuadraticForm (const InformationType &omega, const ErrorVector &weightedError)
Protected Member Functions inherited from g2o::BaseEdge<-1, E >
InformationType robustInformation (const Vector3D &rho)
Protected Member Functions inherited from g2o::OptimizableGraph::Edge
template<typename ParameterType >
bool installParameter (ParameterType *&p, size_t argNo, int paramId=-1)
template<typename CacheType >
void resolveCache (CacheType *&cache, OptimizableGraph::Vertex *, const std::string &_type, const ParameterVector &parameters)
bool resolveParameters ()
virtual bool resolveCaches ()
Protected Attributes
std::vector< HessianHelper > _hessian
std::vector< JacobianType, Eigen::aligned_allocator< JacobianType > > _jacobianOplus
jacobians of the edge (w.r.t. oplus)
Protected Attributes inherited from g2o::BaseEdge<-1, E >
Measurement _measurement
InformationType _information
ErrorVector _error
Protected Attributes inherited from g2o::OptimizableGraph::Edge
int _dimension
int _level
RobustKernel * _robustKernel
long long _internalId
std::vector< int > _cacheIds
std::vector< std::string > _parameterTypes
std::vector< Parameter ** > _parameters
std::vector< int > _parameterIds
Protected Attributes inherited from g2o::HyperGraph::Edge
VertexContainer _vertices
int _id
unique id
Protected Attributes inherited from g2o::HyperGraph::DataContainer
Data * _userData
Detailed Description
template<typename E>
class g2o::BaseMultiEdge<-1, E >
Definition at line 111 of file base_multi_edge.h.
Member Typedef Documentation
template<typename E > typedef BaseEdge<-1,E>::ErrorVector g2o::BaseMultiEdge<-1, E >::ErrorVector
Definition at line 127 of file base_multi_edge.h.
template<typename E > typedef Eigen::Map<MatrixXD, MatrixXD::Flags & Eigen::AlignedBit ? Eigen::Aligned : Eigen::Unaligned > g2o::BaseMultiEdge<-1, E >::HessianBlockType
Definition at line 129 of file base_multi_edge.h.
template<typename E > typedef BaseEdge<-1,E>::InformationType g2o::BaseMultiEdge<-1, E >::InformationType
Definition at line 128 of file base_multi_edge.h.
template<typename E > typedef MatrixXD::MapType g2o::BaseMultiEdge<-1, E >::JacobianType
Definition at line 126 of file base_multi_edge.h.
template<typename E > typedef BaseEdge<-1,E>::Measurement g2o::BaseMultiEdge<-1, E >::Measurement
Definition at line 125 of file base_multi_edge.h.
Constructor & Destructor Documentation
template<typename E > g2o::BaseMultiEdge<-1, E >::BaseMultiEdge () inline
Definition at line 131 of file base_multi_edge.h.
References g2o::BaseMultiEdge< D, E >::allVerticesFixed(), g2o::BaseMultiEdge< D, E >::constructQuadraticForm(), g2o::BaseMultiEdge< D, E >::linearizeOplus(), and g2o::BaseMultiEdge< D, E >::resize().
                       : BaseEdge<-1,E>()
     {
       // this->_variableSize = true;
     }
Member Function Documentation
template<typename E > bool g2o::BaseMultiEdge<-1, E >::allVerticesFixed () const virtual
Implements g2o::OptimizableGraph::Edge.
Definition at line 353 of file base_multi_edge.h.
template<typename E > void g2o::BaseMultiEdge<-1, E >::computeQuadraticForm (const InformationType & omega, const ErrorVector & weightedError) protected
Definition at line 364 of file base_multi_edge.h.
template<typename E > void g2o::BaseMultiEdge<-1, E >::constructQuadraticForm () virtual
Linearizes the constraint in the edge. Makes side effect on the vertices of the graph by changing the parameter vector b and the hessian blocks ii and jj. The off diagoinal block is accesed via _hessian.
Implements g2o::OptimizableGraph::Edge.
Definition at line 229 of file base_multi_edge.h.
template<typename E > void g2o::BaseMultiEdge<-1, E >::linearizeOplus (JacobianWorkspace & jacobianWorkspace) virtual
Linearizes the constraint in the edge in the manifold space, and store the result in the given workspace
Implements g2o::OptimizableGraph::Edge.
Definition at line 245 of file base_multi_edge.h.
template<typename E > void g2o::BaseMultiEdge<-1, E >::linearizeOplus () virtual
Linearizes the oplus operator in the vertex, and stores the result in temporary variable vector _jacobianOplus
Definition at line 256 of file base_multi_edge.h.
template<typename E > void g2o::BaseMultiEdge<-1, E >::mapHessianMemory (double * d, int i, int j, bool rowMajor) virtual
maps the internal matrix to some external memory location, you need to provide the memory before calling constructQuadraticForm
Parameters
d the memory location to which we map
i index of the vertex i
j index of the vertex j (j > i, upper triangular fashion)
rowMajor if true, will write in rowMajor order to the block. Since EIGEN is columnMajor by default, this results in writing the transposed
Implements g2o::OptimizableGraph::Edge.
Definition at line 322 of file base_multi_edge.h.
template<typename E > void g2o::BaseMultiEdge<-1, E >::resize (size_t size) virtual
resizes the number of vertices connected by this edge
Reimplemented from g2o::HyperGraph::Edge.
Definition at line 342 of file base_multi_edge.h.
Member Data Documentation
template<typename E > std::vector<HessianHelper> g2o::BaseMultiEdge<-1, E >::_hessian protected
Definition at line 161 of file base_multi_edge.h.
template<typename E > std::vector<JacobianType, Eigen::aligned_allocator<JacobianType> > g2o::BaseMultiEdge<-1, E >::_jacobianOplus protected
jacobians of the edge (w.r.t. oplus)
Definition at line 162 of file base_multi_edge.h.
template<typename E > const int g2o::BaseMultiEdge<-1, E >::Dimension = BaseEdge<-1,E>::Dimension static
Definition at line 124 of file base_multi_edge.h.
template<typename E > g2o::BaseMultiEdge<-1, E >::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 167 of file base_multi_edge.h.
The documentation for this class was generated from the following file:
/home/xuezhisd/CLionProjects/g2o/g2o/core/base_multi_edge.h