g2o: g2o::deprecated::CacheSE3Offset Class Reference
g2o::deprecated::CacheSE3Offset Class Reference
caching the offset related to a vertex
#include <parameter_se3_offset.h>
Public Member Functions
CacheSE3Offset ()
virtual void updateImpl ()
redefine this to do the update
const ParameterSE3Offset * offsetParam () const
void setOffsetParam (ParameterSE3Offset *offsetParam)
const SE3Quat & w2n () const
const SE3Quat & n2w () const
const Eigen::Isometry3d & w2nMatrix () const
const Eigen::Isometry3d & n2wMatrix () const
const Eigen::Isometry3d & w2lMatrix () const
Public Member Functions inherited from g2o::Cache
Cache (CacheContainer *container_=0, const ParameterVector &parameters_=ParameterVector())
CacheKey key () const
OptimizableGraph::Vertex * vertex ()
OptimizableGraph * graph ()
CacheContainer * container ()
ParameterVector & parameters ()
void update ()
virtual HyperGraph::HyperGraphElementType elementType () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Member Functions
virtual bool resolveDependancies ()
Protected Member Functions inherited from g2o::Cache
Cache * installDependency (const std::string &type_, const std::vector< int > &parameterIndices)
Protected Attributes
ParameterSE3Offset * _offsetParam
the parameter connected to the cache
SE3Quat _se3_w2n
SE3Quat _se3_n2w
Eigen::Isometry3d _w2n
world to sensor transform
Eigen::Isometry3d _w2l
world to local
Eigen::Isometry3d _n2w
sensor to world
Protected Attributes inherited from g2o::Cache
bool _updateNeeded
ParameterVector _parameters
std::vector< Cache * > _parentCaches
CacheContainer * _container
Detailed Description
caching the offset related to a vertex
Definition at line 81 of file parameter_se3_offset.h.
Constructor & Destructor Documentation
g2o::deprecated::CacheSE3Offset::CacheSE3Offset ()
Definition at line 66 of file parameter_se3_offset.cpp.
                                  :
     Cache(),
     _offsetParam(0)
   {
   }
Member Function Documentation
const SE3Quat& g2o::deprecated::CacheSE3Offset::n2w () const inline
Definition at line 91 of file parameter_se3_offset.h.
Referenced by g2o::deprecated::EdgeSE3Prior::computeError(), g2o::deprecated::EdgeSE3Offset::computeError(), g2o::deprecated::EdgeSE3Prior::setMeasurementFromState(), and g2o::deprecated::EdgeSE3Offset::setMeasurementFromState().
 {return _se3_n2w;}
const Eigen::Isometry3d& g2o::deprecated::CacheSE3Offset::n2wMatrix () const inline
Definition at line 94 of file parameter_se3_offset.h.
 { return _n2w;}
const ParameterSE3Offset* g2o::deprecated::CacheSE3Offset::offsetParam () const inline
Definition at line 87 of file parameter_se3_offset.h.
Referenced by g2o::deprecated::EdgeSE3Offset::initialEstimate(), g2o::deprecated::EdgeSE3Prior::linearizeOplus(), g2o::deprecated::EdgeSE3Offset::linearizeOplus(), and setOffsetParam().
 { return _offsetParam;}
bool g2o::deprecated::CacheSE3Offset::resolveDependancies () protected virtual
Function to be called from a cache that has dependencies. It just invokes a sequence of installDependency(). Although the caches returned are stored in the _parentCache vector, it is better that you redefine your own cache member variables, for better readability
Reimplemented from g2o::Cache.
Reimplemented in g2o::deprecated::CacheCamera.
Definition at line 72 of file parameter_se3_offset.cpp.
References _offsetParam, and g2o::Cache::_parameters.
{
     _offsetParam = dynamic_cast <ParameterSE3Offset*> (_parameters[0]);
     return _offsetParam != 0;
   }
void g2o::deprecated::CacheSE3Offset::setOffsetParam (ParameterSE3Offset * offsetParam)
Definition at line 93 of file parameter_se3_offset.cpp.
References _offsetParam, g2o::deprecated::ParameterSE3Offset::offset(), offsetParam(), RAD2DEG, g2o::DrawAction::refreshPropertyPtrs(), g2o::SE3Quat::rotation(), and g2o::SE3Quat::translation().
   {
     _offsetParam = offsetParam;
   }
void g2o::deprecated::CacheSE3Offset::updateImpl () virtual
redefine this to do the update
Implements g2o::Cache.
Reimplemented in g2o::deprecated::CacheCamera.
Definition at line 77 of file parameter_se3_offset.cpp.
References _n2w, _offsetParam, _se3_n2w, _se3_w2n, _w2l, _w2n, g2o::BaseVertex< D, T >::estimate(), g2o::SE3Quat::inverse(), g2o::deprecated::ParameterSE3Offset::offset(), g2o::SE3Quat::rotation(), g2o::SE3Quat::translation(), and g2o::Cache::vertex().
{
     const VertexSE3* v = static_cast<const VertexSE3*>(vertex());
     _se3_n2w = v->estimate() * _offsetParam->offset();
     _n2w = _se3_n2w.rotation().toRotationMatrix();
     _n2w.translation() = _se3_n2w.translation();
     _se3_w2n = _se3_n2w.inverse();
     _w2n = _se3_w2n.rotation().toRotationMatrix();
     _w2n.translation() = _se3_w2n.translation();
     SE3Quat w2l = v->estimate().inverse();
     _w2l = w2l.rotation().toRotationMatrix();
     _w2l.translation() = w2l.translation();
   }
const Eigen::Isometry3d& g2o::deprecated::CacheSE3Offset::w2lMatrix () const inline
Definition at line 95 of file parameter_se3_offset.h.
Referenced by g2o::deprecated::EdgeSE3PointXYZDepth::linearizeOplus(), g2o::deprecated::EdgeSE3PointXYZ::linearizeOplus(), and g2o::deprecated::EdgeSE3PointXYZDisparity::linearizeOplus().
 { return _w2l;}
const SE3Quat& g2o::deprecated::CacheSE3Offset::w2n () const inline
Definition at line 90 of file parameter_se3_offset.h.
Referenced by g2o::deprecated::EdgeSE3Offset::computeError(), and g2o::deprecated::EdgeSE3Offset::setMeasurementFromState().
 {return _se3_w2n;}
const Eigen::Isometry3d& g2o::deprecated::CacheSE3Offset::w2nMatrix () const inline
Definition at line 93 of file parameter_se3_offset.h.
Referenced by g2o::deprecated::EdgeSE3PointXYZ::computeError(), and g2o::deprecated::EdgeSE3PointXYZ::setMeasurementFromState().
 { return _w2n;}
Member Data Documentation
Eigen::Isometry3d g2o::deprecated::CacheSE3Offset::_n2w protected
sensor to world
Definition at line 104 of file parameter_se3_offset.h.
Referenced by updateImpl().
ParameterSE3Offset* g2o::deprecated::CacheSE3Offset::_offsetParam protected
the parameter connected to the cache
Definition at line 98 of file parameter_se3_offset.h.
Referenced by resolveDependancies(), setOffsetParam(), and updateImpl().
SE3Quat g2o::deprecated::CacheSE3Offset::_se3_n2w protected
Definition at line 100 of file parameter_se3_offset.h.
Referenced by updateImpl().
SE3Quat g2o::deprecated::CacheSE3Offset::_se3_w2n protected
Definition at line 99 of file parameter_se3_offset.h.
Referenced by updateImpl().
Eigen::Isometry3d g2o::deprecated::CacheSE3Offset::_w2l protected
world to local
Definition at line 103 of file parameter_se3_offset.h.
Referenced by updateImpl().
Eigen::Isometry3d g2o::deprecated::CacheSE3Offset::_w2n protected
world to sensor transform
Definition at line 102 of file parameter_se3_offset.h.
Referenced by updateImpl().
g2o::deprecated::CacheSE3Offset::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 83 of file parameter_se3_offset.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/deprecated/slam3d/parameter_se3_offset.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/deprecated/slam3d/parameter_se3_offset.cpp