g2o: g2o::LinearSolverPCG< MatrixType > Class Template Reference
g2o::LinearSolverPCG< MatrixType > Class Template Reference
linear solver using PCG, pre-conditioner is block Jacobi
#include <linear_solver_pcg.h>
Public Member Functions
LinearSolverPCG ()
virtual ~LinearSolverPCG ()
virtual bool init ()
bool solve (const SparseBlockMatrix< MatrixType > &A, double *x, double *b)
double tolerance () const
return the tolerance for terminating PCG before convergence
void setTolerance (double tolerance)
int maxIterations () const
void setMaxIterations (int maxIter)
bool absoluteTolerance () const
void setAbsoluteTolerance (bool absoluteTolerance)
bool verbose () const
void setVerbose (bool verbose)
Public Member Functions inherited from g2o::LinearSolver< MatrixType >
LinearSolver ()
virtual ~LinearSolver ()
virtual bool solveBlocks (double **&blocks, const SparseBlockMatrix< MatrixType > &A)
virtual bool solvePattern (SparseBlockMatrix< MatrixXD > &spinv, const std::vector< std::pair< int, int > > &blockIndices, const SparseBlockMatrix< MatrixType > &A)
virtual bool writeDebug () const
write a debug dump of the system matrix if it is not PSD in solve
virtual void setWriteDebug (bool)
Protected Types
typedef std::vector< MatrixType, Eigen::aligned_allocator< MatrixType > > MatrixVector
typedef std::vector< const MatrixType * > MatrixPtrVector
Protected Member Functions
void multDiag (const std::vector< int > &colBlockIndices, MatrixVector &A, const VectorXD &src, VectorXD &dest)
void multDiag (const std::vector< int > &colBlockIndices, MatrixPtrVector &A, const VectorXD &src, VectorXD &dest)
void mult (const std::vector< int > &colBlockIndices, const VectorXD &src, VectorXD &dest)
Protected Attributes
double _tolerance
double _residual
bool _absoluteTolerance
bool _verbose
int _maxIter
MatrixPtrVector _diag
MatrixVector _J
std::vector< std::pair< int, int > > _indices
MatrixPtrVector _sparseMat
Detailed Description
template<typename MatrixType>
class g2o::LinearSolverPCG< MatrixType >
linear solver using PCG, pre-conditioner is block Jacobi
Definition at line 47 of file linear_solver_pcg.h.
Member Typedef Documentation
template<typename MatrixType> typedef std::vector< const MatrixType* > g2o::LinearSolverPCG< MatrixType >::MatrixPtrVector protected
Definition at line 89 of file linear_solver_pcg.h.
template<typename MatrixType> typedef std::vector< MatrixType, Eigen::aligned_allocator<MatrixType> > g2o::LinearSolverPCG< MatrixType >::MatrixVector protected
Definition at line 88 of file linear_solver_pcg.h.
Constructor & Destructor Documentation
template<typename MatrixType> g2o::LinearSolverPCG< MatrixType >::LinearSolverPCG () inline
Definition at line 50 of file linear_solver_pcg.h.
References g2o::LinearSolverPCG< MatrixType >::_tolerance, and g2o::LinearSolverPCG< MatrixType >::_verbose.
                         :
       LinearSolver<MatrixType>()
       {
         _tolerance = 1e-6;
         _verbose = false;
         _absoluteTolerance = true;
         _residual = -1.0;
         _maxIter = -1;
       }
template<typename MatrixType> virtual g2o::LinearSolverPCG< MatrixType >::~LinearSolverPCG () inline virtual
Definition at line 60 of file linear_solver_pcg.h.
       {
       }
Member Function Documentation
template<typename MatrixType> bool g2o::LinearSolverPCG< MatrixType >::absoluteTolerance () const inline
Definition at line 81 of file linear_solver_pcg.h.
Referenced by g2o::LinearSolverPCG< MatrixType >::setAbsoluteTolerance().
 { return _absoluteTolerance;}
template<typename MatrixType> virtual bool g2o::LinearSolverPCG< MatrixType >::init () inline virtual
init for operating on matrices with a different non-zero pattern like before
Implements g2o::LinearSolver< MatrixType >.
Definition at line 64 of file linear_solver_pcg.h.
References g2o::LinearSolverPCG< MatrixType >::_residual.
       {
         _residual = -1.0;
         _indices.clear();
         _sparseMat.clear();
         return true;
       }
template<typename MatrixType> int g2o::LinearSolverPCG< MatrixType >::maxIterations () const inline
Definition at line 78 of file linear_solver_pcg.h.
References g2o::LinearSolverPCG< MatrixType >::_maxIter.
 { return _maxIter;}
template<typename MatrixType > void LinearSolverPCG::mult (const std::vector< int > & colBlockIndices, const VectorXD & src, VectorXD & dest) protected
Definition at line 180 of file linear_solver_pcg.h.
template<typename MatrixType > void LinearSolverPCG::multDiag (const std::vector< int > & colBlockIndices, MatrixVector & A, const VectorXD & src, VectorXD & dest) protected
Definition at line 160 of file linear_solver_pcg.h.
template<typename MatrixType > void LinearSolverPCG::multDiag (const std::vector< int > & colBlockIndices, MatrixPtrVector & A, const VectorXD & src, VectorXD & dest) protected
Definition at line 170 of file linear_solver_pcg.h.
template<typename MatrixType> void g2o::LinearSolverPCG< MatrixType >::setAbsoluteTolerance (bool absoluteTolerance) inline
Definition at line 82 of file linear_solver_pcg.h.
References g2o::LinearSolverPCG< MatrixType >::_absoluteTolerance, and g2o::LinearSolverPCG< MatrixType >::absoluteTolerance().
 { _absoluteTolerance = absoluteTolerance;}
template<typename MatrixType> void g2o::LinearSolverPCG< MatrixType >::setMaxIterations (int maxIter) inline
Definition at line 79 of file linear_solver_pcg.h.
References g2o::LinearSolverPCG< MatrixType >::_maxIter.
 { _maxIter = maxIter;}
template<typename MatrixType> void g2o::LinearSolverPCG< MatrixType >::setTolerance (double tolerance) inline
Definition at line 76 of file linear_solver_pcg.h.
References g2o::LinearSolverPCG< MatrixType >::_tolerance, and g2o::LinearSolverPCG< MatrixType >::tolerance().
 { _tolerance = tolerance;}
template<typename MatrixType> void g2o::LinearSolverPCG< MatrixType >::setVerbose (bool verbose) inline
Definition at line 85 of file linear_solver_pcg.h.
References g2o::LinearSolverPCG< MatrixType >::_verbose, and g2o::LinearSolverPCG< MatrixType >::verbose().
 { _verbose = verbose;}
template<typename MatrixType > bool LinearSolverPCG::solve (const SparseBlockMatrix< MatrixType > & A, double * x, double * b) virtual
Assumes that A is the same matrix for several calls. Among other assumptions, the non-zero pattern does not change! If the matrix changes call init() before. solve system Ax = b, x and b have to allocated beforehand!!
Implements g2o::LinearSolver< MatrixType >.
Definition at line 81 of file linear_solver_pcg.h.
References g2o::LinearSolverPCG< MatrixType >::_absoluteTolerance.
                                      { return _absoluteTolerance;}
       void setAbsoluteTolerance(bool absoluteTolerance) { _absoluteTolerance = absoluteTolerance;}
       bool verbose() const { return _verbose;}
       void setVerbose(bool verbose) { _verbose = verbose;}
     protected:
       typedef std::vector< MatrixType, Eigen::aligned_allocator<MatrixType> > MatrixVector;
       typedef std::vector< const MatrixType* > MatrixPtrVector;
       double _tolerance;
       double _residual;
       bool _absoluteTolerance;
       bool _verbose;
       int _maxIter;
       MatrixPtrVector _diag;
       MatrixVector _J;
       std::vector<std::pair<int, int> > _indices;
       MatrixPtrVector _sparseMat;
       void multDiag(const std::vector<int>& colBlockIndices, MatrixVector& A, const VectorXD& src, VectorXD& dest);
       void multDiag(const std::vector<int>& colBlockIndices, MatrixPtrVector& A, const VectorXD& src, VectorXD& dest);
       void mult(const std::vector<int>& colBlockIndices, const VectorXD& src, VectorXD& dest);
   };
 #include "linear_solver_pcg.hpp"
 }// end namespace
 #endif
template<typename MatrixType> double g2o::LinearSolverPCG< MatrixType >::tolerance () const inline
return the tolerance for terminating PCG before convergence
Definition at line 75 of file linear_solver_pcg.h.
References g2o::LinearSolverPCG< MatrixType >::_tolerance.
Referenced by g2o::LinearSolverPCG< MatrixType >::setTolerance().
 { return _tolerance;}
template<typename MatrixType> bool g2o::LinearSolverPCG< MatrixType >::verbose () const inline
Definition at line 84 of file linear_solver_pcg.h.
References g2o::LinearSolverPCG< MatrixType >::_verbose.
Referenced by g2o::LinearSolverPCG< MatrixType >::setVerbose().
 { return _verbose;}
Member Data Documentation
template<typename MatrixType> bool g2o::LinearSolverPCG< MatrixType >::_absoluteTolerance protected
Definition at line 93 of file linear_solver_pcg.h.
Referenced by g2o::LinearSolverPCG< MatrixType >::setAbsoluteTolerance(), and g2o::LinearSolverPCG< MatrixType >::solve().
template<typename MatrixType> MatrixPtrVector g2o::LinearSolverPCG< MatrixType >::_diag protected
Definition at line 97 of file linear_solver_pcg.h.
template<typename MatrixType> std::vector<std::pair<int, int> > g2o::LinearSolverPCG< MatrixType >::_indices protected
Definition at line 100 of file linear_solver_pcg.h.
template<typename MatrixType> MatrixVector g2o::LinearSolverPCG< MatrixType >::_J protected
Definition at line 98 of file linear_solver_pcg.h.
template<typename MatrixType> int g2o::LinearSolverPCG< MatrixType >::_maxIter protected
Definition at line 95 of file linear_solver_pcg.h.
Referenced by g2o::LinearSolverPCG< MatrixType >::maxIterations(), and g2o::LinearSolverPCG< MatrixType >::setMaxIterations().
template<typename MatrixType> double g2o::LinearSolverPCG< MatrixType >::_residual protected
Definition at line 92 of file linear_solver_pcg.h.
Referenced by g2o::LinearSolverPCG< MatrixType >::init().
template<typename MatrixType> MatrixPtrVector g2o::LinearSolverPCG< MatrixType >::_sparseMat protected
Definition at line 101 of file linear_solver_pcg.h.
template<typename MatrixType> double g2o::LinearSolverPCG< MatrixType >::_tolerance protected
Definition at line 91 of file linear_solver_pcg.h.
Referenced by g2o::LinearSolverPCG< MatrixType >::LinearSolverPCG(), g2o::LinearSolverPCG< MatrixType >::setTolerance(), and g2o::LinearSolverPCG< MatrixType >::tolerance().
template<typename MatrixType> bool g2o::LinearSolverPCG< MatrixType >::_verbose protected
Definition at line 94 of file linear_solver_pcg.h.
Referenced by g2o::LinearSolverPCG< MatrixType >::LinearSolverPCG(), g2o::LinearSolverPCG< MatrixType >::setVerbose(), and g2o::LinearSolverPCG< MatrixType >::verbose().
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/solvers/pcg/linear_solver_pcg.h
/home/xuezhisd/CLionProjects/g2o/g2o/solvers/pcg/linear_solver_pcg.hpp