g2o: g2o::SensorPointXYOffset Class Reference
g2o::SensorPointXYOffset Class Reference
#include <sensor_pointxy_offset.h>
Public Member Functions
SensorPointXYOffset (const std::string &name_)
virtual void sense ()
virtual void addNoise (EdgeType *e)
virtual void addParameters ()
Public Member Functions inherited from g2o::PointSensorParameters
PointSensorParameters ()
double maxRange () const
void setMaxRange (double maxRange_)
double minRange () const
void setMinRange (double minRange_)
double fov () const
void setFov (double fov_)
double maxAngularDifference () const
void setMaxAngularDifference (double angularDifference)
Public Member Functions inherited from g2o::BinarySensor< Robot2D, EdgeSE2PointXYOffset, WorldObjectPointXY >
BinarySensor (const std::string &name)
void setInformation (const InformationType &information_)
const InformationType & information ()
Public Member Functions inherited from g2o::BaseSensor
BaseSensor (const std::string &name_)
BaseRobot * robot ()
void setRobot (BaseRobot *robot_)
World * world ()
OptimizableGraph * graph ()
std::vector< Parameter * > parameters ()
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef PoseVertexType::EstimateType RobotPoseType
Public Attributes inherited from g2o::BinarySensor< Robot2D, EdgeSE2PointXYOffset, WorldObjectPointXY >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Member Functions
bool isVisible (WorldObjectType *to)
Protected Member Functions inherited from g2o::BinarySensor< Robot2D, EdgeSE2PointXYOffset, WorldObjectPointXY >
EdgeType * mkEdge (WorldObjectType *object)
Protected Attributes
ParameterSE2Offset * _offsetParam
RobotPoseType _sensorPose
Protected Attributes inherited from g2o::PointSensorParameters
double _maxRange2
double _minRange2
double _fov
double _maxAngularDifference
Protected Attributes inherited from g2o::BinarySensor< Robot2D, EdgeSE2PointXYOffset, WorldObjectPointXY >
PoseObject * _robotPoseObject
InformationType _information
GaussianSampler< typename EdgeType::ErrorVector, InformationType > _sampler
Protected Attributes inherited from g2o::BaseSensor
std::string _name
std::vector< Parameter * > _parameters
BaseRobot * _robot
Additional Inherited Members
Public Types inherited from g2o::BinarySensor< Robot2D, EdgeSE2PointXYOffset, WorldObjectPointXY >
typedef Robot2D RobotType
typedef RobotType::PoseObject PoseObject
typedef RobotType::TrajectoryType TrajectoryType
typedef RobotType::PoseObject::VertexType PoseVertexType
typedef EdgeSE2PointXYOffset EdgeType
typedef WorldObjectPointXY WorldObjectType
typedef WorldObjectType::VertexType VertexType
typedef EdgeType::InformationType InformationType
Detailed Description
Definition at line 36 of file sensor_pointxy_offset.h.
Constructor & Destructor Documentation
g2o::SensorPointXYOffset::SensorPointXYOffset (const std::string & name_)
Definition at line 35 of file sensor_pointxy_offset.cpp.
References g2o::BinarySensor< Robot2D, EdgeSE2PointXYOffset, WorldObjectPointXY >::_information, _offsetParam, and g2o::BinarySensor< Robot2D, EdgeSE2PointXYOffset, WorldObjectPointXY >::setInformation().
                                                                 : BinarySensor<Robot2D, EdgeSE2PointXYOffset, WorldObjectPointXY>(name_) {
     _offsetParam = 0;
     _information.setIdentity();
     _information*=1000.;
     setInformation(_information);
   }
Member Function Documentation
void g2o::SensorPointXYOffset::addNoise (EdgeType * e) virtual
Reimplemented from g2o::BinarySensor< Robot2D, EdgeSE2PointXYOffset, WorldObjectPointXY >.
Definition at line 71 of file sensor_pointxy_offset.cpp.
References g2o::BinarySensor< Robot2D, EdgeSE2PointXYOffset, WorldObjectPointXY >::_sampler, g2o::GaussianSampler< SampleType, CovarianceType >::generateSample(), g2o::BinarySensor< Robot2D, EdgeSE2PointXYOffset, WorldObjectPointXY >::information(), g2o::BaseEdge< D, E >::measurement(), g2o::BaseEdge< D, E >::setInformation(), and g2o::EdgeSE2PointXYOffset::setMeasurement().
Referenced by sense().
{
     EdgeType::ErrorVector n=_sampler.generateSample();
     e->setMeasurement(e->measurement()+n);
     e->setInformation(information());
   }
void g2o::SensorPointXYOffset::addParameters () virtual
Reimplemented from g2o::BaseSensor.
Definition at line 64 of file sensor_pointxy_offset.cpp.
References _offsetParam, g2o::World::addParameter(), and g2o::BaseSensor::world().
{
     if (!_offsetParam)
       _offsetParam = new ParameterSE2Offset();
     assert(world());
     world()->addParameter(_offsetParam);
   }
bool g2o::SensorPointXYOffset::isVisible (SensorPointXYOffset::WorldObjectType * to) protected
Definition at line 42 of file sensor_pointxy_offset.cpp.
References g2o::PointSensorParameters::_fov, g2o::PointSensorParameters::_maxRange2, g2o::PointSensorParameters::_minRange2, g2o::BinarySensor< Robot2D, EdgeSE2PointXYOffset, WorldObjectPointXY >::_robotPoseObject, _sensorPose, and g2o::WorldObject< VertexType_ >::vertex().
Referenced by sense().
{
     if (! _robotPoseObject)
       return false;
     assert(to && to->vertex());
     VertexType* v=to->vertex();
     VertexType::EstimateType pose=v->estimate();
     VertexType::EstimateType delta = _sensorPose.inverse()*pose;
     Vector2d translation=delta;
     double range2=translation.squaredNorm();
     if (range2>_maxRange2)
       return false;
     if (range2<_minRange2)
       return false;
     translation.normalize();
     // the cameras have the z in front
     double bearing=atan2(translation.y(), translation.x());
     if (fabs(bearing)>_fov)
        return false;
     //cerr <<"a";
     return true;
   }
void g2o::SensorPointXYOffset::sense () virtual
Reimplemented from g2o::BinarySensor< Robot2D, EdgeSE2PointXYOffset, WorldObjectPointXY >.
Definition at line 77 of file sensor_pointxy_offset.cpp.
References _offsetParam, g2o::BinarySensor< Robot2D, EdgeSE2PointXYOffset, WorldObjectPointXY >::_robotPoseObject, _sensorPose, g2o::OptimizableGraph::addEdge(), addNoise(), g2o::BaseSensor::graph(), g2o::Parameter::id(), isVisible(), g2o::BinarySensor< Robot2D, EdgeSE2PointXYOffset, WorldObjectPointXY >::mkEdge(), g2o::World::objects(), g2o::ParameterSE2Offset::offset(), g2o::BaseSensor::robot(), g2o::EdgeSE2PointXYOffset::setMeasurementFromState(), g2o::OptimizableGraph::Edge::setParameterId(), g2o::Robot< RobotPoseObject >::trajectory(), and g2o::BaseSensor::world().
{
     if (! _offsetParam){
       return;
     }
     _robotPoseObject=0;
     RobotType* r= dynamic_cast<RobotType*>(robot());
     std::list<PoseObject*>::reverse_iterator it=r->trajectory().rbegin();
     int count = 0;
     while (it!=r->trajectory().rend() && count < 1){
       if (!_robotPoseObject)
   _robotPoseObject = *it;
       it++;
       count++;
     }
     if (!_robotPoseObject)
       return;
     _sensorPose = _robotPoseObject->vertex()->estimate()*_offsetParam->offset();
     for (std::set<BaseWorldObject*>::iterator it=world()->objects().begin();
    it!=world()->objects().end(); it++){
       WorldObjectType* o=dynamic_cast<WorldObjectType*>(*it);
       if (o && isVisible(o)){
   EdgeType* e=mkEdge(o);
   e->setParameterId(0,_offsetParam->id());
   if (e && graph()) {
     graph()->addEdge(e);
     e->setMeasurementFromState();
           addNoise(e);
   }
       }
     }
   }
Member Data Documentation
ParameterSE2Offset* g2o::SensorPointXYOffset::_offsetParam protected
Definition at line 46 of file sensor_pointxy_offset.h.
Referenced by addParameters(), sense(), and SensorPointXYOffset().
RobotPoseType g2o::SensorPointXYOffset::_sensorPose protected
Definition at line 47 of file sensor_pointxy_offset.h.
Referenced by isVisible(), and sense().
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef PoseVertexType::EstimateType g2o::SensorPointXYOffset::RobotPoseType
Definition at line 39 of file sensor_pointxy_offset.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_simulator/sensor_pointxy_offset.h
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_simulator/sensor_pointxy_offset.cpp