g2o: g2o::CacheSE3Offset Class Reference
g2o::CacheSE3Offset Class Reference
caching the offset related to a vertex
#include <parameter_se3_offset.h>
Public Member Functions
CacheSE3Offset ()
virtual void updateImpl ()
redefine this to do the update
const ParameterSE3Offset * offsetParam () const
void setOffsetParam (ParameterSE3Offset *offsetParam)
const Isometry3D & w2n () const
const Isometry3D & n2w () const
const Isometry3D & w2l () const
Public Member Functions inherited from g2o::Cache
Cache (CacheContainer *container_=0, const ParameterVector &parameters_=ParameterVector())
CacheKey key () const
OptimizableGraph::Vertex * vertex ()
OptimizableGraph * graph ()
CacheContainer * container ()
ParameterVector & parameters ()
void update ()
virtual HyperGraph::HyperGraphElementType elementType () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Member Functions
virtual bool resolveDependancies ()
Protected Member Functions inherited from g2o::Cache
Cache * installDependency (const std::string &type_, const std::vector< int > &parameterIndices)
Protected Attributes
ParameterSE3Offset * _offsetParam
the parameter connected to the cache
Isometry3D _w2n
Isometry3D _n2w
Isometry3D _w2l
Protected Attributes inherited from g2o::Cache
bool _updateNeeded
ParameterVector _parameters
std::vector< Cache * > _parentCaches
CacheContainer * _container
Detailed Description
caching the offset related to a vertex
Definition at line 74 of file parameter_se3_offset.h.
Constructor & Destructor Documentation
g2o::CacheSE3Offset::CacheSE3Offset ()
Definition at line 65 of file parameter_se3_offset.cpp.
                                  :
     Cache(),
     _offsetParam(0)
   {
   }
Member Function Documentation
const Isometry3D& g2o::CacheSE3Offset::n2w () const inline
Definition at line 84 of file parameter_se3_offset.h.
Referenced by g2o::EdgeSE3Prior::computeError(), g2o::EdgeSE3Offset::computeError(), g2o::EdgeSE3Offset::setMeasurementFromState(), and g2o::EdgeSE3Prior::setMeasurementFromState().
 { return _n2w;}
const ParameterSE3Offset* g2o::CacheSE3Offset::offsetParam () const inline
Definition at line 80 of file parameter_se3_offset.h.
Referenced by g2o::EdgeSE3Offset::initialEstimate(), g2o::EdgeSE3Prior::linearizeOplus(), g2o::EdgeSE3Offset::linearizeOplus(), and setOffsetParam().
 { return _offsetParam;}
bool g2o::CacheSE3Offset::resolveDependancies () protected virtual
Function to be called from a cache that has dependencies. It just invokes a sequence of installDependency(). Although the caches returned are stored in the _parentCache vector, it is better that you redefine your own cache member variables, for better readability
Reimplemented from g2o::Cache.
Reimplemented in g2o::CacheCamera.
Definition at line 71 of file parameter_se3_offset.cpp.
References _offsetParam, and g2o::Cache::_parameters.
{
     _offsetParam = dynamic_cast <ParameterSE3Offset*> (_parameters[0]);
     return _offsetParam != 0;
   }
void g2o::CacheSE3Offset::setOffsetParam (ParameterSE3Offset * offsetParam)
Definition at line 83 of file parameter_se3_offset.cpp.
References _offsetParam, g2o::opengl::drawBox(), g2o::ParameterSE3Offset::offset(), offsetParam(), POSE_PARAMETER_COLOR, and g2o::DrawAction::refreshPropertyPtrs().
   {
     _offsetParam = offsetParam;
   }
void g2o::CacheSE3Offset::updateImpl () virtual
redefine this to do the update
Implements g2o::Cache.
Reimplemented in g2o::CacheCamera.
Definition at line 76 of file parameter_se3_offset.cpp.
References _n2w, _offsetParam, _w2l, _w2n, g2o::BaseVertex< D, T >::estimate(), g2o::ParameterSE3Offset::offset(), and g2o::Cache::vertex().
{
     const VertexSE3* v = static_cast<const VertexSE3*>(vertex());
     _n2w = v->estimate() * _offsetParam->offset();
     _w2n = _n2w.inverse();
     _w2l = v->estimate().inverse();
   }
const Isometry3D& g2o::CacheSE3Offset::w2l () const inline
Definition at line 85 of file parameter_se3_offset.h.
Referenced by g2o::EdgeSE3PointXYZDepth::linearizeOplus(), g2o::EdgeSE3PointXYZ::linearizeOplus(), and g2o::EdgeSE3PointXYZDisparity::linearizeOplus().
 { return _w2l;}
const Isometry3D& g2o::CacheSE3Offset::w2n () const inline
Definition at line 83 of file parameter_se3_offset.h.
Referenced by g2o::EdgeSE3Offset::computeError(), g2o::EdgeSE3PointXYZ::computeError(), g2o::EdgeSE3Line3D::computeError(), g2o::EdgeSE3Offset::setMeasurementFromState(), and g2o::EdgeSE3PointXYZ::setMeasurementFromState().
 { return _w2n;}
Member Data Documentation
Isometry3D g2o::CacheSE3Offset::_n2w protected
Definition at line 90 of file parameter_se3_offset.h.
Referenced by updateImpl().
ParameterSE3Offset* g2o::CacheSE3Offset::_offsetParam protected
the parameter connected to the cache
Definition at line 88 of file parameter_se3_offset.h.
Referenced by resolveDependancies(), setOffsetParam(), and updateImpl().
Isometry3D g2o::CacheSE3Offset::_w2l protected
Definition at line 91 of file parameter_se3_offset.h.
Referenced by updateImpl().
Isometry3D g2o::CacheSE3Offset::_w2n protected
Definition at line 89 of file parameter_se3_offset.h.
Referenced by updateImpl().
g2o::CacheSE3Offset::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 76 of file parameter_se3_offset.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam3d/parameter_se3_offset.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam3d/parameter_se3_offset.cpp