g2o: g2o::Sampler Class Reference
g2o::Sampler Class Reference
#include <sampler.h>
Static Public Member Functions
static double gaussRand (double mean, double sigma)
static double uniformRand (double lowerBndr, double upperBndr)
static void seedRand ()
static void seedRand (unsigned int seed)
Detailed Description
Definition at line 79 of file sampler.h.
Member Function Documentation
static double g2o::Sampler::gaussRand (double mean, double sigma) inline static
Gaussian random with a mean and standard deviation. Uses the Polar method of Marsaglia.
Definition at line 86 of file sampler.h.
Referenced by main().
       {
         double x, y, r2;
         do {
           x = -1.0 + 2.0 * uniformRand(0.0, 1.0);
           y = -1.0 + 2.0 * uniformRand(0.0, 1.0);
           r2 = x * x + y * y;
         } while (r2 > 1.0 || r2 == 0.0);
         return mean + sigma * y * std::sqrt(-2.0 * log(r2) / r2);
       }
static void g2o::Sampler::seedRand () inline static
default seed function using the current time in seconds
Definition at line 107 of file sampler.h.
Referenced by main().
       {
         seedRand(static_cast<unsigned int>(std::time(NULL)));
       }
static void g2o::Sampler::seedRand (unsigned int seed) inline static
seed the random number generator
Definition at line 113 of file sampler.h.
       {
         std::srand(seed);
       }
static double g2o::Sampler::uniformRand (double lowerBndr, double upperBndr) inline static
sample a number from a uniform distribution
Definition at line 100 of file sampler.h.
Referenced by main().
       {
         return lowerBndr + ((double) std::rand() / (RAND_MAX + 1.0)) * (upperBndr - lowerBndr);
       }
The documentation for this class was generated from the following file:
/home/xuezhisd/CLionProjects/g2o/g2o/stuff/sampler.h