g2o: g2o::EdgeSE3Euler Class Reference
g2o::EdgeSE3Euler Class Reference
3D edge between two VertexSE3, uses the euler angle parameterization for the read/write functions only.
#include <edge_se3_euler.h>
Public Member Functions
virtual EIGEN_MAKE_ALIGNED_OPERATOR_NEW bool read (std::istream &is)
read the vertex from a stream, i.e., the internal state of the vertex
virtual bool write (std::ostream &os) const
write the vertex to a stream
Public Member Functions inherited from g2o::EdgeSE3
EdgeSE3 ()
void computeError ()
virtual void setMeasurement (const Isometry3D &m)
virtual bool setMeasurementData (const double *d)
virtual bool getMeasurementData (double *d) const
void linearizeOplus ()
virtual int measurementDimension () const
virtual bool setMeasurementFromState ()
virtual double initialEstimatePossible (const OptimizableGraph::VertexSet &, OptimizableGraph::Vertex *)
virtual void initialEstimate (const OptimizableGraph::VertexSet &from, OptimizableGraph::Vertex *to)
Public Member Functions inherited from g2o::BaseBinaryEdge< 6, Isometry3D, VertexSE3, VertexSE3 >
BaseBinaryEdge ()
virtual OptimizableGraph::Vertex * createFrom ()
virtual OptimizableGraph::Vertex * createTo ()
virtual OptimizableGraph::Vertex * createVertex (int i)
virtual void resize (size_t size)
virtual bool allVerticesFixed () const
virtual void linearizeOplus (JacobianWorkspace &jacobianWorkspace)
const JacobianXiOplusType & jacobianOplusXi () const
returns the result of the linearization in the manifold space for the node xi
const JacobianXjOplusType & jacobianOplusXj () const
returns the result of the linearization in the manifold space for the node xj
virtual void constructQuadraticForm ()
virtual void mapHessianMemory (double *d, int i, int j, bool rowMajor)
Public Member Functions inherited from g2o::BaseEdge< D, Isometry3D >
BaseEdge ()
virtual ~BaseEdge ()
virtual double chi2 () const
computes the chi2 based on the cached error value, only valid after computeError has been called.
virtual const double * errorData () const
returns the error vector cached after calling the computeError;
virtual double * errorData ()
const ErrorVector & error () const
ErrorVector & error ()
EIGEN_STRONG_INLINE const InformationType & information () const
information matrix of the constraint
EIGEN_STRONG_INLINE InformationType & information ()
EIGEN_STRONG_INLINE void setInformation (const InformationType &information)
virtual const double * informationData () const
returns the memory of the information matrix, usable for example with a Eigen::Map<MatrixXD>
virtual double * informationData ()
EIGEN_STRONG_INLINE const Measurement & measurement () const
accessor functions for the measurement represented by the edge
virtual int rank () const
Public Member Functions inherited from g2o::OptimizableGraph::Edge
Edge ()
virtual ~Edge ()
virtual Edge * clone () const
RobustKernel * robustKernel () const
if NOT NULL, error of this edge will be robustifed with the kernel
void setRobustKernel (RobustKernel *ptr)
int level () const
returns the level of the edge
void setLevel (int l)
sets the level of the edge
int dimension () const
returns the dimensions of the error function
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createFrom())
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createTo())
long long internalId () const
the internal ID of the edge
OptimizableGraph * graph ()
const OptimizableGraph * graph () const
bool setParameterId (int argNum, int paramId)
const Parameter * parameter (int argNo) const
size_t numParameters () const
void resizeParameters (size_t newSize)
Public Member Functions inherited from g2o::HyperGraph::Edge
Edge (int id=InvalidId)
creates and empty edge with no vertices
const VertexContainer & vertices () const
VertexContainer & vertices ()
const Vertex * vertex (size_t i) const
Vertex * vertex (size_t i)
void setVertex (size_t i, Vertex *v)
int id () const
void setId (int id)
virtual HyperGraphElementType elementType () const
int numUndefinedVertices () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Member Functions inherited from g2o::HyperGraph::DataContainer
DataContainer ()
virtual ~DataContainer ()
const Data * userData () const
the user data associated with this vertex
Data * userData ()
void setUserData (Data *obs)
void addUserData (Data *obs)
Additional Inherited Members
Public Types inherited from g2o::BaseBinaryEdge< 6, Isometry3D, VertexSE3, VertexSE3 >
typedef VertexSE3 VertexXiType
typedef VertexSE3 VertexXjType
typedef BaseEdge< D, Isometry3D >::Measurement Measurement
typedef Eigen::Matrix< double, D, Di, D==1?Eigen::RowMajor:Eigen::ColMajor >::AlignedMapType JacobianXiOplusType
typedef Eigen::Matrix< double, D, Dj, D==1?Eigen::RowMajor:Eigen::ColMajor >::AlignedMapType JacobianXjOplusType
typedef BaseEdge< D, Isometry3D >::ErrorVector ErrorVector
typedef BaseEdge< D, Isometry3D >::InformationType InformationType
typedef Eigen::Map< Eigen::Matrix< double, Di, Dj, Di==1?Eigen::RowMajor:Eigen::ColMajor >, Eigen::Matrix< double, Di, Dj, Di==1?Eigen::RowMajor:Eigen::ColMajor >::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockType
typedef Eigen::Map< Eigen::Matrix< double, Dj, Di, Dj==1?Eigen::RowMajor:Eigen::ColMajor >, Eigen::Matrix< double, Dj, Di, Dj==1?Eigen::RowMajor:Eigen::ColMajor >::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockTransposedType
Public Types inherited from g2o::BaseEdge< D, Isometry3D >
typedef Isometry3D Measurement
typedef Eigen::Matrix< double, D, 1, Eigen::ColMajor > ErrorVector
typedef Eigen::Matrix< double, D, D, Eigen::ColMajor > InformationType
Public Attributes inherited from g2o::EdgeSE3
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Static Public Attributes inherited from g2o::BaseBinaryEdge< 6, Isometry3D, VertexSE3, VertexSE3 >
static const int Di
static const int Dj
static const int Dimension
Static Public Attributes inherited from g2o::BaseEdge< D, Isometry3D >
static const int Dimension
Protected Member Functions inherited from g2o::BaseEdge< D, Isometry3D >
InformationType robustInformation (const Vector3D &rho)
Protected Member Functions inherited from g2o::OptimizableGraph::Edge
template<typename ParameterType >
bool installParameter (ParameterType *&p, size_t argNo, int paramId=-1)
template<typename CacheType >
void resolveCache (CacheType *&cache, OptimizableGraph::Vertex *, const std::string &_type, const ParameterVector &parameters)
bool resolveParameters ()
virtual bool resolveCaches ()
Protected Attributes inherited from g2o::EdgeSE3
Isometry3D _inverseMeasurement
Protected Attributes inherited from g2o::BaseBinaryEdge< 6, Isometry3D, VertexSE3, VertexSE3 >
bool _hessianRowMajor
HessianBlockType _hessian
HessianBlockTransposedType _hessianTransposed
JacobianXiOplusType _jacobianOplusXi
JacobianXjOplusType _jacobianOplusXj
Protected Attributes inherited from g2o::BaseEdge< D, Isometry3D >
Measurement _measurement
InformationType _information
ErrorVector _error
Protected Attributes inherited from g2o::OptimizableGraph::Edge
int _dimension
int _level
RobustKernel * _robustKernel
long long _internalId
std::vector< int > _cacheIds
std::vector< std::string > _parameterTypes
std::vector< Parameter ** > _parameters
std::vector< int > _parameterIds
Protected Attributes inherited from g2o::HyperGraph::Edge
VertexContainer _vertices
int _id
unique id
Protected Attributes inherited from g2o::HyperGraph::DataContainer
Data * _userData
Detailed Description
3D edge between two VertexSE3, uses the euler angle parameterization for the read/write functions only.
Definition at line 41 of file edge_se3_euler.h.
Member Function Documentation
bool g2o::EdgeSE3Euler::read (std::istream & is) virtual
read the vertex from a stream, i.e., the internal state of the vertex
Reimplemented from g2o::EdgeSE3.
Definition at line 57 of file edge_se3_euler.cpp.
References g2o::internal::fromVectorET(), and g2o::jac_quat3_euler3().
   {
     Vector6d meas;
     for (int i=0; i<6; i++)
       is  >> meas[i];
     Isometry3D transf= g2o::internal::fromVectorET(meas);
     Matrix<double, 6, 6, Eigen::ColMajor> infMatEuler;
     for (int i=0; i<6; i++)
       for (int j=i; j<6; j++) {
         is >> infMatEuler(i,j);
         if (i!=j)
           infMatEuler(j,i) = infMatEuler(i,j);
       }
     Matrix<double, 6, 6, Eigen::ColMajor> J;
     jac_quat3_euler3(J, transf);
     Matrix<double, 6, 6, Eigen::ColMajor> infMat = J.transpose() * infMatEuler * J;
     setMeasurement(transf);
     setInformation(infMat);
     return true;
   }
bool g2o::EdgeSE3Euler::write (std::ostream & os) const virtual
write the vertex to a stream
Reimplemented from g2o::EdgeSE3.
Definition at line 78 of file edge_se3_euler.cpp.
References g2o::jac_quat3_euler3(), and g2o::internal::toVectorET().
   {
     Vector6d meas = g2o::internal::toVectorET(_measurement);
     for (int i=0; i<6; i++)
       os << meas[i] << " ";
     Matrix<double, 6, 6, Eigen::ColMajor> J;
     jac_quat3_euler3(J, measurement());
     //HACK: invert the jacobian to simulate the inverse derivative
     J=J.inverse();
     Matrix<double, 6, 6, Eigen::ColMajor> infMatEuler = J.transpose()*information()*J;
     for (int i=0; i<6; i++)
       for (int j=i; j<6; j++){
         os << " " <<  infMatEuler(i,j);
       }
     return os.good();
   }
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam3d_addons/edge_se3_euler.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam3d_addons/edge_se3_euler.cpp