g2o: g2o::DataQueue Class Reference
g2o::DataQueue Class Reference
a simple queue to store data and retrieve based on a timestamp
#include <data_queue.h>
Public Types
typedef std::map< double, RobotData * > Buffer
Public Member Functions
DataQueue ()
~DataQueue ()
void add (RobotData *rd)
RobotData * findClosestData (double timestamp) const
RobotData * before (double timestamp) const
RobotData * after (double timestamp) const
const Buffer & buffer () const
Protected Attributes
Buffer _buffer
Detailed Description
a simple queue to store data and retrieve based on a timestamp
Definition at line 40 of file data_queue.h.
Member Typedef Documentation
typedef std::map<double, RobotData*> g2o::DataQueue::Buffer
Definition at line 43 of file data_queue.h.
Constructor & Destructor Documentation
g2o::DataQueue::DataQueue ()
Definition at line 33 of file data_queue.cpp.
   {
   }
g2o::DataQueue::~DataQueue ()
Definition at line 37 of file data_queue.cpp.
   {
   }
Member Function Documentation
void g2o::DataQueue::add (RobotData * rd)
Definition at line 76 of file data_queue.cpp.
References _buffer, and g2o::RobotData::timestamp().
Referenced by g2o::Gm2dlIO::readRobotLaser().
   {
     _buffer[rd->timestamp()] = rd;
   }
RobotData * g2o::DataQueue::after (double timestamp) const
Definition at line 66 of file data_queue.cpp.
References _buffer.
   {
     if (_buffer.size() == 0 || _buffer.rbegin()->first < timestamp)
       return 0;
     Buffer::const_iterator ub = _buffer.upper_bound(timestamp);
     if (ub == _buffer.end())
       return 0;
     return ub->second;
   }
RobotData * g2o::DataQueue::before (double timestamp) const
Definition at line 57 of file data_queue.cpp.
References _buffer.
   {
     if (_buffer.size() == 0 || _buffer.begin()->first > timestamp)
       return 0;
     Buffer::const_iterator lb = _buffer.upper_bound(timestamp);
     --lb; // now it's the lower bound
     return lb->second;
   }
const Buffer& g2o::DataQueue::buffer () const inline
Definition at line 56 of file data_queue.h.
Referenced by main().
 {return _buffer;}
RobotData * g2o::DataQueue::findClosestData (double timestamp) const
Definition at line 41 of file data_queue.cpp.
References _buffer.
Referenced by g2o::addOdometryCalibLinksDifferential(), and main().
   {
     if (_buffer.rbegin()->first < timestamp)
       return _buffer.rbegin()->second;
     if (_buffer.begin()->first > timestamp)
       return _buffer.begin()->second;
     Buffer::const_iterator ub = _buffer.upper_bound(timestamp);
     Buffer::const_iterator lb = ub;
     --lb;
     if (fabs(lb->first - timestamp) < fabs(ub->first - timestamp))
       return lb->second;
     else
       return ub->second;
   }
Member Data Documentation
Buffer g2o::DataQueue::_buffer protected
Definition at line 59 of file data_queue.h.
Referenced by add(), after(), before(), and findClosestData().
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/data/data_queue.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/data/data_queue.cpp