g2o: g2o::GaussianSampler< SampleType, CovarianceType > Class Template Reference
g2o::GaussianSampler< SampleType, CovarianceType > Class Template Reference
#include <sampler.h>
Public Member Functions
GaussianSampler (bool hasGenerator=true)
~GaussianSampler ()
void setDistribution (const CovarianceType &cov)
SampleType generateSample ()
Protected Attributes
CovarianceType _cholesky
std::mt19937 * _generator
Detailed Description
template<class SampleType, class CovarianceType>
class g2o::GaussianSampler< SampleType, CovarianceType >
Definition at line 48 of file sampler.h.
Constructor & Destructor Documentation
template<class SampleType, class CovarianceType> g2o::GaussianSampler< SampleType, CovarianceType >::GaussianSampler (bool hasGenerator = true) inline
Definition at line 50 of file sampler.h.
                                             :
       _generator(0)
     {
       if (hasGenerator){
         _generator = new std::mt19937;
       }
     }
template<class SampleType, class CovarianceType> g2o::GaussianSampler< SampleType, CovarianceType >::~GaussianSampler () inline
Definition at line 57 of file sampler.h.
{
       delete _generator;
     }
Member Function Documentation
template<class SampleType, class CovarianceType> SampleType g2o::GaussianSampler< SampleType, CovarianceType >::generateSample () inline
Definition at line 67 of file sampler.h.
Referenced by g2o::SensorOdometry2D::addNoise(), g2o::SensorOdometry3D::addNoise(), g2o::SensorPointXYBearing::addNoise(), g2o::SensorPose2D::addNoise(), g2o::SensorPose3DOffset::addNoise(), g2o::SensorPointXY::addNoise(), g2o::SensorPointXYOffset::addNoise(), g2o::SensorSegment2DPointLine::addNoise(), g2o::SensorPose3D::addNoise(), g2o::SensorSegment2D::addNoise(), g2o::SensorSegment2DLine::addNoise(), g2o::SensorPointXYZ::addNoise(), g2o::SensorPointXYZDepth::addNoise(), g2o::SensorSE3Prior::addNoise(), g2o::SensorPointXYZDisparity::addNoise(), and main().
{
       SampleType s;
       for (int i=0; i<s.size(); i++){
         s(i) = (_generator) ? sampleGaussian(_generator) : sampleGaussian();
       }
       return _cholesky*s;
     }
template<class SampleType, class CovarianceType> void g2o::GaussianSampler< SampleType, CovarianceType >::setDistribution (const CovarianceType & cov) inline
Definition at line 60 of file sampler.h.
Referenced by main().
{
       Eigen::LLT<CovarianceType> cholDecomp;
       cholDecomp.compute(cov);
       if (cholDecomp.info()==Eigen::NumericalIssue)
         return;
       _cholesky=cholDecomp.matrixL();
     }
Member Data Documentation
template<class SampleType, class CovarianceType> CovarianceType g2o::GaussianSampler< SampleType, CovarianceType >::_cholesky protected
Definition at line 75 of file sampler.h.
Referenced by g2o::GaussianSampler< typename EdgeType::ErrorVector, InformationType >::generateSample(), and g2o::GaussianSampler< typename EdgeType::ErrorVector, InformationType >::setDistribution().
template<class SampleType, class CovarianceType> std::mt19937* g2o::GaussianSampler< SampleType, CovarianceType >::_generator protected
Definition at line 76 of file sampler.h.
Referenced by g2o::GaussianSampler< typename EdgeType::ErrorVector, InformationType >::GaussianSampler(), g2o::GaussianSampler< typename EdgeType::ErrorVector, InformationType >::generateSample(), and g2o::GaussianSampler< typename EdgeType::ErrorVector, InformationType >::~GaussianSampler().
The documentation for this class was generated from the following file:
/home/xuezhisd/CLionProjects/g2o/g2o/stuff/sampler.h