g2o: FlexLexer Class Reference
FlexLexer Class Reference abstract
#include <FlexLexer.h>
Public Member Functions
virtual ~FlexLexer ()
const char * YYText () const
int YYLeng () const
virtual void yy_switch_to_buffer (struct yy_buffer_state *new_buffer)=0
virtual struct yy_buffer_state * yy_create_buffer (FLEX_STD istream *s, int size)=0
virtual void yy_delete_buffer (struct yy_buffer_state *b)=0
virtual void yyrestart (FLEX_STD istream *s)=0
virtual int yylex ()=0
int yylex (FLEX_STD istream *new_in, FLEX_STD ostream *new_out=0)
virtual void switch_streams (FLEX_STD istream *new_in=0, FLEX_STD ostream *new_out=0)=0
int lineno () const
int debug () const
void set_debug (int flag)
Protected Attributes
char * yytext
int yyleng
int yylineno
int yy_flex_debug
Detailed Description
Definition at line 61 of file FlexLexer.h.
Constructor & Destructor Documentation
virtual FlexLexer::~FlexLexer () inline virtual
Definition at line 63 of file FlexLexer.h.
 { }
Member Function Documentation
int FlexLexer::debug () const inline
Definition at line 91 of file FlexLexer.h.
References yy_flex_debug.
 { return yy_flex_debug; }
int FlexLexer::lineno () const inline
Definition at line 89 of file FlexLexer.h.
References yylineno.
 { return yylineno; }
void FlexLexer::set_debug (int flag) inline
Definition at line 92 of file FlexLexer.h.
References yy_flex_debug.
 { yy_flex_debug = flag; }
virtual void FlexLexer::switch_streams (FLEX_STD istream * new_in = 0, FLEX_STD ostream * new_out = 0) pure virtual
Implemented in yyFlexLexer.
Referenced by yylex().
virtual struct yy_buffer_state* FlexLexer::yy_create_buffer (FLEX_STD istream * s, int size) pure virtual
Implemented in yyFlexLexer.
Referenced by YYLeng().
virtual void FlexLexer::yy_delete_buffer (struct yy_buffer_state * b) pure virtual
Implemented in yyFlexLexer.
Referenced by YYLeng().
virtual void FlexLexer::yy_switch_to_buffer (struct yy_buffer_state * new_buffer) pure virtual
Implemented in yyFlexLexer.
Referenced by YYLeng().
int FlexLexer::YYLeng () const inline
Definition at line 66 of file FlexLexer.h.
References FLEX_STD, yy_create_buffer(), yy_delete_buffer(), yy_switch_to_buffer(), yyleng, yylex(), and yyrestart().
 { return yyleng; }
virtual int FlexLexer::yylex () pure virtual
Implemented in yyFlexLexer.
Referenced by YYLeng(), and yylex().
int FlexLexer::yylex (FLEX_STD istream * new_in, FLEX_STD ostream * new_out = 0) inline
Definition at line 78 of file FlexLexer.h.
References FLEX_STD, switch_streams(), and yylex().
     {
     switch_streams( new_in, new_out );
     return yylex();
     }
virtual void FlexLexer::yyrestart (FLEX_STD istream * s) pure virtual
Implemented in yyFlexLexer.
Referenced by YYLeng().
const char* FlexLexer::YYText () const inline
Definition at line 65 of file FlexLexer.h.
References yytext.
 { return yytext; }
Member Data Documentation
int FlexLexer::yy_flex_debug protected
Definition at line 98 of file FlexLexer.h.
Referenced by debug(), and set_debug().
int FlexLexer::yyleng protected
Definition at line 96 of file FlexLexer.h.
Referenced by YYLeng().
int FlexLexer::yylineno protected
Definition at line 97 of file FlexLexer.h.
Referenced by lineno().
char* FlexLexer::yytext protected
Definition at line 95 of file FlexLexer.h.
Referenced by YYText().
The documentation for this class was generated from the following file:
/home/xuezhisd/CLionProjects/g2o/g2o/examples/interactive_slam/slam_parser/parser/FlexLexer.h