g2o: g2o::LinearSolverCSparse< MatrixType > Class Template Reference
g2o::LinearSolverCSparse< MatrixType > Class Template Reference
linear solver which uses CSparse
#include <linear_solver_csparse.h>
Public Member Functions
LinearSolverCSparse ()
virtual ~LinearSolverCSparse ()
virtual bool init ()
bool solve (const SparseBlockMatrix< MatrixType > &A, double *x, double *b)
bool solveBlocks (double **&blocks, const SparseBlockMatrix< MatrixType > &A)
virtual bool solvePattern (SparseBlockMatrix< MatrixXD > &spinv, const std::vector< std::pair< int, int > > &blockIndices, const SparseBlockMatrix< MatrixType > &A)
bool blockOrdering () const
do the AMD ordering on the blocks or on the scalar matrix
void setBlockOrdering (bool blockOrdering)
virtual bool writeDebug () const
write a debug dump of the system matrix if it is not SPD in solve
virtual void setWriteDebug (bool b)
Public Member Functions inherited from g2o::LinearSolverCCS< MatrixType >
LinearSolverCCS ()
~LinearSolverCCS ()
Public Member Functions inherited from g2o::LinearSolver< MatrixType >
LinearSolver ()
virtual ~LinearSolver ()
Protected Member Functions
void computeSymbolicDecomposition (const SparseBlockMatrix< MatrixType > &A)
void fillCSparse (const SparseBlockMatrix< MatrixType > &A, bool onlyValues)
Protected Member Functions inherited from g2o::LinearSolverCCS< MatrixType >
void initMatrixStructure (const SparseBlockMatrix< MatrixType > &A)
Protected Attributes
css * _symbolicDecomposition
int _csWorkspaceSize
double * _csWorkspace
int * _csIntWorkspace
CSparseExt * _ccsA
bool _blockOrdering
MatrixStructure _matrixStructure
VectorXI _scalarPermutation
bool _writeDebug
Protected Attributes inherited from g2o::LinearSolverCCS< MatrixType >
SparseBlockMatrixCCS< MatrixType > * _ccsMatrix
Detailed Description
template<typename MatrixType>
class g2o::LinearSolverCSparse< MatrixType >
linear solver which uses CSparse
Definition at line 71 of file linear_solver_csparse.h.
Constructor & Destructor Documentation
template<typename MatrixType> g2o::LinearSolverCSparse< MatrixType >::LinearSolverCSparse () inline
Definition at line 74 of file linear_solver_csparse.h.
                           :
       LinearSolverCCS<MatrixType>()
     {
       _symbolicDecomposition = 0;
       _csWorkspaceSize = -1;
       _csWorkspace = 0;
       _csIntWorkspace = 0;
       _ccsA = new CSparseExt;
       _blockOrdering = true;
       _writeDebug = true;
     }
template<typename MatrixType> virtual g2o::LinearSolverCSparse< MatrixType >::~LinearSolverCSparse () inline virtual
Definition at line 86 of file linear_solver_csparse.h.
     {
       if (_symbolicDecomposition) {
         cs_sfree(_symbolicDecomposition);
         _symbolicDecomposition = 0;
       }
       delete[] _csWorkspace; _csWorkspace = 0;
       delete[] _csIntWorkspace; _csIntWorkspace = 0;
       delete _ccsA;
     }
Member Function Documentation
template<typename MatrixType> bool g2o::LinearSolverCSparse< MatrixType >::blockOrdering () const inline
do the AMD ordering on the blocks or on the scalar matrix
Definition at line 228 of file linear_solver_csparse.h.
 { return _blockOrdering;}
template<typename MatrixType> void g2o::LinearSolverCSparse< MatrixType >::computeSymbolicDecomposition (const SparseBlockMatrix< MatrixType > & A) inline protected
Definition at line 246 of file linear_solver_csparse.h.
References g2o::MatrixStructure::Aii, g2o::MatrixStructure::Ap, g2o::SparseBlockMatrix< MatrixType >::colBaseOfBlock(), g2o::SparseBlockMatrix< MatrixType >::colsOfBlock(), g2o::SparseBlockMatrix< MatrixType >::fillBlockStructure(), g2o::get_monotonic_time(), g2o::G2OBatchStatistics::globalStats(), g2o::MatrixStructure::n, g2o::MatrixStructure::nzMax(), and g2o::G2OBatchStatistics::timeSymbolicDecomposition.
     {
       double t=get_monotonic_time();
       if (! _blockOrdering) {
         _symbolicDecomposition = cs_schol (1, _ccsA) ;
       } else {
         A.fillBlockStructure(_matrixStructure);
         // prepare block structure for the CSparse call
         cs auxBlock;
         auxBlock.nzmax = _matrixStructure.nzMax();
         auxBlock.m = auxBlock.n = _matrixStructure.n;
         auxBlock.p = _matrixStructure.Ap;
         auxBlock.i = _matrixStructure.Aii;
         auxBlock.x = NULL; // no values
         auxBlock.nz = -1; // CCS format
         // AMD ordering on the block structure
         const int& n = _ccsA->n;
         int* P = cs_amd(1, &auxBlock);
         // blow up the permutation to the scalar matrix
         if (_scalarPermutation.size() == 0)
           _scalarPermutation.resize(n);
         if (_scalarPermutation.size() < n)
           _scalarPermutation.resize(2*n);
         size_t scalarIdx = 0;
         for (int i = 0; i < _matrixStructure.n; ++i) {
           const int& p = P[i];
           int base  = A.colBaseOfBlock(p);
           int nCols = A.colsOfBlock(p);
           for (int j = 0; j < nCols; ++j)
             _scalarPermutation(scalarIdx++) = base++;
         }
         assert((int)scalarIdx == n);
         cs_free(P);
         // apply the scalar permutation to finish symbolic decomposition
         _symbolicDecomposition = (css*) cs_calloc(1, sizeof(css));       /* allocate result S */
         _symbolicDecomposition->pinv = cs_pinv(_scalarPermutation.data(), n);
         cs* C = cs_symperm(_ccsA, _symbolicDecomposition->pinv, 0);
         _symbolicDecomposition->parent = cs_etree(C, 0);
         int* post = cs_post(_symbolicDecomposition->parent, n);
         int* c = cs_counts(C, _symbolicDecomposition->parent, post, 0);
         cs_free(post);
         cs_spfree(C);
         _symbolicDecomposition->cp = (int*) cs_malloc(n+1, sizeof(int));
         _symbolicDecomposition->unz = _symbolicDecomposition->lnz = cs_cumsum(_symbolicDecomposition->cp, c, n);
         cs_free(c);
         if (_symbolicDecomposition->lnz < 0) {
           cs_sfree(_symbolicDecomposition);
           _symbolicDecomposition = 0;
         }
       }
       G2OBatchStatistics* globalStats = G2OBatchStatistics::globalStats();
       if (globalStats){
         globalStats->timeSymbolicDecomposition = get_monotonic_time() - t;
       }
       /* std::cerr << "# Number of nonzeros in L: " << (int)_symbolicDecomposition->lnz << " by " */
       /*   << (_blockOrdering ? "block" : "scalar") << " AMD ordering " << std::endl; */
     }
template<typename MatrixType> void g2o::LinearSolverCSparse< MatrixType >::fillCSparse (const SparseBlockMatrix< MatrixType > & A, bool onlyValues) inline protected
Definition at line 310 of file linear_solver_csparse.h.
References g2o::SparseBlockMatrix< MatrixType >::cols(), g2o::CSparseExt::columnsAllocated, g2o::SparseBlockMatrix< MatrixType >::nonZeros(), and g2o::SparseBlockMatrix< MatrixType >::rows().
     {
       if (! onlyValues)
         this->initMatrixStructure(A);
       int m = A.rows();
       int n = A.cols();
       assert(m > 0 && n > 0 && "Hessian has 0 rows/cols");
       if (_ccsA->columnsAllocated < n) {
         _ccsA->columnsAllocated = _ccsA->columnsAllocated == 0 ? n : 2 * n; // pre-allocate more space if re-allocating
         delete[] _ccsA->p;
         _ccsA->p = new int[_ccsA->columnsAllocated+1];
       }
       if (! onlyValues) {
         int nzmax = A.nonZeros();
         if (_ccsA->nzmax < nzmax) {
           _ccsA->nzmax = _ccsA->nzmax == 0 ? nzmax : 2 * nzmax; // pre-allocate more space if re-allocating
           delete[] _ccsA->x;
           delete[] _ccsA->i;
           _ccsA->i = new int[_ccsA->nzmax];
           _ccsA->x = new double[_ccsA->nzmax];
         }
       }
       _ccsA->m = m;
       _ccsA->n = n;
       if (onlyValues) {
         this->_ccsMatrix->fillCCS(_ccsA->x, true);
       } else {
         int nz = this->_ccsMatrix->fillCCS(_ccsA->p, _ccsA->i, _ccsA->x, true); (void) nz;
         assert(nz <= _ccsA->nzmax);
       }
       _ccsA->nz=-1; // tag as CCS formatted matrix
     }
template<typename MatrixType> virtual bool g2o::LinearSolverCSparse< MatrixType >::init () inline virtual
init for operating on matrices with a different non-zero pattern like before
Implements g2o::LinearSolver< MatrixType >.
Definition at line 97 of file linear_solver_csparse.h.
Referenced by g2o::SolverSLAM2DLinear::solveOrientation().
     {
       if (_symbolicDecomposition) {
         cs_sfree(_symbolicDecomposition);
         _symbolicDecomposition = 0;
       }
       return true;
     }
template<typename MatrixType> void g2o::LinearSolverCSparse< MatrixType >::setBlockOrdering (bool blockOrdering) inline
Definition at line 229 of file linear_solver_csparse.h.
 { _blockOrdering = blockOrdering;}
template<typename MatrixType> virtual void g2o::LinearSolverCSparse< MatrixType >::setWriteDebug (bool b) inline virtual
Reimplemented from g2o::LinearSolver< MatrixType >.
Definition at line 233 of file linear_solver_csparse.h.
 { _writeDebug = b;}
template<typename MatrixType> bool g2o::LinearSolverCSparse< MatrixType >::solve (const SparseBlockMatrix< MatrixType > & A, double * x, double * b) inline virtual
Assumes that A is the same matrix for several calls. Among other assumptions, the non-zero pattern does not change! If the matrix changes call init() before. solve system Ax = b, x and b have to allocated beforehand!!
Implements g2o::LinearSolver< MatrixType >.
Definition at line 106 of file linear_solver_csparse.h.
References g2o::G2OBatchStatistics::choleskyNNZ, g2o::csparse_extension::cs_cholsolsymb(), g2o::get_monotonic_time(), g2o::G2OBatchStatistics::globalStats(), g2o::G2OBatchStatistics::timeNumericDecomposition, and g2o::csparse_extension::writeCs2Octave().
     {
       fillCSparse(A, _symbolicDecomposition != 0);
       // perform symbolic cholesky once
       if (_symbolicDecomposition == 0) {
         computeSymbolicDecomposition(A);
       }
       // re-allocate the temporary workspace for cholesky
       if (_csWorkspaceSize < _ccsA->n) {
         _csWorkspaceSize = 2 * _ccsA->n;
         delete[] _csWorkspace;
         _csWorkspace = new double[_csWorkspaceSize];
         delete[] _csIntWorkspace;
         _csIntWorkspace = new int[2*_csWorkspaceSize];
       }
       double t=get_monotonic_time();
       // _x = _b for calling csparse
       if (x != b)
         memcpy(x, b, _ccsA->n * sizeof(double));
       int ok = csparse_extension::cs_cholsolsymb(_ccsA, x, _symbolicDecomposition, _csWorkspace, _csIntWorkspace);
       if (! ok) {
         if (_writeDebug) {
           std::cerr << "Cholesky failure, writing debug.txt (Hessian loadable by Octave)" << std::endl;
           csparse_extension::writeCs2Octave("debug.txt", _ccsA, true);
         }
         return false;
       }
       G2OBatchStatistics* globalStats = G2OBatchStatistics::globalStats();
       if (globalStats){
         globalStats->timeNumericDecomposition = get_monotonic_time() - t;
         globalStats->choleskyNNZ = static_cast<size_t>(_symbolicDecomposition->lnz);
       }
       return ok != 0;
     }
template<typename MatrixType> bool g2o::LinearSolverCSparse< MatrixType >::solveBlocks (double **& blocks, const SparseBlockMatrix< MatrixType > & A) inline virtual
Inverts the diagonal blocks of A
Returns
false if not defined.
Reimplemented from g2o::LinearSolver< MatrixType >.
Definition at line 144 of file linear_solver_csparse.h.
References g2o::G2OBatchStatistics::choleskyNNZ, g2o::SparseBlockMatrix< MatrixType >::colsOfBlock(), g2o::MarginalCovarianceCholesky::computeCovariance(), g2o::csparse_extension::cs_chol_workspace(), g2o::G2OBatchStatistics::globalStats(), g2o::SparseBlockMatrix< MatrixType >::rowBlockIndices(), g2o::SparseBlockMatrix< MatrixType >::rows(), g2o::SparseBlockMatrix< MatrixType >::rowsOfBlock(), and g2o::MarginalCovarianceCholesky::setCholeskyFactor().
{
       fillCSparse(A, _symbolicDecomposition != 0);
       // perform symbolic cholesky once
       if (_symbolicDecomposition == 0) {
         computeSymbolicDecomposition(A);
         assert(_symbolicDecomposition && "Symbolic cholesky failed");
       }
       // re-allocate the temporary workspace for cholesky
       if (_csWorkspaceSize < _ccsA->n) {
         _csWorkspaceSize = 2 * _ccsA->n;
         delete[] _csWorkspace;
         _csWorkspace = new double[_csWorkspaceSize];
         delete[] _csIntWorkspace;
         _csIntWorkspace = new int[2*_csWorkspaceSize];
       }
       if (! blocks){
         blocks=new double*[A.rows()];
         double **block=blocks;
         for (size_t i=0; i < A.rowBlockIndices().size(); ++i){
           int dim = A.rowsOfBlock(i) * A.colsOfBlock(i);
           *block = new double [dim];
           block++;
         }
       }
       int ok = 1;
       csn* numericCholesky = csparse_extension::cs_chol_workspace(_ccsA, _symbolicDecomposition, _csIntWorkspace, _csWorkspace);
       if (numericCholesky) {
         MarginalCovarianceCholesky mcc;
         mcc.setCholeskyFactor(_ccsA->n, numericCholesky->L->p, numericCholesky->L->i, numericCholesky->L->x, _symbolicDecomposition->pinv);
         mcc.computeCovariance(blocks, A.rowBlockIndices());
         cs_nfree(numericCholesky);
       } else {
         ok = 0;
         std::cerr << "inverse fail (numeric decomposition)" << std::endl;
       }
       G2OBatchStatistics* globalStats = G2OBatchStatistics::globalStats();
       if (globalStats){
         globalStats->choleskyNNZ = static_cast<size_t>(_symbolicDecomposition->lnz);
       }
       return ok != 0;
     }
template<typename MatrixType> virtual bool g2o::LinearSolverCSparse< MatrixType >::solvePattern (SparseBlockMatrix< MatrixXD > & spinv, const std::vector< std::pair< int, int > > & blockIndices, const SparseBlockMatrix< MatrixType > & A) inline virtual
Inverts the a block pattern of A in spinv
Returns
false if not defined.
Reimplemented from g2o::LinearSolver< MatrixType >.
Definition at line 190 of file linear_solver_csparse.h.
References g2o::G2OBatchStatistics::choleskyNNZ, g2o::MarginalCovarianceCholesky::computeCovariance(), g2o::csparse_extension::cs_chol_workspace(), g2o::G2OBatchStatistics::globalStats(), g2o::SparseBlockMatrix< MatrixType >::rowBlockIndices(), and g2o::MarginalCovarianceCholesky::setCholeskyFactor().
{
       fillCSparse(A, _symbolicDecomposition != 0);
       // perform symbolic cholesky once
       if (_symbolicDecomposition == 0) {
         computeSymbolicDecomposition(A);
         assert(_symbolicDecomposition && "Symbolic cholesky failed");
       }
       // re-allocate the temporary workspace for cholesky
       if (_csWorkspaceSize < _ccsA->n) {
         _csWorkspaceSize = 2 * _ccsA->n;
         delete[] _csWorkspace;
         _csWorkspace = new double[_csWorkspaceSize];
         delete[] _csIntWorkspace;
         _csIntWorkspace = new int[2*_csWorkspaceSize];
       }
       int ok = 1;
       csn* numericCholesky = csparse_extension::cs_chol_workspace(_ccsA, _symbolicDecomposition, _csIntWorkspace, _csWorkspace);
       if (numericCholesky) {
         MarginalCovarianceCholesky mcc;
         mcc.setCholeskyFactor(_ccsA->n, numericCholesky->L->p, numericCholesky->L->i, numericCholesky->L->x, _symbolicDecomposition->pinv);
         mcc.computeCovariance(spinv, A.rowBlockIndices(), blockIndices);
         cs_nfree(numericCholesky);
       } else {
         ok = 0;
         std::cerr << "inverse fail (numeric decomposition)" << std::endl;
       }
       G2OBatchStatistics* globalStats = G2OBatchStatistics::globalStats();
       if (globalStats){
         globalStats->choleskyNNZ = static_cast<size_t>(_symbolicDecomposition->lnz);
       }
       return ok != 0;
     }
template<typename MatrixType> virtual bool g2o::LinearSolverCSparse< MatrixType >::writeDebug () const inline virtual
write a debug dump of the system matrix if it is not SPD in solve
Reimplemented from g2o::LinearSolver< MatrixType >.
Definition at line 232 of file linear_solver_csparse.h.
 { return _writeDebug;}
Member Data Documentation
template<typename MatrixType> bool g2o::LinearSolverCSparse< MatrixType >::_blockOrdering protected
Definition at line 241 of file linear_solver_csparse.h.
template<typename MatrixType> CSparseExt* g2o::LinearSolverCSparse< MatrixType >::_ccsA protected
Definition at line 240 of file linear_solver_csparse.h.
template<typename MatrixType> int* g2o::LinearSolverCSparse< MatrixType >::_csIntWorkspace protected
Definition at line 239 of file linear_solver_csparse.h.
template<typename MatrixType> double* g2o::LinearSolverCSparse< MatrixType >::_csWorkspace protected
Definition at line 238 of file linear_solver_csparse.h.
template<typename MatrixType> int g2o::LinearSolverCSparse< MatrixType >::_csWorkspaceSize protected
Definition at line 237 of file linear_solver_csparse.h.
template<typename MatrixType> MatrixStructure g2o::LinearSolverCSparse< MatrixType >::_matrixStructure protected
Definition at line 242 of file linear_solver_csparse.h.
template<typename MatrixType> VectorXI g2o::LinearSolverCSparse< MatrixType >::_scalarPermutation protected
Definition at line 243 of file linear_solver_csparse.h.
template<typename MatrixType> css* g2o::LinearSolverCSparse< MatrixType >::_symbolicDecomposition protected
Definition at line 236 of file linear_solver_csparse.h.
template<typename MatrixType> bool g2o::LinearSolverCSparse< MatrixType >::_writeDebug protected
Definition at line 244 of file linear_solver_csparse.h.
The documentation for this class was generated from the following file:
/home/xuezhisd/CLionProjects/g2o/g2o/solvers/csparse/linear_solver_csparse.h