g2o: g2o::EdgeSE3PointXYZDepth Class Reference
g2o::EdgeSE3PointXYZDepth Class Reference
#include <edge_se3_pointxyz_depth.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW EdgeSE3PointXYZDepth ()
virtual bool read (std::istream &is)
read the vertex from a stream, i.e., the internal state of the vertex
virtual bool write (std::ostream &os) const
write the vertex to a stream
void computeError ()
virtual void linearizeOplus ()
virtual void setMeasurement (const Vector3D &m)
virtual bool setMeasurementData (const double *d)
virtual bool getMeasurementData (double *d) const
virtual int measurementDimension () const
virtual bool setMeasurementFromState ()
virtual double initialEstimatePossible (const OptimizableGraph::VertexSet &from, OptimizableGraph::Vertex *to)
virtual void initialEstimate (const OptimizableGraph::VertexSet &from, OptimizableGraph::Vertex *to)
Public Member Functions inherited from g2o::BaseBinaryEdge< 3, Vector3D, VertexSE3, VertexPointXYZ >
BaseBinaryEdge ()
virtual OptimizableGraph::Vertex * createFrom ()
virtual OptimizableGraph::Vertex * createTo ()
virtual OptimizableGraph::Vertex * createVertex (int i)
virtual void resize (size_t size)
virtual bool allVerticesFixed () const
virtual void linearizeOplus (JacobianWorkspace &jacobianWorkspace)
const JacobianXiOplusType & jacobianOplusXi () const
returns the result of the linearization in the manifold space for the node xi
const JacobianXjOplusType & jacobianOplusXj () const
returns the result of the linearization in the manifold space for the node xj
virtual void constructQuadraticForm ()
virtual void mapHessianMemory (double *d, int i, int j, bool rowMajor)
Public Member Functions inherited from g2o::BaseEdge< D, Vector3D >
BaseEdge ()
virtual ~BaseEdge ()
virtual double chi2 () const
computes the chi2 based on the cached error value, only valid after computeError has been called.
virtual const double * errorData () const
returns the error vector cached after calling the computeError;
virtual double * errorData ()
const ErrorVector & error () const
ErrorVector & error ()
EIGEN_STRONG_INLINE const InformationType & information () const
information matrix of the constraint
EIGEN_STRONG_INLINE InformationType & information ()
EIGEN_STRONG_INLINE void setInformation (const InformationType &information)
virtual const double * informationData () const
returns the memory of the information matrix, usable for example with a Eigen::Map<MatrixXD>
virtual double * informationData ()
EIGEN_STRONG_INLINE const Measurement & measurement () const
accessor functions for the measurement represented by the edge
virtual int rank () const
Public Member Functions inherited from g2o::OptimizableGraph::Edge
Edge ()
virtual ~Edge ()
virtual Edge * clone () const
RobustKernel * robustKernel () const
if NOT NULL, error of this edge will be robustifed with the kernel
void setRobustKernel (RobustKernel *ptr)
int level () const
returns the level of the edge
void setLevel (int l)
sets the level of the edge
int dimension () const
returns the dimensions of the error function
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createFrom())
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createTo())
long long internalId () const
the internal ID of the edge
OptimizableGraph * graph ()
const OptimizableGraph * graph () const
bool setParameterId (int argNum, int paramId)
const Parameter * parameter (int argNo) const
size_t numParameters () const
void resizeParameters (size_t newSize)
Public Member Functions inherited from g2o::HyperGraph::Edge
Edge (int id=InvalidId)
creates and empty edge with no vertices
const VertexContainer & vertices () const
VertexContainer & vertices ()
const Vertex * vertex (size_t i) const
Vertex * vertex (size_t i)
void setVertex (size_t i, Vertex *v)
int id () const
void setId (int id)
virtual HyperGraphElementType elementType () const
int numUndefinedVertices () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Member Functions inherited from g2o::HyperGraph::DataContainer
DataContainer ()
virtual ~DataContainer ()
const Data * userData () const
the user data associated with this vertex
Data * userData ()
void setUserData (Data *obs)
void addUserData (Data *obs)
Private Member Functions
virtual bool resolveCaches ()
Private Attributes
Eigen::Matrix< double, 3, 9, Eigen::ColMajor > J
ParameterCamera * params
CacheCamera * cache
Additional Inherited Members
Public Types inherited from g2o::BaseBinaryEdge< 3, Vector3D, VertexSE3, VertexPointXYZ >
typedef VertexSE3 VertexXiType
typedef VertexPointXYZ VertexXjType
typedef BaseEdge< D, Vector3D >::Measurement Measurement
typedef Eigen::Matrix< double, D, Di, D==1?Eigen::RowMajor:Eigen::ColMajor >::AlignedMapType JacobianXiOplusType
typedef Eigen::Matrix< double, D, Dj, D==1?Eigen::RowMajor:Eigen::ColMajor >::AlignedMapType JacobianXjOplusType
typedef BaseEdge< D, Vector3D >::ErrorVector ErrorVector
typedef BaseEdge< D, Vector3D >::InformationType InformationType
typedef Eigen::Map< Eigen::Matrix< double, Di, Dj, Di==1?Eigen::RowMajor:Eigen::ColMajor >, Eigen::Matrix< double, Di, Dj, Di==1?Eigen::RowMajor:Eigen::ColMajor >::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockType
typedef Eigen::Map< Eigen::Matrix< double, Dj, Di, Dj==1?Eigen::RowMajor:Eigen::ColMajor >, Eigen::Matrix< double, Dj, Di, Dj==1?Eigen::RowMajor:Eigen::ColMajor >::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockTransposedType
Public Types inherited from g2o::BaseEdge< D, Vector3D >
typedef Vector3D Measurement
typedef Eigen::Matrix< double, D, 1, Eigen::ColMajor > ErrorVector
typedef Eigen::Matrix< double, D, D, Eigen::ColMajor > InformationType
Static Public Attributes inherited from g2o::BaseBinaryEdge< 3, Vector3D, VertexSE3, VertexPointXYZ >
static const int Di
static const int Dj
static const int Dimension
Static Public Attributes inherited from g2o::BaseEdge< D, Vector3D >
static const int Dimension
Protected Member Functions inherited from g2o::BaseEdge< D, Vector3D >
InformationType robustInformation (const Vector3D &rho)
Protected Member Functions inherited from g2o::OptimizableGraph::Edge
template<typename ParameterType >
bool installParameter (ParameterType *&p, size_t argNo, int paramId=-1)
template<typename CacheType >
void resolveCache (CacheType *&cache, OptimizableGraph::Vertex *, const std::string &_type, const ParameterVector &parameters)
bool resolveParameters ()
Protected Attributes inherited from g2o::BaseBinaryEdge< 3, Vector3D, VertexSE3, VertexPointXYZ >
bool _hessianRowMajor
HessianBlockType _hessian
HessianBlockTransposedType _hessianTransposed
JacobianXiOplusType _jacobianOplusXi
JacobianXjOplusType _jacobianOplusXj
Protected Attributes inherited from g2o::BaseEdge< D, Vector3D >
Measurement _measurement
InformationType _information
ErrorVector _error
Protected Attributes inherited from g2o::OptimizableGraph::Edge
int _dimension
int _level
RobustKernel * _robustKernel
long long _internalId
std::vector< int > _cacheIds
std::vector< std::string > _parameterTypes
std::vector< Parameter ** > _parameters
std::vector< int > _parameterIds
Protected Attributes inherited from g2o::HyperGraph::Edge
VertexContainer _vertices
int _id
unique id
Protected Attributes inherited from g2o::HyperGraph::DataContainer
Data * _userData
Detailed Description
Definition at line 42 of file edge_se3_pointxyz_depth.h.
Constructor & Destructor Documentation
g2o::EdgeSE3PointXYZDepth::EdgeSE3PointXYZDepth ()
Definition at line 33 of file edge_se3_pointxyz_depth.cpp.
References g2o::BaseEdge< D, Vector3D >::information(), g2o::OptimizableGraph::Edge::installParameter(), J, params, and g2o::OptimizableGraph::Edge::resizeParameters().
                                              : BaseBinaryEdge<3, Vector3D, VertexSE3, VertexPointXYZ>() {
     resizeParameters(1);
     installParameter(params, 0);
     information().setIdentity();
     information()(2,2)=100;
     J.fill(0);
     J.block<3,3>(0,0) = -Matrix3D::Identity();
   }
Member Function Documentation
void g2o::EdgeSE3PointXYZDepth::computeError () virtual
Implements g2o::OptimizableGraph::Edge.
Definition at line 91 of file edge_se3_pointxyz_depth.cpp.
References g2o::BaseEdge< D, Vector3D >::_error, g2o::BaseEdge< D, Vector3D >::_measurement, g2o::HyperGraph::Edge::_vertices, cache, g2o::BaseVertex< D, T >::estimate(), and g2o::CacheCamera::w2i().
{
     // from cam to point (track)
     //VertexSE3 *cam = static_cast<VertexSE3*>(_vertices[0]);
     VertexPointXYZ *point = static_cast<VertexPointXYZ*>(_vertices[1]);
     Vector3D p = cache->w2i() * point->estimate();
     Vector3D perr;
     perr.head<2>() = p.head<2>()/p(2);
     perr(2) = p(2);
     // error, which is backwards from the normal observed - calculated
     // _measurement is the measured projection
     _error = perr - _measurement;
     //    std::cout << _error << std::endl << std::endl;
   }
virtual bool g2o::EdgeSE3PointXYZDepth::getMeasurementData (double * m) const inline virtual
writes the measurement to an array of double
Returns
true on success
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 65 of file edge_se3_pointxyz_depth.h.
{
       Eigen::Map<Vector3D> v(d);
       v=_measurement;
       return true;
     }
void g2o::EdgeSE3PointXYZDepth::initialEstimate (const OptimizableGraph::VertexSet & , OptimizableGraph::Vertex *) virtual
set the estimate of the to vertex, based on the estimate of the from vertices in the edge.
Reimplemented from g2o::BaseEdge< D, Vector3D >.
Definition at line 157 of file edge_se3_pointxyz_depth.cpp.
References g2o::BaseEdge< D, Vector3D >::_measurement, g2o::HyperGraph::Edge::_vertices, g2o::ParameterCamera::invKcam(), g2o::ParameterSE3Offset::offset(), params, and g2o::BaseVertex< D, T >::setEstimate().
   {
     (void) from;
     assert(from.size() == 1 && from.count(_vertices[0]) == 1 && "Can not initialize VertexDepthCam position by VertexTrackXYZ");
     VertexSE3 *cam = dynamic_cast<VertexSE3*>(_vertices[0]);
     VertexPointXYZ *point = dynamic_cast<VertexPointXYZ*>(_vertices[1]);
     const Eigen::Matrix<double, 3, 3, Eigen::ColMajor>& invKcam = params->invKcam();
     Vector3D p;
     p(2) = _measurement(2);
     p.head<2>() = _measurement.head<2>()*p(2);
     p=invKcam*p;
     point->setEstimate(cam->estimate() * (params->offset() * p));
   }
virtual double g2o::EdgeSE3PointXYZDepth::initialEstimatePossible (const OptimizableGraph::VertexSet & from, OptimizableGraph::Vertex * to) inline virtual
override in your class if it's possible to initialize the vertices in certain combinations. The return value may correspond to the cost for initiliaizng the vertex but should be positive if the initialization is possible and negative if not possible.
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 75 of file edge_se3_pointxyz_depth.h.
{
       (void) to;
       return (from.count(_vertices[0]) == 1 ? 1.0 : -1.0);
     }
void g2o::EdgeSE3PointXYZDepth::linearizeOplus () virtual
Linearizes the oplus operator in the vertex, and stores the result in temporary variables _jacobianOplusXi and _jacobianOplusXj
Reimplemented from g2o::BaseBinaryEdge< 3, Vector3D, VertexSE3, VertexPointXYZ >.
Definition at line 107 of file edge_se3_pointxyz_depth.cpp.
References g2o::BaseBinaryEdge< 3, Vector3D, VertexSE3, VertexPointXYZ >::_jacobianOplusXi, g2o::BaseBinaryEdge< 3, Vector3D, VertexSE3, VertexPointXYZ >::_jacobianOplusXj, g2o::HyperGraph::Edge::_vertices, cache, g2o::BaseVertex< D, T >::estimate(), J, g2o::ParameterCamera::Kcam_inverseOffsetR(), params, g2o::CacheCamera::w2i(), and g2o::CacheSE3Offset::w2l().
{
     //VertexSE3 *cam = static_cast<VertexSE3 *>(_vertices[0]);
     VertexPointXYZ *vp = static_cast<VertexPointXYZ *>(_vertices[1]);
     const Vector3D& pt = vp->estimate();
     Vector3D Zcam = cache->w2l() * pt;
     //  J(0,3) = -0.0;
     J(0,4) = -2*Zcam(2);
     J(0,5) = 2*Zcam(1);
     J(1,3) = 2*Zcam(2);
     //  J(1,4) = -0.0;
     J(1,5) = -2*Zcam(0);
     J(2,3) = -2*Zcam(1);
     J(2,4) = 2*Zcam(0);
     //  J(2,5) = -0.0;
     J.block<3,3>(0,6) = cache->w2l().rotation();
     Eigen::Matrix<double,3,9,Eigen::ColMajor> Jprime = params->Kcam_inverseOffsetR()  * J;
     Vector3D Zprime = cache->w2i() * pt;
     Eigen::Matrix<double,3,9,Eigen::ColMajor> Jhom;
     Jhom.block<2,9>(0,0) = 1/(Zprime(2)*Zprime(2)) * (Jprime.block<2,9>(0,0)*Zprime(2) - Zprime.head<2>() * Jprime.block<1,9>(2,0));
     Jhom.block<1,9>(2,0) = Jprime.block<1,9>(2,0);
     _jacobianOplusXi = Jhom.block<3,6>(0,0);
     _jacobianOplusXj = Jhom.block<3,3>(0,6);
   }
virtual int g2o::EdgeSE3PointXYZDepth::measurementDimension () const inline virtual
returns the dimension of the measurement in the extended representation which is used by get/setMeasurement;
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 71 of file edge_se3_pointxyz_depth.h.
 {return 3;}
bool g2o::EdgeSE3PointXYZDepth::read (std::istream & is) virtual
read the vertex from a stream, i.e., the internal state of the vertex
Implements g2o::OptimizableGraph::Edge.
Definition at line 52 of file edge_se3_pointxyz_depth.cpp.
References g2o::BaseEdge< D, Vector3D >::_measurement, g2o::BaseEdge< D, Vector3D >::information(), setMeasurement(), and g2o::OptimizableGraph::Edge::setParameterId().
{
     int pid;
     is >> pid;
     setParameterId(0,pid);
     // measured keypoint
     Vector3D meas;
     for (int i=0; i<3; i++) is >> meas[i];
     setMeasurement(meas);
     // don't need this if we don't use it in error calculation (???)
     // information matrix is the identity for features, could be changed to allow arbitrary covariances
     if (is.bad()) {
       return false;
     }
     for ( int i=0; i<information().rows() && is.good(); i++)
       for (int j=i; j<information().cols() && is.good(); j++){
   is >> information()(i,j);
   if (i!=j)
     information()(j,i)=information()(i,j);
       }
     if (is.bad()) {
       //  we overwrite the information matrix
       information().setIdentity();
       information()(2,2)=10/_measurement(2); // scale the info by the inverse of the measured depth
     }
     return true;
   }
bool g2o::EdgeSE3PointXYZDepth::resolveCaches () private virtual
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 42 of file edge_se3_pointxyz_depth.cpp.
References g2o::HyperGraph::Edge::_vertices, cache, params, and g2o::OptimizableGraph::Edge::resolveCache().
{
     ParameterVector pv(1);
     pv[0]=params;
     resolveCache(cache, (OptimizableGraph::Vertex*)_vertices[0],"CACHE_CAMERA",pv);
     return cache != 0;
   }
virtual void g2o::EdgeSE3PointXYZDepth::setMeasurement (const Vector3D & m) inline virtual
Reimplemented from g2o::BaseEdge< D, Vector3D >.
Definition at line 55 of file edge_se3_pointxyz_depth.h.
Referenced by g2o::SensorPointXYZDepth::addNoise(), and read().
{
       _measurement = m;
     }
virtual bool g2o::EdgeSE3PointXYZDepth::setMeasurementData (const double * m) inline virtual
sets the measurement from an array of double
Returns
true on success
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 59 of file edge_se3_pointxyz_depth.h.
{
       Eigen::Map<const Vector3D> v(d);
       _measurement = v;
       return true;
     }
bool g2o::EdgeSE3PointXYZDepth::setMeasurementFromState () virtual
sets the estimate to have a zero error, based on the current value of the state variables returns false if not supported.
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 141 of file edge_se3_pointxyz_depth.cpp.
References g2o::BaseEdge< D, Vector3D >::_measurement, g2o::HyperGraph::Edge::_vertices, cache, g2o::BaseVertex< D, T >::estimate(), and g2o::CacheCamera::w2i().
Referenced by g2o::SensorPointXYZDepth::sense().
{
     //VertexSE3 *cam = static_cast<VertexSE3*>(_vertices[0]);
     VertexPointXYZ *point = static_cast<VertexPointXYZ*>(_vertices[1]);
     // calculate the projection
     const Vector3D& pt = point->estimate();
     Vector3D p = cache->w2i() * pt;
     Vector3D perr;
     perr.head<2>() = p.head<2>()/p(2);
     perr(2) = p(2);
     _measurement = perr;
     return true;
   }
bool g2o::EdgeSE3PointXYZDepth::write (std::ostream & os) const virtual
write the vertex to a stream
Implements g2o::OptimizableGraph::Edge.
Definition at line 80 of file edge_se3_pointxyz_depth.cpp.
References g2o::Parameter::id(), g2o::BaseEdge< D, Vector3D >::information(), g2o::BaseEdge< D, Vector3D >::measurement(), and params.
{
     os << params->id() << " ";
     for (int i=0; i<3; i++) os  << measurement()[i] << " ";
     for (int i=0; i<information().rows(); i++)
       for (int j=i; j<information().cols(); j++) {
         os <<  information()(i,j) << " ";
       }
     return os.good();
   }
Member Data Documentation
CacheCamera* g2o::EdgeSE3PointXYZDepth::cache private
Definition at line 88 of file edge_se3_pointxyz_depth.h.
Referenced by computeError(), linearizeOplus(), resolveCaches(), and setMeasurementFromState().
Eigen::Matrix<double,3,9,Eigen::ColMajor> g2o::EdgeSE3PointXYZDepth::J private
Definition at line 84 of file edge_se3_pointxyz_depth.h.
Referenced by EdgeSE3PointXYZDepth(), and linearizeOplus().
ParameterCamera* g2o::EdgeSE3PointXYZDepth::params private
Definition at line 87 of file edge_se3_pointxyz_depth.h.
Referenced by EdgeSE3PointXYZDepth(), initialEstimate(), linearizeOplus(), resolveCaches(), and write().
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam3d/edge_se3_pointxyz_depth.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam3d/edge_se3_pointxyz_depth.cpp