g2o: g2o::EdgeProjectP2MC_Intrinsics Class Reference
g2o::EdgeProjectP2MC_Intrinsics Class Reference
#include <types_sba.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW EdgeProjectP2MC_Intrinsics ()
virtual bool read (std::istream &is)
read the vertex from a stream, i.e., the internal state of the vertex
virtual bool write (std::ostream &os) const
write the vertex to a stream
void computeError ()
virtual void linearizeOplus ()
Jacobian for monocular projection with intrinsics calibration.
Public Member Functions inherited from g2o::BaseMultiEdge< 2, Vector2D >
BaseMultiEdge ()
virtual void linearizeOplus (JacobianWorkspace &jacobianWorkspace)
virtual void resize (size_t size)
virtual bool allVerticesFixed () const
virtual void constructQuadraticForm ()
virtual void mapHessianMemory (double *d, int i, int j, bool rowMajor)
Public Member Functions inherited from g2o::BaseEdge< D, Vector2D >
BaseEdge ()
virtual ~BaseEdge ()
virtual double chi2 () const
computes the chi2 based on the cached error value, only valid after computeError has been called.
virtual const double * errorData () const
returns the error vector cached after calling the computeError;
virtual double * errorData ()
const ErrorVector & error () const
ErrorVector & error ()
EIGEN_STRONG_INLINE const InformationType & information () const
information matrix of the constraint
EIGEN_STRONG_INLINE InformationType & information ()
EIGEN_STRONG_INLINE void setInformation (const InformationType &information)
virtual const double * informationData () const
returns the memory of the information matrix, usable for example with a Eigen::Map<MatrixXD>
virtual double * informationData ()
EIGEN_STRONG_INLINE const Measurement & measurement () const
accessor functions for the measurement represented by the edge
virtual void setMeasurement (const Measurement &m)
virtual int rank () const
virtual void initialEstimate (const OptimizableGraph::VertexSet &, OptimizableGraph::Vertex *)
Public Member Functions inherited from g2o::OptimizableGraph::Edge
Edge ()
virtual ~Edge ()
virtual Edge * clone () const
virtual bool setMeasurementData (const double *m)
virtual bool getMeasurementData (double *m) const
virtual int measurementDimension () const
virtual bool setMeasurementFromState ()
RobustKernel * robustKernel () const
if NOT NULL, error of this edge will be robustifed with the kernel
void setRobustKernel (RobustKernel *ptr)
virtual double initialEstimatePossible (const OptimizableGraph::VertexSet &from, OptimizableGraph::Vertex *to)
int level () const
returns the level of the edge
void setLevel (int l)
sets the level of the edge
int dimension () const
returns the dimensions of the error function
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createFrom())
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createTo())
virtual Vertex * createVertex (int)
long long internalId () const
the internal ID of the edge
OptimizableGraph * graph ()
const OptimizableGraph * graph () const
bool setParameterId (int argNum, int paramId)
const Parameter * parameter (int argNo) const
size_t numParameters () const
void resizeParameters (size_t newSize)
Public Member Functions inherited from g2o::HyperGraph::Edge
Edge (int id=InvalidId)
creates and empty edge with no vertices
const VertexContainer & vertices () const
VertexContainer & vertices ()
const Vertex * vertex (size_t i) const
Vertex * vertex (size_t i)
void setVertex (size_t i, Vertex *v)
int id () const
void setId (int id)
virtual HyperGraphElementType elementType () const
int numUndefinedVertices () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Member Functions inherited from g2o::HyperGraph::DataContainer
DataContainer ()
virtual ~DataContainer ()
const Data * userData () const
the user data associated with this vertex
Data * userData ()
void setUserData (Data *obs)
void addUserData (Data *obs)
Additional Inherited Members
Public Types inherited from g2o::BaseMultiEdge< 2, Vector2D >
typedef BaseEdge< D, Vector2D >::Measurement Measurement
typedef MatrixXD::MapType JacobianType
typedef BaseEdge< D, Vector2D >::ErrorVector ErrorVector
typedef BaseEdge< D, Vector2D >::InformationType InformationType
typedef Eigen::Map< MatrixXD, MatrixXD::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockType
Public Types inherited from g2o::BaseEdge< D, Vector2D >
typedef Vector2D Measurement
typedef Eigen::Matrix< double, D, 1, Eigen::ColMajor > ErrorVector
typedef Eigen::Matrix< double, D, D, Eigen::ColMajor > InformationType
Static Public Attributes inherited from g2o::BaseMultiEdge< 2, Vector2D >
static const int Dimension
Static Public Attributes inherited from g2o::BaseEdge< D, Vector2D >
static const int Dimension
Protected Member Functions inherited from g2o::BaseMultiEdge< 2, Vector2D >
void computeQuadraticForm (const InformationType &omega, const ErrorVector &weightedError)
Protected Member Functions inherited from g2o::BaseEdge< D, Vector2D >
InformationType robustInformation (const Vector3D &rho)
Protected Member Functions inherited from g2o::OptimizableGraph::Edge
template<typename ParameterType >
bool installParameter (ParameterType *&p, size_t argNo, int paramId=-1)
template<typename CacheType >
void resolveCache (CacheType *&cache, OptimizableGraph::Vertex *, const std::string &_type, const ParameterVector &parameters)
bool resolveParameters ()
virtual bool resolveCaches ()
Protected Attributes inherited from g2o::BaseMultiEdge< 2, Vector2D >
std::vector< HessianHelper > _hessian
std::vector< JacobianType, Eigen::aligned_allocator< JacobianType > > _jacobianOplus
jacobians of the edge (w.r.t. oplus)
Protected Attributes inherited from g2o::BaseEdge< D, Vector2D >
Measurement _measurement
InformationType _information
ErrorVector _error
Protected Attributes inherited from g2o::OptimizableGraph::Edge
int _dimension
int _level
RobustKernel * _robustKernel
long long _internalId
std::vector< int > _cacheIds
std::vector< std::string > _parameterTypes
std::vector< Parameter ** > _parameters
std::vector< int > _parameterIds
Protected Attributes inherited from g2o::HyperGraph::Edge
VertexContainer _vertices
int _id
unique id
Protected Attributes inherited from g2o::HyperGraph::DataContainer
Data * _userData
Detailed Description
Definition at line 254 of file types_sba.h.
Constructor & Destructor Documentation
g2o::EdgeProjectP2MC_Intrinsics::EdgeProjectP2MC_Intrinsics ()
Definition at line 409 of file types_sba.cpp.
References g2o::BaseEdge< D, Vector2D >::information(), and g2o::BaseMultiEdge< 2, Vector2D >::resize().
                                                          :
     BaseMultiEdge<2, Vector2D>()
   {
     information().setIdentity();
     resize(3);
   }
Member Function Documentation
void g2o::EdgeProjectP2MC_Intrinsics::computeError () inline virtual
Implements g2o::OptimizableGraph::Edge.
Definition at line 263 of file types_sba.h.
References g2o::BaseVertex< D, T >::estimate(), and g2o::SBACam::w2i.
     {
       // from <Point> to <Cam>, the intrinsics in KCam should be already set!
       const VertexSBAPointXYZ *point = static_cast<const VertexSBAPointXYZ*>(_vertices[0]);
       VertexCam *cam = static_cast<VertexCam*>(_vertices[1]);
       // calculate the projection
       const Vector3D &pt = point->estimate();
       Vector4D ppt(pt(0),pt(1),pt(2),1.0);
       Vector3D p = cam->estimate().w2i * ppt;
       Vector2D perr = p.head<2>()/p(2);
       _error = perr - _measurement;
     }
void g2o::EdgeProjectP2MC_Intrinsics::linearizeOplus () virtual
Jacobian for monocular projection with intrinsics calibration.
Reimplemented from g2o::BaseMultiEdge< 2, Vector2D >.
Definition at line 419 of file types_sba.cpp.
References g2o::BaseMultiEdge< 2, Vector2D >::_jacobianOplus, g2o::HyperGraph::Edge::_vertices, g2o::SBACam::dRdx, g2o::SBACam::dRdy, g2o::SBACam::dRdz, g2o::BaseVertex< D, T >::estimate(), g2o_isnan, g2o::SBACam::Kcam, g2o::SE3Quat::translation(), and g2o::SBACam::w2n.
   {
     _jacobianOplus[0].resize(2,3);
     _jacobianOplus[1].resize(2,6);
     _jacobianOplus[2].resize(2,4);
     VertexCam *vc = static_cast<VertexCam *>(_vertices[1]);
     const SBACam &cam = vc->estimate();
     VertexSBAPointXYZ *vp = static_cast<VertexSBAPointXYZ *>(_vertices[0]);
     //VertexIntrinsics *intr = static_cast<VertexIntrinsics *>(_vertices[2]);
     Vector4D pt, trans;
     pt.head<3>() = vp->estimate();
     pt(3) = 1.0;
     trans.head<3>() = cam.translation();
     trans(3) = 1.0;
     // first get the world point in camera coords
     Eigen::Matrix<double,3,1,Eigen::ColMajor> pc = cam.w2n * pt;
     // Jacobians wrt camera parameters
     // set d(quat-x) values [ pz*dpx/dx - px*dpz/dx ] / pz^2
     double px = pc(0);
     double py = pc(1);
     double pz = pc(2);
     double ipz2 = 1.0/(pz*pz);
     if (g2o_isnan(ipz2) ) {
       std::cout << "[SetJac] infinite jac" << std::endl;
       abort();
     }
     double ipz2fx = ipz2*cam.Kcam(0,0); // Fx
     double ipz2fy = ipz2*cam.Kcam(1,1); // Fy
     Eigen::Matrix<double,3,1,Eigen::ColMajor> pwt;
     // check for local vars
     pwt = (pt-trans).head<3>(); // transform translations, use differential rotation
     // dx
     Eigen::Matrix<double,3,1,Eigen::ColMajor> dp = cam.dRdx * pwt; // dR'/dq * [pw - t]
     _jacobianOplus[1](0,3) = (pz*dp(0) - px*dp(2))*ipz2fx;
     _jacobianOplus[1](1,3) = (pz*dp(1) - py*dp(2))*ipz2fy;
     // dy
     dp = cam.dRdy * pwt; // dR'/dq * [pw - t]
     _jacobianOplus[1](0,4) = (pz*dp(0) - px*dp(2))*ipz2fx;
     _jacobianOplus[1](1,4) = (pz*dp(1) - py*dp(2))*ipz2fy;
     // dz
     dp = cam.dRdz * pwt; // dR'/dq * [pw - t]
     _jacobianOplus[1](0,5) = (pz*dp(0) - px*dp(2))*ipz2fx;
     _jacobianOplus[1](1,5) = (pz*dp(1) - py*dp(2))*ipz2fy;
     // set d(t) values [ pz*dpx/dx - px*dpz/dx ] / pz^2
     dp = -cam.w2n.col(0);        // dpc / dx
     _jacobianOplus[1](0,0) = (pz*dp(0) - px*dp(2))*ipz2fx;
     _jacobianOplus[1](1,0) = (pz*dp(1) - py*dp(2))*ipz2fy;
     dp = -cam.w2n.col(1);        // dpc / dy
     _jacobianOplus[1](0,1) = (pz*dp(0) - px*dp(2))*ipz2fx;
     _jacobianOplus[1](1,1) = (pz*dp(1) - py*dp(2))*ipz2fy;
     dp = -cam.w2n.col(2);        // dpc / dz
     _jacobianOplus[1](0,2) = (pz*dp(0) - px*dp(2))*ipz2fx;
     _jacobianOplus[1](1,2) = (pz*dp(1) - py*dp(2))*ipz2fy;
     // Jacobians wrt point parameters
     // set d(t) values [ pz*dpx/dx - px*dpz/dx ] / pz^2
     dp = cam.w2n.col(0); // dpc / dx
     _jacobianOplus[0](0,0) = (pz*dp(0) - px*dp(2))*ipz2fx;
     _jacobianOplus[0](1,0) = (pz*dp(1) - py*dp(2))*ipz2fy;
     dp = cam.w2n.col(1); // dpc / dy
     _jacobianOplus[0](0,1) = (pz*dp(0) - px*dp(2))*ipz2fx;
     _jacobianOplus[0](1,1) = (pz*dp(1) - py*dp(2))*ipz2fy;
     dp = cam.w2n.col(2); // dpc / dz
     _jacobianOplus[0](0,2) = (pz*dp(0) - px*dp(2))*ipz2fx;
     _jacobianOplus[0](1,2) = (pz*dp(1) - py*dp(2))*ipz2fy;
     // Jacobians w.r.t the intrinsics
     _jacobianOplus[2].setZero();
     _jacobianOplus[2](0,0) = px/pz; // dx/dfx
     _jacobianOplus[2](1,1) = py/pz; // dy/dfy
     _jacobianOplus[2](0,2) = 1.;    // dx/dcx
     _jacobianOplus[2](1,3) = 1.;    // dy/dcy
   }
bool g2o::EdgeProjectP2MC_Intrinsics::read (std::istream & is) virtual
read the vertex from a stream, i.e., the internal state of the vertex
Implements g2o::OptimizableGraph::Edge.
Definition at line 503 of file types_sba.cpp.
References g2o::BaseEdge< D, Vector2D >::information(), and g2o::BaseEdge< D, Vector2D >::setMeasurement().
   {
     // measured keypoint
     Vector2D meas;
     for (int i=0; i<2; i++)
       is >> meas[i];
     setMeasurement(meas);
     // information matrix is the identity for features, could be changed to allow arbitrary covariances
     information().setIdentity();
     return true;
   }
bool g2o::EdgeProjectP2MC_Intrinsics::write (std::ostream & os) const virtual
write the vertex to a stream
Implements g2o::OptimizableGraph::Edge.
Definition at line 515 of file types_sba.cpp.
References g2o::BaseEdge< D, Vector2D >::measurement().
   {
     for (int i=0; i<2; i++)
       os  << measurement()[i] << " ";
     return os.good();
   }
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/sba/types_sba.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/sba/types_sba.cpp