g2o: g2o::BaseRobot Class Reference
g2o::BaseRobot Class Reference
#include <simulator.h>
Public Member Functions
BaseRobot (World *world_, const std::string &name_)
void setWorld (World *world_)
World * world ()
const std::string & name () const
OptimizableGraph * graph ()
bool addSensor (BaseSensor *sensor)
const std::set< BaseSensor * > sensors ()
virtual void sense ()
Protected Attributes
World * _world
std::set< BaseSensor * > _sensors
std::string _name
Detailed Description
Definition at line 78 of file simulator.h.
Constructor & Destructor Documentation
g2o::BaseRobot::BaseRobot (World * world_, const std::string & name_) inline
Definition at line 80 of file simulator.h.
 {_world = world_; _name = name_; }
Member Function Documentation
bool g2o::BaseRobot::addSensor (BaseSensor * sensor)
Definition at line 51 of file simulator.cpp.
References g2o::BaseSensor::addParameters(), graph, and g2o::BaseSensor::setRobot().
Referenced by main().
{
     assert (graph());
     std::pair<std::set<BaseSensor*>::iterator, bool> result=_sensors.insert(sensor);
     if(result.second){
       sensor->setRobot(this);
       sensor->addParameters();
     }
     return result.second;
   }
OptimizableGraph * g2o::BaseRobot::graph ()
Definition at line 45 of file simulator.cpp.
References graph.
{
     if (_world)
       return _world-> graph();
     return 0;
   }
const std::string& g2o::BaseRobot::name () const inline
Definition at line 83 of file simulator.h.
References graph.
 {return _name;}
void g2o::BaseRobot::sense () virtual
Definition at line 61 of file simulator.cpp.
References g2o::BaseSensor::sense().
Referenced by main(), and Simulator::sense().
{
     for (std::set<BaseSensor*>::iterator it=_sensors.begin(); it!=_sensors.end(); it++){
       BaseSensor* s=*it;
       s->sense();
     }
   }
const std::set<BaseSensor*> g2o::BaseRobot::sensors () inline
Definition at line 86 of file simulator.h.
 {return _sensors;}
void g2o::BaseRobot::setWorld (World * world_) inline
Definition at line 81 of file simulator.h.
Referenced by g2o::World::addRobot().
 {_world = world_;}
World* g2o::BaseRobot::world () inline
Definition at line 82 of file simulator.h.
 {return _world;}
Member Data Documentation
std::string g2o::BaseRobot::_name protected
Definition at line 91 of file simulator.h.
std::set<BaseSensor*> g2o::BaseRobot::_sensors protected
Definition at line 90 of file simulator.h.
Referenced by main().
World* g2o::BaseRobot::_world protected
Definition at line 89 of file simulator.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_simulator/simulator.h
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_simulator/simulator.cpp