g2o: SlamParser::AddNode Class Reference
SlamParser::AddNode Class Reference
#include <commands.h>
Public Member Functions
AddNode (const std::string &tag, int id, int dimension, const std::vector< double > &values=std::vector< double >())
int id () const
int dimension () const
const std::vector< double > & values ()
Public Member Functions inherited from SlamParser::CommandNode
CommandNode (CommandType commandType, const std::string &tag)
virtual ~CommandNode ()
CommandType commandType () const
const std::string & tag () const
Protected Attributes
int _id
int _dimension
std::vector< double > _values
Protected Attributes inherited from SlamParser::CommandNode
CommandType _commandType
std::string _tag
Detailed Description
Definition at line 56 of file commands.h.
Constructor & Destructor Documentation
SlamParser::AddNode::AddNode (const std::string & tag, int id, int dimension, const std::vector< double > & values = std::vector<double>()) inline
Definition at line 59 of file commands.h.
                                                                                                                   :
         CommandNode(CT_ADD_NODE, tag),
         _id(id), _dimension(dimension), _values(values)
     {
     }
Member Function Documentation
int SlamParser::AddNode::dimension () const inline
Definition at line 66 of file commands.h.
Referenced by SlamParser::SlamContextInterface::process().
 {return _dimension;}
int SlamParser::AddNode::id () const inline
Definition at line 65 of file commands.h.
Referenced by SlamParser::SlamContextInterface::process().
 {return _id;}
const std::vector<double>& SlamParser::AddNode::values () inline
Definition at line 67 of file commands.h.
Referenced by SlamParser::SlamContextInterface::process().
 { return _values;}
Member Data Documentation
int SlamParser::AddNode::_dimension protected
Definition at line 71 of file commands.h.
int SlamParser::AddNode::_id protected
Definition at line 70 of file commands.h.
std::vector<double> SlamParser::AddNode::_values protected
Definition at line 72 of file commands.h.
The documentation for this class was generated from the following file:
/home/xuezhisd/CLionProjects/g2o/g2o/examples/interactive_slam/slam_parser/parser/commands.h