g2o: g2o::deprecated::ParameterCamera Class Reference
g2o::deprecated::ParameterCamera Class Reference
parameters for a camera
#include <parameter_camera.h>
Public Member Functions
ParameterCamera ()
void setKcam (double fx, double fy, double cx, double cy)
void setOffset (const SE3Quat &offset_=SE3Quat())
virtual bool read (std::istream &is)
read the data from a stream
virtual bool write (std::ostream &os) const
write the data to a stream
const Eigen::Matrix3d & Kcam () const
const Eigen::Matrix3d & invKcam () const
const Eigen::Matrix3d & Kcam_inverseOffsetR () const
Public Member Functions inherited from g2o::deprecated::ParameterSE3Offset
ParameterSE3Offset ()
void setOffset (const SE3Quat &offset_=SE3Quat())
const SE3Quat & offset () const
return the offset as SE3Quat
const Eigen::Isometry3d & offsetMatrix () const
rotation of the offset as 3x3 rotation matrix
const Eigen::Isometry3d & inverseOffsetMatrix () const
rotation of the inverse offset as 3x3 rotation matrix
Public Member Functions inherited from g2o::Parameter
Parameter ()
virtual ~Parameter ()
int id () const
void setId (int id_)
virtual HyperGraph::HyperGraphElementType elementType () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Public Attributes inherited from g2o::deprecated::ParameterSE3Offset
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Attributes
Eigen::Matrix3d _Kcam
Eigen::Matrix3d _invKcam
Eigen::Matrix3d _Kcam_inverseOffsetR
Protected Attributes inherited from g2o::deprecated::ParameterSE3Offset
SE3Quat _offset
Eigen::Isometry3d _offsetMatrix
Eigen::Isometry3d _inverseOffsetMatrix
Protected Attributes inherited from g2o::Parameter
int _id
Detailed Description
parameters for a camera
Definition at line 41 of file parameter_camera.h.
Constructor & Destructor Documentation
g2o::deprecated::ParameterCamera::ParameterCamera ()
Definition at line 36 of file parameter_camera.cpp.
{
     setId(-1);
     setKcam(1,1,0.5,0.5);
     setOffset();
   }
Member Function Documentation
const Eigen::Matrix3d& g2o::deprecated::ParameterCamera::invKcam () const inline
Definition at line 52 of file parameter_camera.h.
Referenced by g2o::deprecated::EdgeSE3PointXYZDepth::initialEstimate(), and g2o::deprecated::EdgeSE3PointXYZDisparity::initialEstimate().
 { return _invKcam;}
const Eigen::Matrix3d& g2o::deprecated::ParameterCamera::Kcam () const inline
Definition at line 51 of file parameter_camera.h.
 { return _Kcam;}
const Eigen::Matrix3d& g2o::deprecated::ParameterCamera::Kcam_inverseOffsetR () const inline
Definition at line 53 of file parameter_camera.h.
Referenced by g2o::deprecated::EdgeSE3PointXYZDepth::linearizeOplus(), and g2o::deprecated::EdgeSE3PointXYZDisparity::linearizeOplus().
 { return _Kcam_inverseOffsetR;}
bool g2o::deprecated::ParameterCamera::read (std::istream & is) virtual
read the data from a stream
Reimplemented from g2o::deprecated::ParameterSE3Offset.
Definition at line 59 of file parameter_camera.cpp.
{
     Vector7d off;
     for (int i=0; i<7; i++)
       is >> off[i];
     setOffset(SE3Quat(off));
     double fx,fy,cx,cy;
     is >> fx >> fy >> cx >> cy;
     setKcam(fx,fy,cx,cy);
     return is.good();
   }
void g2o::deprecated::ParameterCamera::setKcam (double fx, double fy, double cx, double cy)
Definition at line 47 of file parameter_camera.cpp.
{
     _Kcam.setZero();
     _Kcam(0,0) = fx;
     _Kcam(1,1) = fy;
     _Kcam(0,2) = cx;
     _Kcam(1,2) = cy;
     _Kcam(2,2) = 1.0;
     _invKcam = _Kcam.inverse();
     _Kcam_inverseOffsetR = _Kcam * inverseOffsetMatrix().rotation();
   }
void g2o::deprecated::ParameterCamera::setOffset (const SE3Quat & offset_ = SE3Quat())
Definition at line 42 of file parameter_camera.cpp.
{
     ParameterSE3Offset::setOffset(offset_);
     _Kcam_inverseOffsetR = _Kcam * inverseOffsetMatrix().rotation();
   }
bool g2o::deprecated::ParameterCamera::write (std::ostream & os) const virtual
write the data to a stream
Reimplemented from g2o::deprecated::ParameterSE3Offset.
Definition at line 70 of file parameter_camera.cpp.
{
     Vector7d off = offset().toVector();
     for (int i=0; i<7; i++)
       os << off[i] << " ";
     os << _Kcam(0,0) << " ";
     os << _Kcam(1,1) << " ";
     os << _Kcam(0,2) << " ";
     os << _Kcam(1,2) << " ";
     return os.good();
   }
Member Data Documentation
Eigen::Matrix3d g2o::deprecated::ParameterCamera::_invKcam protected
Definition at line 57 of file parameter_camera.h.
Eigen::Matrix3d g2o::deprecated::ParameterCamera::_Kcam protected
Definition at line 56 of file parameter_camera.h.
Eigen::Matrix3d g2o::deprecated::ParameterCamera::_Kcam_inverseOffsetR protected
Definition at line 58 of file parameter_camera.h.
g2o::deprecated::ParameterCamera::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 43 of file parameter_camera.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/deprecated/slam3d/parameter_camera.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/deprecated/slam3d/parameter_camera.cpp