g2o: g2o::RawLaser Class Reference
g2o::RawLaser Class Reference
Raw laser measuerement.
#include <raw_laser.h>
Public Types
typedef std::vector< Vector2D, Eigen::aligned_allocator< Vector2D > > Point2DVector
Public Member Functions
RawLaser ()
~RawLaser ()
virtual bool write (std::ostream &os) const
write the data to a stream
virtual bool read (std::istream &is)
read the data from a stream
Point2DVector cartesian () const
const std::vector< double > & ranges () const
the range measurements by the laser
void setRanges (const std::vector< double > &ranges)
const std::vector< double > & remissions () const
the remission measurements by the laser
void setRemissions (const std::vector< double > &remissions)
const LaserParameters & laserParams () const
the parameters of the laser
void setLaserParams (const LaserParameters &laserParams)
Public Member Functions inherited from g2o::RobotData
RobotData ()
virtual ~RobotData ()
double timestamp () const
void setTimestamp (double ts)
double loggerTimestamp () const
void setLoggerTimestamp (double ts)
const std::string & tag () const
void setTag (const std::string &tag)
const std::string & hostname () const
void setHostname (const std::string &hostname)
Public Member Functions inherited from g2o::HyperGraph::Data
Data ()
~Data ()
virtual HyperGraph::HyperGraphElementType elementType () const
const Data * next () const
Data * next ()
void setNext (Data *next_)
DataContainer * dataContainer ()
const DataContainer * dataContainer () const
void setDataContainer (DataContainer *dataContainer_)
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Protected Attributes
std::vector< double > _ranges
std::vector< double > _remissions
LaserParameters _laserParams
Protected Attributes inherited from g2o::RobotData
double _timestamp
timestamp when the measurement was generated
double _loggerTimestamp
timestamp when the measurement was recorded
std::string _tag
string tag (FLASER, ROBOTLASER, ODOM..) of the line in the log
std::string _hostname
name of the computer/robot generating the data
Protected Attributes inherited from g2o::HyperGraph::Data
Data * _next
DataContainer * _dataContainer
Detailed Description
Raw laser measuerement.
A raw laser measuerement. The read/write function correspond to the format of CARMEN.
Definition at line 46 of file raw_laser.h.
Member Typedef Documentation
typedef std::vector<Vector2D, Eigen::aligned_allocator<Vector2D> > g2o::RawLaser::Point2DVector
Definition at line 48 of file raw_laser.h.
Constructor & Destructor Documentation
g2o::RawLaser::RawLaser ()
Definition at line 35 of file raw_laser.cpp.
                      :
     RobotData(),
     _laserParams(0, 180, -M_PI/2, M_PI/180., 50.,0.1, 0)
   {
   }
g2o::RawLaser::~RawLaser ()
Definition at line 41 of file raw_laser.cpp.
   {
   }
Member Function Documentation
RawLaser::Point2DVector g2o::RawLaser::cartesian () const
computes a cartesian view of the beams (x,y).
Returns
a vector with the points of the scan in cartesian coordinates.
Definition at line 93 of file raw_laser.cpp.
References _laserParams, _ranges, g2o::LaserParameters::angularStep, g2o::LaserParameters::firstBeamAngle, and g2o::LaserParameters::maxRange.
Referenced by g2o::RobotLaser::setOdomPose().
   {
     Point2DVector points;
     for (size_t i = 0; i < _ranges.size(); ++i) {
       const double& r = _ranges[i];
       if (r < _laserParams.maxRange) {
         double alpha = _laserParams.firstBeamAngle + i * _laserParams.angularStep;
         points.push_back(Vector2D(cos(alpha) * r, sin(alpha) * r));
       }
     }
     return points;
   }
const LaserParameters& g2o::RawLaser::laserParams () const inline
the parameters of the laser
Definition at line 72 of file raw_laser.h.
Referenced by g2o::Gm2dlIO::readGm2dl(), setLaserParams(), g2o::RobotLaser::setOdomPose(), and g2o::Gm2dlIO::updateLaserData().
 { return _laserParams;}
const std::vector<double>& g2o::RawLaser::ranges () const inline
the range measurements by the laser
Definition at line 64 of file raw_laser.h.
Referenced by setRanges(), and g2o::RobotLaser::write().
 { return _ranges;}
bool g2o::RawLaser::read (std::istream & is) virtual
read the data from a stream
Implements g2o::HyperGraph::Data.
Reimplemented in g2o::RobotLaser.
Definition at line 52 of file raw_laser.cpp.
References g2o::RobotData::_hostname, _laserParams, g2o::RobotData::_loggerTimestamp, _ranges, _remissions, and g2o::RobotData::_timestamp.
   {
     int type;
     double angle, fov, res, maxrange, acc;
     int remission_mode;
     is >> type >> angle >> fov >> res >> maxrange >> acc >> remission_mode;
     int beams;
     is >> beams;
     _laserParams = LaserParameters(type, beams, angle, res, maxrange, acc, remission_mode);
     _ranges.resize(beams);
     for (int i=0; i<beams; i++)
       is >> _ranges[i];
     is >> beams;
     _remissions.resize(beams);
     for (int i=0; i < beams; i++)
       is >> _remissions[i];
     // timestamp + host
     is >> _timestamp;
     is >> _hostname;
     is >> _loggerTimestamp;
     return true;
   }
const std::vector<double>& g2o::RawLaser::remissions () const inline
the remission measurements by the laser
Definition at line 68 of file raw_laser.h.
Referenced by setRemissions().
 { return _remissions;}
void g2o::RawLaser::setLaserParams (const LaserParameters & laserParams)
Definition at line 88 of file raw_laser.cpp.
References _laserParams, and laserParams().
Referenced by g2o::Gm2dlIO::updateLaserData().
   {
     _laserParams = laserParams;
   }
void g2o::RawLaser::setRanges (const std::vector< double > & ranges)
Definition at line 78 of file raw_laser.cpp.
References _ranges, and ranges().
   {
     _ranges = ranges;
   }
void g2o::RawLaser::setRemissions (const std::vector< double > & remissions)
Definition at line 83 of file raw_laser.cpp.
References _remissions, and remissions().
   {
     _remissions = remissions;
   }
bool g2o::RawLaser::write (std::ostream & os) const virtual
write the data to a stream
Implements g2o::HyperGraph::Data.
Reimplemented in g2o::RobotLaser.
Definition at line 45 of file raw_laser.cpp.
   {
     // TODO
     cerr << "RawLaser::write() not implemented yet." << endl;
     return false;
   }
Member Data Documentation
LaserParameters g2o::RawLaser::_laserParams protected
Definition at line 78 of file raw_laser.h.
Referenced by cartesian(), g2o::RobotLaser::read(), read(), setLaserParams(), and g2o::RobotLaser::write().
std::vector<double> g2o::RawLaser::_ranges protected
Definition at line 76 of file raw_laser.h.
Referenced by cartesian(), g2o::RobotLaser::read(), read(), and setRanges().
std::vector<double> g2o::RawLaser::_remissions protected
Definition at line 77 of file raw_laser.h.
Referenced by g2o::RobotLaser::read(), read(), setRemissions(), and g2o::RobotLaser::write().
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/data/raw_laser.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/data/raw_laser.cpp