g2o: g2o::EdgeProjectXYZ2UV Class Reference
g2o::EdgeProjectXYZ2UV Class Reference
#include <types_six_dof_expmap.h>
Public Member Functions
EdgeProjectXYZ2UV ()
bool read (std::istream &is)
read the vertex from a stream, i.e., the internal state of the vertex
bool write (std::ostream &os) const
write the vertex to a stream
void computeError ()
virtual void linearizeOplus ()
Public Member Functions inherited from g2o::BaseBinaryEdge< 2, Vector2D, VertexSBAPointXYZ, VertexSE3Expmap >
BaseBinaryEdge ()
virtual OptimizableGraph::Vertex * createFrom ()
virtual OptimizableGraph::Vertex * createTo ()
virtual OptimizableGraph::Vertex * createVertex (int i)
virtual void resize (size_t size)
virtual bool allVerticesFixed () const
virtual void linearizeOplus (JacobianWorkspace &jacobianWorkspace)
const JacobianXiOplusType & jacobianOplusXi () const
returns the result of the linearization in the manifold space for the node xi
const JacobianXjOplusType & jacobianOplusXj () const
returns the result of the linearization in the manifold space for the node xj
virtual void constructQuadraticForm ()
virtual void mapHessianMemory (double *d, int i, int j, bool rowMajor)
Public Member Functions inherited from g2o::BaseEdge< D, Vector2D >
BaseEdge ()
virtual ~BaseEdge ()
virtual double chi2 () const
computes the chi2 based on the cached error value, only valid after computeError has been called.
virtual const double * errorData () const
returns the error vector cached after calling the computeError;
virtual double * errorData ()
const ErrorVector & error () const
ErrorVector & error ()
EIGEN_STRONG_INLINE const InformationType & information () const
information matrix of the constraint
EIGEN_STRONG_INLINE InformationType & information ()
EIGEN_STRONG_INLINE void setInformation (const InformationType &information)
virtual const double * informationData () const
returns the memory of the information matrix, usable for example with a Eigen::Map<MatrixXD>
virtual double * informationData ()
EIGEN_STRONG_INLINE const Measurement & measurement () const
accessor functions for the measurement represented by the edge
virtual void setMeasurement (const Measurement &m)
virtual int rank () const
virtual void initialEstimate (const OptimizableGraph::VertexSet &, OptimizableGraph::Vertex *)
Public Member Functions inherited from g2o::OptimizableGraph::Edge
Edge ()
virtual ~Edge ()
virtual Edge * clone () const
virtual bool setMeasurementData (const double *m)
virtual bool getMeasurementData (double *m) const
virtual int measurementDimension () const
virtual bool setMeasurementFromState ()
RobustKernel * robustKernel () const
if NOT NULL, error of this edge will be robustifed with the kernel
void setRobustKernel (RobustKernel *ptr)
virtual double initialEstimatePossible (const OptimizableGraph::VertexSet &from, OptimizableGraph::Vertex *to)
int level () const
returns the level of the edge
void setLevel (int l)
sets the level of the edge
int dimension () const
returns the dimensions of the error function
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createFrom())
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createTo())
long long internalId () const
the internal ID of the edge
OptimizableGraph * graph ()
const OptimizableGraph * graph () const
bool setParameterId (int argNum, int paramId)
const Parameter * parameter (int argNo) const
size_t numParameters () const
void resizeParameters (size_t newSize)
Public Member Functions inherited from g2o::HyperGraph::Edge
Edge (int id=InvalidId)
creates and empty edge with no vertices
const VertexContainer & vertices () const
VertexContainer & vertices ()
const Vertex * vertex (size_t i) const
Vertex * vertex (size_t i)
void setVertex (size_t i, Vertex *v)
int id () const
void setId (int id)
virtual HyperGraphElementType elementType () const
int numUndefinedVertices () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Member Functions inherited from g2o::HyperGraph::DataContainer
DataContainer ()
virtual ~DataContainer ()
const Data * userData () const
the user data associated with this vertex
Data * userData ()
void setUserData (Data *obs)
void addUserData (Data *obs)
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
CameraParameters * _cam
Additional Inherited Members
Public Types inherited from g2o::BaseBinaryEdge< 2, Vector2D, VertexSBAPointXYZ, VertexSE3Expmap >
typedef VertexSBAPointXYZ VertexXiType
typedef VertexSE3Expmap VertexXjType
typedef BaseEdge< D, Vector2D >::Measurement Measurement
typedef Eigen::Matrix< double, D, Di, D==1?Eigen::RowMajor:Eigen::ColMajor >::AlignedMapType JacobianXiOplusType
typedef Eigen::Matrix< double, D, Dj, D==1?Eigen::RowMajor:Eigen::ColMajor >::AlignedMapType JacobianXjOplusType
typedef BaseEdge< D, Vector2D >::ErrorVector ErrorVector
typedef BaseEdge< D, Vector2D >::InformationType InformationType
typedef Eigen::Map< Eigen::Matrix< double, Di, Dj, Di==1?Eigen::RowMajor:Eigen::ColMajor >, Eigen::Matrix< double, Di, Dj, Di==1?Eigen::RowMajor:Eigen::ColMajor >::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockType
typedef Eigen::Map< Eigen::Matrix< double, Dj, Di, Dj==1?Eigen::RowMajor:Eigen::ColMajor >, Eigen::Matrix< double, Dj, Di, Dj==1?Eigen::RowMajor:Eigen::ColMajor >::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockTransposedType
Public Types inherited from g2o::BaseEdge< D, Vector2D >
typedef Vector2D Measurement
typedef Eigen::Matrix< double, D, 1, Eigen::ColMajor > ErrorVector
typedef Eigen::Matrix< double, D, D, Eigen::ColMajor > InformationType
Static Public Attributes inherited from g2o::BaseBinaryEdge< 2, Vector2D, VertexSBAPointXYZ, VertexSE3Expmap >
static const int Di
static const int Dj
static const int Dimension
Static Public Attributes inherited from g2o::BaseEdge< D, Vector2D >
static const int Dimension
Protected Member Functions inherited from g2o::BaseEdge< D, Vector2D >
InformationType robustInformation (const Vector3D &rho)
Protected Member Functions inherited from g2o::OptimizableGraph::Edge
template<typename ParameterType >
bool installParameter (ParameterType *&p, size_t argNo, int paramId=-1)
template<typename CacheType >
void resolveCache (CacheType *&cache, OptimizableGraph::Vertex *, const std::string &_type, const ParameterVector &parameters)
bool resolveParameters ()
virtual bool resolveCaches ()
Protected Attributes inherited from g2o::BaseBinaryEdge< 2, Vector2D, VertexSBAPointXYZ, VertexSE3Expmap >
bool _hessianRowMajor
HessianBlockType _hessian
HessianBlockTransposedType _hessianTransposed
JacobianXiOplusType _jacobianOplusXi
JacobianXjOplusType _jacobianOplusXj
Protected Attributes inherited from g2o::BaseEdge< D, Vector2D >
Measurement _measurement
InformationType _information
ErrorVector _error
Protected Attributes inherited from g2o::OptimizableGraph::Edge
int _dimension
int _level
RobustKernel * _robustKernel
long long _internalId
std::vector< int > _cacheIds
std::vector< std::string > _parameterTypes
std::vector< Parameter ** > _parameters
std::vector< int > _parameterIds
Protected Attributes inherited from g2o::HyperGraph::Edge
VertexContainer _vertices
int _id
unique id
Protected Attributes inherited from g2o::HyperGraph::DataContainer
Data * _userData
Detailed Description
Definition at line 131 of file types_six_dof_expmap.h.
Constructor & Destructor Documentation
g2o::EdgeProjectXYZ2UV::EdgeProjectXYZ2UV ()
Definition at line 138 of file types_six_dof_expmap.cpp.
References _cam, g2o::OptimizableGraph::Edge::installParameter(), and g2o::OptimizableGraph::Edge::resizeParameters().
                                      : BaseBinaryEdge<2, Vector2D, VertexSBAPointXYZ, VertexSE3Expmap>() {
   _cam = 0;
   resizeParameters(1);
   installParameter(_cam, 0);
 }
Member Function Documentation
void g2o::EdgeProjectXYZ2UV::computeError () inline virtual
Implements g2o::OptimizableGraph::Edge.
Definition at line 141 of file types_six_dof_expmap.h.
References g2o::CameraParameters::cam_map(), g2o::BaseVertex< D, T >::estimate(), and g2o::SE3Quat::map().
{
       const VertexSE3Expmap* v1 = static_cast<const VertexSE3Expmap*>(_vertices[1]);
       const VertexSBAPointXYZ* v2 = static_cast<const VertexSBAPointXYZ*>(_vertices[0]);
       const CameraParameters * cam
         = static_cast<const CameraParameters *>(parameter(0));
       Vector2D obs(_measurement);
       _error = obs-cam->cam_map(v1->estimate().map(v2->estimate()));
     }
void g2o::EdgeProjectXYZ2UV::linearizeOplus () virtual
Linearizes the oplus operator in the vertex, and stores the result in temporary variables _jacobianOplusXi and _jacobianOplusXj
Reimplemented from g2o::BaseBinaryEdge< 2, Vector2D, VertexSBAPointXYZ, VertexSE3Expmap >.
Definition at line 291 of file types_six_dof_expmap.cpp.
References g2o::BaseBinaryEdge< 3, Vector3D, VertexSBAPointXYZ, VertexSE3Expmap >::_jacobianOplusXi, g2o::BaseBinaryEdge< 3, Vector3D, VertexSBAPointXYZ, VertexSE3Expmap >::_jacobianOplusXj, g2o::HyperGraph::Edge::_vertices, g2o::BaseVertex< D, T >::estimate(), g2o::CameraParameters::focal_length, and g2o::OptimizableGraph::Edge::parameter().
{
   VertexSE3Expmap * vj = static_cast<VertexSE3Expmap *>(_vertices[1]);
   SE3Quat T(vj->estimate());
   VertexSBAPointXYZ* vi = static_cast<VertexSBAPointXYZ*>(_vertices[0]);
   Vector3D xyz = vi->estimate();
   Vector3D xyz_trans = T.map(xyz);
   double x = xyz_trans[0];
   double y = xyz_trans[1];
   double z = xyz_trans[2];
   double z_2 = z*z;
   const CameraParameters * cam = static_cast<const CameraParameters *>(parameter(0));
   Matrix<double,2,3,Eigen::ColMajor> tmp;
   tmp(0,0) = cam->focal_length;
   tmp(0,1) = 0;
   tmp(0,2) = -x/z*cam->focal_length;
   tmp(1,0) = 0;
   tmp(1,1) = cam->focal_length;
   tmp(1,2) = -y/z*cam->focal_length;
   _jacobianOplusXi =  -1./z * tmp * T.rotation().toRotationMatrix();
   _jacobianOplusXj(0,0) =  x*y/z_2 *cam->focal_length;
   _jacobianOplusXj(0,1) = -(1+(x*x/z_2)) *cam->focal_length;
   _jacobianOplusXj(0,2) = y/z *cam->focal_length;
   _jacobianOplusXj(0,3) = -1./z *cam->focal_length;
   _jacobianOplusXj(0,4) = 0;
   _jacobianOplusXj(0,5) = x/z_2 *cam->focal_length;
   _jacobianOplusXj(1,0) = (1+y*y/z_2) *cam->focal_length;
   _jacobianOplusXj(1,1) = -x*y/z_2 *cam->focal_length;
   _jacobianOplusXj(1,2) = -x/z *cam->focal_length;
   _jacobianOplusXj(1,3) = 0;
   _jacobianOplusXj(1,4) = -1./z *cam->focal_length;
   _jacobianOplusXj(1,5) = y/z_2 *cam->focal_length;
 }
bool g2o::EdgeProjectXYZ2UV::read (std::istream & is) virtual
read the vertex from a stream, i.e., the internal state of the vertex
Implements g2o::OptimizableGraph::Edge.
Definition at line 244 of file types_six_dof_expmap.cpp.
References g2o::BaseEdge< D, Vector3D >::_measurement, g2o::BaseEdge< D, Vector3D >::information(), and g2o::OptimizableGraph::Edge::setParameterId().
{
   int paramId;
   is >> paramId;
   setParameterId(0, paramId);
   for (int i=0; i<2; i++){
     is >> _measurement[i];
   }
   for (int i=0; i<2; i++)
     for (int j=i; j<2; j++) {
       is >> information()(i,j);
       if (i!=j)
         information()(j,i)=information()(i,j);
     }
   return true;
 }
bool g2o::EdgeProjectXYZ2UV::write (std::ostream & os) const virtual
write the vertex to a stream
Implements g2o::OptimizableGraph::Edge.
Definition at line 261 of file types_six_dof_expmap.cpp.
References g2o::EdgeProjectXYZ2UVU::_cam, g2o::Parameter::id(), g2o::BaseEdge< D, Vector3D >::information(), and g2o::BaseEdge< D, Vector3D >::measurement().
{
   os << _cam->id() << " ";
   for (int i=0; i<2; i++){
     os << measurement()[i] << " ";
   }
   for (int i=0; i<2; i++)
     for (int j=i; j<2; j++){
       os << " " <<  information()(i,j);
     }
   return os.good();
 }
Member Data Documentation
CameraParameters* g2o::EdgeProjectXYZ2UV::_cam
Definition at line 152 of file types_six_dof_expmap.h.
Referenced by EdgeProjectXYZ2UV(), and g2o::EdgeProjectPSI2UV::write().
g2o::EdgeProjectXYZ2UV::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 133 of file types_six_dof_expmap.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/sba/types_six_dof_expmap.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/sba/types_six_dof_expmap.cpp