g2o: g2o::MotionMeasurement Class Reference
g2o::MotionMeasurement Class Reference
A 2D odometry measurement expressed as a transformation.
#include <odometry_measurement.h>
Public Member Functions
MotionMeasurement ()
MotionMeasurement (double x, double y, double theta, double dt)
MotionMeasurement (const Vector3D &m, double dt)
double x () const
void setX (double v)
double y () const
void setY (double v)
double theta () const
void setTheta (double v)
double dt () const
void setDt (double t)
const Vector3D & measurement () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Attributes
Vector3D _measurement
double _dt
Detailed Description
A 2D odometry measurement expressed as a transformation.
Definition at line 64 of file odometry_measurement.h.
Constructor & Destructor Documentation
g2o::MotionMeasurement::MotionMeasurement ()
Definition at line 44 of file odometry_measurement.cpp.
Referenced by g2o::OdomConvert::convertToMotion().
                                        :
     _measurement(0., 0., 0.), _dt(0.)
   {
   }
g2o::MotionMeasurement::MotionMeasurement (double x, double y, double theta, double dt)
Definition at line 49 of file odometry_measurement.cpp.
                                                                                   :
     _measurement(x, y, theta), _dt(dt)
   {
   }
g2o::MotionMeasurement::MotionMeasurement (const Vector3D & m, double dt)
Definition at line 54 of file odometry_measurement.cpp.
                                                                    :
     _measurement(m), _dt(dt)
   {
   }
Member Function Documentation
double g2o::MotionMeasurement::dt () const inline
Definition at line 81 of file odometry_measurement.h.
Referenced by g2o::OdomConvert::convertToVelocity().
 { return _dt;}
const Vector3D& g2o::MotionMeasurement::measurement () const inline
Definition at line 84 of file odometry_measurement.h.
Referenced by main().
 { return _measurement;}
void g2o::MotionMeasurement::setDt (double t) inline
Definition at line 82 of file odometry_measurement.h.
 { _dt = t;}
void g2o::MotionMeasurement::setTheta (double v) inline
Definition at line 79 of file odometry_measurement.h.
 { _measurement(2) = v;}
void g2o::MotionMeasurement::setX (double v) inline
Definition at line 73 of file odometry_measurement.h.
 { _measurement(0) = v;}
void g2o::MotionMeasurement::setY (double v) inline
Definition at line 76 of file odometry_measurement.h.
 { _measurement(1) = v;}
double g2o::MotionMeasurement::theta () const inline
Definition at line 78 of file odometry_measurement.h.
Referenced by g2o::OdomConvert::convertToMotion(), and g2o::OdomConvert::convertToVelocity().
 { return _measurement(2);}
double g2o::MotionMeasurement::x () const inline
Definition at line 72 of file odometry_measurement.h.
Referenced by g2o::OdomConvert::convertToMotion(), and g2o::OdomConvert::convertToVelocity().
 { return _measurement(0);}
double g2o::MotionMeasurement::y () const inline
Definition at line 75 of file odometry_measurement.h.
Referenced by g2o::OdomConvert::convertToMotion(), and g2o::OdomConvert::convertToVelocity().
 { return _measurement(1);}
Member Data Documentation
double g2o::MotionMeasurement::_dt protected
Definition at line 88 of file odometry_measurement.h.
Vector3D g2o::MotionMeasurement::_measurement protected
Definition at line 87 of file odometry_measurement.h.
g2o::MotionMeasurement::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 67 of file odometry_measurement.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/sclam2d/odometry_measurement.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/sclam2d/odometry_measurement.cpp