g2o: g2o::ThetaTreeAction Class Reference
g2o::ThetaTreeAction Class Reference
compute the initial guess of theta while travelling along the MST
Public Member Functions
ThetaTreeAction (double *theta)
virtual double perform (HyperGraph::Vertex *v, HyperGraph::Vertex *vParent, HyperGraph::Edge *e)
Public Member Functions inherited from g2o::HyperDijkstra::TreeAction
virtual double perform (HyperGraph::Vertex *v, HyperGraph::Vertex *vParent, HyperGraph::Edge *e, double distance)
Protected Attributes
double * _thetaGuess
Detailed Description
compute the initial guess of theta while travelling along the MST
Definition at line 49 of file solver_slam2d_linear.cpp.
Constructor & Destructor Documentation
g2o::ThetaTreeAction::ThetaTreeAction (double * theta) inline
Definition at line 52 of file solver_slam2d_linear.cpp.
 : HyperDijkstra::TreeAction(), _thetaGuess(theta) {}
Member Function Documentation
virtual double g2o::ThetaTreeAction::perform (HyperGraph::Vertex * v, HyperGraph::Vertex * vParent, HyperGraph::Edge * e) inline virtual
Reimplemented from g2o::HyperDijkstra::TreeAction.
Definition at line 53 of file solver_slam2d_linear.cpp.
References g2o::OptimizableGraph::Vertex::hessianIndex(), g2o::BaseEdge< D, E >::measurement(), g2o::SE2::rotation(), and g2o::HyperGraph::Edge::vertices().
       {
         if (! vParent)
           return 0.;
         EdgeSE2* odom    = static_cast<EdgeSE2*>(e);
         VertexSE2* from  = static_cast<VertexSE2*>(vParent);
         VertexSE2* to    = static_cast<VertexSE2*>(v);
         assert(to->hessianIndex() >= 0);
         double fromTheta = from->hessianIndex() < 0 ? 0. : _thetaGuess[from->hessianIndex()];
         bool direct      = odom->vertices()[0] == from;
         if (direct)
           _thetaGuess[to->hessianIndex()] = fromTheta + odom->measurement().rotation().angle();
         else
           _thetaGuess[to->hessianIndex()] = fromTheta - odom->measurement().rotation().angle();
         return 1.;
       }
Member Data Documentation
double* g2o::ThetaTreeAction::_thetaGuess protected
Definition at line 70 of file solver_slam2d_linear.cpp.
The documentation for this class was generated from the following file:
/home/xuezhisd/CLionProjects/g2o/g2o/solvers/slam2d_linear/solver_slam2d_linear.cpp