g2o: g2o::EdgeSE2PointXYBearingWriteGnuplotAction Class Reference
g2o::EdgeSE2PointXYBearingWriteGnuplotAction Class Reference
#include <edge_se2_pointxy_bearing.h>
Public Member Functions
EdgeSE2PointXYBearingWriteGnuplotAction ()
virtual HyperGraphElementAction * operator() (HyperGraph::HyperGraphElement *element, HyperGraphElementAction::Parameters *params_)
redefine this to do the action stuff. If successful, the action returns a pointer to itself
Public Member Functions inherited from g2o::WriteGnuplotAction
WriteGnuplotAction (const std::string &typeName_)
Public Member Functions inherited from g2o::HyperGraphElementAction
HyperGraphElementAction (const std::string &typeName_="")
virtual HyperGraphElementAction * operator() (const HyperGraph::HyperGraphElement *element, Parameters *parameters)
redefine this to do the action stuff. If successful, the action returns a pointer to itself
virtual ~HyperGraphElementAction ()
destroyed actions release the memory
const std::string & typeName () const
returns the typeid name of the action
const std::string & name () const
returns the name of an action, e.g "draw"
void setTypeName (const std::string &typeName_)
sets the type on which an action has to operate
Additional Inherited Members
Public Types inherited from g2o::HyperGraphElementAction
typedef std::map< std::string, HyperGraphElementAction * > ActionMap
Protected Attributes inherited from g2o::HyperGraphElementAction
std::string _typeName
std::string _name
Detailed Description
Definition at line 79 of file edge_se2_pointxy_bearing.h.
Constructor & Destructor Documentation
g2o::EdgeSE2PointXYBearingWriteGnuplotAction::EdgeSE2PointXYBearingWriteGnuplotAction ()
Definition at line 69 of file edge_se2_pointxy_bearing.cpp.
 : WriteGnuplotAction(typeid(EdgeSE2PointXYBearing).name()){}
Member Function Documentation
HyperGraphElementAction * g2o::EdgeSE2PointXYBearingWriteGnuplotAction::operator() (HyperGraph::HyperGraphElement * element, HyperGraphElementAction::Parameters * parameters) virtual
redefine this to do the action stuff. If successful, the action returns a pointer to itself
Reimplemented from g2o::HyperGraphElementAction.
Definition at line 71 of file edge_se2_pointxy_bearing.cpp.
References __PRETTY_FUNCTION__, g2o::HyperGraphElementAction::_typeName, g2o::BaseVertex< D, T >::estimate(), LANDMARK_EDGE_COLOR, LANDMARK_EDGE_GHOST_COLOR, g2o::BaseEdge< D, E >::measurement(), g2o::HyperGraphElementAction::name(), g2o::WriteGnuplotAction::Parameters::os, g2o::SE2::rotation(), g2o::SE2::translation(), and g2o::HyperGraph::Edge::vertex().
{
     if (typeid(*element).name()!=_typeName)
       return 0;
     WriteGnuplotAction::Parameters* params=static_cast<WriteGnuplotAction::Parameters*>(params_);
     if (!params->os){
       std::cerr << __PRETTY_FUNCTION__ << ": warning, on valid os specified" << std::endl;
       return 0;
     }
     EdgeSE2PointXYBearing* e =  static_cast<EdgeSE2PointXYBearing*>(element);
     VertexSE2* fromEdge = static_cast<VertexSE2*>(e->vertex(0));
     VertexPointXY* toEdge   = static_cast<VertexPointXY*>(e->vertex(1));
     *(params->os) << fromEdge->estimate().translation().x() << " " << fromEdge->estimate().translation().y()
       << " " << fromEdge->estimate().rotation().angle() << std::endl;
     *(params->os) << toEdge->estimate().x() << " " << toEdge->estimate().y() << std::endl;
     *(params->os) << std::endl;
     return this;
   }
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam2d/edge_se2_pointxy_bearing.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam2d/edge_se2_pointxy_bearing.cpp