g2o: g2o::opengl::GLUWrapper Class Reference
g2o::opengl::GLUWrapper Class Reference
handle the GLU quadratic
Static Public Member Functions
static GLUquadricObj * getQuadradic ()
Protected Member Functions
GLUWrapper ()
~GLUWrapper ()
Protected Attributes
GLUquadricObj * _quadratic
Detailed Description
handle the GLU quadratic
Definition at line 36 of file opengl_primitives.cpp.
Constructor & Destructor Documentation
g2o::opengl::GLUWrapper::GLUWrapper () inline protected
Definition at line 45 of file opengl_primitives.cpp.
References _quadratic.
     {
       //std::cerr << __PRETTY_FUNCTION__ << std::endl;
       _quadratic = gluNewQuadric();              // Create A Pointer To The Quadric Object ( NEW )
       gluQuadricNormals(_quadratic, GLU_SMOOTH); // Create Smooth Normals ( NEW )
     }
g2o::opengl::GLUWrapper::~GLUWrapper () inline protected
Definition at line 51 of file opengl_primitives.cpp.
References _quadratic.
     {
       //std::cerr << __PRETTY_FUNCTION__ << std::endl;
       gluDeleteQuadric(_quadratic);
     }
Member Function Documentation
static GLUquadricObj* g2o::opengl::GLUWrapper::getQuadradic () inline static
Definition at line 39 of file opengl_primitives.cpp.
References _quadratic.
Referenced by g2o::opengl::drawCone(), g2o::opengl::drawCylinder(), g2o::opengl::drawDisk(), g2o::opengl::drawEllipsoid(), g2o::opengl::drawPyramid(), g2o::opengl::drawRangeRing(), and g2o::opengl::drawSphere().
     {
       static GLUWrapper inst;
       return inst._quadratic;
     }
Member Data Documentation
GLUquadricObj* g2o::opengl::GLUWrapper::_quadratic protected
Definition at line 56 of file opengl_primitives.cpp.
Referenced by getQuadradic(), GLUWrapper(), and ~GLUWrapper().
The documentation for this class was generated from the following file:
/home/xuezhisd/CLionProjects/g2o/g2o/stuff/opengl_primitives.cpp