g2o: g2o::ParameterCamera Class Reference
g2o::ParameterCamera Class Reference
parameters for a camera
#include <parameter_camera.h>
Public Member Functions
ParameterCamera ()
void setKcam (double fx, double fy, double cx, double cy)
void setOffset (const Isometry3D &offset_=Isometry3D::Identity())
virtual bool read (std::istream &is)
read the data from a stream
virtual bool write (std::ostream &os) const
write the data to a stream
const Matrix3D & Kcam () const
const Matrix3D & invKcam () const
const Matrix3D & Kcam_inverseOffsetR () const
Public Member Functions inherited from g2o::ParameterSE3Offset
ParameterSE3Offset ()
void setOffset (const Isometry3D &offset_=Isometry3D::Identity())
const Isometry3D & offset () const
rotation of the offset as 3x3 rotation matrix
const Isometry3D & inverseOffset () const
rotation of the inverse offset as 3x3 rotation matrix
Public Member Functions inherited from g2o::Parameter
Parameter ()
virtual ~Parameter ()
int id () const
void setId (int id_)
virtual HyperGraph::HyperGraphElementType elementType () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Public Attributes inherited from g2o::ParameterSE3Offset
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Attributes
Matrix3D _Kcam
Matrix3D _invKcam
Matrix3D _Kcam_inverseOffsetR
Protected Attributes inherited from g2o::ParameterSE3Offset
Isometry3D _offset
Isometry3D _inverseOffset
Protected Attributes inherited from g2o::Parameter
int _id
Detailed Description
parameters for a camera
Definition at line 38 of file parameter_camera.h.
Constructor & Destructor Documentation
g2o::ParameterCamera::ParameterCamera ()
Definition at line 40 of file parameter_camera.cpp.
{
     setId(-1);
     setKcam(1,1,0.5,0.5);
     setOffset();
   }
Member Function Documentation
const Matrix3D& g2o::ParameterCamera::invKcam () const inline
Definition at line 49 of file parameter_camera.h.
Referenced by g2o::EdgeSE3PointXYZDepth::initialEstimate(), and g2o::EdgeSE3PointXYZDisparity::initialEstimate().
 { return _invKcam;}
const Matrix3D& g2o::ParameterCamera::Kcam () const inline
Definition at line 48 of file parameter_camera.h.
 { return _Kcam;}
const Matrix3D& g2o::ParameterCamera::Kcam_inverseOffsetR () const inline
Definition at line 50 of file parameter_camera.h.
Referenced by g2o::EdgeSE3PointXYZDepth::linearizeOplus(), and g2o::EdgeSE3PointXYZDisparity::linearizeOplus().
 { return _Kcam_inverseOffsetR;}
bool g2o::ParameterCamera::read (std::istream & is) virtual
read the data from a stream
Reimplemented from g2o::ParameterSE3Offset.
Reimplemented in g2o::ParameterStereoCamera.
Definition at line 63 of file parameter_camera.cpp.
References g2o::internal::fromVectorQT(), and g2o::internal::normalize().
{
     Vector7d off;
     for (int i=0; i<7; i++)
       is >> off[i];
     // normalize the quaternion to recover numerical precision lost by storing as human readable text
     Vector4D::MapType(off.data()+3).normalize();
     setOffset(internal::fromVectorQT(off));
     double fx,fy,cx,cy;
     is >> fx >> fy >> cx >> cy;
     setKcam(fx,fy,cx,cy);
     return is.good();
   }
void g2o::ParameterCamera::setKcam (double fx, double fy, double cx, double cy)
Definition at line 51 of file parameter_camera.cpp.
Referenced by main().
{
     _Kcam.setZero();
     _Kcam(0,0) = fx;
     _Kcam(1,1) = fy;
     _Kcam(0,2) = cx;
     _Kcam(1,2) = cy;
     _Kcam(2,2) = 1.0;
     _invKcam = _Kcam.inverse();
     _Kcam_inverseOffsetR = _Kcam * inverseOffset().rotation();
   }
void g2o::ParameterCamera::setOffset (const Isometry3D & offset_ = Isometry3D::Identity())
Definition at line 46 of file parameter_camera.cpp.
{
     ParameterSE3Offset::setOffset(offset_);
     _Kcam_inverseOffsetR = _Kcam * inverseOffset().rotation();
   }
bool g2o::ParameterCamera::write (std::ostream & os) const virtual
write the data to a stream
Reimplemented from g2o::ParameterSE3Offset.
Reimplemented in g2o::ParameterStereoCamera.
Definition at line 76 of file parameter_camera.cpp.
References g2o::internal::toVectorQT().
{
     Vector7d off = internal::toVectorQT(_offset);
     for (int i=0; i<7; i++)
       os << off[i] << " ";
     os << _Kcam(0,0) << " ";
     os << _Kcam(1,1) << " ";
     os << _Kcam(0,2) << " ";
     os << _Kcam(1,2) << " ";
     return os.good();
   }
Member Data Documentation
Matrix3D g2o::ParameterCamera::_invKcam protected
Definition at line 54 of file parameter_camera.h.
Matrix3D g2o::ParameterCamera::_Kcam protected
Definition at line 53 of file parameter_camera.h.
Matrix3D g2o::ParameterCamera::_Kcam_inverseOffsetR protected
Definition at line 55 of file parameter_camera.h.
g2o::ParameterCamera::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 40 of file parameter_camera.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam3d/parameter_camera.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam3d/parameter_camera.cpp