g2o: g2o::G2oQGLViewer Class Reference
g2o::G2oQGLViewer Class Reference
OpenGL based viewer for the graph.
#include <g2o_qglviewer.h>
Public Member Functions
G2oQGLViewer (QWidget *parent=NULL, const QGLWidget *shareWidget=0, Qt::WindowFlags flags=0)
~G2oQGLViewer ()
void draw ()
void init ()
bool updateDisplay () const
void setUpdateDisplay (bool updateDisplay)
DrawAction::Parameters * parameters ()
Public Attributes
SparseOptimizer * graph
Protected Attributes
HyperGraphElementAction * _drawActions
GLuint _drawList
bool _updateDisplay
DrawAction::Parameters * _drawActionParameters
Detailed Description
OpenGL based viewer for the graph.
Definition at line 33 of file g2o_qglviewer.h.
Constructor & Destructor Documentation
g2o::G2oQGLViewer::G2oQGLViewer (QWidget * parent = NULL, const QGLWidget * shareWidget = 0, Qt::WindowFlags flags = 0)
Definition at line 85 of file g2o_qglviewer.cpp.
References _drawActionParameters.
                                                                                              :
   QGLViewer(parent, shareWidget, flags),
   graph(0), _drawActions(0), _drawList(0)
 {
   setAxisIsDrawn(false);
   _drawActionParameters = new DrawAction::Parameters();
 }
g2o::G2oQGLViewer::~G2oQGLViewer ()
Definition at line 93 of file g2o_qglviewer.cpp.
References _drawActionParameters, and _drawList.
 {
   delete _drawActionParameters;
   glDeleteLists(_drawList, 1);
 }
Member Function Documentation
void g2o::G2oQGLViewer::draw ()
Definition at line 99 of file g2o_qglviewer.cpp.
References _drawActionParameters, _drawActions, _drawList, _updateDisplay, g2o::HyperGraphActionLibrary::actionByName(), g2o::applyAction(), graph, and g2o::HyperGraphActionLibrary::instance().
 {
   if (! graph)
     return;
   if (_drawActions == 0) {
     _drawActions = HyperGraphActionLibrary::instance()->actionByName("draw");
     assert(_drawActions);
   }
   if (! _drawActions) // avoid segmentation fault in release build
     return;
   if (_updateDisplay) {
     _updateDisplay = false;
     glNewList(_drawList, GL_COMPILE_AND_EXECUTE);
     applyAction(graph, _drawActions, _drawActionParameters);
     glEndList();
   } else {
     glCallList(_drawList);
   }
 }
void g2o::G2oQGLViewer::init ()
Definition at line 121 of file g2o_qglviewer.cpp.
References _drawList, and g2o::types_icp::init().
 {
   QGLViewer::init();
   //glDisable(GL_LIGHT0);
  //glDisable(GL_LIGHTING);
   setBackgroundColor(QColor::fromRgb(51, 51, 51));
   // some default settings i like
   glEnable(GL_LINE_SMOOTH);
   glEnable(GL_BLEND);
   glEnable(GL_DEPTH_TEST);
   glEnable(GL_NORMALIZE);
   //glEnable(GL_CULL_FACE);
   glShadeModel(GL_FLAT);
   //glShadeModel(GL_SMOOTH);
   glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
   setAxisIsDrawn();
   // don't save state
   setStateFileName(QString::null);
   // mouse bindings
 #ifdef QGLVIEWER_DEPRECATED_MOUSEBINDING
   setMouseBinding(Qt::NoModifier, Qt::RightButton, CAMERA, ZOOM);
   setMouseBinding(Qt::NoModifier, Qt::MidButton, CAMERA, TRANSLATE);
 #else
   setMouseBinding(Qt::RightButton, CAMERA, ZOOM);
   setMouseBinding(Qt::MidButton, CAMERA, TRANSLATE);
 #endif
   // keyboard shortcuts
   setShortcut(CAMERA_MODE, 0);
   setShortcut(EXIT_VIEWER, 0);
   //setShortcut(SAVE_SCREENSHOT, 0);
   // replace camera
   qglviewer::Camera* oldcam = camera();
   qglviewer::Camera* cam = new StandardCamera();
   setCamera(cam);
   cam->setPosition(qglviewer::Vec(0., 0., 75.));
   cam->setUpVector(qglviewer::Vec(0., 1., 0.));
   cam->lookAt(qglviewer::Vec(0., 0., 0.));
   delete oldcam;
   // getting a display list
   _drawList = glGenLists(1);
 }
DrawAction::Parameters* g2o::G2oQGLViewer::parameters () inline
Definition at line 48 of file g2o_qglviewer.h.
Referenced by ViewerPropertiesWidget::setViewer().
 { return _drawActionParameters;}
void g2o::G2oQGLViewer::setUpdateDisplay (bool updateDisplay)
Definition at line 171 of file g2o_qglviewer.cpp.
References _updateDisplay, and updateDisplay().
Referenced by ViewerPropertiesWidget::applyProperties(), and g2o::GuiHyperGraphAction::operator()().
 {
   _updateDisplay = updateDisplay;
 }
bool g2o::G2oQGLViewer::updateDisplay () const inline
the viewer uses a display list to cache the drawing, use setUpdateDisplay() to force the creation of an updated display list.
Definition at line 45 of file g2o_qglviewer.h.
References updateDisplay().
Referenced by setUpdateDisplay().
 { return _updateDisplay;}
Member Data Documentation
DrawAction::Parameters* g2o::G2oQGLViewer::_drawActionParameters protected
Definition at line 57 of file g2o_qglviewer.h.
Referenced by draw(), G2oQGLViewer(), and ~G2oQGLViewer().
HyperGraphElementAction* g2o::G2oQGLViewer::_drawActions protected
Definition at line 54 of file g2o_qglviewer.h.
Referenced by draw().
GLuint g2o::G2oQGLViewer::_drawList protected
Definition at line 55 of file g2o_qglviewer.h.
Referenced by draw(), init(), and ~G2oQGLViewer().
bool g2o::G2oQGLViewer::_updateDisplay protected
Definition at line 56 of file g2o_qglviewer.h.
Referenced by draw(), and setUpdateDisplay().
SparseOptimizer* g2o::G2oQGLViewer::graph
Definition at line 51 of file g2o_qglviewer.h.
Referenced by draw().
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_viewer/g2o_qglviewer.h
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_viewer/g2o_qglviewer.cpp