g2o: g2o::tutorial::SE2 Class Reference
g2o::tutorial::SE2 Class Reference
#include <se2.h>
Public Member Functions
SE2 ()
SE2 (double x, double y, double theta)
const Eigen::Vector2d & translation () const
Eigen::Vector2d & translation ()
const Eigen::Rotation2Dd & rotation () const
Eigen::Rotation2Dd & rotation ()
SE2 operator* (const SE2 &tr2) const
SE2 & operator*= (const SE2 &tr2)
Eigen::Vector2d operator* (const Eigen::Vector2d &v) const
SE2 inverse () const
double operator[] (int i) const
double & operator[] (int i)
void fromVector (const Eigen::Vector3d &v)
Eigen::Vector3d toVector () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Attributes
Eigen::Rotation2Dd _R
Eigen::Vector2d _t
Detailed Description
Definition at line 42 of file se2.h.
Constructor & Destructor Documentation
g2o::tutorial::SE2::SE2 () inline
Definition at line 45 of file se2.h.
 :_R(0),_t(0,0){}
g2o::tutorial::SE2::SE2 (double x, double y, double theta) inline
Definition at line 47 of file se2.h.
 :_R(theta),_t(x,y){}
Member Function Documentation
void g2o::tutorial::SE2::fromVector (const Eigen::Vector3d & v) inline
Definition at line 98 of file se2.h.
{
           *this=SE2(v[0], v[1], v[2]);
         }
SE2 g2o::tutorial::SE2::inverse () const inline
Definition at line 76 of file se2.h.
References _R, _t, and g2o::normalize_theta().
Referenced by g2o::tutorial::EdgeSE2::setMeasurement(), g2o::tutorial::ParameterSE2Offset::setOffset(), and g2o::tutorial::Simulator::simulate().
{
           SE2 ret;
           ret._R=_R.inverse();
           ret._R.angle()=normalize_theta(ret._R.angle());
           ret._t=ret._R*(Eigen::Vector2d(-1 * _t));
           return ret;
         }
SE2 g2o::tutorial::SE2::operator* (const SE2 & tr2) const inline
Definition at line 57 of file se2.h.
References _R, _t, and g2o::normalize_theta().
{
           SE2 result(*this);
           result._t += _R*tr2._t;
           result._R.angle()+= tr2._R.angle();
           result._R.angle()=normalize_theta(result._R.angle());
           return result;
         }
Eigen::Vector2d g2o::tutorial::SE2::operator* (const Eigen::Vector2d & v) const inline
Definition at line 72 of file se2.h.
{
           return _t+_R*v;
         }
SE2& g2o::tutorial::SE2::operator*= (const SE2 & tr2) inline
Definition at line 65 of file se2.h.
References _R, _t, and g2o::normalize_theta().
{
           _t+=_R*tr2._t;
           _R.angle()+=tr2._R.angle();
           _R.angle()=normalize_theta(_R.angle());
           return *this;
         }
double g2o::tutorial::SE2::operator[] (int i) const inline
Definition at line 84 of file se2.h.
{
           assert (i>=0 && i<3);
           if (i<2)
             return _t(i);
           return _R.angle();
         }
double& g2o::tutorial::SE2::operator[] (int i) inline
Definition at line 91 of file se2.h.
{
           assert (i>=0 && i<3);
           if (i<2)
             return _t(i);
           return _R.angle();
         }
const Eigen::Rotation2Dd& g2o::tutorial::SE2::rotation () const inline
Definition at line 53 of file se2.h.
Referenced by g2o::tutorial::ParameterSE2Offset::write().
 {return _R;}
Eigen::Rotation2Dd& g2o::tutorial::SE2::rotation () inline
Definition at line 55 of file se2.h.
 {return _R;}
Eigen::Vector3d g2o::tutorial::SE2::toVector () const inline
Definition at line 102 of file se2.h.
Referenced by g2o::tutorial::EdgeSE2::computeError(), and g2o::tutorial::Simulator::sampleTransformation().
{
           Eigen::Vector3d ret;
           for (int i=0; i<3; i++){
             ret(i)=(*this)[i];
           }
           return ret;
         }
const Eigen::Vector2d& g2o::tutorial::SE2::translation () const inline
Definition at line 49 of file se2.h.
Referenced by g2o::tutorial::Simulator::simulate(), and g2o::tutorial::ParameterSE2Offset::write().
 {return _t;}
Eigen::Vector2d& g2o::tutorial::SE2::translation () inline
Definition at line 51 of file se2.h.
 {return _t;}
Member Data Documentation
Eigen::Rotation2Dd g2o::tutorial::SE2::_R protected
Definition at line 111 of file se2.h.
Referenced by inverse(), operator*(), and operator*=().
Eigen::Vector2d g2o::tutorial::SE2::_t protected
Definition at line 112 of file se2.h.
Referenced by inverse(), operator*(), and operator*=().
g2o::tutorial::SE2::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 44 of file se2.h.
The documentation for this class was generated from the following file:
/home/xuezhisd/CLionProjects/g2o/g2o/examples/tutorial_slam2d/se2.h