g2o: g2o::EdgeLine2DPointXY Class Reference
g2o::EdgeLine2DPointXY Class Reference
#include <edge_line2d_pointxy.h>
Public Member Functions
G2O_TYPES_SLAM2D_ADDONS_API EIGEN_MAKE_ALIGNED_OPERATOR_NEW G2O_TYPES_SLAM2D_ADDONS_API EdgeLine2DPointXY ()
G2O_TYPES_SLAM2D_ADDONS_API void computeError ()
virtual G2O_TYPES_SLAM2D_ADDONS_API bool setMeasurementData (const double *d)
virtual G2O_TYPES_SLAM2D_ADDONS_API bool getMeasurementData (double *d) const
virtual G2O_TYPES_SLAM2D_ADDONS_API int measurementDimension () const
virtual G2O_TYPES_SLAM2D_ADDONS_API bool setMeasurementFromState ()
virtual G2O_TYPES_SLAM2D_ADDONS_API bool read (std::istream &is)
read the vertex from a stream, i.e., the internal state of the vertex
virtual G2O_TYPES_SLAM2D_ADDONS_API bool write (std::ostream &os) const
write the vertex to a stream
Public Member Functions inherited from g2o::BaseBinaryEdge< 1, double, VertexLine2D, VertexPointXY >
BaseBinaryEdge ()
virtual OptimizableGraph::Vertex * createFrom ()
virtual OptimizableGraph::Vertex * createTo ()
virtual OptimizableGraph::Vertex * createVertex (int i)
virtual void resize (size_t size)
virtual bool allVerticesFixed () const
virtual void linearizeOplus (JacobianWorkspace &jacobianWorkspace)
virtual void linearizeOplus ()
const JacobianXiOplusType & jacobianOplusXi () const
returns the result of the linearization in the manifold space for the node xi
const JacobianXjOplusType & jacobianOplusXj () const
returns the result of the linearization in the manifold space for the node xj
virtual void constructQuadraticForm ()
virtual void mapHessianMemory (double *d, int i, int j, bool rowMajor)
Public Member Functions inherited from g2o::BaseEdge< D, double >
BaseEdge ()
virtual ~BaseEdge ()
virtual double chi2 () const
computes the chi2 based on the cached error value, only valid after computeError has been called.
virtual const double * errorData () const
returns the error vector cached after calling the computeError;
virtual double * errorData ()
const ErrorVector & error () const
ErrorVector & error ()
EIGEN_STRONG_INLINE const InformationType & information () const
information matrix of the constraint
EIGEN_STRONG_INLINE InformationType & information ()
EIGEN_STRONG_INLINE void setInformation (const InformationType &information)
virtual const double * informationData () const
returns the memory of the information matrix, usable for example with a Eigen::Map<MatrixXD>
virtual double * informationData ()
EIGEN_STRONG_INLINE const Measurement & measurement () const
accessor functions for the measurement represented by the edge
virtual void setMeasurement (const Measurement &m)
virtual int rank () const
virtual void initialEstimate (const OptimizableGraph::VertexSet &, OptimizableGraph::Vertex *)
Public Member Functions inherited from g2o::OptimizableGraph::Edge
Edge ()
virtual ~Edge ()
virtual Edge * clone () const
RobustKernel * robustKernel () const
if NOT NULL, error of this edge will be robustifed with the kernel
void setRobustKernel (RobustKernel *ptr)
virtual double initialEstimatePossible (const OptimizableGraph::VertexSet &from, OptimizableGraph::Vertex *to)
int level () const
returns the level of the edge
void setLevel (int l)
sets the level of the edge
int dimension () const
returns the dimensions of the error function
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createFrom())
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createTo())
long long internalId () const
the internal ID of the edge
OptimizableGraph * graph ()
const OptimizableGraph * graph () const
bool setParameterId (int argNum, int paramId)
const Parameter * parameter (int argNo) const
size_t numParameters () const
void resizeParameters (size_t newSize)
Public Member Functions inherited from g2o::HyperGraph::Edge
Edge (int id=InvalidId)
creates and empty edge with no vertices
const VertexContainer & vertices () const
VertexContainer & vertices ()
const Vertex * vertex (size_t i) const
Vertex * vertex (size_t i)
void setVertex (size_t i, Vertex *v)
int id () const
void setId (int id)
virtual HyperGraphElementType elementType () const
int numUndefinedVertices () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Member Functions inherited from g2o::HyperGraph::DataContainer
DataContainer ()
virtual ~DataContainer ()
const Data * userData () const
the user data associated with this vertex
Data * userData ()
void setUserData (Data *obs)
void addUserData (Data *obs)
Additional Inherited Members
Public Types inherited from g2o::BaseBinaryEdge< 1, double, VertexLine2D, VertexPointXY >
typedef VertexLine2D VertexXiType
typedef VertexPointXY VertexXjType
typedef BaseEdge< D, double >::Measurement Measurement
typedef Eigen::Matrix< double, D, Di, D==1?Eigen::RowMajor:Eigen::ColMajor >::AlignedMapType JacobianXiOplusType
typedef Eigen::Matrix< double, D, Dj, D==1?Eigen::RowMajor:Eigen::ColMajor >::AlignedMapType JacobianXjOplusType
typedef BaseEdge< D, double >::ErrorVector ErrorVector
typedef BaseEdge< D, double >::InformationType InformationType
typedef Eigen::Map< Eigen::Matrix< double, Di, Dj, Di==1?Eigen::RowMajor:Eigen::ColMajor >, Eigen::Matrix< double, Di, Dj, Di==1?Eigen::RowMajor:Eigen::ColMajor >::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockType
typedef Eigen::Map< Eigen::Matrix< double, Dj, Di, Dj==1?Eigen::RowMajor:Eigen::ColMajor >, Eigen::Matrix< double, Dj, Di, Dj==1?Eigen::RowMajor:Eigen::ColMajor >::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockTransposedType
Public Types inherited from g2o::BaseEdge< D, double >
typedef double Measurement
typedef Eigen::Matrix< double, D, 1, Eigen::ColMajor > ErrorVector
typedef Eigen::Matrix< double, D, D, Eigen::ColMajor > InformationType
Static Public Attributes inherited from g2o::BaseBinaryEdge< 1, double, VertexLine2D, VertexPointXY >
static const int Di
static const int Dj
static const int Dimension
Static Public Attributes inherited from g2o::BaseEdge< D, double >
static const int Dimension
Protected Member Functions inherited from g2o::BaseEdge< D, double >
InformationType robustInformation (const Vector3D &rho)
Protected Member Functions inherited from g2o::OptimizableGraph::Edge
template<typename ParameterType >
bool installParameter (ParameterType *&p, size_t argNo, int paramId=-1)
template<typename CacheType >
void resolveCache (CacheType *&cache, OptimizableGraph::Vertex *, const std::string &_type, const ParameterVector &parameters)
bool resolveParameters ()
virtual bool resolveCaches ()
Protected Attributes inherited from g2o::BaseBinaryEdge< 1, double, VertexLine2D, VertexPointXY >
bool _hessianRowMajor
HessianBlockType _hessian
HessianBlockTransposedType _hessianTransposed
JacobianXiOplusType _jacobianOplusXi
JacobianXjOplusType _jacobianOplusXj
Protected Attributes inherited from g2o::BaseEdge< D, double >
Measurement _measurement
InformationType _information
ErrorVector _error
Protected Attributes inherited from g2o::OptimizableGraph::Edge
int _dimension
int _level
RobustKernel * _robustKernel
long long _internalId
std::vector< int > _cacheIds
std::vector< std::string > _parameterTypes
std::vector< Parameter ** > _parameters
std::vector< int > _parameterIds
Protected Attributes inherited from g2o::HyperGraph::Edge
VertexContainer _vertices
int _id
unique id
Protected Attributes inherited from g2o::HyperGraph::DataContainer
Data * _userData
Detailed Description
Definition at line 39 of file edge_line2d_pointxy.h.
Constructor & Destructor Documentation
g2o::EdgeLine2DPointXY::EdgeLine2DPointXY ()
Definition at line 43 of file edge_line2d_pointxy.cpp.
                                        :
     BaseBinaryEdge<1, double, VertexLine2D, VertexPointXY>()
   {
   }
Member Function Documentation
G2O_TYPES_SLAM2D_ADDONS_API void g2o::EdgeLine2DPointXY::computeError () inline virtual
Implements g2o::OptimizableGraph::Edge.
Definition at line 45 of file edge_line2d_pointxy.h.
References g2o::BaseEdge< D, double >::_error, g2o::BaseEdge< D, double >::_measurement, g2o::HyperGraph::Edge::_vertices, g2o::BaseVertex< D, T >::estimate(), g2o::VertexLine2D::rho(), and g2o::VertexLine2D::theta().
       {
         const VertexLine2D* l = static_cast<const VertexLine2D*>(_vertices[0]);
         const VertexPointXY* p = static_cast<const VertexPointXY*>(_vertices[1]);
         Vector2D n(cos(l->theta()), sin(l->theta()));
         double prediction=n.dot(p->estimate())-l->rho();
         _error[0] =  prediction - _measurement;
       }
virtual G2O_TYPES_SLAM2D_ADDONS_API bool g2o::EdgeLine2DPointXY::getMeasurementData (double * m) const inline virtual
writes the measurement to an array of double
Returns
true on success
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 59 of file edge_line2d_pointxy.h.
References g2o::BaseEdge< D, double >::_measurement.
{
         *d = _measurement;
         return true;
       }
virtual G2O_TYPES_SLAM2D_ADDONS_API int g2o::EdgeLine2DPointXY::measurementDimension () const inline virtual
returns the dimension of the measurement in the extended representation which is used by get/setMeasurement;
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 64 of file edge_line2d_pointxy.h.
 {return 1;}
bool g2o::EdgeLine2DPointXY::read (std::istream & is) virtual
read the vertex from a stream, i.e., the internal state of the vertex
Implements g2o::OptimizableGraph::Edge.
Definition at line 48 of file edge_line2d_pointxy.cpp.
References g2o::BaseEdge< D, double >::_measurement, and g2o::BaseEdge< D, double >::information().
Referenced by setMeasurementFromState().
   {
     is >> _measurement;
     is >> information()(0,0);
     return true;
   }
virtual G2O_TYPES_SLAM2D_ADDONS_API bool g2o::EdgeLine2DPointXY::setMeasurementData (const double * m) inline virtual
sets the measurement from an array of double
Returns
true on success
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 54 of file edge_line2d_pointxy.h.
References g2o::BaseEdge< D, double >::_measurement.
{
         _measurement = *d;
         return true;
       }
virtual G2O_TYPES_SLAM2D_ADDONS_API bool g2o::EdgeLine2DPointXY::setMeasurementFromState () inline virtual
sets the estimate to have a zero error, based on the current value of the state variables returns false if not supported.
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 66 of file edge_line2d_pointxy.h.
References g2o::BaseEdge< D, double >::_measurement, g2o::HyperGraph::Edge::_vertices, g2o::BaseVertex< D, T >::estimate(), G2O_TYPES_SLAM2D_ADDONS_API, read(), g2o::VertexLine2D::rho(), g2o::VertexLine2D::theta(), and write().
{
         const VertexLine2D* l = static_cast<const VertexLine2D*>(_vertices[0]);
         const VertexPointXY* p = static_cast<const VertexPointXY*>(_vertices[1]);
         Vector2D n(cos(l->theta()), sin(l->theta()));
         double prediction=n.dot(p->estimate())-l->rho();
         _measurement = prediction;
         return true;
       }
bool g2o::EdgeLine2DPointXY::write (std::ostream & os) const virtual
write the vertex to a stream
Implements g2o::OptimizableGraph::Edge.
Definition at line 55 of file edge_line2d_pointxy.cpp.
References g2o::BaseEdge< D, double >::information(), and g2o::BaseEdge< D, double >::measurement().
Referenced by setMeasurementFromState().
   {
     os << measurement() << " ";
     os << information()(0,0);
     return os.good();
   }
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam2d_addons/edge_line2d_pointxy.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam2d_addons/edge_line2d_pointxy.cpp