g2o: g2o::VertexPointXYWriteGnuplotAction Class Reference
g2o::VertexPointXYWriteGnuplotAction Class Reference
#include <vertex_point_xy.h>
Public Member Functions
VertexPointXYWriteGnuplotAction ()
virtual HyperGraphElementAction * operator() (HyperGraph::HyperGraphElement *element, HyperGraphElementAction::Parameters *params_)
redefine this to do the action stuff. If successful, the action returns a pointer to itself
Public Member Functions inherited from g2o::WriteGnuplotAction
WriteGnuplotAction (const std::string &typeName_)
Public Member Functions inherited from g2o::HyperGraphElementAction
HyperGraphElementAction (const std::string &typeName_="")
virtual HyperGraphElementAction * operator() (const HyperGraph::HyperGraphElement *element, Parameters *parameters)
redefine this to do the action stuff. If successful, the action returns a pointer to itself
virtual ~HyperGraphElementAction ()
destroyed actions release the memory
const std::string & typeName () const
returns the typeid name of the action
const std::string & name () const
returns the name of an action, e.g "draw"
void setTypeName (const std::string &typeName_)
sets the type on which an action has to operate
Additional Inherited Members
Public Types inherited from g2o::HyperGraphElementAction
typedef std::map< std::string, HyperGraphElementAction * > ActionMap
Protected Attributes inherited from g2o::HyperGraphElementAction
std::string _typeName
std::string _name
Detailed Description
Definition at line 88 of file vertex_point_xy.h.
Constructor & Destructor Documentation
g2o::VertexPointXYWriteGnuplotAction::VertexPointXYWriteGnuplotAction ()
Definition at line 58 of file vertex_point_xy.cpp.
 : WriteGnuplotAction(typeid(VertexPointXY).name()){}
Member Function Documentation
HyperGraphElementAction * g2o::VertexPointXYWriteGnuplotAction::operator() (HyperGraph::HyperGraphElement * element, HyperGraphElementAction::Parameters * parameters) virtual
redefine this to do the action stuff. If successful, the action returns a pointer to itself
Reimplemented from g2o::HyperGraphElementAction.
Definition at line 60 of file vertex_point_xy.cpp.
References __PRETTY_FUNCTION__, g2o::HyperGraphElementAction::_typeName, g2o::OptimizableGraph::Vertex::cacheContainer(), g2o::opengl::drawPoint(), g2o::BaseVertex< D, T >::estimate(), LANDMARK_VERTEX_COLOR, g2o::HyperGraphElementAction::name(), g2o::WriteGnuplotAction::Parameters::os, g2o::DrawAction::refreshPropertyPtrs(), and g2o::HyperGraph::DataContainer::userData().
{
     if (typeid(*element).name()!=_typeName)
       return 0;
     WriteGnuplotAction::Parameters* params=static_cast<WriteGnuplotAction::Parameters*>(params_);
     if (!params->os){
       std::cerr << __PRETTY_FUNCTION__ << ": warning, on valid os specified" << std::endl;
       return 0;
     }
     VertexPointXY* v =  static_cast<VertexPointXY*>(element);
     *(params->os) << v->estimate().x() << " " << v->estimate().y() << std::endl;
     return this;
   }
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam2d/vertex_point_xy.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam2d/vertex_point_xy.cpp