g2o: g2o::DrawAction Class Reference
g2o::DrawAction Class Reference
draw actions
#include <hyper_graph_action.h>
Classes
class Parameters
Public Member Functions
DrawAction (const std::string &typeName_)
Public Member Functions inherited from g2o::HyperGraphElementAction
HyperGraphElementAction (const std::string &typeName_="")
virtual HyperGraphElementAction * operator() (HyperGraph::HyperGraphElement *element, Parameters *parameters)
redefine this to do the action stuff. If successful, the action returns a pointer to itself
virtual HyperGraphElementAction * operator() (const HyperGraph::HyperGraphElement *element, Parameters *parameters)
redefine this to do the action stuff. If successful, the action returns a pointer to itself
virtual ~HyperGraphElementAction ()
destroyed actions release the memory
const std::string & typeName () const
returns the typeid name of the action
const std::string & name () const
returns the name of an action, e.g "draw"
void setTypeName (const std::string &typeName_)
sets the type on which an action has to operate
Protected Member Functions
virtual bool refreshPropertyPtrs (HyperGraphElementAction::Parameters *params_)
void initializeDrawActionsCache ()
void drawCache (CacheContainer *caches, HyperGraphElementAction::Parameters *params_)
void drawUserData (HyperGraph::Data *data, HyperGraphElementAction::Parameters *params_)
Protected Attributes
Parameters * _previousParams
BoolProperty * _show
BoolProperty * _showId
HyperGraphElementAction * _cacheDrawActions
Protected Attributes inherited from g2o::HyperGraphElementAction
std::string _typeName
std::string _name
Additional Inherited Members
Public Types inherited from g2o::HyperGraphElementAction
typedef std::map< std::string, HyperGraphElementAction * > ActionMap
Detailed Description
draw actions
Definition at line 180 of file hyper_graph_action.h.
Constructor & Destructor Documentation
g2o::DrawAction::DrawAction (const std::string & typeName_)
Definition at line 230 of file hyper_graph_action.cpp.
References _cacheDrawActions, g2o::HyperGraphElementAction::_name, _previousParams, and refreshPropertyPtrs().
     : HyperGraphElementAction(typeName_)
   {
     _name="draw";
     _previousParams = (Parameters*)0x42;
     refreshPropertyPtrs(0);
     _cacheDrawActions = 0;
   }
Member Function Documentation
void g2o::DrawAction::drawCache (CacheContainer * caches, HyperGraphElementAction::Parameters * params_) protected
Definition at line 261 of file hyper_graph_action.cpp.
{
     if (caches){
       for (CacheContainer::iterator it=caches->begin(); it!=caches->end(); it++){
         Cache* c = it->second;
         (*_cacheDrawActions)(c, params_);
       }
     }
   }
void g2o::DrawAction::drawUserData (HyperGraph::Data * data, HyperGraphElementAction::Parameters * params_) protected
Definition at line 270 of file hyper_graph_action.cpp.
References _cacheDrawActions.
{
     while (data && _cacheDrawActions ){
       (*_cacheDrawActions)(data, params_);
       data=data->next();
     }
   }
void g2o::DrawAction::initializeDrawActionsCache () protected
Definition at line 255 of file hyper_graph_action.cpp.
References _cacheDrawActions, g2o::HyperGraphActionLibrary::actionByName(), and g2o::HyperGraphActionLibrary::instance().
{
     if (! _cacheDrawActions){
       _cacheDrawActions = HyperGraphActionLibrary::instance()->actionByName("draw");
     }
   }
bool g2o::DrawAction::refreshPropertyPtrs (HyperGraphElementAction::Parameters * params_) protected virtual
Definition at line 239 of file hyper_graph_action.cpp.
References _previousParams, _show, _showId, g2o::HyperGraphElementAction::_typeName, and g2o::PropertyMap::makeProperty().
Referenced by DrawAction(), g2o::VertexSE2WriteGnuplotAction::operator()(), g2o::VertexPointXYWriteGnuplotAction::operator()(), g2o::VertexSegment2DWriteGnuplotAction::operator()(), g2o::EdgeSE2WriteGnuplotAction::operator()(), g2o::deprecated::VertexSE3WriteGnuplotAction::operator()(), g2o::VertexSE3WriteGnuplotAction::operator()(), g2o::RobotLaser::setOdomPose(), g2o::CacheSE3Offset::setOffsetParam(), g2o::deprecated::CacheSE3Offset::setOffsetParam(), g2o::VertexPointXYZ::write(), g2o::VertexPlane::write(), g2o::deprecated::VertexPointXYZ::write(), g2o::VertexEllipse::write(), g2o::VertexTag::write(), g2o::EdgeSE3PlaneSensorCalib::write(), and g2o::VertexLine2D::write().
{
     if (_previousParams == params_)
       return false;
     DrawAction::Parameters* p=dynamic_cast<DrawAction::Parameters*>(params_);
     if (! p){
       _previousParams = 0;
       _show = 0;
       _showId = 0;
     } else {
       _previousParams = p;
       _show = p->makeProperty<BoolProperty>(_typeName+"::SHOW", true);
       _showId = p->makeProperty<BoolProperty>(_typeName+"::SHOW_ID", false);
     }
     return true;
   }
Member Data Documentation
HyperGraphElementAction* g2o::DrawAction::_cacheDrawActions protected
Definition at line 195 of file hyper_graph_action.h.
Referenced by DrawAction(), drawUserData(), and initializeDrawActionsCache().
Parameters* g2o::DrawAction::_previousParams protected
Definition at line 192 of file hyper_graph_action.h.
Referenced by DrawAction(), and refreshPropertyPtrs().
BoolProperty* g2o::DrawAction::_show protected
Definition at line 193 of file hyper_graph_action.h.
Referenced by refreshPropertyPtrs().
BoolProperty* g2o::DrawAction::_showId protected
Definition at line 194 of file hyper_graph_action.h.
Referenced by refreshPropertyPtrs().
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/core/hyper_graph_action.h
/home/xuezhisd/CLionProjects/g2o/g2o/core/hyper_graph_action.cpp