g2o: g2o::EdgeSE3LotsOfXYZ Class Reference
g2o::EdgeSE3LotsOfXYZ Class Reference
#include <edge_se3_lotsofxyz.h>
Public Member Functions
EdgeSE3LotsOfXYZ ()
void setDimension (int dimension_)
void setSize (int vertices)
virtual void computeError ()
virtual bool read (std::istream &is)
read the vertex from a stream, i.e., the internal state of the vertex
virtual bool write (std::ostream &os) const
write the vertex to a stream
virtual bool setMeasurementFromState ()
virtual void initialEstimate (const OptimizableGraph::VertexSet &, OptimizableGraph::Vertex *)
virtual double initialEstimatePossible (const OptimizableGraph::VertexSet &, OptimizableGraph::Vertex *)
virtual void linearizeOplus ()
Public Member Functions inherited from g2o::BaseMultiEdge<-1, VectorXD >
BaseMultiEdge ()
virtual void linearizeOplus (JacobianWorkspace &jacobianWorkspace)
virtual void resize (size_t size)
virtual bool allVerticesFixed () const
virtual void constructQuadraticForm ()
virtual void mapHessianMemory (double *d, int i, int j, bool rowMajor)
Public Member Functions inherited from g2o::BaseEdge< D, VectorXD >
BaseEdge ()
virtual ~BaseEdge ()
virtual double chi2 () const
computes the chi2 based on the cached error value, only valid after computeError has been called.
virtual const double * errorData () const
returns the error vector cached after calling the computeError;
virtual double * errorData ()
const ErrorVector & error () const
ErrorVector & error ()
EIGEN_STRONG_INLINE const InformationType & information () const
information matrix of the constraint
EIGEN_STRONG_INLINE InformationType & information ()
EIGEN_STRONG_INLINE void setInformation (const InformationType &information)
virtual const double * informationData () const
returns the memory of the information matrix, usable for example with a Eigen::Map<MatrixXD>
virtual double * informationData ()
EIGEN_STRONG_INLINE const Measurement & measurement () const
accessor functions for the measurement represented by the edge
virtual void setMeasurement (const Measurement &m)
virtual int rank () const
Public Member Functions inherited from g2o::OptimizableGraph::Edge
Edge ()
virtual ~Edge ()
virtual Edge * clone () const
virtual bool setMeasurementData (const double *m)
virtual bool getMeasurementData (double *m) const
virtual int measurementDimension () const
RobustKernel * robustKernel () const
if NOT NULL, error of this edge will be robustifed with the kernel
void setRobustKernel (RobustKernel *ptr)
int level () const
returns the level of the edge
void setLevel (int l)
sets the level of the edge
int dimension () const
returns the dimensions of the error function
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createFrom())
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createTo())
virtual Vertex * createVertex (int)
long long internalId () const
the internal ID of the edge
OptimizableGraph * graph ()
const OptimizableGraph * graph () const
bool setParameterId (int argNum, int paramId)
const Parameter * parameter (int argNo) const
size_t numParameters () const
void resizeParameters (size_t newSize)
Public Member Functions inherited from g2o::HyperGraph::Edge
Edge (int id=InvalidId)
creates and empty edge with no vertices
const VertexContainer & vertices () const
VertexContainer & vertices ()
const Vertex * vertex (size_t i) const
Vertex * vertex (size_t i)
void setVertex (size_t i, Vertex *v)
int id () const
void setId (int id)
virtual HyperGraphElementType elementType () const
int numUndefinedVertices () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Member Functions inherited from g2o::HyperGraph::DataContainer
DataContainer ()
virtual ~DataContainer ()
const Data * userData () const
the user data associated with this vertex
Data * userData ()
void setUserData (Data *obs)
void addUserData (Data *obs)
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Attributes
unsigned int _observedPoints
Protected Attributes inherited from g2o::BaseMultiEdge<-1, VectorXD >
std::vector< HessianHelper > _hessian
std::vector< JacobianType, Eigen::aligned_allocator< JacobianType > > _jacobianOplus
jacobians of the edge (w.r.t. oplus)
Protected Attributes inherited from g2o::BaseEdge< D, VectorXD >
Measurement _measurement
InformationType _information
ErrorVector _error
Protected Attributes inherited from g2o::OptimizableGraph::Edge
int _dimension
int _level
RobustKernel * _robustKernel
long long _internalId
std::vector< int > _cacheIds
std::vector< std::string > _parameterTypes
std::vector< Parameter ** > _parameters
std::vector< int > _parameterIds
Protected Attributes inherited from g2o::HyperGraph::Edge
VertexContainer _vertices
int _id
unique id
Protected Attributes inherited from g2o::HyperGraph::DataContainer
Data * _userData
Additional Inherited Members
Public Types inherited from g2o::BaseMultiEdge<-1, VectorXD >
typedef BaseEdge< D, VectorXD >::Measurement Measurement
typedef MatrixXD::MapType JacobianType
typedef BaseEdge< D, VectorXD >::ErrorVector ErrorVector
typedef BaseEdge< D, VectorXD >::InformationType InformationType
typedef Eigen::Map< MatrixXD, MatrixXD::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockType
Public Types inherited from g2o::BaseEdge< D, VectorXD >
typedef VectorXD Measurement
typedef Eigen::Matrix< double, D, 1, Eigen::ColMajor > ErrorVector
typedef Eigen::Matrix< double, D, D, Eigen::ColMajor > InformationType
Static Public Attributes inherited from g2o::BaseMultiEdge<-1, VectorXD >
static const int Dimension
Static Public Attributes inherited from g2o::BaseEdge< D, VectorXD >
static const int Dimension
Protected Member Functions inherited from g2o::BaseMultiEdge<-1, VectorXD >
void computeQuadraticForm (const InformationType &omega, const ErrorVector &weightedError)
Protected Member Functions inherited from g2o::BaseEdge< D, VectorXD >
InformationType robustInformation (const Vector3D &rho)
Protected Member Functions inherited from g2o::OptimizableGraph::Edge
template<typename ParameterType >
bool installParameter (ParameterType *&p, size_t argNo, int paramId=-1)
template<typename CacheType >
void resolveCache (CacheType *&cache, OptimizableGraph::Vertex *, const std::string &_type, const ParameterVector &parameters)
bool resolveParameters ()
virtual bool resolveCaches ()
Detailed Description
Definition at line 12 of file edge_se3_lotsofxyz.h.
Constructor & Destructor Documentation
g2o::EdgeSE3LotsOfXYZ::EdgeSE3LotsOfXYZ ()
Definition at line 5 of file edge_se3_lotsofxyz.cpp.
References g2o::BaseMultiEdge<-1, VectorXD >::resize().
{
     resize(0);
   }
Member Function Documentation
void g2o::EdgeSE3LotsOfXYZ::computeError () virtual
Implements g2o::OptimizableGraph::Edge.
Definition at line 27 of file edge_se3_lotsofxyz.cpp.
References g2o::BaseEdge< D, VectorXD >::_error, g2o::BaseEdge< D, VectorXD >::_measurement, _observedPoints, g2o::HyperGraph::Edge::_vertices, and g2o::BaseVertex< D, T >::estimate().
{
     VertexSE3 * pose = static_cast<VertexSE3 *> (_vertices[0]);
     for(unsigned int i=0; i<_observedPoints; i++){
       VertexPointXYZ * xyz = static_cast<VertexPointXYZ *> (_vertices[1+i]);
       Vector3D m = pose->estimate().inverse() * xyz->estimate();
       unsigned int index = 3*i;
       _error[index] = m[0] - _measurement[index];
       _error[index+1] = m[1] - _measurement[index+1];
       _error[index+2] = m[2] - _measurement[index+2];
     }
   }
void g2o::EdgeSE3LotsOfXYZ::initialEstimate (const OptimizableGraph::VertexSet & , OptimizableGraph::Vertex *) virtual
set the estimate of the to vertex, based on the estimate of the from vertices in the edge.
Reimplemented from g2o::BaseEdge< D, VectorXD >.
Definition at line 135 of file edge_se3_lotsofxyz.cpp.
References g2o::BaseEdge< D, VectorXD >::_measurement, _observedPoints, g2o::HyperGraph::Edge::_vertices, g2o::BaseVertex< D, T >::estimate(), g2o::HyperGraph::Vertex::id(), initialEstimatePossible(), and g2o::BaseVertex< D, T >::setEstimate().
{
     (void) toEstimate;
     assert(initialEstimatePossible(fixed, toEstimate) && "Bad vertices specified");
     VertexSE3 * pose = static_cast<VertexSE3 *>(_vertices[0]);
 #ifdef _MSC_VER
         std::vector<bool> estimate_this(_observedPoints, true);
 #else
     bool estimate_this[_observedPoints];
     for(unsigned int i=0; i<_observedPoints; i++){
       estimate_this[i] = true;
     }
 #endif
     for(std::set<HyperGraph::Vertex*>::iterator it=fixed.begin(); it!=fixed.end(); it++){
       for(unsigned int i=1; i<_vertices.size(); i++){
         VertexPointXYZ * vert = static_cast<VertexPointXYZ *>(_vertices[i]);
         if(vert->id() == (*it)->id()) estimate_this[i-1] = false;
       }
     }
     for(unsigned int i=1; i<_vertices.size(); i++){
       if(estimate_this[i-1]){
         unsigned int index = 3*(i-1);
         Vector3D submeas(_measurement[index], _measurement[index+1], _measurement[index+2]);
         VertexPointXYZ * vert = static_cast<VertexPointXYZ *>(_vertices[i]);
         vert->setEstimate(pose->estimate() * submeas);
       }
     }
   }
double g2o::EdgeSE3LotsOfXYZ::initialEstimatePossible (const OptimizableGraph::VertexSet & from, OptimizableGraph::Vertex * to) virtual
override in your class if it's possible to initialize the vertices in certain combinations. The return value may correspond to the cost for initiliaizng the vertex but should be positive if the initialization is possible and negative if not possible.
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 170 of file edge_se3_lotsofxyz.cpp.
References g2o::HyperGraph::Edge::_vertices.
Referenced by initialEstimate().
{
     (void) toEstimate;
     for(std::set<HyperGraph::Vertex *>::iterator it=fixed.begin(); it!=fixed.end(); it++){
       if(_vertices[0]->id() == (*it)->id()){
         return 1.0;
       }
     }
     return -1.0;
   }
void g2o::EdgeSE3LotsOfXYZ::linearizeOplus () virtual
Linearizes the oplus operator in the vertex, and stores the result in temporary variable vector _jacobianOplus
Reimplemented from g2o::BaseMultiEdge<-1, VectorXD >.
Definition at line 41 of file edge_se3_lotsofxyz.cpp.
References g2o::BaseMultiEdge<-1, VectorXD >::_jacobianOplus, g2o::HyperGraph::Edge::_vertices, and g2o::BaseVertex< D, T >::estimate().
{
     g2o::VertexSE3 * pose = (g2o::VertexSE3 *) (_vertices[0]);
     // initialize Ji matrix
     MatrixXD Ji;
     unsigned int rows = 3*(_vertices.size()-1);
     Ji.resize(rows, 6);
     Ji.fill(0);
     Matrix3D poseRot = pose->estimate().inverse().rotation();
     for(unsigned int i=1; i<_vertices.size(); i++){
       g2o::VertexPointXYZ * point = (g2o::VertexPointXYZ *) (_vertices[i]);
       Vector3D Zcam = pose->estimate().inverse() * point->estimate();
       unsigned int index=3*(i-1);
       // Ji.block<3,3>(index,0) = -poseRot;
       Ji.block<3,3>(index,0) = -Matrix3D::Identity();
       Ji(index, 3) = -0.0;
       Ji(index, 4) = -2*Zcam(2);
       Ji(index, 5) = 2*Zcam(1);
       Ji(index+1, 3) = 2*Zcam(2);
       Ji(index+1, 4) = -0.0;
       Ji(index+1, 5) = -2*Zcam(0);
       Ji(index+2, 3) = -2*Zcam(1);
       Ji(index+2, 4) = 2*Zcam(0);
       Ji(index+2, 5) = -0.0;
       MatrixXD Jj;
       Jj.resize(rows, 3);
       Jj.fill(0);
       Jj.block<3,3>(index,0) = poseRot;
       _jacobianOplus[i] = Jj;
     }
     _jacobianOplus[0] = Ji;
   }
bool g2o::EdgeSE3LotsOfXYZ::read (std::istream & is) virtual
read the vertex from a stream, i.e., the internal state of the vertex
Implements g2o::OptimizableGraph::Edge.
Definition at line 85 of file edge_se3_lotsofxyz.cpp.
References g2o::BaseEdge< D, VectorXD >::_measurement, _observedPoints, g2o::BaseEdge< D, VectorXD >::information(), and setSize().
{
     is >> _observedPoints;
     setSize(_observedPoints + 1);
     // read the measurements
     for(unsigned int i=0; i<_observedPoints; i++){
       unsigned int index = 3*i;
       is >> _measurement[index] >> _measurement[index+1] >> _measurement[index+2];
     }
     // read the information matrix
     for(unsigned int i=0; i<_observedPoints*3; i++){
       // fill the "upper triangle" part of the matrix
       for(unsigned int j=i; j<_observedPoints*3; j++){
         is >> information()(i,j);
       }
       // fill the lower triangle part
       for(unsigned int j=0; j<i; j++){
         information()(i,j) = information()(j,i);
       }
     }
     return true;
   }
void g2o::EdgeSE3LotsOfXYZ::setDimension (int dimension_) inline
Definition at line 21 of file edge_se3_lotsofxyz.h.
{
         _dimension = dimension_;
         _information.resize(dimension_, dimension_);
         _error.resize(dimension_, 1);
         _measurement.resize(dimension_, 1);
       }
bool g2o::EdgeSE3LotsOfXYZ::setMeasurementFromState () virtual
sets the estimate to have a zero error, based on the current value of the state variables returns false if not supported.
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 9 of file edge_se3_lotsofxyz.cpp.
References g2o::BaseEdge< D, VectorXD >::_measurement, _observedPoints, g2o::HyperGraph::Edge::_vertices, and g2o::BaseVertex< D, T >::estimate().
{
     VertexSE3 * pose = static_cast<VertexSE3 *> (_vertices[0]);
     Eigen::Transform<double, 3, 1> poseinv = pose->estimate().inverse();
     for(unsigned int i=0; i<_observedPoints; i++){
       VertexPointXYZ * xyz = static_cast<VertexPointXYZ *> (_vertices[1+i]);
       //      const Vector3D &pt = xyz->estimate();
       Vector3D m = poseinv * xyz->estimate();
       unsigned int index = 3*i;
       _measurement[index] = m[0];
       _measurement[index+1] = m[1];
       _measurement[index+2] = m[2];
     }
     return true;
   }
void g2o::EdgeSE3LotsOfXYZ::setSize (int vertices) inline
Definition at line 28 of file edge_se3_lotsofxyz.h.
Referenced by read().
{
         resize(vertices);
         _observedPoints = vertices-1;
         setDimension(_observedPoints*3);
       }
bool g2o::EdgeSE3LotsOfXYZ::write (std::ostream & os) const virtual
write the vertex to a stream
Implements g2o::OptimizableGraph::Edge.
Definition at line 114 of file edge_se3_lotsofxyz.cpp.
References g2o::BaseEdge< D, VectorXD >::_measurement, _observedPoints, and g2o::BaseEdge< D, VectorXD >::information().
{
     // write number of observed points
     os << "|| " << _observedPoints;
     // write measurements
     for(unsigned int i=0; i<_observedPoints; i++){
       unsigned int index = 3*i;
       os << " " << _measurement[index] << " " << _measurement[index+1] << " " << _measurement[index+2];
     }
     // write information matrix
     for(unsigned int i=0; i<_observedPoints*3; i++){
       for(unsigned int j=i; j<_observedPoints*3; j++){
         os << " " << information()(i,j);
       }
     }
     return os.good();
   }
Member Data Documentation
unsigned int g2o::EdgeSE3LotsOfXYZ::_observedPoints protected
Definition at line 15 of file edge_se3_lotsofxyz.h.
Referenced by computeError(), initialEstimate(), read(), setMeasurementFromState(), and write().
g2o::EdgeSE3LotsOfXYZ::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 18 of file edge_se3_lotsofxyz.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam3d/edge_se3_lotsofxyz.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/slam3d/edge_se3_lotsofxyz.cpp