g2o: g2o::tutorial::CacheSE2Offset Class Reference
g2o::tutorial::CacheSE2Offset Class Reference
#include <parameter_se2_offset.h>
Public Member Functions
const SE2 & w2n () const
const SE2 & n2w () const
Public Member Functions inherited from g2o::Cache
Cache (CacheContainer *container_=0, const ParameterVector &parameters_=ParameterVector())
CacheKey key () const
OptimizableGraph::Vertex * vertex ()
OptimizableGraph * graph ()
CacheContainer * container ()
ParameterVector & parameters ()
void update ()
virtual HyperGraph::HyperGraphElementType elementType () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Member Functions
virtual void updateImpl ()
redefine this to do the update
virtual bool resolveDependancies ()
Protected Member Functions inherited from g2o::Cache
Cache * installDependency (const std::string &type_, const std::vector< int > &parameterIndices)
Protected Attributes
ParameterSE2Offset * _offsetParam
SE2 _w2n
SE2 _n2w
Protected Attributes inherited from g2o::Cache
bool _updateNeeded
ParameterVector _parameters
std::vector< Cache * > _parentCaches
CacheContainer * _container
Detailed Description
Definition at line 56 of file parameter_se2_offset.h.
Member Function Documentation
const SE2& g2o::tutorial::CacheSE2Offset::n2w () const inline
Definition at line 62 of file parameter_se2_offset.h.
 { return _n2w;}
bool g2o::tutorial::CacheSE2Offset::resolveDependancies () protected virtual
Function to be called from a cache that has dependencies. It just invokes a sequence of installDependency(). Although the caches returned are stored in the _parentCache vector, it is better that you redefine your own cache member variables, for better readability
Reimplemented from g2o::Cache.
Definition at line 65 of file parameter_se2_offset.cpp.
     {
       _offsetParam = dynamic_cast<ParameterSE2Offset*> (_parameters[0]);
       return _offsetParam != 0;
     }
void g2o::tutorial::CacheSE2Offset::updateImpl () protected virtual
redefine this to do the update
Implements g2o::Cache.
Definition at line 58 of file parameter_se2_offset.cpp.
References g2o::BaseVertex< D, T >::estimate(), and g2o::SE2::inverse().
     {
       const VertexSE2* v = static_cast<const VertexSE2*>(vertex());
       _n2w = v->estimate() * _offsetParam->offset();
       _w2n = _n2w.inverse();
     }
const SE2& g2o::tutorial::CacheSE2Offset::w2n () const inline
Definition at line 61 of file parameter_se2_offset.h.
Referenced by g2o::tutorial::EdgeSE2PointXY::computeError().
 { return _w2n;}
Member Data Documentation
SE2 g2o::tutorial::CacheSE2Offset::_n2w protected
Definition at line 69 of file parameter_se2_offset.h.
ParameterSE2Offset* g2o::tutorial::CacheSE2Offset::_offsetParam protected
Definition at line 68 of file parameter_se2_offset.h.
SE2 g2o::tutorial::CacheSE2Offset::_w2n protected
Definition at line 69 of file parameter_se2_offset.h.
g2o::tutorial::CacheSE2Offset::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 59 of file parameter_se2_offset.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/examples/tutorial_slam2d/parameter_se2_offset.h
/home/xuezhisd/CLionProjects/g2o/g2o/examples/tutorial_slam2d/parameter_se2_offset.cpp