g2o: g2o::deprecated::EdgeSE3WriteGnuplotAction Class Reference
g2o::deprecated::EdgeSE3WriteGnuplotAction Class Reference
#include <edge_se3_quat.h>
Public Member Functions
EdgeSE3WriteGnuplotAction ()
virtual HyperGraphElementAction * operator() (HyperGraph::HyperGraphElement *element, HyperGraphElementAction::Parameters *params_)
redefine this to do the action stuff. If successful, the action returns a pointer to itself
Public Member Functions inherited from g2o::WriteGnuplotAction
WriteGnuplotAction (const std::string &typeName_)
Public Member Functions inherited from g2o::HyperGraphElementAction
HyperGraphElementAction (const std::string &typeName_="")
virtual HyperGraphElementAction * operator() (const HyperGraph::HyperGraphElement *element, Parameters *parameters)
redefine this to do the action stuff. If successful, the action returns a pointer to itself
virtual ~HyperGraphElementAction ()
destroyed actions release the memory
const std::string & typeName () const
returns the typeid name of the action
const std::string & name () const
returns the name of an action, e.g "draw"
void setTypeName (const std::string &typeName_)
sets the type on which an action has to operate
Additional Inherited Members
Public Types inherited from g2o::HyperGraphElementAction
typedef std::map< std::string, HyperGraphElementAction * > ActionMap
Protected Attributes inherited from g2o::HyperGraphElementAction
std::string _typeName
std::string _name
Detailed Description
Definition at line 101 of file edge_se3_quat.h.
Constructor & Destructor Documentation
g2o::deprecated::EdgeSE3WriteGnuplotAction::EdgeSE3WriteGnuplotAction ()
Definition at line 119 of file edge_se3_quat.cpp.
 : WriteGnuplotAction(typeid(EdgeSE3).name()){}
Member Function Documentation
HyperGraphElementAction * g2o::deprecated::EdgeSE3WriteGnuplotAction::operator() (HyperGraph::HyperGraphElement * element, HyperGraphElementAction::Parameters * parameters) virtual
redefine this to do the action stuff. If successful, the action returns a pointer to itself
Reimplemented from g2o::HyperGraphElementAction.
Definition at line 121 of file edge_se3_quat.cpp.
References __PRETTY_FUNCTION__, g2o::HyperGraphElementAction::_typeName, g2o::BaseVertex< D, T >::estimate(), g2o::HyperGraphElementAction::name(), g2o::WriteGnuplotAction::Parameters::os, g2o::SE3Quat::rotation(), g2o::SE3Quat::translation(), and g2o::HyperGraph::Edge::vertex().
{
     if (typeid(*element).name()!=_typeName)
       return 0;
     WriteGnuplotAction::Parameters* params=static_cast<WriteGnuplotAction::Parameters*>(params_);
     if (!params->os){
       std::cerr << __PRETTY_FUNCTION__ << ": warning, on valid os specified" << std::endl;
       return 0;
     }
     EdgeSE3* e =  static_cast<EdgeSE3*>(element);
     VertexSE3* fromEdge = static_cast<VertexSE3*>(e->vertex(0));
     VertexSE3* toEdge   = static_cast<VertexSE3*>(e->vertex(1));
     *(params->os) << fromEdge->estimate().translation().x() << " "
       << fromEdge->estimate().translation().y() << " "
       << fromEdge->estimate().translation().z() << " ";
     *(params->os) << fromEdge->estimate().rotation().x() << " "
       << fromEdge->estimate().rotation().y() << " "
       << fromEdge->estimate().rotation().z() << " " << std::endl;
     *(params->os) << toEdge->estimate().translation().x() << " "
       << toEdge->estimate().translation().y() << " "
       << toEdge->estimate().translation().z() << " ";
     *(params->os) << toEdge->estimate().rotation().x() << " "
       << toEdge->estimate().rotation().y() << " "
       << toEdge->estimate().rotation().z() << " " << std::endl;
     *(params->os) << std::endl;
     return this;
   }
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/deprecated/slam3d/edge_se3_quat.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/deprecated/slam3d/edge_se3_quat.cpp