g2o: g2o::HyperGraph::DataContainer Class Reference
g2o::HyperGraph::DataContainer Class Reference
Container class that implements an interface for adding/removing Data elements in a linked list.
#include <hyper_graph.h>
Public Member Functions
DataContainer ()
virtual ~DataContainer ()
const Data * userData () const
the user data associated with this vertex
Data * userData ()
void setUserData (Data *obs)
void addUserData (Data *obs)
Protected Attributes
Data * _userData
Detailed Description
Container class that implements an interface for adding/removing Data elements in a linked list.
Definition at line 121 of file hyper_graph.h.
Constructor & Destructor Documentation
g2o::HyperGraph::DataContainer::DataContainer () inline
Definition at line 123 of file hyper_graph.h.
 {_userData = 0;}
virtual g2o::HyperGraph::DataContainer::~DataContainer () inline virtual
Definition at line 124 of file hyper_graph.h.
 { delete _userData;}
Member Function Documentation
void g2o::HyperGraph::DataContainer::addUserData (Data * obs) inline
Definition at line 129 of file hyper_graph.h.
References g2o::HyperGraph::Data::setNext().
 { if (obs) { obs->setNext(_userData); _userData=obs; } }
void g2o::HyperGraph::DataContainer::setUserData (Data * obs) inline
Definition at line 128 of file hyper_graph.h.
Referenced by g2o::OptimizableGraph::addVertex(), g2o::Gm2dlIO::readGm2dl(), and g2o::OptimizableGraph::setFixed().
 { _userData = obs;}
const Data* g2o::HyperGraph::DataContainer::userData () const inline
the user data associated with this vertex
Definition at line 126 of file hyper_graph.h.
Referenced by g2o::addOdometryCalibLinksDifferential(), g2o::VertexPointXYWriteGnuplotAction::operator()(), g2o::VertexSE2WriteGnuplotAction::operator()(), g2o::deprecated::VertexSE3WriteGnuplotAction::operator()(), g2o::VertexSE3WriteGnuplotAction::operator()(), g2o::OptimizableGraph::saveEdge(), g2o::OptimizableGraph::saveVertex(), g2o::Gm2dlIO::updateLaserData(), g2o::VertexPointXYZ::write(), and g2o::Gm2dlIO::writeGm2dl().
 { return _userData; }
Data* g2o::HyperGraph::DataContainer::userData () inline
Definition at line 127 of file hyper_graph.h.
 { return _userData; }
Member Data Documentation
Data* g2o::HyperGraph::DataContainer::_userData protected
Definition at line 131 of file hyper_graph.h.
The documentation for this class was generated from the following file:
/home/xuezhisd/CLionProjects/g2o/g2o/core/hyper_graph.h