g2o: MainWindow Class Reference
MainWindow Class Reference
main window of the g2o viewer
#include <main_window.h>
Public Slots
void on_actionLoad_triggered (bool)
void on_actionSave_triggered (bool)
void on_actionQuit_triggered (bool)
void on_actionWhite_Background_triggered (bool)
void on_actionDefault_Background_triggered (bool)
void on_actionProperties_triggered (bool)
void on_actionSave_Screenshot_triggered (bool)
void on_actionLoad_Viewer_State_triggered (bool)
void on_actionSave_Viewer_State_triggered (bool)
void on_btnOptimize_clicked ()
void on_btnInitialGuess_clicked ()
void on_btnSetZero_clicked ()
void on_btnForceStop_clicked ()
void on_btnOptimizerParamaters_clicked ()
void on_actionLoad_triggered (bool)
void on_actionSave_triggered (bool)
void on_actionQuit_triggered (bool)
void on_btnOptimize_clicked ()
void on_btnInitialGuess_clicked ()
Public Member Functions
MainWindow (QWidget *parent=0, Qt::WindowFlags flags=0)
~MainWindow ()
void updateDisplayedSolvers ()
void updateRobustKernels ()
bool loadFromFile (const QString &filename)
MainWindow (QWidget *parent=0, Qt::WindowFlags flags=0)
~MainWindow ()
Public Attributes
g2o::OptimizationAlgorithm * solverGaussNewton
g2o::OptimizationAlgorithm * solverLevenberg
Protected Member Functions
void fixGraph ()
bool allocateSolver (bool &allocatedNewSolver)
bool prepare ()
void setRobustKernel ()
bool load (const QString &filename)
void fixGraph ()
Protected Attributes
std::vector< g2o::OptimizationAlgorithmProperty > _knownSolvers
int _lastSolver
bool _forceStopFlag
g2o::OptimizationAlgorithmProperty _currentOptimizationAlgorithmProperty
g2o::OptimizationAlgorithm * _currentSolver
ViewerPropertiesWidget * _viewerPropertiesWidget
PropertiesWidget * _optimizerPropertiesWidget
Detailed Description
main window of the g2o viewer
Definition at line 40 of file main_window.h.
Constructor & Destructor Documentation
MainWindow::MainWindow (QWidget * parent = 0, Qt::WindowFlags flags = 0)
Definition at line 41 of file main_window.cpp.
                                                             :
   QMainWindow(parent, flags),
   _lastSolver(-1), _currentSolver(0), _viewerPropertiesWidget(0), _optimizerPropertiesWidget(0)
 {
   setupUi(this);
   leKernelWidth->setValidator(new QDoubleValidator(-numeric_limits<double>::max(), numeric_limits<double>::max(), 7, this));
   plainTextEdit->setMaximumBlockCount(1000);
   btnForceStop->hide();
   QObject::connect(cbDrawAxis, SIGNAL(toggled(bool)), viewer, SLOT(setAxisIsDrawn(bool)));
 }
MainWindow::~MainWindow ()
Definition at line 52 of file main_window.cpp.
 {
 }
MainWindow::MainWindow (QWidget * parent = 0, Qt::WindowFlags flags = 0)
MainWindow::~MainWindow ()
Member Function Documentation
bool MainWindow::allocateSolver (bool & allocatedNewSolver) protected
Definition at line 255 of file main_window.cpp.
References _currentOptimizationAlgorithmProperty, _currentSolver, _lastSolver, and g2o::OptimizationAlgorithmFactory::construct().
Referenced by on_btnOptimize_clicked(), and on_btnOptimizerParamaters_clicked().
 {
   if (coOptimizer->count() == 0) {
     cerr << "No solvers available" << endl;
     return false;
   }
   int currentIndex = coOptimizer->currentIndex();
   bool enabled = qobject_cast<QStandardItemModel *>(coOptimizer->model())->item(currentIndex)->isEnabled();
   if (! enabled) {
     cerr << "selected solver is not enabled" << endl;
     return false;
   }
   if (currentIndex == _lastSolver)
     return true;
   allocatedNewSolver = true;
   QString strSolver = coOptimizer->currentText();
   // delete the old optimization algorithm
   OptimizationAlgorithm* algorithmPointer = const_cast<OptimizationAlgorithm*>(viewer->graph->algorithm());
   viewer->graph->setAlgorithm(0);
   delete algorithmPointer;
   // create the new algorithm
   OptimizationAlgorithmFactory* solverFactory = OptimizationAlgorithmFactory::instance();
   _currentSolver = solverFactory->construct(strSolver.toStdString(), _currentOptimizationAlgorithmProperty);
   viewer->graph->setAlgorithm(_currentSolver);
   _lastSolver = currentIndex;
   return true;
 }
void MainWindow::fixGraph () protected
void MainWindow::fixGraph () protected
Definition at line 150 of file main_window.cpp.
References g2o::OptimizableGraph::Vertex::graph(), g2o::HyperGraph::Vertex::id(), and g2o::OptimizableGraph::Vertex::setFixed().
Referenced by loadFromFile().
 {
   if (viewer->graph->vertices().size() == 0 || viewer->graph->edges().size() == 0) {
     return;
   }
   // check for vertices to fix to remove DoF
   bool gaugeFreedom = viewer->graph->gaugeFreedom();
   g2o::OptimizableGraph::Vertex* gauge = viewer->graph->findGauge();
   if (gaugeFreedom) {
     if (! gauge) {
       cerr <<  "cannot find a vertex to fix in this thing" << endl;
       return;
     } else {
       cerr << "graph is fixed by node " << gauge->id() << endl;
       gauge->setFixed(true);
     }
   } else {
     cerr << "graph is fixed by priors or nodes are already fixed" << endl;
   }
   viewer->graph->setVerbose(true);
   //viewer->graph->computeActiveErrors();
 }
bool MainWindow::load (const QString & filename) protected
Definition at line 229 of file main_window.cpp.
References _knownSolvers, _lastSolver, g2o::OptimizationAlgorithmProperty::desc, g2o::OptimizableGraph::dimensions(), g2o::OptimizableGraph::isSolverSuitable(), and g2o::OptimizationAlgorithmProperty::name.
Referenced by loadFromFile().
 {
   ifstream ifs(filename.toStdString().c_str());
   if (! ifs)
     return false;
   viewer->graph->clear();
   bool loadStatus = viewer->graph->load(ifs);
   if (! loadStatus)
     return false;
   _lastSolver = -1;
   viewer->setUpdateDisplay(true);
   SparseOptimizer* optimizer = viewer->graph;
   // update the solvers which are suitable for this graph
   set<int> vertDims = optimizer->dimensions();
   for (size_t i = 0; i < _knownSolvers.size(); ++i) {
     const OptimizationAlgorithmProperty& sp = _knownSolvers[i];
     if (sp.name == "" && sp.desc == "")
       continue;
     bool suitableSolver = optimizer->isSolverSuitable(sp, vertDims);
     qobject_cast<QStandardItemModel *>(coOptimizer->model())->item(i)->setEnabled(suitableSolver);
   }
   return loadStatus;
 }
bool MainWindow::loadFromFile (const QString & filename)
load a graph on which we will operate from a file
Definition at line 352 of file main_window.cpp.
References fixGraph(), and load().
Referenced by on_actionLoad_triggered(), and g2o::RunG2OViewer::run().
 {
   viewer->graph->clear();
   bool loadStatus = load(filename);
   cerr << "loaded " << filename.toStdString() << " with " << viewer->graph->vertices().size()
     << " vertices and " << viewer->graph->edges().size() << " measurements" << endl;
   viewer->updateGL();
   fixGraph();
   return loadStatus;
 }
void MainWindow::on_actionDefault_Background_triggered (bool) slot
Definition at line 369 of file main_window.cpp.
 {
   viewer->setBackgroundColor(QColor::fromRgb(51, 51, 51));
   viewer->updateGL();
 }
void MainWindow::on_actionLoad_triggered (bool) slot
void MainWindow::on_actionLoad_triggered (bool) slot
Definition at line 56 of file main_window.cpp.
References loadFromFile().
 {
   QString filename = QFileDialog::getOpenFileName(this, "Load g2o file", "", "g2o files (*.g2o);;All Files (*)");
   if (! filename.isNull()) {
     loadFromFile(filename);
   }
 }
void MainWindow::on_actionLoad_Viewer_State_triggered (bool) slot
Definition at line 430 of file main_window.cpp.
 {
   QString filename = QFileDialog::getOpenFileName(this, "Load State", "camera.xml", "Camera/State file (*.xml)");
   if (!filename.isEmpty()) {
     viewer->setStateFileName(filename);
     viewer->restoreStateFromFile();
     viewer->setStateFileName(QString::null);
     viewer->updateGL();
     cerr << "Loaded state from " << filename.toStdString() << endl;
   }
 }
void MainWindow::on_actionProperties_triggered (bool) slot
Definition at line 375 of file main_window.cpp.
References _viewerPropertiesWidget, and ViewerPropertiesWidget::setViewer().
 {
   if (! _viewerPropertiesWidget) {
     _viewerPropertiesWidget = new ViewerPropertiesWidget(this);
     _viewerPropertiesWidget->setWindowTitle(tr("Drawing Options"));
   }
   _viewerPropertiesWidget->setViewer(viewer);
   _viewerPropertiesWidget->show();
 }
void MainWindow::on_actionQuit_triggered (bool) slot
void MainWindow::on_actionQuit_triggered (bool) slot
Definition at line 175 of file main_window.cpp.
 {
   close();
 }
void MainWindow::on_actionSave_Screenshot_triggered (bool) slot
Definition at line 407 of file main_window.cpp.
 {
   QString selectedFilter;
   QString filename = QFileDialog::getSaveFileName(this, "Save screen to a file", "viewer.png",
       "PNG files (*.png);;JPG files (*.jpg);;EPS files (*.eps)", &selectedFilter);
   if (! filename.isNull()) {
     // extract the file format from the filter options
     int spacePos = selectedFilter.indexOf(' ');
     assert(spacePos > 0 && "extracting the image format failed");
     QString format = selectedFilter.left(spacePos);
     // setting up the snapshot and save to file
     if (format == "JPG") {
       viewer->setSnapshotQuality(90);
     } else {
       viewer->setSnapshotQuality(-1);
     }
     viewer->setSnapshotFormat(format);
     viewer->saveSnapshot(filename);
     cerr << "saved snapshot " << filename.toStdString() << "(" << format.toStdString() << ")" << endl;
   }
 }
void MainWindow::on_actionSave_triggered (bool) slot
void MainWindow::on_actionSave_triggered (bool) slot
Definition at line 64 of file main_window.cpp.
 {
   QString filename = QFileDialog::getSaveFileName(this, "Save g2o file", "", "g2o files (*.g2o)");
   if (! filename.isNull()) {
     ofstream fout(filename.toStdString().c_str());
     viewer->graph->save(fout);
     if (fout.good())
       cerr << "Saved " << filename.toStdString() << endl;
     else
       cerr << "Error while saving file" << endl;
   }
 }
void MainWindow::on_actionSave_Viewer_State_triggered (bool) slot
Definition at line 442 of file main_window.cpp.
 {
   QString filename = QFileDialog::getSaveFileName(this, "Save State", "camera.xml", "Camera/State file (*.xml)");
   if (!filename.isEmpty()) {
     viewer->setStateFileName(filename);
     viewer->saveStateToFile();
     viewer->setStateFileName(QString::null);
     cerr << "Saved state to " << filename.toStdString() << endl;
   }
 }
void MainWindow::on_actionWhite_Background_triggered (bool) slot
Definition at line 363 of file main_window.cpp.
 {
   viewer->setBackgroundColor(QColor::fromRgb(255, 255, 255));
   viewer->updateGL();
 }
void MainWindow::on_btnForceStop_clicked () slot
Definition at line 347 of file main_window.cpp.
References _forceStopFlag.
 {
   _forceStopFlag = true;
 }
void MainWindow::on_btnInitialGuess_clicked () slot
void MainWindow::on_btnInitialGuess_clicked () slot
Definition at line 114 of file main_window.cpp.
References __PRETTY_FUNCTION__.
 {
   if (viewer->graph->activeEdges().size() == 0)
     viewer->graph->initializeOptimization();
   switch (cbxIniitialGuessMethod->currentIndex()) {
     case 0:
       // spanning tree
       viewer->graph->computeInitialGuess();
       break;
     case 1:
       // odometry
       {
         EstimatePropagatorCostOdometry costFunction(viewer->graph);
         viewer->graph->computeInitialGuess(costFunction);
       }
       break;
     default:
       cerr << __PRETTY_FUNCTION__ << " Unknown initialization method" << endl;
       break;
   }
   viewer->setUpdateDisplay(true);
   viewer->updateGL();
 }
void MainWindow::on_btnOptimize_clicked () slot
void MainWindow::on_btnOptimize_clicked () slot
Definition at line 77 of file main_window.cpp.
References _forceStopFlag, allocateSolver(), prepare(), and setRobustKernel().
 {
   if (viewer->graph->vertices().size() == 0 || viewer->graph->edges().size() == 0) {
     cerr << "Graph has no vertices / egdes" << endl;
     return;
   }
   bool allocatedNewSolver;
   bool allocateStatus = allocateSolver(allocatedNewSolver);
   if (! allocateStatus) {
     cerr << "Error while allocating solver" << endl;
     return;
   }
   if (allocatedNewSolver)
     prepare();
   setRobustKernel();
   btnOptimize->hide();
   btnForceStop->show();
   _forceStopFlag = false;
   viewer->graph->setForceStopFlag(&_forceStopFlag);
   int maxIterations = spIterations->value();
   int iter = viewer->graph->optimize(maxIterations);
   if (maxIterations > 0 && !iter){
     cerr << "Optimization failed, result might be invalid" << endl;
   }
   btnOptimize->show();
   btnForceStop->hide();
   viewer->setUpdateDisplay(true);
   viewer->updateGL();
   _forceStopFlag = false;
 }
void MainWindow::on_btnOptimizerParamaters_clicked () slot
Definition at line 385 of file main_window.cpp.
References _currentSolver, _optimizerPropertiesWidget, allocateSolver(), prepare(), g2o::OptimizationAlgorithm::properties(), and PropertiesWidget::setProperties().
 {
   if (! _optimizerPropertiesWidget) {
     _optimizerPropertiesWidget = new PropertiesWidget(this);
     _optimizerPropertiesWidget->setWindowTitle(tr("Internal Solver Properties"));
   }
   bool allocatedNewSolver;
   bool allocateStatus = allocateSolver(allocatedNewSolver);
   if (! allocateStatus) {
     cerr << "Error while allocating solver" << endl;
     return;
   }
   if (allocatedNewSolver)
     prepare();
   if (_currentSolver) {
     _optimizerPropertiesWidget->setProperties(const_cast<g2o::PropertyMap*>(&_currentSolver->properties()));
   } else {
     _optimizerPropertiesWidget->setProperties(0);
   }
   _optimizerPropertiesWidget->show();
 }
void MainWindow::on_btnSetZero_clicked () slot
Definition at line 140 of file main_window.cpp.
 {
   if (viewer->graph->activeEdges().size() == 0)
     viewer->graph->initializeOptimization();
   viewer->graph->setToOrigin();
   viewer->setUpdateDisplay(true);
   viewer->updateGL();
 }
bool MainWindow::prepare () protected
Definition at line 289 of file main_window.cpp.
References _currentOptimizationAlgorithmProperty, g2o::OptimizableGraph::Vertex::dimension(), g2o::OptimizationAlgorithmProperty::landmarkDim, g2o::OptimizationAlgorithmProperty::requiresMarginalize, g2o::OptimizableGraph::Vertex::setMarginalized(), and g2o::HyperGraph::vertices().
Referenced by on_btnOptimize_clicked(), and on_btnOptimizerParamaters_clicked().
 {
   SparseOptimizer* optimizer = viewer->graph;
   if (_currentOptimizationAlgorithmProperty.requiresMarginalize) {
     cerr << "Marginalizing Landmarks" << endl;
     for (SparseOptimizer::VertexIDMap::const_iterator it = optimizer->vertices().begin(); it != optimizer->vertices().end(); ++it) {
       OptimizableGraph::Vertex* v = static_cast<OptimizableGraph::Vertex*>(it->second);
       int vdim = v->dimension();
       v->setMarginalized((vdim == _currentOptimizationAlgorithmProperty.landmarkDim));
     }
   }
   else {
     cerr << "Preparing (no marginalization of Landmarks)" << endl;
     for (SparseOptimizer::VertexIDMap::const_iterator it = optimizer->vertices().begin(); it != optimizer->vertices().end(); ++it) {
       OptimizableGraph::Vertex* v = static_cast<OptimizableGraph::Vertex*>(it->second);
       v->setMarginalized(false);
     }
   }
   viewer->graph->initializeOptimization();
   return true;
 }
void MainWindow::setRobustKernel () protected
Definition at line 311 of file main_window.cpp.
References g2o::AbstractRobustKernelCreator::construct(), g2o::HyperGraph::edges(), g2o::HyperGraph::Vertex::id(), g2o::OptimizableGraph::Edge::robustKernel(), g2o::RobustKernel::setDelta(), g2o::OptimizableGraph::Edge::setRobustKernel(), g2o::HyperGraph::Edge::vertex(), and g2o::HyperGraph::Edge::vertices().
Referenced by on_btnOptimize_clicked().
 {
   SparseOptimizer* optimizer = viewer->graph;
   bool robustKernel = cbRobustKernel->isChecked();
   double huberWidth = leKernelWidth->text().toDouble();
   //odometry edges are those whose node ids differ by 1
   bool onlyLoop = cbOnlyLoop->isChecked();
   if (robustKernel) {
     QString strRobustKernel = coRobustKernel->currentText();
     AbstractRobustKernelCreator* creator = RobustKernelFactory::instance()->creator(strRobustKernel.toStdString());
     if (! creator) {
       cerr << strRobustKernel.toStdString() << " is not a valid robust kernel" << endl;
       return;
     }
     for (SparseOptimizer::EdgeSet::const_iterator it = optimizer->edges().begin(); it != optimizer->edges().end(); ++it) {
       OptimizableGraph::Edge* e = static_cast<OptimizableGraph::Edge*>(*it);
       if (onlyLoop) {
         if (e->vertices().size() >= 2 && std::abs(e->vertex(0)->id() - e->vertex(1)->id()) != 1) {
           e->setRobustKernel(creator->construct());
           e->robustKernel()->setDelta(huberWidth);
         }
       } else {
         e->setRobustKernel(creator->construct());
         e->robustKernel()->setDelta(huberWidth);
       }
     }
   } else {
     for (SparseOptimizer::EdgeSet::const_iterator it = optimizer->edges().begin(); it != optimizer->edges().end(); ++it) {
       OptimizableGraph::Edge* e = static_cast<OptimizableGraph::Edge*>(*it);
       e->setRobustKernel(0);
     }
   }
 }
void MainWindow::updateDisplayedSolvers ()
list the available solvers in the GUI
Definition at line 180 of file main_window.cpp.
References _knownSolvers, g2o::OptimizationAlgorithmProperty::name, and g2o::OptimizationAlgorithmProperty::type.
Referenced by g2o::RunG2OViewer::run().
 {
   coOptimizer->clear();
   _knownSolvers.clear();
   const OptimizationAlgorithmFactory::CreatorList& knownSolvers = OptimizationAlgorithmFactory::instance()->creatorList();
   bool varFound = false;
   string varType = "";
   for (OptimizationAlgorithmFactory::CreatorList::const_iterator it = knownSolvers.begin(); it != knownSolvers.end(); ++it) {
     const OptimizationAlgorithmProperty& sp = (*it)->property();
     if (sp.name == "gn_var" || sp.name == "gn_var_cholmod") {
       varType = sp.type;
       varFound = true;
       break;
     }
   }
   if (varFound) {
     for (OptimizationAlgorithmFactory::CreatorList::const_iterator it = knownSolvers.begin(); it != knownSolvers.end(); ++it) {
       const OptimizationAlgorithmProperty& sp = (*it)->property();
       if (sp.type == varType) {
         coOptimizer->addItem(QString::fromStdString(sp.name));
         _knownSolvers.push_back(sp);
       }
     }
   }
   map<string, vector<OptimizationAlgorithmProperty> > solverLookUp;
   for (OptimizationAlgorithmFactory::CreatorList::const_iterator it = knownSolvers.begin(); it != knownSolvers.end(); ++it) {
     const OptimizationAlgorithmProperty& sp = (*it)->property();
     if (varFound && varType == sp.type)
       continue;
     solverLookUp[sp.type].push_back(sp);
   }
   for (map<string, vector<OptimizationAlgorithmProperty> >::iterator it = solverLookUp.begin(); it != solverLookUp.end(); ++it) {
     if (_knownSolvers.size() > 0) {
       coOptimizer->insertSeparator(coOptimizer->count());
       _knownSolvers.push_back(OptimizationAlgorithmProperty());
     }
     const vector<OptimizationAlgorithmProperty>& vsp = it->second;
     for (size_t j = 0; j < vsp.size(); ++j) {
       coOptimizer->addItem(QString::fromStdString(vsp[j].name));
       _knownSolvers.push_back(vsp[j]);
     }
   }
 }
void MainWindow::updateRobustKernels ()
list the available robust kernels in the GUI
Definition at line 453 of file main_window.cpp.
Referenced by g2o::RunG2OViewer::run().
 {
   coRobustKernel->clear();
   std::vector<std::string> kernels;
   RobustKernelFactory::instance()->fillKnownKernels(kernels);
   for (size_t i = 0; i < kernels.size(); ++i) {
     coRobustKernel->addItem(QString::fromStdString(kernels[i]));
   }
 }
Member Data Documentation
g2o::OptimizationAlgorithmProperty MainWindow::_currentOptimizationAlgorithmProperty protected
Definition at line 90 of file main_window.h.
Referenced by allocateSolver(), and prepare().
g2o::OptimizationAlgorithm* MainWindow::_currentSolver protected
Definition at line 91 of file main_window.h.
Referenced by allocateSolver(), and on_btnOptimizerParamaters_clicked().
bool MainWindow::_forceStopFlag protected
Definition at line 89 of file main_window.h.
Referenced by on_btnForceStop_clicked(), and on_btnOptimize_clicked().
std::vector<g2o::OptimizationAlgorithmProperty> MainWindow::_knownSolvers protected
Definition at line 87 of file main_window.h.
Referenced by load(), and updateDisplayedSolvers().
int MainWindow::_lastSolver protected
Definition at line 88 of file main_window.h.
Referenced by allocateSolver(), and load().
PropertiesWidget* MainWindow::_optimizerPropertiesWidget protected
Definition at line 94 of file main_window.h.
Referenced by on_btnOptimizerParamaters_clicked().
ViewerPropertiesWidget* MainWindow::_viewerPropertiesWidget protected
Definition at line 93 of file main_window.h.
Referenced by on_actionProperties_triggered().
g2o::OptimizationAlgorithm* MainWindow::solverGaussNewton
Definition at line 35 of file main_window.h.
Referenced by main().
g2o::OptimizationAlgorithm* MainWindow::solverLevenberg
Definition at line 36 of file main_window.h.
Referenced by main().
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_viewer/main_window.h
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_viewer/main_window.cpp