g2o: g2o::EdgeSBACam Class Reference
g2o::EdgeSBACam Class Reference
3D edge between two SBAcam
#include <types_sba.h>
Public Member Functions
EdgeSBACam ()
virtual bool read (std::istream &is)
read the vertex from a stream, i.e., the internal state of the vertex
virtual bool write (std::ostream &os) const
write the vertex to a stream
void computeError ()
virtual void setMeasurement (const SE3Quat &meas)
virtual double initialEstimatePossible (const OptimizableGraph::VertexSet &, OptimizableGraph::Vertex *)
virtual void initialEstimate (const OptimizableGraph::VertexSet &from, OptimizableGraph::Vertex *to)
virtual bool setMeasurementData (const double *d)
virtual bool getMeasurementData (double *d) const
virtual int measurementDimension () const
virtual bool setMeasurementFromState ()
Public Member Functions inherited from g2o::BaseBinaryEdge< 6, SE3Quat, VertexCam, VertexCam >
BaseBinaryEdge ()
virtual OptimizableGraph::Vertex * createFrom ()
virtual OptimizableGraph::Vertex * createTo ()
virtual OptimizableGraph::Vertex * createVertex (int i)
virtual void resize (size_t size)
virtual bool allVerticesFixed () const
virtual void linearizeOplus (JacobianWorkspace &jacobianWorkspace)
virtual void linearizeOplus ()
const JacobianXiOplusType & jacobianOplusXi () const
returns the result of the linearization in the manifold space for the node xi
const JacobianXjOplusType & jacobianOplusXj () const
returns the result of the linearization in the manifold space for the node xj
virtual void constructQuadraticForm ()
virtual void mapHessianMemory (double *d, int i, int j, bool rowMajor)
Public Member Functions inherited from g2o::BaseEdge< D, SE3Quat >
BaseEdge ()
virtual ~BaseEdge ()
virtual double chi2 () const
computes the chi2 based on the cached error value, only valid after computeError has been called.
virtual const double * errorData () const
returns the error vector cached after calling the computeError;
virtual double * errorData ()
const ErrorVector & error () const
ErrorVector & error ()
EIGEN_STRONG_INLINE const InformationType & information () const
information matrix of the constraint
EIGEN_STRONG_INLINE InformationType & information ()
EIGEN_STRONG_INLINE void setInformation (const InformationType &information)
virtual const double * informationData () const
returns the memory of the information matrix, usable for example with a Eigen::Map<MatrixXD>
virtual double * informationData ()
EIGEN_STRONG_INLINE const Measurement & measurement () const
accessor functions for the measurement represented by the edge
virtual int rank () const
Public Member Functions inherited from g2o::OptimizableGraph::Edge
Edge ()
virtual ~Edge ()
virtual Edge * clone () const
RobustKernel * robustKernel () const
if NOT NULL, error of this edge will be robustifed with the kernel
void setRobustKernel (RobustKernel *ptr)
int level () const
returns the level of the edge
void setLevel (int l)
sets the level of the edge
int dimension () const
returns the dimensions of the error function
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createFrom())
G2O_ATTRIBUTE_DEPRECATED (virtual Vertex *createTo())
long long internalId () const
the internal ID of the edge
OptimizableGraph * graph ()
const OptimizableGraph * graph () const
bool setParameterId (int argNum, int paramId)
const Parameter * parameter (int argNo) const
size_t numParameters () const
void resizeParameters (size_t newSize)
Public Member Functions inherited from g2o::HyperGraph::Edge
Edge (int id=InvalidId)
creates and empty edge with no vertices
const VertexContainer & vertices () const
VertexContainer & vertices ()
const Vertex * vertex (size_t i) const
Vertex * vertex (size_t i)
void setVertex (size_t i, Vertex *v)
int id () const
void setId (int id)
virtual HyperGraphElementType elementType () const
int numUndefinedVertices () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Member Functions inherited from g2o::HyperGraph::DataContainer
DataContainer ()
virtual ~DataContainer ()
const Data * userData () const
the user data associated with this vertex
Data * userData ()
void setUserData (Data *obs)
void addUserData (Data *obs)
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Attributes
SE3Quat _inverseMeasurement
Protected Attributes inherited from g2o::BaseBinaryEdge< 6, SE3Quat, VertexCam, VertexCam >
bool _hessianRowMajor
HessianBlockType _hessian
HessianBlockTransposedType _hessianTransposed
JacobianXiOplusType _jacobianOplusXi
JacobianXjOplusType _jacobianOplusXj
Protected Attributes inherited from g2o::BaseEdge< D, SE3Quat >
Measurement _measurement
InformationType _information
ErrorVector _error
Protected Attributes inherited from g2o::OptimizableGraph::Edge
int _dimension
int _level
RobustKernel * _robustKernel
long long _internalId
std::vector< int > _cacheIds
std::vector< std::string > _parameterTypes
std::vector< Parameter ** > _parameters
std::vector< int > _parameterIds
Protected Attributes inherited from g2o::HyperGraph::Edge
VertexContainer _vertices
int _id
unique id
Protected Attributes inherited from g2o::HyperGraph::DataContainer
Data * _userData
Additional Inherited Members
Public Types inherited from g2o::BaseBinaryEdge< 6, SE3Quat, VertexCam, VertexCam >
typedef VertexCam VertexXiType
typedef VertexCam VertexXjType
typedef BaseEdge< D, SE3Quat >::Measurement Measurement
typedef Eigen::Matrix< double, D, Di, D==1?Eigen::RowMajor:Eigen::ColMajor >::AlignedMapType JacobianXiOplusType
typedef Eigen::Matrix< double, D, Dj, D==1?Eigen::RowMajor:Eigen::ColMajor >::AlignedMapType JacobianXjOplusType
typedef BaseEdge< D, SE3Quat >::ErrorVector ErrorVector
typedef BaseEdge< D, SE3Quat >::InformationType InformationType
typedef Eigen::Map< Eigen::Matrix< double, Di, Dj, Di==1?Eigen::RowMajor:Eigen::ColMajor >, Eigen::Matrix< double, Di, Dj, Di==1?Eigen::RowMajor:Eigen::ColMajor >::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockType
typedef Eigen::Map< Eigen::Matrix< double, Dj, Di, Dj==1?Eigen::RowMajor:Eigen::ColMajor >, Eigen::Matrix< double, Dj, Di, Dj==1?Eigen::RowMajor:Eigen::ColMajor >::Flags &Eigen::AlignedBit?Eigen::Aligned:Eigen::Unaligned > HessianBlockTransposedType
Public Types inherited from g2o::BaseEdge< D, SE3Quat >
typedef SE3Quat Measurement
typedef Eigen::Matrix< double, D, 1, Eigen::ColMajor > ErrorVector
typedef Eigen::Matrix< double, D, D, Eigen::ColMajor > InformationType
Static Public Attributes inherited from g2o::BaseBinaryEdge< 6, SE3Quat, VertexCam, VertexCam >
static const int Di
static const int Dj
static const int Dimension
Static Public Attributes inherited from g2o::BaseEdge< D, SE3Quat >
static const int Dimension
Protected Member Functions inherited from g2o::BaseEdge< D, SE3Quat >
InformationType robustInformation (const Vector3D &rho)
Protected Member Functions inherited from g2o::OptimizableGraph::Edge
template<typename ParameterType >
bool installParameter (ParameterType *&p, size_t argNo, int paramId=-1)
template<typename CacheType >
void resolveCache (CacheType *&cache, OptimizableGraph::Vertex *, const std::string &_type, const ParameterVector &parameters)
bool resolveParameters ()
virtual bool resolveCaches ()
Detailed Description
3D edge between two SBAcam
Definition at line 285 of file types_sba.h.
Constructor & Destructor Documentation
g2o::EdgeSBACam::EdgeSBACam ()
Definition at line 134 of file types_sba.cpp.
                          :
     BaseBinaryEdge<6, SE3Quat, VertexCam, VertexCam>()
   {
   }
Member Function Documentation
void g2o::EdgeSBACam::computeError () inline virtual
Implements g2o::OptimizableGraph::Edge.
Definition at line 292 of file types_sba.h.
References g2o::BaseVertex< D, T >::estimate(), g2o::SE3Quat::inverse(), g2o::SE3Quat::rotation(), and g2o::SE3Quat::translation().
     {
       const VertexCam* v1 = dynamic_cast<const VertexCam*>(_vertices[0]);
       const VertexCam* v2 = dynamic_cast<const VertexCam*>(_vertices[1]);
       SE3Quat delta = _inverseMeasurement * (v1->estimate().inverse()*v2->estimate());
       _error[0]=delta.translation().x();
       _error[1]=delta.translation().y();
       _error[2]=delta.translation().z();
       _error[3]=delta.rotation().x();
       _error[4]=delta.rotation().y();
       _error[5]=delta.rotation().z();
     }
virtual bool g2o::EdgeSBACam::getMeasurementData (double * m) const inline virtual
writes the measurement to an array of double
Returns
true on success
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 320 of file types_sba.h.
{
       Eigen::Map<Vector7d> v(d);
       v = _measurement.toVector();
       return true;
     }
void g2o::EdgeSBACam::initialEstimate (const OptimizableGraph::VertexSet & , OptimizableGraph::Vertex *) virtual
set the estimate of the to vertex, based on the estimate of the from vertices in the edge.
Reimplemented from g2o::BaseEdge< D, SE3Quat >.
Definition at line 166 of file types_sba.cpp.
References _inverseMeasurement, g2o::BaseEdge< D, SE3Quat >::_measurement, g2o::HyperGraph::Edge::_vertices, g2o::BaseVertex< D, T >::estimate(), and g2o::VertexCam::setEstimate().
   {
     VertexCam* from = static_cast<VertexCam*>(_vertices[0]);
     VertexCam* to = static_cast<VertexCam*>(_vertices[1]);
     if (from_.count(from) > 0)
       to->setEstimate((SE3Quat) from->estimate() * _measurement);
     else
       from->setEstimate((SE3Quat) to->estimate() * _inverseMeasurement);
   }
virtual double g2o::EdgeSBACam::initialEstimatePossible (const OptimizableGraph::VertexSet & from, OptimizableGraph::Vertex * to) inline virtual
override in your class if it's possible to initialize the vertices in certain combinations. The return value may correspond to the cost for initiliaizng the vertex but should be positive if the initialization is possible and negative if not possible.
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 310 of file types_sba.h.
 { return 1.;}
virtual int g2o::EdgeSBACam::measurementDimension () const inline virtual
returns the dimension of the measurement in the extended representation which is used by get/setMeasurement;
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 326 of file types_sba.h.
 {return 7;}
bool g2o::EdgeSBACam::read (std::istream & is) virtual
read the vertex from a stream, i.e., the internal state of the vertex
Implements g2o::OptimizableGraph::Edge.
Definition at line 139 of file types_sba.cpp.
References g2o::BaseEdge< D, SE3Quat >::information(), and setMeasurement().
   {
     Vector7d meas;
     for (int i=0; i<7; i++)
       is >> meas[i];
     setMeasurement(SE3Quat(meas));
     for (int i=0; i<6; i++)
       for (int j=i; j<6; j++) {
   is >> information()(i,j);
   if (i!=j)
     information()(j,i)=information()(i,j);
       }
     return true;
   }
virtual void g2o::EdgeSBACam::setMeasurement (const SE3Quat & meas) inline virtual
Reimplemented from g2o::BaseEdge< D, SE3Quat >.
Definition at line 305 of file types_sba.h.
References g2o::SE3Quat::inverse().
Referenced by read().
{
       _measurement=meas;
       _inverseMeasurement=meas.inverse();
     }
virtual bool g2o::EdgeSBACam::setMeasurementData (const double * m) inline virtual
sets the measurement from an array of double
Returns
true on success
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 313 of file types_sba.h.
{
       Eigen::Map<const Vector7d> v(d);
       _measurement.fromVector(v);
       _inverseMeasurement = _measurement.inverse();
       return true;
     }
bool g2o::EdgeSBACam::setMeasurementFromState () virtual
sets the estimate to have a zero error, based on the current value of the state variables returns false if not supported.
Reimplemented from g2o::OptimizableGraph::Edge.
Definition at line 565 of file types_sba.cpp.
References g2o::BaseEdge< D, double >::_measurement, g2o::HyperGraph::Edge::_vertices, g2o::BaseVertex< D, T >::estimate(), and g2o::SE3Quat::inverse().
   {
     const VertexCam* v1 = dynamic_cast<const VertexCam*>(_vertices[0]);
     const VertexCam* v2 = dynamic_cast<const VertexCam*>(_vertices[1]);
     _measurement = (v1->estimate().inverse()*v2->estimate());
     _inverseMeasurement = _measurement.inverse();
     return true;
   }
bool g2o::EdgeSBACam::write (std::ostream & os) const virtual
write the vertex to a stream
Implements g2o::OptimizableGraph::Edge.
Definition at line 155 of file types_sba.cpp.
References g2o::BaseEdge< D, SE3Quat >::information(), and g2o::BaseEdge< D, SE3Quat >::measurement().
   {
     for (int i=0; i<7; i++)
       os << measurement()[i] << " ";
     for (int i=0; i<6; i++)
       for (int j=i; j<6; j++){
   os << " " <<  information()(i,j);
       }
     return os.good();
   }
Member Data Documentation
SE3Quat g2o::EdgeSBACam::_inverseMeasurement protected
Definition at line 331 of file types_sba.h.
Referenced by initialEstimate().
g2o::EdgeSBACam::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 288 of file types_sba.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/sba/types_sba.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/sba/types_sba.cpp