g2o: g2o::Robot< RobotPoseObject > Class Template Reference
g2o::Robot< RobotPoseObject > Class Template Reference
#include <simulator.h>
Public Types
typedef RobotPoseObject PoseObject
typedef std::list< PoseObject * > TrajectoryType
typedef PoseObject::VertexType VertexType
typedef PoseObject::EstimateType PoseType
Public Member Functions
Robot (World *world_, const std::string &name_)
virtual void relativeMove (const PoseType &movement_)
virtual void move (const PoseType &pose_)
TrajectoryType & trajectory ()
const PoseType & pose () const
Public Member Functions inherited from g2o::BaseRobot
BaseRobot (World *world_, const std::string &name_)
void setWorld (World *world_)
World * world ()
const std::string & name () const
OptimizableGraph * graph ()
bool addSensor (BaseSensor *sensor)
const std::set< BaseSensor * > sensors ()
virtual void sense ()
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Attributes
TrajectoryType _trajectory
PoseType _pose
Protected Attributes inherited from g2o::BaseRobot
World * _world
std::set< BaseSensor * > _sensors
std::string _name
Detailed Description
template<class RobotPoseObject>
class g2o::Robot< RobotPoseObject >
Definition at line 95 of file simulator.h.
Member Typedef Documentation
template<class RobotPoseObject > typedef RobotPoseObject g2o::Robot< RobotPoseObject >::PoseObject
Definition at line 98 of file simulator.h.
template<class RobotPoseObject > typedef PoseObject::EstimateType g2o::Robot< RobotPoseObject >::PoseType
Definition at line 101 of file simulator.h.
template<class RobotPoseObject > typedef std::list<PoseObject*> g2o::Robot< RobotPoseObject >::TrajectoryType
Definition at line 99 of file simulator.h.
template<class RobotPoseObject > typedef PoseObject::VertexType g2o::Robot< RobotPoseObject >::VertexType
Definition at line 100 of file simulator.h.
Constructor & Destructor Documentation
template<class RobotPoseObject > g2o::Robot< RobotPoseObject >::Robot (World * world_, const std::string & name_) inline
Definition at line 103 of file simulator.h.
 : BaseRobot(world_, name_){}
Member Function Documentation
template<class RobotPoseObject > virtual void g2o::Robot< RobotPoseObject >::move (const PoseType & pose_) inline virtual
Definition at line 109 of file simulator.h.
Referenced by main(), and Simulator::move().
{
       _pose=pose_;
       if (world()) {
         PoseObject* po=new PoseObject();
         po->vertex()->setEstimate(_pose);
         world()->addWorldObject(po);
         _trajectory.push_back(po);
       }
     }
template<class RobotPoseObject > const PoseType& g2o::Robot< RobotPoseObject >::pose () const inline
Definition at line 120 of file simulator.h.
Referenced by main().
 {return _pose;}
template<class RobotPoseObject > virtual void g2o::Robot< RobotPoseObject >::relativeMove (const PoseType & movement_) inline virtual
Definition at line 104 of file simulator.h.
Referenced by main(), and Simulator::relativeMove().
{
       _pose=_pose*movement_;
       move(_pose);
     }
template<class RobotPoseObject > TrajectoryType& g2o::Robot< RobotPoseObject >::trajectory () inline
Definition at line 119 of file simulator.h.
Referenced by g2o::SensorPose3DOffset::sense(), g2o::SensorOdometry2D::sense(), g2o::SensorOdometry3D::sense(), g2o::SensorPose3D::sense(), g2o::SensorPose2D::sense(), g2o::SensorPointXY::sense(), g2o::SensorPointXYZ::sense(), g2o::SensorSE3Prior::sense(), g2o::SensorPointXYZDepth::sense(), g2o::SensorPointXYBearing::sense(), g2o::SensorPointXYZDisparity::sense(), g2o::SensorSegment2DLine::sense(), g2o::SensorSegment2DPointLine::sense(), g2o::SensorPointXYOffset::sense(), g2o::SensorSegment2D::sense(), g2o::UnarySensor< Robot3D, EdgeSE3Prior >::sense(), and g2o::BinarySensor< Robot2D, EdgeSE2PointXY, WorldObjectPointXY >::sense().
 {return _trajectory;}
Member Data Documentation
template<class RobotPoseObject > PoseType g2o::Robot< RobotPoseObject >::_pose protected
Definition at line 123 of file simulator.h.
template<class RobotPoseObject > TrajectoryType g2o::Robot< RobotPoseObject >::_trajectory protected
Definition at line 122 of file simulator.h.
template<class RobotPoseObject > g2o::Robot< RobotPoseObject >::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 97 of file simulator.h.
The documentation for this class was generated from the following file:
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_simulator/simulator.h