g2o: g2o::OptimizableGraph::Vertex Class Reference
g2o::OptimizableGraph::Vertex Class Reference abstract
A general case Vertex for optimization.
#include <optimizable_graph.h>
Public Member Functions
Vertex ()
virtual Vertex * clone () const
returns a deep copy of the current vertex
virtual ~Vertex ()
void setToOrigin ()
sets the node to the origin (used in the multilevel stuff)
virtual const double & hessian (int i, int j) const =0
get the element from the hessian matrix
virtual double & hessian (int i, int j)=0
virtual double hessianDeterminant () const =0
virtual double * hessianData ()=0
virtual void mapHessianMemory (double *d)=0
virtual int copyB (double *b_) const =0
virtual const double & b (int i) const =0
get the b vector element
virtual double & b (int i)=0
virtual double * bData ()=0
return a pointer to the b vector associated with this vertex
virtual void clearQuadraticForm ()=0
virtual double solveDirect (double lambda=0)=0
bool setEstimateData (const double *estimate)
bool setEstimateData (const std::vector< double > &estimate)
virtual bool getEstimateData (double *estimate) const
virtual bool getEstimateData (std::vector< double > &estimate) const
virtual int estimateDimension () const
bool setMinimalEstimateData (const double *estimate)
bool setMinimalEstimateData (const std::vector< double > &estimate)
virtual bool getMinimalEstimateData (double *estimate) const
virtual bool getMinimalEstimateData (std::vector< double > &estimate) const
virtual int minimalEstimateDimension () const
virtual void push ()=0
backup the position of the vertex to a stack
virtual void pop ()=0
restore the position of the vertex by retrieving the position from the stack
virtual void discardTop ()=0
pop the last element from the stack, without restoring the current estimate
virtual int stackSize () const =0
return the stack size
void oplus (const double *v)
int hessianIndex () const
temporary index of this node in the parameter vector obtained from linearization
int G2O_ATTRIBUTE_DEPRECATED (tempIndex() const)
void setHessianIndex (int ti)
set the temporary index of the vertex in the parameter blocks
void G2O_ATTRIBUTE_DEPRECATED (setTempIndex(int ti))
bool fixed () const
true => this node is fixed during the optimization
void setFixed (bool fixed)
true => this node should be considered fixed during the optimization
bool marginalized () const
true => this node is marginalized out during the optimization
void setMarginalized (bool marginalized)
true => this node should be marginalized out during the optimization
int dimension () const
dimension of the estimated state belonging to this node
virtual void setId (int id)
sets the id of the node in the graph be sure that the graph keeps consistent after changing the id
void setColInHessian (int c)
set the row of this vertex in the Hessian
int colInHessian () const
get the row of this vertex in the Hessian
const OptimizableGraph * graph () const
OptimizableGraph * graph ()
void lockQuadraticForm ()
void unlockQuadraticForm ()
virtual bool read (std::istream &is)=0
read the vertex from a stream, i.e., the internal state of the vertex
virtual bool write (std::ostream &os) const =0
write the vertex to a stream
virtual void updateCache ()
CacheContainer * cacheContainer ()
Public Member Functions inherited from g2o::HyperGraph::Vertex
Vertex (int id=InvalidId)
creates a vertex having an ID specified by the argument
int id () const
returns the id
const EdgeSet & edges () const
returns the set of hyper-edges that are leaving/entering in this vertex
EdgeSet & edges ()
returns the set of hyper-edges that are leaving/entering in this vertex
virtual HyperGraphElementType elementType () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Member Functions inherited from g2o::HyperGraph::DataContainer
DataContainer ()
virtual ~DataContainer ()
const Data * userData () const
the user data associated with this vertex
Data * userData ()
void setUserData (Data *obs)
void addUserData (Data *obs)
Protected Member Functions
virtual void oplusImpl (const double *v)=0
virtual void setToOriginImpl ()=0
sets the node to the origin (used in the multilevel stuff)
virtual bool setEstimateDataImpl (const double *)
virtual bool setMinimalEstimateDataImpl (const double *)
Protected Attributes
OptimizableGraph * _graph
Data * _userData
int _hessianIndex
bool _fixed
bool _marginalized
int _dimension
int _colInHessian
OpenMPMutex _quadraticFormMutex
CacheContainer * _cacheContainer
Protected Attributes inherited from g2o::HyperGraph::Vertex
int _id
EdgeSet _edges
Protected Attributes inherited from g2o::HyperGraph::DataContainer
Data * _userData
Friends
struct OptimizableGraph
Detailed Description
A general case Vertex for optimization.
Definition at line 107 of file optimizable_graph.h.
Constructor & Destructor Documentation
g2o::OptimizableGraph::Vertex::Vertex ()
Definition at line 53 of file optimizable_graph.cpp.
                                  :
     HyperGraph::Vertex(),
     _graph(0), _userData(0), _hessianIndex(-1), _fixed(false), _marginalized(false),
     _colInHessian(-1), _cacheContainer(0)
   {
   }
g2o::OptimizableGraph::Vertex::~Vertex () virtual
Reimplemented from g2o::HyperGraph::Vertex.
Definition at line 74 of file optimizable_graph.cpp.
References _cacheContainer, and _userData.
   {
     delete _cacheContainer;
     delete _userData;
   }
Member Function Documentation
virtual const double& g2o::OptimizableGraph::Vertex::b (int i) const pure virtual
get the b vector element
Implemented in g2o::BaseVertex< D, T >, g2o::BaseVertex< 6, Isometry3D >, g2o::BaseVertex< 3, Eigen::Vector3d >, g2o::BaseVertex< 6, Line3D >, g2o::BaseVertex< 4, Eigen::Matrix< double, 5, 1, Eigen::ColMajor > >, g2o::BaseVertex< 4, Vector4D >, g2o::BaseVertex< 3, SE2 >, g2o::BaseVertex< 2, Vector2D >, g2o::BaseVertex< 1, double >, g2o::BaseVertex< 3, Plane3D >, g2o::BaseVertex< 7, Sim3 >, g2o::BaseVertex< 3, Vector3D >, g2o::BaseVertex< 6, SBACam >, g2o::BaseVertex< 2, Eigen::Vector2d >, g2o::BaseVertex< 2, Line2D >, g2o::BaseVertex< 9, Eigen::VectorXd >, g2o::BaseVertex< 6, SE3Quat >, and g2o::BaseVertex< 6, Vector6d >.
virtual double& g2o::OptimizableGraph::Vertex::b (int i) pure virtual
Implemented in g2o::BaseVertex< D, T >, g2o::BaseVertex< 6, Isometry3D >, g2o::BaseVertex< 3, Eigen::Vector3d >, g2o::BaseVertex< 6, Line3D >, g2o::BaseVertex< 4, Eigen::Matrix< double, 5, 1, Eigen::ColMajor > >, g2o::BaseVertex< 4, Vector4D >, g2o::BaseVertex< 3, SE2 >, g2o::BaseVertex< 2, Vector2D >, g2o::BaseVertex< 1, double >, g2o::BaseVertex< 3, Plane3D >, g2o::BaseVertex< 7, Sim3 >, g2o::BaseVertex< 3, Vector3D >, g2o::BaseVertex< 6, SBACam >, g2o::BaseVertex< 2, Eigen::Vector2d >, g2o::BaseVertex< 2, Line2D >, g2o::BaseVertex< 9, Eigen::VectorXd >, g2o::BaseVertex< 6, SE3Quat >, and g2o::BaseVertex< 6, Vector6d >.
virtual double* g2o::OptimizableGraph::Vertex::bData () pure virtual
return a pointer to the b vector associated with this vertex
Implemented in g2o::BaseVertex< D, T >, g2o::BaseVertex< 6, Isometry3D >, g2o::BaseVertex< 3, Eigen::Vector3d >, g2o::BaseVertex< 6, Line3D >, g2o::BaseVertex< 4, Eigen::Matrix< double, 5, 1, Eigen::ColMajor > >, g2o::BaseVertex< 4, Vector4D >, g2o::BaseVertex< 3, SE2 >, g2o::BaseVertex< 2, Vector2D >, g2o::BaseVertex< 1, double >, g2o::BaseVertex< 3, Plane3D >, g2o::BaseVertex< 7, Sim3 >, g2o::BaseVertex< 3, Vector3D >, g2o::BaseVertex< 6, SBACam >, g2o::BaseVertex< 2, Eigen::Vector2d >, g2o::BaseVertex< 2, Line2D >, g2o::BaseVertex< 9, Eigen::VectorXd >, g2o::BaseVertex< 6, SE3Quat >, and g2o::BaseVertex< 6, Vector6d >.
Referenced by g2o::StructureOnlySolver< PointDoF >::calc().
CacheContainer * g2o::OptimizableGraph::Vertex::cacheContainer ()
Definition at line 60 of file optimizable_graph.cpp.
References _cacheContainer.
Referenced by g2o::VertexPointXYWriteGnuplotAction::operator()(), g2o::VertexSE2WriteGnuplotAction::operator()(), g2o::deprecated::VertexSE3WriteGnuplotAction::operator()(), g2o::VertexSE3WriteGnuplotAction::operator()(), g2o::OptimizableGraph::Edge::resolveCache(), and g2o::VertexPointXYZ::write().
{
     if (! _cacheContainer)
       _cacheContainer = new CacheContainer(this);
     return _cacheContainer;
   }
virtual void g2o::OptimizableGraph::Vertex::clearQuadraticForm () pure virtual
set the b vector part of this vertex to zero
Implemented in g2o::BaseVertex< D, T >, g2o::BaseVertex< 6, Isometry3D >, g2o::BaseVertex< 3, Eigen::Vector3d >, g2o::BaseVertex< 6, Line3D >, g2o::BaseVertex< 4, Eigen::Matrix< double, 5, 1, Eigen::ColMajor > >, g2o::BaseVertex< 4, Vector4D >, g2o::BaseVertex< 3, SE2 >, g2o::BaseVertex< 2, Vector2D >, g2o::BaseVertex< 1, double >, g2o::BaseVertex< 3, Plane3D >, g2o::BaseVertex< 7, Sim3 >, g2o::BaseVertex< 3, Vector3D >, g2o::BaseVertex< 6, SBACam >, g2o::BaseVertex< 2, Eigen::Vector2d >, g2o::BaseVertex< 2, Line2D >, g2o::BaseVertex< 9, Eigen::VectorXd >, g2o::BaseVertex< 6, SE3Quat >, and g2o::BaseVertex< 6, Vector6d >.
Referenced by g2o::BlockSolver< Traits >::buildSystem(), g2o::StructureOnlySolver< PointDoF >::calc(), g2o::SparseOptimizerIncremental::updateInitialization(), and g2o::SparseOptimizerOnline::updateInitialization().
OptimizableGraph::Vertex * g2o::OptimizableGraph::Vertex::clone () const virtual
returns a deep copy of the current vertex
Definition at line 80 of file optimizable_graph.cpp.
Referenced by g2o::OptimizableGraph::addGraph(), and main().
   {
     return 0;
   }
int g2o::OptimizableGraph::Vertex::colInHessian () const inline
get the row of this vertex in the Hessian
Definition at line 291 of file optimizable_graph.h.
Referenced by g2o::BlockSolver< Traits >::buildSystem(), g2o::SparseOptimizerIncremental::optimize(), and g2o::SparseOptimizerOnline::optimize().
 {return _colInHessian;}
virtual int g2o::OptimizableGraph::Vertex::copyB (double * b_) const pure virtual
copies the b vector in the array b_
Returns
the number of elements copied
Implemented in g2o::BaseVertex< D, T >, g2o::BaseVertex< 6, Isometry3D >, g2o::BaseVertex< 3, Eigen::Vector3d >, g2o::BaseVertex< 6, Line3D >, g2o::BaseVertex< 4, Eigen::Matrix< double, 5, 1, Eigen::ColMajor > >, g2o::BaseVertex< 4, Vector4D >, g2o::BaseVertex< 3, SE2 >, g2o::BaseVertex< 2, Vector2D >, g2o::BaseVertex< 1, double >, g2o::BaseVertex< 3, Plane3D >, g2o::BaseVertex< 7, Sim3 >, g2o::BaseVertex< 3, Vector3D >, g2o::BaseVertex< 6, SBACam >, g2o::BaseVertex< 2, Eigen::Vector2d >, g2o::BaseVertex< 2, Line2D >, g2o::BaseVertex< 9, Eigen::VectorXd >, g2o::BaseVertex< 6, SE3Quat >, and g2o::BaseVertex< 6, Vector6d >.
Referenced by g2o::BlockSolver< Traits >::buildSystem(), g2o::SparseOptimizerIncremental::optimize(), and g2o::SparseOptimizerOnline::optimize().
int g2o::OptimizableGraph::Vertex::dimension () const inline
dimension of the estimated state belonging to this node
Definition at line 283 of file optimizable_graph.h.
Referenced by g2o::BlockSolver< Traits >::buildStructure(), g2o::BlockSolver< Traits >::buildSystem(), g2o::StructureOnlySolver< PointDoF >::calc(), g2o::OptimizationAlgorithmLevenberg::computeLambdaInit(), g2o::computeSimpleStars(), g2o::OptimizableGraph::dimensions(), g2o::edgeAllVertsSameDim(), g2o::SparseOptimizer::findGauge(), g2o::SparseOptimizer::gaugeFreedom(), main(), g2o::OptimizableGraph::maxDimension(), g2o::SparseOptimizer::optimize(), MainWindow::prepare(), g2o::G2oSlamInterface::printVertex(), g2o::saveGnuplot(), g2o::SparseOptimizerIncremental::updateInitialization(), g2o::JacobianWorkspace::updateSize(), and g2o::BlockSolver< Traits >::updateStructure().
 { return _dimension;}
virtual void g2o::OptimizableGraph::Vertex::discardTop () pure virtual
pop the last element from the stack, without restoring the current estimate
Implemented in g2o::BaseVertex< D, T >, g2o::BaseVertex< 6, Isometry3D >, g2o::BaseVertex< 3, Eigen::Vector3d >, g2o::BaseVertex< 6, Line3D >, g2o::BaseVertex< 4, Eigen::Matrix< double, 5, 1, Eigen::ColMajor > >, g2o::BaseVertex< 4, Vector4D >, g2o::BaseVertex< 3, SE2 >, g2o::BaseVertex< 2, Vector2D >, g2o::BaseVertex< 1, double >, g2o::BaseVertex< 3, Plane3D >, g2o::BaseVertex< 7, Sim3 >, g2o::BaseVertex< 3, Vector3D >, g2o::BaseVertex< 6, SBACam >, g2o::BaseVertex< 2, Eigen::Vector2d >, g2o::BaseVertex< 2, Line2D >, g2o::BaseVertex< 9, Eigen::VectorXd >, g2o::BaseVertex< 6, SE3Quat >, and g2o::BaseVertex< 6, Vector6d >.
Referenced by g2o::StructureOnlySolver< PointDoF >::calc(), and g2o::OptimizableGraph::discardTop().
int g2o::OptimizableGraph::Vertex::estimateDimension () const virtual
returns the dimension of the extended representation used by get/setEstimate(double*) -1 if it is not supported
Reimplemented in g2o::VertexCam, g2o::VertexSE3, g2o::deprecated::VertexSE3, g2o::VertexSE2, g2o::VertexLine2D, g2o::deprecated::VertexPointXYZ, g2o::VertexPlane, g2o::VertexSegment2D, g2o::VertexPointXYZ, g2o::VertexLine3D, and g2o::VertexPointXY.
Definition at line 97 of file optimizable_graph.cpp.
Referenced by g2o::SparseOptimizer::initializeOptimization().
   {
     return -1;
   }
bool g2o::OptimizableGraph::Vertex::fixed () const inline
true => this node is fixed during the optimization
Definition at line 273 of file optimizable_graph.h.
Referenced by g2o::SparseOptimizer::buildIndexMapping(), g2o::BlockSolver< Traits >::buildSystem(), g2o::StructureOnlySolver< PointDoF >::calc(), g2o::SparseOptimizer::computeInitialGuess(), g2o::SparseOptimizer::gaugeFreedom(), g2o::Edge_V_V_GICP::linearizeOplus(), main(), g2o::EstimatePropagator::PropagateAction::operator()(), g2o::OptimizableGraph::saveVertex(), g2o::SolverSLAM2DLinear::solveOrientation(), g2o::SparseOptimizerIncremental::updateInitialization(), and g2o::SparseOptimizer::updateInitialization().
 {return _fixed;}
int g2o::OptimizableGraph::Vertex::G2O_ATTRIBUTE_DEPRECATED (tempIndex() const) inline
Definition at line 267 of file optimizable_graph.h.
 { return hessianIndex();}
void g2o::OptimizableGraph::Vertex::G2O_ATTRIBUTE_DEPRECATED (setTempIndex(int ti)) inline
Definition at line 270 of file optimizable_graph.h.
 { setHessianIndex(ti);}
bool g2o::OptimizableGraph::Vertex::getEstimateData (double * estimate) const virtual
writes the estimater to an array of double
Returns
true on success
Reimplemented in g2o::VertexCam, g2o::VertexSE3, g2o::deprecated::VertexSE3, g2o::VertexSE2, g2o::VertexLine2D, g2o::deprecated::VertexPointXYZ, g2o::VertexPlane, g2o::VertexSegment2D, g2o::VertexPointXYZ, g2o::VertexLine3D, and g2o::VertexPointXY.
Definition at line 92 of file optimizable_graph.cpp.
Referenced by g2o::SparseOptimizer::initializeOptimization().
   {
     return false;
   }
virtual bool g2o::OptimizableGraph::Vertex::getEstimateData (std::vector< double > & estimate) const inline virtual
writes the estimater to an array of double
Returns
true on success
Definition at line 183 of file optimizable_graph.h.
{
           int dim = estimateDimension();
           if (dim < 0)
             return false;
           estimate.resize(dim);
           return getEstimateData(&estimate[0]);
         };
bool g2o::OptimizableGraph::Vertex::getMinimalEstimateData (double * estimate) const virtual
writes the estimate to an array of double
Returns
true on success
Reimplemented in g2o::VertexCam, g2o::VertexSE3, g2o::deprecated::VertexSE3, g2o::VertexLine2D, g2o::deprecated::VertexPointXYZ, g2o::VertexSE2, g2o::VertexSegment2D, g2o::VertexPointXYZ, and g2o::VertexPointXY.
Definition at line 109 of file optimizable_graph.cpp.
Referenced by testMarginals().
   {
     return false;
   }
virtual bool g2o::OptimizableGraph::Vertex::getMinimalEstimateData (std::vector< double > & estimate) const inline virtual
writes the estimate to an array of double
Returns
true on success
Definition at line 227 of file optimizable_graph.h.
{
           int dim = minimalEstimateDimension();
           if (dim < 0)
             return false;
           estimate.resize(dim);
           return getMinimalEstimateData(&estimate[0]);
         };
const OptimizableGraph* g2o::OptimizableGraph::Vertex::graph () const inline
Definition at line 293 of file optimizable_graph.h.
Referenced by g2o::activeVertexChi(), MainWindow::fixGraph(), g2o::OptimizableGraph::Edge::graph(), and g2o::VertexLine2D::write().
 {return _graph;}
OptimizableGraph* g2o::OptimizableGraph::Vertex::graph () inline
Definition at line 294 of file optimizable_graph.h.
 {return _graph;}
virtual const double& g2o::OptimizableGraph::Vertex::hessian (int i, int j) const pure virtual
get the element from the hessian matrix
Implemented in g2o::BaseVertex< D, T >, g2o::BaseVertex< 6, Isometry3D >, g2o::BaseVertex< 3, Eigen::Vector3d >, g2o::BaseVertex< 6, Line3D >, g2o::BaseVertex< 4, Eigen::Matrix< double, 5, 1, Eigen::ColMajor > >, g2o::BaseVertex< 4, Vector4D >, g2o::BaseVertex< 3, SE2 >, g2o::BaseVertex< 2, Vector2D >, g2o::BaseVertex< 1, double >, g2o::BaseVertex< 3, Plane3D >, g2o::BaseVertex< 7, Sim3 >, g2o::BaseVertex< 3, Vector3D >, g2o::BaseVertex< 6, SBACam >, g2o::BaseVertex< 2, Eigen::Vector2d >, g2o::BaseVertex< 2, Line2D >, g2o::BaseVertex< 9, Eigen::VectorXd >, g2o::BaseVertex< 6, SE3Quat >, and g2o::BaseVertex< 6, Vector6d >.
Referenced by g2o::OptimizationAlgorithmLevenberg::computeLambdaInit(), and g2o::computeSimpleStars().
virtual double& g2o::OptimizableGraph::Vertex::hessian (int i, int j) pure virtual
Implemented in g2o::BaseVertex< D, T >, g2o::BaseVertex< 6, Isometry3D >, g2o::BaseVertex< 3, Eigen::Vector3d >, g2o::BaseVertex< 6, Line3D >, g2o::BaseVertex< 4, Eigen::Matrix< double, 5, 1, Eigen::ColMajor > >, g2o::BaseVertex< 4, Vector4D >, g2o::BaseVertex< 3, SE2 >, g2o::BaseVertex< 2, Vector2D >, g2o::BaseVertex< 1, double >, g2o::BaseVertex< 3, Plane3D >, g2o::BaseVertex< 7, Sim3 >, g2o::BaseVertex< 3, Vector3D >, g2o::BaseVertex< 6, SBACam >, g2o::BaseVertex< 2, Eigen::Vector2d >, g2o::BaseVertex< 2, Line2D >, g2o::BaseVertex< 9, Eigen::VectorXd >, g2o::BaseVertex< 6, SE3Quat >, and g2o::BaseVertex< 6, Vector6d >.
virtual double* g2o::OptimizableGraph::Vertex::hessianData () pure virtual
Implemented in g2o::BaseVertex< D, T >, g2o::BaseVertex< 6, Isometry3D >, g2o::BaseVertex< 3, Eigen::Vector3d >, g2o::BaseVertex< 6, Line3D >, g2o::BaseVertex< 4, Eigen::Matrix< double, 5, 1, Eigen::ColMajor > >, g2o::BaseVertex< 4, Vector4D >, g2o::BaseVertex< 3, SE2 >, g2o::BaseVertex< 2, Vector2D >, g2o::BaseVertex< 1, double >, g2o::BaseVertex< 3, Plane3D >, g2o::BaseVertex< 7, Sim3 >, g2o::BaseVertex< 3, Vector3D >, g2o::BaseVertex< 6, SBACam >, g2o::BaseVertex< 2, Eigen::Vector2d >, g2o::BaseVertex< 2, Line2D >, g2o::BaseVertex< 9, Eigen::VectorXd >, g2o::BaseVertex< 6, SE3Quat >, and g2o::BaseVertex< 6, Vector6d >.
Referenced by g2o::SparseOptimizerIncremental::updateInitialization().
virtual double g2o::OptimizableGraph::Vertex::hessianDeterminant () const pure virtual
Implemented in g2o::BaseVertex< D, T >, g2o::BaseVertex< 6, Isometry3D >, g2o::BaseVertex< 3, Eigen::Vector3d >, g2o::BaseVertex< 6, Line3D >, g2o::BaseVertex< 4, Eigen::Matrix< double, 5, 1, Eigen::ColMajor > >, g2o::BaseVertex< 4, Vector4D >, g2o::BaseVertex< 3, SE2 >, g2o::BaseVertex< 2, Vector2D >, g2o::BaseVertex< 1, double >, g2o::BaseVertex< 3, Plane3D >, g2o::BaseVertex< 7, Sim3 >, g2o::BaseVertex< 3, Vector3D >, g2o::BaseVertex< 6, SBACam >, g2o::BaseVertex< 2, Eigen::Vector2d >, g2o::BaseVertex< 2, Line2D >, g2o::BaseVertex< 9, Eigen::VectorXd >, g2o::BaseVertex< 6, SE3Quat >, and g2o::BaseVertex< 6, Vector6d >.
int g2o::OptimizableGraph::Vertex::hessianIndex () const inline
temporary index of this node in the parameter vector obtained from linearization
Definition at line 266 of file optimizable_graph.h.
Referenced by g2o::EdgeLabeler::augmentSparsePattern(), g2o::BlockSolver< Traits >::buildStructure(), g2o::SparseOptimizer::computeInitialGuess(), g2o::EdgeLabeler::labelEdge(), g2o::Star::labelStarEdges(), main(), g2o::SparseOptimizerIncremental::optimize(), g2o::ThetaTreeAction::perform(), g2o::SparseOptimizer::removeVertex(), g2o::SolverSLAM2DLinear::solveOrientation(), testMarginals(), g2o::SparseOptimizerIncremental::updateInitialization(), and g2o::BlockSolver< Traits >::updateStructure().
 { return _hessianIndex;}
void g2o::OptimizableGraph::Vertex::lockQuadraticForm () inline
lock for the block of the hessian and the b vector associated with this vertex, to avoid race-conditions if multi-threaded.
Definition at line 300 of file optimizable_graph.h.
 { _quadraticFormMutex.lock();}
virtual void g2o::OptimizableGraph::Vertex::mapHessianMemory (double * d) pure virtual
maps the internal matrix to some external memory location
Implemented in g2o::BaseVertex< D, T >, g2o::BaseVertex< 6, Isometry3D >, g2o::BaseVertex< 3, Eigen::Vector3d >, g2o::BaseVertex< 6, Line3D >, g2o::BaseVertex< 4, Eigen::Matrix< double, 5, 1, Eigen::ColMajor > >, g2o::BaseVertex< 4, Vector4D >, g2o::BaseVertex< 3, SE2 >, g2o::BaseVertex< 2, Vector2D >, g2o::BaseVertex< 1, double >, g2o::BaseVertex< 3, Plane3D >, g2o::BaseVertex< 7, Sim3 >, g2o::BaseVertex< 3, Vector3D >, g2o::BaseVertex< 6, SBACam >, g2o::BaseVertex< 2, Eigen::Vector2d >, g2o::BaseVertex< 2, Line2D >, g2o::BaseVertex< 9, Eigen::VectorXd >, g2o::BaseVertex< 6, SE3Quat >, and g2o::BaseVertex< 6, Vector6d >.
Referenced by g2o::BlockSolver< Traits >::buildStructure(), g2o::StructureOnlySolver< PointDoF >::calc(), g2o::SparseOptimizerIncremental::updateInitialization(), and g2o::BlockSolver< Traits >::updateStructure().
bool g2o::OptimizableGraph::Vertex::marginalized () const inline
true => this node is marginalized out during the optimization
Definition at line 278 of file optimizable_graph.h.
Referenced by g2o::SparseOptimizer::buildIndexMapping(), g2o::BlockSolver< Traits >::buildStructure(), g2o::BlockSolver< Traits >::buildSystem(), g2o::OptimizationAlgorithmWithHessian::init(), g2o::StructureOnlySolver< PointDoF >::init(), main(), g2o::SparseOptimizerIncremental::updateInitialization(), g2o::SparseOptimizer::updateInitialization(), and g2o::BlockSolver< Traits >::updateStructure().
 {return _marginalized;}
int g2o::OptimizableGraph::Vertex::minimalEstimateDimension () const virtual
returns the dimension of the extended representation used by get/setEstimate(double*) -1 if it is not supported
Reimplemented in g2o::VertexCam, g2o::VertexSE3, g2o::deprecated::VertexSE3, g2o::deprecated::VertexPointXYZ, g2o::VertexLine2D, g2o::VertexSE2, g2o::VertexPointXYZ, g2o::VertexSegment2D, and g2o::VertexPointXY.
Definition at line 114 of file optimizable_graph.cpp.
Referenced by g2o::EdgeLabeler::labelEdge(), and testMarginals().
   {
     return -1;
   }
void g2o::OptimizableGraph::Vertex::oplus (const double * v) inline
Update the position of the node from the parameters in v. Depends on the implementation of oplusImpl in derived classes to actually carry out the update. Will also call updateCache() to update the caches of depending on the vertex.
Definition at line 259 of file optimizable_graph.h.
Referenced by g2o::StructureOnlySolver< PointDoF >::calc(), g2o::EdgeLabeler::labelEdge(), g2o::SparseOptimizer::optimize(), and testMarginals().
         {
           oplusImpl(v);
           updateCache();
         }
virtual void g2o::OptimizableGraph::Vertex::oplusImpl (const double * v) protected pure virtual
update the position of the node from the parameters in v. Implement in your class!
Implemented in g2o::VertexSCam, g2o::VertexSBAPointXYZ, VertexPointBAL, g2o::VertexSE3, g2o::VertexSE3Expmap, g2o::deprecated::VertexSE3, g2o::VertexCam, VertexCameraBAL, g2o::VertexLine2D, VertexCircle, g2o::VertexSegment2D, g2o::VertexPointXY, VertexParams, VertexBaseline, VertexPositionVelocity3D, g2o::VertexIntrinsics, VertexVelocity3D, g2o::VertexSim3Expmap, g2o::tutorial::VertexSE2, g2o::deprecated::VertexPointXYZ, g2o::VertexSE2, g2o::VertexPlane, g2o::tutorial::VertexPointXY, g2o::VertexPointXYZ, g2o::VertexLine3D, g2o::OnlineVertexSE2, g2o::OnlineVertexSE3, g2o::VertexOdomDifferentialParams, VertexPosition3D, and VertexPosition3D.
virtual void g2o::OptimizableGraph::Vertex::pop () pure virtual
restore the position of the vertex by retrieving the position from the stack
Implemented in g2o::BaseVertex< D, T >, g2o::BaseVertex< 6, Isometry3D >, g2o::BaseVertex< 3, Eigen::Vector3d >, g2o::BaseVertex< 6, Line3D >, g2o::BaseVertex< 4, Eigen::Matrix< double, 5, 1, Eigen::ColMajor > >, g2o::BaseVertex< 4, Vector4D >, g2o::BaseVertex< 3, SE2 >, g2o::BaseVertex< 2, Vector2D >, g2o::BaseVertex< 1, double >, g2o::BaseVertex< 3, Plane3D >, g2o::BaseVertex< 7, Sim3 >, g2o::BaseVertex< 3, Vector3D >, g2o::BaseVertex< 6, SBACam >, g2o::BaseVertex< 2, Eigen::Vector2d >, g2o::BaseVertex< 2, Line2D >, g2o::BaseVertex< 9, Eigen::VectorXd >, g2o::BaseVertex< 6, SE3Quat >, and g2o::BaseVertex< 6, Vector6d >.
Referenced by g2o::StructureOnlySolver< PointDoF >::calc(), g2o::EdgeLabeler::labelEdge(), g2o::Star::labelStarEdges(), g2o::SparseOptimizer::pop(), g2o::OptimizableGraph::pop(), and testMarginals().
virtual void g2o::OptimizableGraph::Vertex::push () pure virtual
backup the position of the vertex to a stack
Implemented in g2o::BaseVertex< D, T >, g2o::BaseVertex< 6, Isometry3D >, g2o::BaseVertex< 3, Eigen::Vector3d >, g2o::BaseVertex< 6, Line3D >, g2o::BaseVertex< 4, Eigen::Matrix< double, 5, 1, Eigen::ColMajor > >, g2o::BaseVertex< 4, Vector4D >, g2o::BaseVertex< 3, SE2 >, g2o::BaseVertex< 2, Vector2D >, g2o::BaseVertex< 1, double >, g2o::BaseVertex< 3, Plane3D >, g2o::BaseVertex< 7, Sim3 >, g2o::BaseVertex< 3, Vector3D >, g2o::BaseVertex< 6, SBACam >, g2o::BaseVertex< 2, Eigen::Vector2d >, g2o::BaseVertex< 2, Line2D >, g2o::BaseVertex< 9, Eigen::VectorXd >, g2o::BaseVertex< 6, SE3Quat >, and g2o::BaseVertex< 6, Vector6d >.
Referenced by g2o::StructureOnlySolver< PointDoF >::calc(), g2o::SparseOptimizer::computeInitialGuess(), g2o::EdgeLabeler::labelEdge(), g2o::Star::labelStarEdges(), g2o::SparseOptimizer::push(), g2o::OptimizableGraph::push(), and testMarginals().
virtual bool g2o::OptimizableGraph::Vertex::read (std::istream & is) pure virtual
read the vertex from a stream, i.e., the internal state of the vertex
Implemented in g2o::VertexSCam, g2o::VertexSBAPointXYZ, VertexPointBAL, g2o::VertexLine2D, g2o::VertexSE3Expmap, g2o::VertexSegment2D, g2o::VertexPointXY, g2o::VertexSE2, g2o::VertexCam, VertexCameraBAL, VertexPositionVelocity3D, VertexCircle, VertexBaseline, VertexVelocity3D, g2o::VertexSE3, g2o::tutorial::VertexSE2, g2o::tutorial::VertexPointXY, g2o::deprecated::VertexSE3, VertexParams, g2o::VertexIntrinsics, g2o::VertexOdomDifferentialParams, g2o::VertexSim3Expmap, g2o::deprecated::VertexPointXYZ, g2o::VertexPlane, g2o::VertexSE3Euler, g2o::VertexPointXYZ, g2o::VertexLine3D, VertexPosition3D, and VertexPosition3D.
Referenced by g2o::OptimizableGraph::setFixed().
void g2o::OptimizableGraph::Vertex::setColInHessian (int c) inline
set the row of this vertex in the Hessian
Definition at line 289 of file optimizable_graph.h.
Referenced by g2o::BlockSolver< Traits >::buildStructure(), and g2o::BlockSolver< Traits >::updateStructure().
 { _colInHessian = c;}
bool g2o::OptimizableGraph::Vertex::setEstimateData (const double * estimate)
sets the initial estimate from an array of double Implement setEstimateDataImpl()
Returns
true on success
Definition at line 85 of file optimizable_graph.cpp.
References setEstimateDataImpl(), and updateCache().
   {
     bool ret = setEstimateDataImpl(v);
     updateCache();
     return ret;
   }
bool g2o::OptimizableGraph::Vertex::setEstimateData (const std::vector< double > & estimate) inline
sets the initial estimate from an array of double Implement setEstimateDataImpl()
Returns
true on success
Definition at line 165 of file optimizable_graph.h.
{
 #ifndef NDEBUG
           int dim = estimateDimension();
           assert((dim == -1) || (estimate.size() == std::size_t(dim)));
 #endif
           return setEstimateData(&estimate[0]);
         };
virtual bool g2o::OptimizableGraph::Vertex::setEstimateDataImpl (const double *) inline protected virtual
writes the estimater to an array of double
Returns
true on success
Reimplemented in g2o::VertexCam, g2o::VertexSE3, g2o::VertexSE2, g2o::deprecated::VertexSE3, g2o::VertexLine2D, g2o::deprecated::VertexPointXYZ, g2o::VertexPlane, g2o::VertexSegment2D, g2o::VertexPointXYZ, g2o::VertexLine3D, and g2o::VertexPointXY.
Definition at line 339 of file optimizable_graph.h.
Referenced by setEstimateData().
 { return false;}
void g2o::OptimizableGraph::Vertex::setFixed (bool fixed) inline
true => this node should be considered fixed during the optimization
Definition at line 275 of file optimizable_graph.h.
Referenced by g2o::StructureOnlySolver< PointDoF >::calc(), MainWindow::fixGraph(), g2o::G2oSlamInterface::fixNode(), g2o::Star::labelStarEdges(), main(), and g2o::OptimizableGraph::setFixed().
 { _fixed = fixed;}
void g2o::OptimizableGraph::Vertex::setHessianIndex (int ti) inline
set the temporary index of the vertex in the parameter blocks
Definition at line 269 of file optimizable_graph.h.
Referenced by g2o::OptimizableGraph::addGraph(), g2o::SparseOptimizer::buildIndexMapping(), g2o::SparseOptimizerIncremental::updateInitialization(), and g2o::SparseOptimizer::updateInitialization().
 { _hessianIndex = ti;}
virtual void g2o::OptimizableGraph::Vertex::setId (int id) inline virtual
sets the id of the node in the graph be sure that the graph keeps consistent after changing the id
Reimplemented from g2o::HyperGraph::Vertex.
Definition at line 286 of file optimizable_graph.h.
Referenced by g2o::G2oSlamInterface::addVertex(), main(), Robot::move(), PlaneItem::PlaneItem(), g2o::Gm2dlIO::readGm2dl(), and g2o::OptimizableGraph::setFixed().
 {_id = id;}
void g2o::OptimizableGraph::Vertex::setMarginalized (bool marginalized) inline
true => this node should be marginalized out during the optimization
Definition at line 280 of file optimizable_graph.h.
Referenced by main(), and MainWindow::prepare().
 { _marginalized = marginalized;}
bool g2o::OptimizableGraph::Vertex::setMinimalEstimateData (const double * estimate)
sets the initial estimate from an array of double. Implement setMinimalEstimateDataImpl()
Returns
true on success
Definition at line 102 of file optimizable_graph.cpp.
References setMinimalEstimateDataImpl(), and updateCache().
   {
     bool ret = setMinimalEstimateDataImpl(v);
     updateCache();
     return ret;
   }
bool g2o::OptimizableGraph::Vertex::setMinimalEstimateData (const std::vector< double > & estimate) inline
sets the initial estimate from an array of double. Implement setMinimalEstimateDataImpl()
Returns
true on success
Definition at line 209 of file optimizable_graph.h.
{
 #ifndef NDEBUG
           int dim = minimalEstimateDimension();
           assert((dim == -1) || (estimate.size() == std::size_t(dim)));
 #endif
           return setMinimalEstimateData(&estimate[0]);
         };
virtual bool g2o::OptimizableGraph::Vertex::setMinimalEstimateDataImpl (const double *) inline protected virtual
sets the initial estimate from an array of double
Returns
true on success
Reimplemented in g2o::VertexCam, g2o::VertexSE3, g2o::deprecated::VertexSE3, g2o::VertexLine2D, g2o::VertexSE2, g2o::deprecated::VertexPointXYZ, g2o::VertexSegment2D, g2o::VertexPointXYZ, and g2o::VertexPointXY.
Definition at line 345 of file optimizable_graph.h.
Referenced by setMinimalEstimateData().
 { return false;}
void g2o::OptimizableGraph::Vertex::setToOrigin () inline
sets the node to the origin (used in the multilevel stuff)
Definition at line 119 of file optimizable_graph.h.
Referenced by g2o::SparseOptimizer::setToOrigin().
 { setToOriginImpl(); updateCache();}
virtual void g2o::OptimizableGraph::Vertex::setToOriginImpl () protected pure virtual
sets the node to the origin (used in the multilevel stuff)
Implemented in g2o::VertexSBAPointXYZ, VertexPointBAL, g2o::VertexSE3Expmap, VertexCameraBAL, VertexCircle, g2o::VertexCam, VertexParams, VertexBaseline, VertexPositionVelocity3D, g2o::VertexSE3, g2o::VertexLine2D, g2o::VertexIntrinsics, VertexVelocity3D, g2o::deprecated::VertexSE3, g2o::VertexSim3Expmap, g2o::VertexSegment2D, g2o::deprecated::VertexPointXYZ, g2o::VertexPlane, g2o::tutorial::VertexSE2, g2o::VertexSE2, g2o::VertexPointXYZ, g2o::tutorial::VertexPointXY, g2o::VertexPointXY, g2o::VertexLine3D, g2o::VertexOdomDifferentialParams, VertexPosition3D, and VertexPosition3D.
virtual double g2o::OptimizableGraph::Vertex::solveDirect (double lambda = 0) pure virtual
updates the current vertex with the direct solution x += H_ii
Returns
the determinant of the inverted hessian
Implemented in g2o::BaseVertex< D, T >, g2o::BaseVertex< 6, Isometry3D >, g2o::BaseVertex< 3, Eigen::Vector3d >, g2o::BaseVertex< 6, Line3D >, g2o::BaseVertex< 4, Eigen::Matrix< double, 5, 1, Eigen::ColMajor > >, g2o::BaseVertex< 4, Vector4D >, g2o::BaseVertex< 3, SE2 >, g2o::BaseVertex< 2, Vector2D >, g2o::BaseVertex< 1, double >, g2o::BaseVertex< 3, Plane3D >, g2o::BaseVertex< 7, Sim3 >, g2o::BaseVertex< 3, Vector3D >, g2o::BaseVertex< 6, SBACam >, g2o::BaseVertex< 2, Eigen::Vector2d >, g2o::BaseVertex< 2, Line2D >, g2o::BaseVertex< 9, Eigen::VectorXd >, g2o::BaseVertex< 6, SE3Quat >, and g2o::BaseVertex< 6, Vector6d >.
Referenced by g2o::computeSimpleStars().
virtual int g2o::OptimizableGraph::Vertex::stackSize () const pure virtual
return the stack size
Implemented in g2o::BaseVertex< D, T >, g2o::BaseVertex< 6, Isometry3D >, g2o::BaseVertex< 3, Eigen::Vector3d >, g2o::BaseVertex< 6, Line3D >, g2o::BaseVertex< 4, Eigen::Matrix< double, 5, 1, Eigen::ColMajor > >, g2o::BaseVertex< 4, Vector4D >, g2o::BaseVertex< 3, SE2 >, g2o::BaseVertex< 2, Vector2D >, g2o::BaseVertex< 1, double >, g2o::BaseVertex< 3, Plane3D >, g2o::BaseVertex< 7, Sim3 >, g2o::BaseVertex< 3, Vector3D >, g2o::BaseVertex< 6, SBACam >, g2o::BaseVertex< 2, Eigen::Vector2d >, g2o::BaseVertex< 2, Line2D >, g2o::BaseVertex< 9, Eigen::VectorXd >, g2o::BaseVertex< 6, SE3Quat >, and g2o::BaseVertex< 6, Vector6d >.
void g2o::OptimizableGraph::Vertex::unlockQuadraticForm () inline
unlock the block of the hessian and the b vector associated with this vertex
Definition at line 304 of file optimizable_graph.h.
 { _quadraticFormMutex.unlock();}
void g2o::OptimizableGraph::Vertex::updateCache () virtual
Definition at line 67 of file optimizable_graph.cpp.
References _cacheContainer, g2o::CacheContainer::setUpdateNeeded(), and g2o::CacheContainer::update().
Referenced by g2o::BaseVertex< 6, Vector6d >::pop(), g2o::deprecated::VertexSE3::read(), g2o::BaseVertex< 6, Vector6d >::setEstimate(), setEstimateData(), setMinimalEstimateData(), g2o::deprecated::VertexSE3::VertexSE3(), and g2o::VertexSE3::VertexSE3().
{
     if (_cacheContainer){
       _cacheContainer->setUpdateNeeded();
       _cacheContainer->update();
     }
   }
virtual bool g2o::OptimizableGraph::Vertex::write (std::ostream & os) const pure virtual
write the vertex to a stream
Implemented in g2o::VertexSCam, g2o::VertexSBAPointXYZ, VertexPointBAL, g2o::VertexSE3Expmap, g2o::VertexLine2D, g2o::VertexSegment2D, g2o::VertexPointXY, g2o::VertexSE2, VertexCameraBAL, g2o::VertexCam, VertexPositionVelocity3D, VertexCircle, VertexVelocity3D, VertexBaseline, g2o::VertexSE3, VertexParams, g2o::tutorial::VertexSE2, g2o::tutorial::VertexPointXY, g2o::deprecated::VertexSE3, g2o::VertexIntrinsics, g2o::VertexOdomDifferentialParams, g2o::VertexSim3Expmap, g2o::deprecated::VertexPointXYZ, g2o::VertexPlane, g2o::VertexSE3Euler, g2o::VertexPointXYZ, g2o::VertexLine3D, VertexPosition3D, and VertexPosition3D.
Referenced by g2o::OptimizableGraph::saveVertex(), and g2o::Gm2dlIO::writeGm2dl().
Friends And Related Function Documentation
friend struct OptimizableGraph friend
Definition at line 109 of file optimizable_graph.h.
Member Data Documentation
CacheContainer* g2o::OptimizableGraph::Vertex::_cacheContainer protected
Definition at line 324 of file optimizable_graph.h.
Referenced by cacheContainer(), updateCache(), and ~Vertex().
int g2o::OptimizableGraph::Vertex::_colInHessian protected
Definition at line 321 of file optimizable_graph.h.
int g2o::OptimizableGraph::Vertex::_dimension protected
Definition at line 320 of file optimizable_graph.h.
bool g2o::OptimizableGraph::Vertex::_fixed protected
Definition at line 318 of file optimizable_graph.h.
OptimizableGraph* g2o::OptimizableGraph::Vertex::_graph protected
Definition at line 315 of file optimizable_graph.h.
Referenced by g2o::OptimizableGraph::addVertex().
int g2o::OptimizableGraph::Vertex::_hessianIndex protected
Definition at line 317 of file optimizable_graph.h.
bool g2o::OptimizableGraph::Vertex::_marginalized protected
Definition at line 319 of file optimizable_graph.h.
Referenced by g2o::VertexSim3Expmap::VertexSim3Expmap().
OpenMPMutex g2o::OptimizableGraph::Vertex::_quadraticFormMutex protected
Definition at line 322 of file optimizable_graph.h.
Data* g2o::OptimizableGraph::Vertex::_userData protected
Definition at line 316 of file optimizable_graph.h.
Referenced by ~Vertex().
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/core/optimizable_graph.h
/home/xuezhisd/CLionProjects/g2o/g2o/core/optimizable_graph.cpp