g2o: g2o::SensorPointXYZDepth Class Reference
g2o::SensorPointXYZDepth Class Reference
#include <sensor_pointxyz_depth.h>
Public Member Functions
SensorPointXYZDepth (const std::string &name_)
virtual void sense ()
virtual void addParameters ()
ParameterSE3Offset * offsetParam ()
void addNoise (EdgeType *e)
Public Member Functions inherited from g2o::PointSensorParameters
PointSensorParameters ()
double maxRange () const
void setMaxRange (double maxRange_)
double minRange () const
void setMinRange (double minRange_)
double fov () const
void setFov (double fov_)
double maxAngularDifference () const
void setMaxAngularDifference (double angularDifference)
Public Member Functions inherited from g2o::BinarySensor< Robot3D, EdgeSE3PointXYZDepth, WorldObjectTrackXYZ >
BinarySensor (const std::string &name)
void setInformation (const InformationType &information_)
const InformationType & information ()
Public Member Functions inherited from g2o::BaseSensor
BaseSensor (const std::string &name_)
BaseRobot * robot ()
void setRobot (BaseRobot *robot_)
World * world ()
OptimizableGraph * graph ()
std::vector< Parameter * > parameters ()
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef PoseVertexType::EstimateType RobotPoseType
Public Attributes inherited from g2o::BinarySensor< Robot3D, EdgeSE3PointXYZDepth, WorldObjectTrackXYZ >
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Member Functions
bool isVisible (WorldObjectType *to)
Protected Member Functions inherited from g2o::BinarySensor< Robot3D, EdgeSE3PointXYZDepth, WorldObjectTrackXYZ >
EdgeType * mkEdge (WorldObjectType *object)
Protected Attributes
RobotPoseType _sensorPose
ParameterSE3Offset * _offsetParam
Protected Attributes inherited from g2o::PointSensorParameters
double _maxRange2
double _minRange2
double _fov
double _maxAngularDifference
Protected Attributes inherited from g2o::BinarySensor< Robot3D, EdgeSE3PointXYZDepth, WorldObjectTrackXYZ >
PoseObject * _robotPoseObject
InformationType _information
GaussianSampler< typename EdgeType::ErrorVector, InformationType > _sampler
Protected Attributes inherited from g2o::BaseSensor
std::string _name
std::vector< Parameter * > _parameters
BaseRobot * _robot
Additional Inherited Members
Public Types inherited from g2o::BinarySensor< Robot3D, EdgeSE3PointXYZDepth, WorldObjectTrackXYZ >
typedef Robot3D RobotType
typedef RobotType::PoseObject PoseObject
typedef RobotType::TrajectoryType TrajectoryType
typedef RobotType::PoseObject::VertexType PoseVertexType
typedef EdgeSE3PointXYZDepth EdgeType
typedef WorldObjectTrackXYZ WorldObjectType
typedef WorldObjectType::VertexType VertexType
typedef EdgeType::InformationType InformationType
Detailed Description
Definition at line 35 of file sensor_pointxyz_depth.h.
Constructor & Destructor Documentation
g2o::SensorPointXYZDepth::SensorPointXYZDepth (const std::string & name_)
Definition at line 34 of file sensor_pointxyz_depth.cpp.
References g2o::BinarySensor< Robot3D, EdgeSE3PointXYZDepth, WorldObjectTrackXYZ >::_information, _offsetParam, and g2o::BinarySensor< Robot3D, EdgeSE3PointXYZDepth, WorldObjectTrackXYZ >::setInformation().
                                                                 : BinarySensor<Robot3D, EdgeSE3PointXYZDepth, WorldObjectTrackXYZ>(name_) {
     _offsetParam = 0;
     _information.setIdentity();
     _information*=1000;
     setInformation(_information);
   }
Member Function Documentation
void g2o::SensorPointXYZDepth::addNoise (EdgeType * e) virtual
Reimplemented from g2o::BinarySensor< Robot3D, EdgeSE3PointXYZDepth, WorldObjectTrackXYZ >.
Definition at line 69 of file sensor_pointxyz_depth.cpp.
References g2o::BinarySensor< Robot3D, EdgeSE3PointXYZDepth, WorldObjectTrackXYZ >::_sampler, g2o::GaussianSampler< SampleType, CovarianceType >::generateSample(), g2o::BinarySensor< Robot3D, EdgeSE3PointXYZDepth, WorldObjectTrackXYZ >::information(), g2o::BaseEdge< D, E >::measurement(), g2o::BaseEdge< D, E >::setInformation(), and g2o::EdgeSE3PointXYZDepth::setMeasurement().
Referenced by sense().
{
     EdgeType::ErrorVector n=_sampler.generateSample();
     e->setMeasurement(e->measurement()+n);
     e->setInformation(information());
   }
void g2o::SensorPointXYZDepth::addParameters () virtual
Reimplemented from g2o::BaseSensor.
Definition at line 62 of file sensor_pointxyz_depth.cpp.
References _offsetParam, g2o::World::addParameter(), and g2o::BaseSensor::world().
{
     if (!_offsetParam)
       _offsetParam = new ParameterCamera();
     assert(world());
     world()->addParameter(_offsetParam);
   }
bool g2o::SensorPointXYZDepth::isVisible (SensorPointXYZDepth::WorldObjectType * to) protected
Definition at line 41 of file sensor_pointxyz_depth.cpp.
References g2o::PointSensorParameters::_fov, g2o::PointSensorParameters::_maxRange2, g2o::PointSensorParameters::_minRange2, g2o::BinarySensor< Robot3D, EdgeSE3PointXYZDepth, WorldObjectTrackXYZ >::_robotPoseObject, _sensorPose, and g2o::WorldObject< VertexType_ >::vertex().
Referenced by sense().
{
     if (! _robotPoseObject)
       return false;
     assert(to && to->vertex());
     VertexType* v=to->vertex();
     VertexType::EstimateType pose=v->estimate();
     VertexType::EstimateType delta = _sensorPose.inverse()*pose;
     Vector3d translation=delta;
     double range2=translation.squaredNorm();
     if (range2>_maxRange2)
       return false;
     if (range2<_minRange2)
       return false;
     translation.normalize();
     // the cameras have the z in front
     double bearing=acos(translation.z());
     if (fabs(bearing)>_fov)
        return false;
     return true;
   }
ParameterSE3Offset* g2o::SensorPointXYZDepth::offsetParam () inline
Definition at line 42 of file sensor_pointxyz_depth.h.
Referenced by main().
 {return _offsetParam;};
void g2o::SensorPointXYZDepth::sense () virtual
Reimplemented from g2o::BinarySensor< Robot3D, EdgeSE3PointXYZDepth, WorldObjectTrackXYZ >.
Definition at line 75 of file sensor_pointxyz_depth.cpp.
References _offsetParam, g2o::BinarySensor< Robot3D, EdgeSE3PointXYZDepth, WorldObjectTrackXYZ >::_robotPoseObject, _sensorPose, g2o::OptimizableGraph::addEdge(), addNoise(), g2o::BaseSensor::graph(), g2o::Parameter::id(), isVisible(), g2o::BinarySensor< Robot3D, EdgeSE3PointXYZDepth, WorldObjectTrackXYZ >::mkEdge(), g2o::World::objects(), g2o::ParameterSE3Offset::offset(), g2o::BaseSensor::robot(), g2o::EdgeSE3PointXYZDepth::setMeasurementFromState(), g2o::OptimizableGraph::Edge::setParameterId(), g2o::Robot< RobotPoseObject >::trajectory(), and g2o::BaseSensor::world().
{
     if (! _offsetParam){
       return;
     }
     _robotPoseObject=0;
     RobotType* r= dynamic_cast<RobotType*>(robot());
     std::list<PoseObject*>::reverse_iterator it=r->trajectory().rbegin();
     int count = 0;
     while (it!=r->trajectory().rend() && count < 1){
       if (!_robotPoseObject)
   _robotPoseObject = *it;
       it++;
       count++;
     }
     if (!_robotPoseObject)
       return;
     _sensorPose = _robotPoseObject->vertex()->estimate()*_offsetParam->offset();
     for (std::set<BaseWorldObject*>::iterator it=world()->objects().begin();
    it!=world()->objects().end(); it++){
       WorldObjectType* o=dynamic_cast<WorldObjectType*>(*it);
       if (o && isVisible(o)){
   EdgeType* e=mkEdge(o);
   e->setParameterId(0,_offsetParam->id());
   if (e && graph()) {
     graph()->addEdge(e);
     e->setMeasurementFromState();
           addNoise(e);
   }
       }
     }
   }
Member Data Documentation
ParameterSE3Offset* g2o::SensorPointXYZDepth::_offsetParam protected
Definition at line 47 of file sensor_pointxyz_depth.h.
Referenced by addParameters(), sense(), and SensorPointXYZDepth().
RobotPoseType g2o::SensorPointXYZDepth::_sensorPose protected
Definition at line 46 of file sensor_pointxyz_depth.h.
Referenced by isVisible(), and sense().
EIGEN_MAKE_ALIGNED_OPERATOR_NEW typedef PoseVertexType::EstimateType g2o::SensorPointXYZDepth::RobotPoseType
Definition at line 38 of file sensor_pointxyz_depth.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_simulator/sensor_pointxyz_depth.h
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_simulator/sensor_pointxyz_depth.cpp