g2o: g2o::SLAM2DLinearSolverCreator Class Reference
g2o::SLAM2DLinearSolverCreator Class Reference
Public Member Functions
SLAM2DLinearSolverCreator (const OptimizationAlgorithmProperty &p)
virtual OptimizationAlgorithm * construct ()
allocate a solver operating on optimizer, re-implement for your creator
Public Member Functions inherited from g2o::AbstractOptimizationAlgorithmCreator
AbstractOptimizationAlgorithmCreator (const OptimizationAlgorithmProperty &p)
virtual ~AbstractOptimizationAlgorithmCreator ()
const OptimizationAlgorithmProperty & property () const
return the properties of the solver
Additional Inherited Members
Protected Attributes inherited from g2o::AbstractOptimizationAlgorithmCreator
OptimizationAlgorithmProperty _property
Detailed Description
Definition at line 67 of file slam2d_linear.cpp.
Constructor & Destructor Documentation
g2o::SLAM2DLinearSolverCreator::SLAM2DLinearSolverCreator (const OptimizationAlgorithmProperty & p) inline
Definition at line 70 of file slam2d_linear.cpp.
Referenced by construct().
 : AbstractOptimizationAlgorithmCreator(p) {}
Member Function Documentation
virtual OptimizationAlgorithm* g2o::SLAM2DLinearSolverCreator::construct () inline virtual
allocate a solver operating on optimizer, re-implement for your creator
Implements g2o::AbstractOptimizationAlgorithmCreator.
Definition at line 71 of file slam2d_linear.cpp.
References g2o::createSolver(), g2o::G2O_REGISTER_OPTIMIZATION_ALGORITHM(), g2o::G2O_REGISTER_OPTIMIZATION_LIBRARY(), g2o::AbstractOptimizationAlgorithmCreator::property(), and SLAM2DLinearSolverCreator().
       {
         return createSolver(property().name);
       }
The documentation for this class was generated from the following file:
/home/xuezhisd/CLionProjects/g2o/g2o/solvers/slam2d_linear/slam2d_linear.cpp