g2o: g2o::HyperGraph::Vertex Class Reference
g2o::HyperGraph::Vertex Class Reference
abstract Vertex, your types must derive from that one
#include <hyper_graph.h>
Public Member Functions
Vertex (int id=InvalidId)
creates a vertex having an ID specified by the argument
virtual ~Vertex ()
int id () const
returns the id
virtual void setId (int newId)
const EdgeSet & edges () const
returns the set of hyper-edges that are leaving/entering in this vertex
EdgeSet & edges ()
returns the set of hyper-edges that are leaving/entering in this vertex
virtual HyperGraphElementType elementType () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Protected Attributes
int _id
EdgeSet _edges
Detailed Description
abstract Vertex, your types must derive from that one
Definition at line 142 of file hyper_graph.h.
Constructor & Destructor Documentation
g2o::HyperGraph::Vertex::Vertex (int id = InvalidId) explicit
creates a vertex having an ID specified by the argument
Definition at line 43 of file hyper_graph.cpp.
                                  : _id(id)
   {
   }
g2o::HyperGraph::Vertex::~Vertex () virtual
Reimplemented in g2o::OptimizableGraph::Vertex.
Definition at line 47 of file hyper_graph.cpp.
   {
   }
Member Function Documentation
const EdgeSet& g2o::HyperGraph::Vertex::edges () const inline
returns the set of hyper-edges that are leaving/entering in this vertex
Definition at line 151 of file hyper_graph.h.
Referenced by g2o::activeVertexChi(), g2o::HyperGraph::addEdge(), g2o::OptimizableGraph::addGraph(), g2o::BlockSolver< Traits >::buildStructure(), g2o::StructureOnlySolver< PointDoF >::calc(), g2o::SparseOptimizer::computeInitialGuess(), g2o::computeSimpleStars(), g2o::HyperGraph::detachVertex(), g2o::SparseOptimizer::gaugeFreedom(), g2o::SparseOptimizer::initializeOptimization(), main(), g2o::HyperGraph::mergeVertices(), g2o::EstimatePropagator::propagate(), g2o::HyperGraph::removeEdge(), g2o::HyperGraph::removeVertex(), g2o::HyperGraph::setEdgeVertex(), g2o::HyperDijkstra::shortestPaths(), g2o::starsInVertex(), and g2o::vertexEdgesInStar().
 {return _edges;}
EdgeSet& g2o::HyperGraph::Vertex::edges () inline
returns the set of hyper-edges that are leaving/entering in this vertex
Definition at line 153 of file hyper_graph.h.
 {return _edges;}
virtual HyperGraphElementType g2o::HyperGraph::Vertex::elementType () const inline virtual
returns the type of the graph element, see HyperGraphElementType
Implements g2o::HyperGraph::HyperGraphElement.
Definition at line 154 of file hyper_graph.h.
References HGET_VERTEX.
 { return HGET_VERTEX;}
int g2o::HyperGraph::Vertex::id () const inline
returns the id
Definition at line 148 of file hyper_graph.h.
Referenced by g2o::G2oSlamInterface::addEdge(), g2o::OptimizableGraph::addGraph(), g2o::addOdometryCalibLinksDifferential(), g2o::HyperGraph::addVertex(), g2o::OptimizableGraph::addVertex(), anonymizePoseEdge(), g2o::HyperGraph::changeId(), g2o::HyperGraph::detachVertex(), MainWindow::fixGraph(), g2o::EdgeSE2TwoPointsXY::initialEstimate(), g2o::EdgeSE3LotsOfXYZ::initialEstimate(), g2o::EdgeSE2LotsOfXY::initialEstimate(), TargetOdometry3DEdge::initialEstimatePossible(), g2o::SparseOptimizer::initializeOptimization(), g2o::Star::labelStarEdges(), LineInfo::LineInfo(), main(), g2o::HyperGraph::mergeVertices(), g2o::EstimatePropagatorCostOdometry::operator()(), g2o::OptimizableGraph::VertexIDCompare::operator()(), g2o::EstimatePropagator::VertexIDHashFunction::operator()(), g2o::SparseOptimizer::optimize(), g2o::G2oSlamInterface::printVertex(), g2o::EstimatePropagator::propagate(), g2o::HyperGraph::removeVertex(), g2o::OptimizableGraph::saveVertex(), g2o::OptimizableGraph::setFixed(), MainWindow::setRobustKernel(), g2o::HyperDijkstra::shortestPaths(), testMarginals(), g2o::Gm2dlIO::updateLaserData(), g2o::OptimizableGraph::verifyInformationMatrices(), and g2o::Gm2dlIO::writeGm2dl().
 {return _id;}
virtual void g2o::HyperGraph::Vertex::setId (int newId) inline virtual
Reimplemented in g2o::OptimizableGraph::Vertex.
Definition at line 149 of file hyper_graph.h.
Referenced by g2o::addOdometryCalibLinksDifferential(), and g2o::HyperGraph::changeId().
 { _id=newId; }
Member Data Documentation
EdgeSet g2o::HyperGraph::Vertex::_edges protected
Definition at line 157 of file hyper_graph.h.
int g2o::HyperGraph::Vertex::_id protected
Definition at line 156 of file hyper_graph.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/core/hyper_graph.h
/home/xuezhisd/CLionProjects/g2o/g2o/core/hyper_graph.cpp