g2o: g2o::HyperGraphElementAction Class Reference
g2o::HyperGraphElementAction Class Reference
Abstract action that operates on a graph entity.
#include <hyper_graph_action.h>
Classes
struct Parameters
Public Types
typedef std::map< std::string, HyperGraphElementAction * > ActionMap
Public Member Functions
HyperGraphElementAction (const std::string &typeName_="")
virtual HyperGraphElementAction * operator() (HyperGraph::HyperGraphElement *element, Parameters *parameters)
redefine this to do the action stuff. If successful, the action returns a pointer to itself
virtual HyperGraphElementAction * operator() (const HyperGraph::HyperGraphElement *element, Parameters *parameters)
redefine this to do the action stuff. If successful, the action returns a pointer to itself
virtual ~HyperGraphElementAction ()
destroyed actions release the memory
const std::string & typeName () const
returns the typeid name of the action
const std::string & name () const
returns the name of an action, e.g "draw"
void setTypeName (const std::string &typeName_)
sets the type on which an action has to operate
Protected Attributes
std::string _typeName
std::string _name
Detailed Description
Abstract action that operates on a graph entity.
Definition at line 74 of file hyper_graph_action.h.
Member Typedef Documentation
typedef std::map<std::string, HyperGraphElementAction*> g2o::HyperGraphElementAction::ActionMap
Definition at line 79 of file hyper_graph_action.h.
Constructor & Destructor Documentation
g2o::HyperGraphElementAction::HyperGraphElementAction (const std::string & typeName_ = "")
an action should be instantiated with the typeid.name of the graph element on which it operates
Definition at line 63 of file hyper_graph_action.cpp.
   {
     _typeName = typeName_;
   }
g2o::HyperGraphElementAction::~HyperGraphElementAction () virtual
destroyed actions release the memory
Definition at line 84 of file hyper_graph_action.cpp.
   {
   }
Member Function Documentation
const std::string& g2o::HyperGraphElementAction::name () const inline
returns the name of an action, e.g "draw"
Definition at line 97 of file hyper_graph_action.h.
Referenced by g2o::applyAction(), g2o::EdgeSE3WriteGnuplotAction::operator()(), g2o::EdgeSE2PointXYBearingWriteGnuplotAction::operator()(), g2o::EdgeSE2PointXYWriteGnuplotAction::operator()(), g2o::VertexPointXYWriteGnuplotAction::operator()(), g2o::VertexSE2WriteGnuplotAction::operator()(), g2o::VertexSegment2DWriteGnuplotAction::operator()(), g2o::EdgeSE2WriteGnuplotAction::operator()(), g2o::deprecated::VertexSE3WriteGnuplotAction::operator()(), g2o::deprecated::EdgeSE3WriteGnuplotAction::operator()(), g2o::VertexSE3WriteGnuplotAction::operator()(), g2o::HyperGraphElementActionCollection::registerAction(), and g2o::HyperGraphActionLibrary::registerAction().
 { return _name;}
HyperGraphElementAction * g2o::HyperGraphElementAction::operator() (HyperGraph::HyperGraphElement * element, HyperGraphElementAction::Parameters * parameters) virtual
redefine this to do the action stuff. If successful, the action returns a pointer to itself
Reimplemented in g2o::VertexSE3WriteGnuplotAction, g2o::HyperGraphElementActionCollection, g2o::deprecated::EdgeSE3WriteGnuplotAction, g2o::deprecated::VertexSE3WriteGnuplotAction, g2o::EdgeSE2WriteGnuplotAction, g2o::VertexSegment2DWriteGnuplotAction, g2o::deprecated::VertexPointXYZWriteGnuplotAction, g2o::VertexPointXYWriteGnuplotAction, g2o::VertexSE2WriteGnuplotAction, g2o::VertexPointXYZWriteGnuplotAction, g2o::EdgeSE2PointXYWriteGnuplotAction, g2o::EdgeSE2PointXYBearingWriteGnuplotAction, and g2o::EdgeSE3WriteGnuplotAction.
Definition at line 74 of file hyper_graph_action.cpp.
   {
     return 0;
   }
HyperGraphElementAction * g2o::HyperGraphElementAction::operator() (const HyperGraph::HyperGraphElement * element, HyperGraphElementAction::Parameters * parameters) virtual
redefine this to do the action stuff. If successful, the action returns a pointer to itself
Reimplemented in g2o::HyperGraphElementActionCollection.
Definition at line 79 of file hyper_graph_action.cpp.
   {
     return 0;
   }
void g2o::HyperGraphElementAction::setTypeName (const std::string & typeName_)
sets the type on which an action has to operate
Definition at line 68 of file hyper_graph_action.cpp.
Referenced by g2o::G2O_ATTRIBUTE_CONSTRUCTOR().
   {
     _typeName = typeName_;
   }
const std::string& g2o::HyperGraphElementAction::typeName () const inline
returns the typeid name of the action
Definition at line 94 of file hyper_graph_action.h.
Referenced by g2o::applyAction(), and g2o::HyperGraphElementActionCollection::registerAction().
 { return _typeName;}
Member Data Documentation
std::string g2o::HyperGraphElementAction::_name protected
Definition at line 104 of file hyper_graph_action.h.
Referenced by g2o::DrawAction::DrawAction(), and g2o::WriteGnuplotAction::WriteGnuplotAction().
std::string g2o::HyperGraphElementAction::_typeName protected
Definition at line 103 of file hyper_graph_action.h.
Referenced by g2o::EdgeSE3WriteGnuplotAction::operator()(), g2o::EdgeSE2PointXYBearingWriteGnuplotAction::operator()(), g2o::EdgeSE2PointXYWriteGnuplotAction::operator()(), g2o::VertexPointXYZWriteGnuplotAction::operator()(), g2o::VertexPointXYWriteGnuplotAction::operator()(), g2o::VertexSE2WriteGnuplotAction::operator()(), g2o::deprecated::VertexPointXYZWriteGnuplotAction::operator()(), g2o::VertexSegment2DWriteGnuplotAction::operator()(), g2o::EdgeSE2WriteGnuplotAction::operator()(), g2o::deprecated::VertexSE3WriteGnuplotAction::operator()(), g2o::deprecated::EdgeSE3WriteGnuplotAction::operator()(), g2o::VertexSE3WriteGnuplotAction::operator()(), and g2o::DrawAction::refreshPropertyPtrs().
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/core/hyper_graph_action.h
/home/xuezhisd/CLionProjects/g2o/g2o/core/hyper_graph_action.cpp