g2o: ViewerPropertiesWidget Class Reference
ViewerPropertiesWidget Class Reference
#include <viewer_properties_widget.h>
Public Member Functions
ViewerPropertiesWidget (QWidget *parent=0, Qt::WindowFlags f=0)
virtual ~ViewerPropertiesWidget ()
void setViewer (g2o::G2oQGLViewer *viewer)
Public Member Functions inherited from PropertiesWidget
PropertiesWidget (QWidget *parent=0, Qt::WindowFlags f=0)
virtual ~PropertiesWidget ()
void setProperties (g2o::PropertyMap *properties)
Protected Member Functions
virtual void applyProperties ()
virtual std::string humanReadablePropName (const std::string &probName) const
Protected Member Functions inherited from PropertiesWidget
virtual void updateDisplayedProperties ()
Protected Attributes
g2o::G2oQGLViewer * _viewer
Protected Attributes inherited from PropertiesWidget
std::vector< std::string > _propNames
g2o::PropertyMap * _properties
Additional Inherited Members
Public Slots inherited from PropertiesWidget
void on_btnApply_clicked ()
void on_btnOK_clicked ()
Detailed Description
Definition at line 30 of file viewer_properties_widget.h.
Constructor & Destructor Documentation
ViewerPropertiesWidget::ViewerPropertiesWidget (QWidget * parent = 0, Qt::WindowFlags f = 0)
Definition at line 70 of file viewer_properties_widget.cpp.
                                                                                 :
   PropertiesWidget(parent, f)
 {
 }
ViewerPropertiesWidget::~ViewerPropertiesWidget () virtual
Definition at line 75 of file viewer_properties_widget.cpp.
 {
 }
Member Function Documentation
void ViewerPropertiesWidget::applyProperties () protected virtual
Reimplemented from PropertiesWidget.
Definition at line 79 of file viewer_properties_widget.cpp.
References _viewer, PropertiesWidget::applyProperties(), and g2o::G2oQGLViewer::setUpdateDisplay().
 {
   PropertiesWidget::applyProperties();
   // draw with the new properties
   _viewer->setUpdateDisplay(true);
   _viewer->updateGL();
 }
std::string ViewerPropertiesWidget::humanReadablePropName (const std::string & probName) const protected virtual
Reimplemented from PropertiesWidget.
Definition at line 94 of file viewer_properties_widget.cpp.
References demangleName().
 {
   return demangleName(propertyName);
 }
void ViewerPropertiesWidget::setViewer (g2o::G2oQGLViewer * viewer)
Definition at line 88 of file viewer_properties_widget.cpp.
References _viewer, g2o::G2oQGLViewer::parameters(), and PropertiesWidget::setProperties().
Referenced by MainWindow::on_actionProperties_triggered().
 {
   _viewer = viewer;
   setProperties(viewer->parameters());
 }
Member Data Documentation
g2o::G2oQGLViewer* ViewerPropertiesWidget::_viewer protected
Definition at line 39 of file viewer_properties_widget.h.
Referenced by applyProperties(), and setViewer().
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_viewer/viewer_properties_widget.h
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_viewer/viewer_properties_widget.cpp