g2o: g2o::SparseBlockMatrixCCS< MatrixType > Class Template Reference
g2o::SparseBlockMatrixCCS< MatrixType > Class Template Reference
Sparse matrix which uses blocks.
#include <sparse_block_matrix_ccs.h>
Classes
struct RowBlock
A block within a column.
Public Types
typedef MatrixType SparseMatrixBlock
this is the type of the elementary block, it is an Eigen::Matrix.
typedef std::vector< RowBlock > SparseColumn
Public Member Functions
int cols () const
columns of the matrix
int rows () const
rows of the matrix
SparseBlockMatrixCCS (const std::vector< int > &rowIndices, const std::vector< int > &colIndices)
int rowsOfBlock (int r) const
how many rows does the block at block-row r has?
int colsOfBlock (int c) const
how many cols does the block at block-col c has?
int rowBaseOfBlock (int r) const
where does the row at block-row r start?
int colBaseOfBlock (int c) const
where does the col at block-col r start?
const std::vector< SparseColumn > & blockCols () const
the block matrices per block-column
std::vector< SparseColumn > & blockCols ()
const std::vector< int > & rowBlockIndices () const
indices of the row blocks
const std::vector< int > & colBlockIndices () const
indices of the column blocks
void rightMultiply (double *&dest, const double *src) const
void sortColumns ()
int fillCCS (int *Cp, int *Ci, double *Cx, bool upperTriangle=false) const
int fillCCS (double *Cx, bool upperTriangle=false) const
Protected Attributes
const std::vector< int > & _rowBlockIndices
vector of the indices of the blocks along the rows.
const std::vector< int > & _colBlockIndices
vector of the indices of the blocks along the cols
std::vector< SparseColumn > _blockCols
the matrices stored in CCS order
Detailed Description
template<class MatrixType>
class g2o::SparseBlockMatrixCCS< MatrixType >
Sparse matrix which uses blocks.
This class is used as a const view on a SparseBlockMatrix which allows a faster iteration over the elements of the matrix.
Definition at line 49 of file sparse_block_matrix_ccs.h.
Member Typedef Documentation
template<class MatrixType> typedef std::vector<RowBlock> g2o::SparseBlockMatrixCCS< MatrixType >::SparseColumn
Definition at line 71 of file sparse_block_matrix_ccs.h.
template<class MatrixType> typedef MatrixType g2o::SparseBlockMatrixCCS< MatrixType >::SparseMatrixBlock
this is the type of the elementary block, it is an Eigen::Matrix.
Definition at line 53 of file sparse_block_matrix_ccs.h.
Constructor & Destructor Documentation
template<class MatrixType> g2o::SparseBlockMatrixCCS< MatrixType >::SparseBlockMatrixCCS (const std::vector< int > & rowIndices, const std::vector< int > & colIndices) inline
Definition at line 73 of file sparse_block_matrix_ccs.h.
                                                                                                :
         _rowBlockIndices(rowIndices), _colBlockIndices(colIndices)
       {}
Member Function Documentation
template<class MatrixType> const std::vector<SparseColumn>& g2o::SparseBlockMatrixCCS< MatrixType >::blockCols () const inline
the block matrices per block-column
Definition at line 90 of file sparse_block_matrix_ccs.h.
Referenced by g2o::SparseBlockMatrix< MatrixType >::fillSparseBlockMatrixCCS(), g2o::SparseBlockMatrix< MatrixType >::fillSparseBlockMatrixCCSTransposed(), and g2o::BlockSolver< Traits >::solve().
 { return _blockCols;}
template<class MatrixType> std::vector<SparseColumn>& g2o::SparseBlockMatrixCCS< MatrixType >::blockCols () inline
Definition at line 91 of file sparse_block_matrix_ccs.h.
 { return _blockCols;}
template<class MatrixType> int g2o::SparseBlockMatrixCCS< MatrixType >::colBaseOfBlock (int c) const inline
where does the col at block-col r start?
Definition at line 87 of file sparse_block_matrix_ccs.h.
Referenced by g2o::SparseBlockMatrixCCS< PoseMatrixType >::rightMultiply().
 { return c ? _colBlockIndices[c-1] : 0 ; }
template<class MatrixType> const std::vector<int>& g2o::SparseBlockMatrixCCS< MatrixType >::colBlockIndices () const inline
indices of the column blocks
Definition at line 97 of file sparse_block_matrix_ccs.h.
 { return _colBlockIndices;}
template<class MatrixType> int g2o::SparseBlockMatrixCCS< MatrixType >::cols () const inline
columns of the matrix
Definition at line 56 of file sparse_block_matrix_ccs.h.
Referenced by g2o::SparseBlockMatrixCCS< PoseMatrixType >::rightMultiply().
 {return _colBlockIndices.size() ? _colBlockIndices.back() : 0;}
template<class MatrixType> int g2o::SparseBlockMatrixCCS< MatrixType >::colsOfBlock (int c) const inline
how many cols does the block at block-col c has?
Definition at line 81 of file sparse_block_matrix_ccs.h.
Referenced by g2o::SparseBlockMatrixHashMap< MatrixType >::addBlock(), and g2o::SparseBlockMatrixCCS< PoseMatrixType >::fillCCS().
 { return c ? _colBlockIndices[c] - _colBlockIndices[c-1] : _colBlockIndices[0]; }
template<class MatrixType> int g2o::SparseBlockMatrixCCS< MatrixType >::fillCCS (int * Cp, int * Ci, double * Cx, bool upperTriangle = false) const inline
fill the CCS arrays of a matrix, arrays have to be allocated beforehand
Definition at line 139 of file sparse_block_matrix_ccs.h.
       {
         assert(Cp && Ci && Cx && "Target destination is NULL");
         int nz=0;
         for (size_t i=0; i<_blockCols.size(); ++i){
           int cstart=i ? _colBlockIndices[i-1] : 0;
           int csize=colsOfBlock(i);
           for (int c=0; c<csize; ++c) {
             *Cp=nz;
             for (typename SparseColumn::const_iterator it = _blockCols[i].begin(); it!=_blockCols[i].end(); ++it) {
               const SparseMatrixBlock* b=it->block;
               int rstart=it->row ? _rowBlockIndices[it->row-1] : 0;
               int elemsToCopy = b->rows();
               if (upperTriangle && rstart == cstart)
                 elemsToCopy = c + 1;
               for (int r=0; r<elemsToCopy; ++r){
                 *Cx++ = (*b)(r,c);
                 *Ci++ = rstart++;
                 ++nz;
               }
             }
             ++Cp;
           }
         }
         *Cp=nz;
         return nz;
       }
template<class MatrixType> int g2o::SparseBlockMatrixCCS< MatrixType >::fillCCS (double * Cx, bool upperTriangle = false) const inline
fill the CCS arrays of a matrix, arrays have to be allocated beforehand. This function only writes the values and assumes that column and row structures have already been written.
Definition at line 172 of file sparse_block_matrix_ccs.h.
       {
         assert(Cx && "Target destination is NULL");
         double* CxStart = Cx;
         int cstart = 0;
         for (size_t i=0; i<_blockCols.size(); ++i){
           int csize = _colBlockIndices[i] - cstart;
           for (int c=0; c<csize; ++c) {
             for (typename SparseColumn::const_iterator it = _blockCols[i].begin(); it!=_blockCols[i].end(); ++it) {
               const SparseMatrixBlock* b = it->block;
               int rstart = it->row ? _rowBlockIndices[it->row-1] : 0;
               int elemsToCopy = b->rows();
               if (upperTriangle && rstart == cstart)
                 elemsToCopy = c + 1;
               memcpy(Cx, b->data() + c*b->rows(), elemsToCopy * sizeof(double));
               Cx += elemsToCopy;
             }
           }
           cstart = _colBlockIndices[i];
         }
         return Cx - CxStart;
       }
template<class MatrixType> void g2o::SparseBlockMatrixCCS< MatrixType >::rightMultiply (double *& dest, const double * src) const inline
Definition at line 99 of file sparse_block_matrix_ccs.h.
Referenced by g2o::BlockSolver< Traits >::solve().
       {
         int destSize=cols();
         if (! dest){
           dest=new double [ destSize ];
           memset(dest,0, destSize*sizeof(double));
         }
         // map the memory by Eigen
         Eigen::Map<Eigen::VectorXd> destVec(dest, destSize);
         Eigen::Map<const Eigen::VectorXd> srcVec(src, rows());
 #      ifdef G2O_OPENMP
 #      pragma omp parallel for default (shared) schedule(dynamic, 10)
 #      endif
         for (int i=0; i < static_cast<int>(_blockCols.size()); ++i){
           int destOffset = colBaseOfBlock(i);
           for (typename SparseColumn::const_iterator it = _blockCols[i].begin(); it!=_blockCols[i].end(); ++it) {
             const SparseMatrixBlock* a = it->block;
             int srcOffset = rowBaseOfBlock(it->row);
             // destVec += *a.transpose() * srcVec (according to the sub-vector parts)
             internal::template atxpy<SparseMatrixBlock>(*a, srcVec, srcOffset, destVec, destOffset);
           }
         }
       }
template<class MatrixType> int g2o::SparseBlockMatrixCCS< MatrixType >::rowBaseOfBlock (int r) const inline
where does the row at block-row r start?
Definition at line 84 of file sparse_block_matrix_ccs.h.
Referenced by g2o::SparseBlockMatrixCCS< PoseMatrixType >::rightMultiply(), and g2o::BlockSolver< Traits >::solve().
 { return r ? _rowBlockIndices[r-1] : 0 ; }
template<class MatrixType> const std::vector<int>& g2o::SparseBlockMatrixCCS< MatrixType >::rowBlockIndices () const inline
indices of the row blocks
Definition at line 94 of file sparse_block_matrix_ccs.h.
 { return _rowBlockIndices;}
template<class MatrixType> int g2o::SparseBlockMatrixCCS< MatrixType >::rows () const inline
rows of the matrix
Definition at line 58 of file sparse_block_matrix_ccs.h.
Referenced by g2o::SparseBlockMatrixCCS< PoseMatrixType >::rightMultiply().
 {return _rowBlockIndices.size() ? _rowBlockIndices.back() : 0;}
template<class MatrixType> int g2o::SparseBlockMatrixCCS< MatrixType >::rowsOfBlock (int r) const inline
how many rows does the block at block-row r has?
Definition at line 78 of file sparse_block_matrix_ccs.h.
Referenced by g2o::SparseBlockMatrixHashMap< MatrixType >::addBlock().
 { return r ? _rowBlockIndices[r] - _rowBlockIndices[r-1] : _rowBlockIndices[0] ; }
template<class MatrixType> void g2o::SparseBlockMatrixCCS< MatrixType >::sortColumns () inline
sort the blocks in each column
Definition at line 129 of file sparse_block_matrix_ccs.h.
       {
         for (int i=0; i < static_cast<int>(_blockCols.size()); ++i){
           std::sort(_blockCols[i].begin(), _blockCols[i].end());
         }
       }
Member Data Documentation
template<class MatrixType> std::vector<SparseColumn> g2o::SparseBlockMatrixCCS< MatrixType >::_blockCols protected
the matrices stored in CCS order
Definition at line 200 of file sparse_block_matrix_ccs.h.
Referenced by g2o::SparseBlockMatrixHashMap< MatrixType >::addBlock(), g2o::SparseBlockMatrixCCS< PoseMatrixType >::blockCols(), g2o::SparseBlockMatrixHashMap< MatrixType >::blockCols(), g2o::SparseBlockMatrixCCS< PoseMatrixType >::fillCCS(), g2o::SparseBlockMatrixCCS< PoseMatrixType >::rightMultiply(), and g2o::SparseBlockMatrixCCS< PoseMatrixType >::sortColumns().
template<class MatrixType> const std::vector<int>& g2o::SparseBlockMatrixCCS< MatrixType >::_colBlockIndices protected
vector of the indices of the blocks along the cols
Definition at line 199 of file sparse_block_matrix_ccs.h.
Referenced by g2o::SparseBlockMatrixCCS< PoseMatrixType >::colBaseOfBlock(), g2o::SparseBlockMatrixHashMap< MatrixType >::colBaseOfBlock(), g2o::SparseBlockMatrixCCS< PoseMatrixType >::colBlockIndices(), g2o::SparseBlockMatrixHashMap< MatrixType >::colBlockIndices(), g2o::SparseBlockMatrixCCS< PoseMatrixType >::cols(), g2o::SparseBlockMatrixHashMap< MatrixType >::cols(), g2o::SparseBlockMatrixCCS< PoseMatrixType >::colsOfBlock(), g2o::SparseBlockMatrixHashMap< MatrixType >::colsOfBlock(), and g2o::SparseBlockMatrixCCS< PoseMatrixType >::fillCCS().
template<class MatrixType> const std::vector<int>& g2o::SparseBlockMatrixCCS< MatrixType >::_rowBlockIndices protected
vector of the indices of the blocks along the rows.
Definition at line 198 of file sparse_block_matrix_ccs.h.
Referenced by g2o::SparseBlockMatrixCCS< PoseMatrixType >::fillCCS(), g2o::SparseBlockMatrixCCS< PoseMatrixType >::rowBaseOfBlock(), g2o::SparseBlockMatrixHashMap< MatrixType >::rowBaseOfBlock(), g2o::SparseBlockMatrixCCS< PoseMatrixType >::rowBlockIndices(), g2o::SparseBlockMatrixHashMap< MatrixType >::rowBlockIndices(), g2o::SparseBlockMatrixCCS< PoseMatrixType >::rows(), g2o::SparseBlockMatrixHashMap< MatrixType >::rows(), g2o::SparseBlockMatrixCCS< PoseMatrixType >::rowsOfBlock(), and g2o::SparseBlockMatrixHashMap< MatrixType >::rowsOfBlock().
The documentation for this class was generated from the following file:
/home/xuezhisd/CLionProjects/g2o/g2o/core/sparse_block_matrix_ccs.h