g2o: g2o::Parameter Class Reference
g2o::Parameter Class Reference abstract
#include <parameter.h>
Public Member Functions
Parameter ()
virtual ~Parameter ()
virtual bool read (std::istream &is)=0
read the data from a stream
virtual bool write (std::ostream &os) const =0
write the data to a stream
int id () const
void setId (int id_)
virtual HyperGraph::HyperGraphElementType elementType () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Protected Attributes
int _id
Detailed Description
Definition at line 36 of file parameter.h.
Constructor & Destructor Documentation
g2o::Parameter::Parameter ()
Definition at line 31 of file parameter.cpp.
                        : _id(-1)
   {
   }
virtual g2o::Parameter::~Parameter () inline virtual
Definition at line 40 of file parameter.h.
 {};
Member Function Documentation
virtual HyperGraph::HyperGraphElementType g2o::Parameter::elementType () const inline virtual
returns the type of the graph element, see HyperGraphElementType
Implements g2o::HyperGraph::HyperGraphElement.
Definition at line 47 of file parameter.h.
References HGET_PARAMETER.
 { return HyperGraph::HGET_PARAMETER;}
int g2o::Parameter::id () const inline
Definition at line 45 of file parameter.h.
Referenced by g2o::ParameterContainer::addParameter(), main(), g2o::OptimizableGraph::saveParameter(), g2o::SensorPose3DOffset::sense(), g2o::SensorPointXYZDepth::sense(), g2o::SensorPointXYZ::sense(), g2o::SensorSE3Prior::sense(), g2o::SensorPointXYOffset::sense(), g2o::SensorPointXYZDisparity::sense(), g2o::deprecated::EdgeSE3Prior::write(), g2o::EdgeSE3Prior::write(), g2o::EdgeSE3PointXYZDepth::write(), g2o::EdgeSE3PointXYZ::write(), g2o::deprecated::EdgeSE3PointXYZDepth::write(), g2o::EdgeSE3Offset::write(), g2o::EdgeSE2PointXYOffset::write(), g2o::deprecated::EdgeSE3Offset::write(), g2o::deprecated::EdgeSE3PointXYZ::write(), g2o::EdgeSE2Offset::write(), g2o::EdgeSE3PointXYZDisparity::write(), g2o::EdgeSE3Line3D::write(), g2o::deprecated::EdgeSE3PointXYZDisparity::write(), g2o::tutorial::EdgeSE2PointXY::write(), g2o::EdgeProjectXYZ2UV::write(), and g2o::EdgeProjectPSI2UV::write().
 {return _id;}
virtual bool g2o::Parameter::read (std::istream & is) pure virtual
read the data from a stream
Implemented in g2o::CameraParameters, g2o::deprecated::ParameterSE3Offset, g2o::ParameterSE2Offset, g2o::ParameterSE3Offset, g2o::tutorial::ParameterSE2Offset, g2o::deprecated::ParameterCamera, g2o::ParameterCamera, and g2o::ParameterStereoCamera.
void g2o::Parameter::setId (int id_)
Definition at line 35 of file parameter.cpp.
References _id.
Referenced by g2o::World::addParameter(), main(), and g2o::ParameterContainer::read().
   {
     _id = id_;
   }
virtual bool g2o::Parameter::write (std::ostream & os) const pure virtual
write the data to a stream
Implemented in g2o::CameraParameters, g2o::deprecated::ParameterSE3Offset, g2o::ParameterSE2Offset, g2o::ParameterSE3Offset, g2o::tutorial::ParameterSE2Offset, g2o::deprecated::ParameterCamera, g2o::ParameterCamera, and g2o::ParameterStereoCamera.
Referenced by g2o::OptimizableGraph::saveParameter().
Member Data Documentation
int g2o::Parameter::_id protected
Definition at line 49 of file parameter.h.
Referenced by setId().
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/core/parameter.h
/home/xuezhisd/CLionProjects/g2o/g2o/core/parameter.cpp