g2o: PropertiesWidget Class Reference
PropertiesWidget Class Reference
#include <properties_widget.h>
Public Slots
void on_btnApply_clicked ()
void on_btnOK_clicked ()
Public Member Functions
PropertiesWidget (QWidget *parent=0, Qt::WindowFlags f=0)
virtual ~PropertiesWidget ()
void setProperties (g2o::PropertyMap *properties)
Protected Member Functions
virtual void updateDisplayedProperties ()
virtual void applyProperties ()
virtual std::string humanReadablePropName (const std::string &propertyName) const
Protected Attributes
std::vector< std::string > _propNames
g2o::PropertyMap * _properties
Detailed Description
Definition at line 36 of file properties_widget.h.
Constructor & Destructor Documentation
PropertiesWidget::PropertiesWidget (QWidget * parent = 0, Qt::WindowFlags f = 0)
Definition at line 32 of file properties_widget.cpp.
                                                                     :
   QDialog(parent, f),
   _properties(0)
 {
   setupUi(this);
 }
PropertiesWidget::~PropertiesWidget () virtual
Definition at line 39 of file properties_widget.cpp.
 {
 }
Member Function Documentation
void PropertiesWidget::applyProperties () protected virtual
Reimplemented in ViewerPropertiesWidget.
Definition at line 100 of file properties_widget.cpp.
References _properties, _propNames, g2o::BaseProperty::fromString(), g2o::BaseProperty::name(), and g2o::Property< T >::setValue().
Referenced by ViewerPropertiesWidget::applyProperties(), on_btnApply_clicked(), and on_btnOK_clicked().
 {
   assert(tableWidget->rowCount() == (int) _propNames.size());
   PropertyMap* properties = _properties;
   for (int r = 0; r < tableWidget->rowCount(); ++r) {
     const std::string& propName = _propNames[r];
     BaseProperty* baseProp = properties->getProperty<BaseProperty>(propName);
     if (! baseProp)
       continue;
     if (dynamic_cast<Property<bool>*>(baseProp)) {
       Property<bool>* prop = static_cast<Property<bool>*>(baseProp);
       QTableWidgetItem* checkItem = tableWidget->item(r, 1);
       prop->setValue(checkItem->checkState() == Qt::Checked);
     } else {
       QLineEdit* editor = dynamic_cast<QLineEdit*>(tableWidget->cellWidget(r, 1));
       bool status = baseProp->fromString(editor->text().toStdString());
       if (! status) {
         cerr << "Warning: unable to set property " << baseProp->name() << endl;
       }
     }
   }
 }
std::string PropertiesWidget::humanReadablePropName (const std::string & propertyName) const protected virtual
Reimplemented in ViewerPropertiesWidget.
Definition at line 135 of file properties_widget.cpp.
Referenced by updateDisplayedProperties().
 {
   return propertyName;
 }
void PropertiesWidget::on_btnApply_clicked () slot
Definition at line 124 of file properties_widget.cpp.
References applyProperties().
 {
   applyProperties();
 }
void PropertiesWidget::on_btnOK_clicked () slot
Definition at line 129 of file properties_widget.cpp.
References applyProperties().
 {
   applyProperties();
   close();
 }
void PropertiesWidget::setProperties (g2o::PropertyMap * properties)
Definition at line 140 of file properties_widget.cpp.
References _properties, and updateDisplayedProperties().
Referenced by MainWindow::on_btnOptimizerParamaters_clicked(), and ViewerPropertiesWidget::setViewer().
 {
   _properties = properties;
   updateDisplayedProperties();
 }
void PropertiesWidget::updateDisplayedProperties () protected virtual
Definition at line 43 of file properties_widget.cpp.
References _properties, _propNames, humanReadablePropName(), and g2o::Property< T >::value().
Referenced by setProperties().
 {
   tableWidget->clear();
   _propNames.clear();
   tableWidget->setColumnCount(2);
   QStringList horizontalHeaders;
   horizontalHeaders.append("Name");
   horizontalHeaders.append("Value");
   tableWidget->setHorizontalHeaderLabels(horizontalHeaders);
   tableWidget->verticalHeader()->hide();
   PropertyMap* properties = _properties;
   if (! properties)
     return;
   tableWidget->setRowCount(properties->size());
   int r = 0;
   for (PropertyMap::PropertyMapIterator it = properties->begin(); it != properties->end(); ++it, ++r) {
     QTableWidgetItem* textItem = new QTableWidgetItem;
     textItem->setText(QString::fromStdString(humanReadablePropName(it->first)));
     textItem->setFlags(textItem->flags() & ~Qt::ItemIsEditable);
     tableWidget->setItem(r, 0, textItem);
     _propNames.push_back(it->first);
     if (dynamic_cast<Property<bool>*>(it->second)) {
       Property<bool>* prop = static_cast<Property<bool>*>(it->second);
       QTableWidgetItem* checkItem = new QTableWidgetItem;
       checkItem->setText("enabled");
       checkItem->setFlags(checkItem->flags() | Qt::ItemIsUserCheckable);
       if (prop->value())
         checkItem->setCheckState(Qt::Checked);
       else
         checkItem->setCheckState(Qt::Unchecked);
       tableWidget->setItem(r, 1, checkItem);
     } else {
       QLineEdit* editor = new QLineEdit(tableWidget);
       editor->setText(QString::fromStdString(it->second->toString()));
       if (dynamic_cast<Property<int>*>(it->second)) {
         editor->setValidator(new QIntValidator(editor));
       }
       else if (dynamic_cast<Property<float>*>(it->second)) {
         editor->setValidator(new QDoubleValidator(editor));
       }
       else if (dynamic_cast<Property<double>*>(it->second)) {
         editor->setValidator(new QDoubleValidator(editor));
       }
       tableWidget->setCellWidget(r, 1, editor);
     }
   }
   tableWidget->resizeColumnToContents(0);
 }
Member Data Documentation
g2o::PropertyMap* PropertiesWidget::_properties protected
Definition at line 51 of file properties_widget.h.
Referenced by applyProperties(), setProperties(), and updateDisplayedProperties().
std::vector<std::string> PropertiesWidget::_propNames protected
Definition at line 50 of file properties_widget.h.
Referenced by applyProperties(), and updateDisplayedProperties().
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_viewer/properties_widget.h
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_viewer/properties_widget.cpp