g2o: g2o::CameraParameters Class Reference
g2o::CameraParameters Class Reference
#include <types_six_dof_expmap.h>
Public Member Functions
CameraParameters ()
CameraParameters (double focal_length, const Vector2D &principle_point, double baseline)
Vector2D cam_map (const Vector3D &trans_xyz) const
Vector3D stereocam_uvu_map (const Vector3D &trans_xyz) const
virtual bool read (std::istream &is)
read the data from a stream
virtual bool write (std::ostream &os) const
write the data to a stream
Public Member Functions inherited from g2o::Parameter
Parameter ()
virtual ~Parameter ()
int id () const
void setId (int id_)
virtual HyperGraph::HyperGraphElementType elementType () const
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
double focal_length
Vector2D principle_point
double baseline
Additional Inherited Members
Protected Attributes inherited from g2o::Parameter
int _id
Detailed Description
Definition at line 43 of file types_six_dof_expmap.h.
Constructor & Destructor Documentation
g2o::CameraParameters::CameraParameters ()
Definition at line 45 of file types_six_dof_expmap.cpp.
   : focal_length(1.),
     principle_point(Vector2D(0., 0.)),
     baseline(0.5)  {
 }
g2o::CameraParameters::CameraParameters (double focal_length, const Vector2D & principle_point, double baseline) inline
Definition at line 49 of file types_six_dof_expmap.h.
       : focal_length(focal_length),
       principle_point(principle_point),
       baseline(baseline){}
Member Function Documentation
Vector2D g2o::CameraParameters::cam_map (const Vector3D & trans_xyz) const
Definition at line 70 of file types_six_dof_expmap.cpp.
References g2o::project2d().
Referenced by g2o::EdgeProjectXYZ2UV::computeError(), g2o::EdgeProjectPSI2UV::computeError(), and main().
{
   Vector2D proj = project2d(trans_xyz);
   Vector2D res;
   res[0] = proj[0]*focal_length + principle_point[0];
   res[1] = proj[1]*focal_length + principle_point[1];
   return res;
 }
virtual bool g2o::CameraParameters::read (std::istream & is) inline virtual
read the data from a stream
Implements g2o::Parameter.
Definition at line 60 of file types_six_dof_expmap.h.
{
       is >> focal_length;
       is >> principle_point[0];
       is >> principle_point[1];
       is >> baseline;
       return true;
     }
Vector3D g2o::CameraParameters::stereocam_uvu_map (const Vector3D & trans_xyz) const
Definition at line 78 of file types_six_dof_expmap.cpp.
Referenced by g2o::EdgeProjectXYZ2UVU::computeError().
{
   Vector2D uv_left = cam_map(trans_xyz);
   double proj_x_right = (trans_xyz[0]-baseline)/trans_xyz[2];
   double u_right = proj_x_right*focal_length + principle_point[0];
   return Vector3D(uv_left[0],uv_left[1],u_right);
 }
virtual bool g2o::CameraParameters::write (std::ostream & os) const inline virtual
write the data to a stream
Implements g2o::Parameter.
Definition at line 68 of file types_six_dof_expmap.h.
{
       os << focal_length << " ";
       os << principle_point.x() << " ";
       os << principle_point.y() << " ";
       os << baseline << " ";
       return true;
     }
Member Data Documentation
double g2o::CameraParameters::baseline
Definition at line 78 of file types_six_dof_expmap.h.
g2o::CameraParameters::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 46 of file types_six_dof_expmap.h.
double g2o::CameraParameters::focal_length
Definition at line 76 of file types_six_dof_expmap.h.
Referenced by g2o::EdgeProjectXYZ2UV::linearizeOplus(), and g2o::EdgeProjectPSI2UV::linearizeOplus().
Vector2D g2o::CameraParameters::principle_point
Definition at line 77 of file types_six_dof_expmap.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/sba/types_six_dof_expmap.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/sba/types_six_dof_expmap.cpp