g2o: g2o::RobotLaser Class Reference
g2o::RobotLaser Class Reference
laser measurement obtained by a robot
#include <robot_laser.h>
Public Member Functions
RobotLaser ()
~RobotLaser ()
virtual bool write (std::ostream &os) const
write the data to a stream
virtual bool read (std::istream &is)
read the data from a stream
SE2 laserPose () const
const SE2 & odomPose () const
void setOdomPose (const SE2 &odomPose)
Public Member Functions inherited from g2o::RawLaser
RawLaser ()
~RawLaser ()
Point2DVector cartesian () const
const std::vector< double > & ranges () const
the range measurements by the laser
void setRanges (const std::vector< double > &ranges)
const std::vector< double > & remissions () const
the remission measurements by the laser
void setRemissions (const std::vector< double > &remissions)
const LaserParameters & laserParams () const
the parameters of the laser
void setLaserParams (const LaserParameters &laserParams)
Public Member Functions inherited from g2o::RobotData
RobotData ()
virtual ~RobotData ()
double timestamp () const
void setTimestamp (double ts)
double loggerTimestamp () const
void setLoggerTimestamp (double ts)
const std::string & tag () const
void setTag (const std::string &tag)
const std::string & hostname () const
void setHostname (const std::string &hostname)
Public Member Functions inherited from g2o::HyperGraph::Data
Data ()
~Data ()
virtual HyperGraph::HyperGraphElementType elementType () const
const Data * next () const
Data * next ()
void setNext (Data *next_)
DataContainer * dataContainer ()
const DataContainer * dataContainer () const
void setDataContainer (DataContainer *dataContainer_)
Public Member Functions inherited from g2o::HyperGraph::HyperGraphElement
virtual ~HyperGraphElement ()
HyperGraphElement * clone () const
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Protected Attributes
SE2 _odomPose
double _laserTv
velocities and safety distances of the robot.
double _laserRv
double _forwardSafetyDist
double _sideSaftyDist
double _turnAxis
Protected Attributes inherited from g2o::RawLaser
std::vector< double > _ranges
std::vector< double > _remissions
LaserParameters _laserParams
Protected Attributes inherited from g2o::RobotData
double _timestamp
timestamp when the measurement was generated
double _loggerTimestamp
timestamp when the measurement was recorded
std::string _tag
string tag (FLASER, ROBOTLASER, ODOM..) of the line in the log
std::string _hostname
name of the computer/robot generating the data
Protected Attributes inherited from g2o::HyperGraph::Data
Data * _next
DataContainer * _dataContainer
Additional Inherited Members
Public Types inherited from g2o::RawLaser
typedef std::vector< Vector2D, Eigen::aligned_allocator< Vector2D > > Point2DVector
Detailed Description
laser measurement obtained by a robot
A laser measurement obtained by a robot. The measurement is equipped with a pose of the robot at which the measurement was taken. The read/write function correspond to the CARMEN logfile format.
Definition at line 42 of file robot_laser.h.
Constructor & Destructor Documentation
g2o::RobotLaser::RobotLaser ()
Definition at line 40 of file robot_laser.cpp.
                          :
     RawLaser(),
     _laserTv(0.), _laserRv(0.), _forwardSafetyDist(0.), _sideSaftyDist(0.), _turnAxis(0.)
   {
   }
g2o::RobotLaser::~RobotLaser ()
Definition at line 46 of file robot_laser.cpp.
   {
   }
Member Function Documentation
SE2 g2o::RobotLaser::laserPose () const inline
Definition at line 52 of file robot_laser.h.
Referenced by main(), and setOdomPose().
 { return _odomPose * _laserParams.laserPose;}
const SE2& g2o::RobotLaser::odomPose () const inline
Definition at line 53 of file robot_laser.h.
Referenced by g2o::addOdometryCalibLinksDifferential(), main(), and setOdomPose().
 { return _odomPose;}
bool g2o::RobotLaser::read (std::istream & is) virtual
read the data from a stream
Reimplemented from g2o::RawLaser.
Definition at line 50 of file robot_laser.cpp.
References _forwardSafetyDist, g2o::RobotData::_hostname, g2o::RawLaser::_laserParams, _laserRv, _laserTv, g2o::RobotData::_loggerTimestamp, _odomPose, g2o::RawLaser::_ranges, g2o::RawLaser::_remissions, _sideSaftyDist, g2o::RobotData::_timestamp, _turnAxis, g2o::SE2::inverse(), and g2o::LaserParameters::laserPose.
Referenced by g2o::Gm2dlIO::readGm2dl(), and g2o::Gm2dlIO::readRobotLaser().
   {
     int type;
     double angle, fov, res, maxrange, acc;
     int remission_mode;
     is >> type >> angle >> fov >> res >> maxrange >> acc >> remission_mode;
     int beams;
     is >> beams;
     _laserParams = LaserParameters(type, beams, angle, res, maxrange, acc, remission_mode);
     _ranges.resize(beams);
     for (int i=0; i<beams; i++)
       is >> _ranges[i];
     is >> beams;
     _remissions.resize(beams);
     for (int i = 0; i < beams; i++)
       is >> _remissions[i];
     // special robot laser stuff
     double x,y,theta;
     is >> x >> y >> theta;
     SE2 lp(x,y,theta);
     //cerr << "x: " << x << " y:" << y << " th:" << theta << " ";
     is >> x >> y >> theta;
     //cerr << "x: " << x << " y:" << y << " th:" << theta;
     _odomPose = SE2(x,y,theta);
     _laserParams.laserPose = _odomPose.inverse()*lp;
     is >> _laserTv >>  _laserRv >>  _forwardSafetyDist >> _sideSaftyDist >> _turnAxis;
     // timestamp + host
     is >> _timestamp;
     is >> _hostname;
     is >> _loggerTimestamp;
     return true;
   }
void g2o::RobotLaser::setOdomPose (const SE2 & odomPose)
Definition at line 113 of file robot_laser.cpp.
References _odomPose, g2o::RawLaser::cartesian(), g2o::RawLaser::laserParams(), g2o::LaserParameters::laserPose, laserPose(), odomPose(), RAD2DEG, g2o::DrawAction::refreshPropertyPtrs(), g2o::SE2::rotation(), step(), and g2o::SE2::translation().
Referenced by g2o::Gm2dlIO::updateLaserData().
   {
     _odomPose = odomPose;
   }
bool g2o::RobotLaser::write (std::ostream & os) const virtual
write the data to a stream
Reimplemented from g2o::RawLaser.
Definition at line 87 of file robot_laser.cpp.
References _forwardSafetyDist, g2o::RawLaser::_laserParams, _laserRv, _laserTv, _odomPose, g2o::RawLaser::_remissions, _sideSaftyDist, _turnAxis, g2o::LaserParameters::accuracy, g2o::LaserParameters::angularStep, g2o::LaserParameters::firstBeamAngle, g2o::LaserParameters::fov, g2o::RobotData::hostname(), g2o::LaserParameters::laserPose, g2o::RobotData::loggerTimestamp(), g2o::LaserParameters::maxRange, g2o::RawLaser::ranges(), g2o::LaserParameters::remissionMode, g2o::RobotData::timestamp(), g2o::SE2::toVector(), and g2o::LaserParameters::type.
   {
     os << _laserParams.type << " " << _laserParams.firstBeamAngle << " " << _laserParams.fov << " "
       << _laserParams.angularStep << " " << _laserParams.maxRange << " " << _laserParams.accuracy << " "
       << _laserParams.remissionMode << " ";
     os << ranges().size();
     for (size_t i = 0; i < ranges().size(); ++i)
       os << " " << ranges()[i];
     os << " " << _remissions.size();
     for (size_t i = 0; i < _remissions.size(); ++i)
       os << " " << _remissions[i];
     // odometry pose
     Vector3D p = (_odomPose * _laserParams.laserPose).toVector();
     os << " " << p.x() << " " << p.y() << " " << p.z();
     p = _odomPose.toVector();
     os << " " << p.x() << " " << p.y() << " " << p.z();
     // crap values
     os << FIXED(" " <<  _laserTv << " " <<  _laserRv << " " << _forwardSafetyDist << " "
         << _sideSaftyDist << " " << _turnAxis);
     os << FIXED(" " << timestamp() << " " << hostname() << " " << loggerTimestamp());
     return os.good();
   }
Member Data Documentation
double g2o::RobotLaser::_forwardSafetyDist protected
Definition at line 59 of file robot_laser.h.
Referenced by read(), and write().
double g2o::RobotLaser::_laserRv protected
Definition at line 59 of file robot_laser.h.
Referenced by read(), and write().
double g2o::RobotLaser::_laserTv protected
velocities and safety distances of the robot.
Definition at line 59 of file robot_laser.h.
Referenced by read(), and write().
SE2 g2o::RobotLaser::_odomPose protected
Definition at line 57 of file robot_laser.h.
Referenced by read(), setOdomPose(), and write().
double g2o::RobotLaser::_sideSaftyDist protected
Definition at line 59 of file robot_laser.h.
Referenced by read(), and write().
double g2o::RobotLaser::_turnAxis protected
Definition at line 59 of file robot_laser.h.
Referenced by read(), and write().
g2o::RobotLaser::EIGEN_MAKE_ALIGNED_OPERATOR_NEW
Definition at line 45 of file robot_laser.h.
The documentation for this class was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/types/data/robot_laser.h
/home/xuezhisd/CLionProjects/g2o/g2o/types/data/robot_laser.cpp