g2o: /home/xuezhisd/CLionProjects/g2o/g2o/examples/data_fitting/curve_fit.cpp File Reference
curve_fit.cpp File Reference
#include <Eigen/Core>
#include <iostream>
#include "g2o/stuff/sampler.h"
#include "g2o/stuff/command_args.h"
#include "g2o/core/sparse_optimizer.h"
#include "g2o/core/block_solver.h"
#include "g2o/core/solver.h"
#include "g2o/core/optimization_algorithm_levenberg.h"
#include "g2o/core/base_vertex.h"
#include "g2o/core/base_unary_edge.h"
#include "g2o/solvers/dense/linear_solver_dense.h"
Classes
class VertexParams
the params, a, b, and lambda for a * exp(-lambda * t) + b
class EdgePointOnCurve
measurement for a point on the curve
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 113 of file curve_fit.cpp.
References g2o::OptimizableGraph::addEdge(), g2o::OptimizableGraph::addVertex(), g2o::BaseVertex< D, T >::estimate(), g2o::Sampler::gaussRand(), g2o::SparseOptimizer::initializeOptimization(), g2o::SparseOptimizer::optimize(), g2o::CommandArgs::param(), g2o::CommandArgs::parseArgs(), g2o::SparseOptimizer::setAlgorithm(), g2o::BaseVertex< D, T >::setEstimate(), g2o::OptimizableGraph::Vertex::setId(), g2o::BaseEdge< D, E >::setInformation(), g2o::BaseEdge< D, E >::setMeasurement(), g2o::SparseOptimizer::setVerbose(), g2o::HyperGraph::Edge::setVertex(), and g2o::Sampler::uniformRand().
 {
   int numPoints;
   int maxIterations;
   bool verbose;
   std::vector<int> gaugeList;
   string dumpFilename;
   g2o::CommandArgs arg;
   arg.param("dump", dumpFilename, "", "dump the points into a file");
   arg.param("numPoints", numPoints, 50, "number of points sampled from the curve");
   arg.param("i", maxIterations, 10, "perform n iterations");
   arg.param("v", verbose, false, "verbose output of the optimization process");
   arg.parseArgs(argc, argv);
   // generate random data
   double a = 2.;
   double b = 0.4;
   double lambda = 0.2;
   Eigen::Vector2d* points = new Eigen::Vector2d[numPoints];
   for (int i = 0; i < numPoints; ++i) {
     double x = g2o::Sampler::uniformRand(0, 10);
     double y = a * exp(-lambda * x) + b;
     // add Gaussian noise
     y += g2o::Sampler::gaussRand(0, 0.02);
     points[i].x() = x;
     points[i].y() = y;
   }
   if (dumpFilename.size() > 0) {
     ofstream fout(dumpFilename.c_str());
     for (int i = 0; i < numPoints; ++i)
       fout << points[i].transpose() << endl;
   }
   // some handy typedefs
   typedef g2o::BlockSolver< g2o::BlockSolverTraits<Eigen::Dynamic, Eigen::Dynamic> >  MyBlockSolver;
   typedef g2o::LinearSolverDense<MyBlockSolver::PoseMatrixType> MyLinearSolver;
   // setup the solver
   g2o::SparseOptimizer optimizer;
   optimizer.setVerbose(false);
   MyLinearSolver* linearSolver = new MyLinearSolver();
   MyBlockSolver* solver_ptr = new MyBlockSolver(linearSolver);
   g2o::OptimizationAlgorithmLevenberg* solver = new g2o::OptimizationAlgorithmLevenberg(solver_ptr);
   optimizer.setAlgorithm(solver);
   // build the optimization problem given the points
   // 1. add the parameter vertex
   VertexParams* params = new VertexParams();
   params->setId(0);
   params->setEstimate(Eigen::Vector3d(1,1,1)); // some initial value for the params
   optimizer.addVertex(params);
   // 2. add the points we measured to be on the curve
   for (int i = 0; i < numPoints; ++i) {
     EdgePointOnCurve* e = new EdgePointOnCurve;
     e->setInformation(Eigen::Matrix<double, 1, 1>::Identity());
     e->setVertex(0, params);
     e->setMeasurement(points[i]);
     optimizer.addEdge(e);
   }
   // perform the optimization
   optimizer.initializeOptimization();
   optimizer.setVerbose(verbose);
   optimizer.optimize(maxIterations);
   if (verbose)
     cout << endl;
   // print out the result
   cout << "Target curve" << endl;
   cout << "a * exp(-lambda * x) + b" << endl;
   cout << "Iterative least squares solution" << endl;
   cout << "a      = " << params->estimate()(0) << endl;
   cout << "b      = " << params->estimate()(1) << endl;
   cout << "lambda = " << params->estimate()(2) << endl;
   cout << endl;
   // clean up
   delete[] points;
   return 0;
 }