g2o: /home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_simulator/g2o_anonymize_observations.cpp File Reference
g2o_anonymize_observations.cpp File Reference
#include <cstdlib>
#include "g2o/core/optimizable_graph.h"
#include "g2o/stuff/command_args.h"
#include "g2o/types/slam2d/types_slam2d.h"
#include "g2o/types/slam3d/types_slam3d.h"
#include <iostream>
#include <fstream>
#include <sstream>
Functions
template<typename T >
bool anonymizeLandmarkEdge (HyperGraph::Edge *e_, OptimizableGraph &g)
template<typename T >
bool anonymizePoseEdge (HyperGraph::Edge *e_, OptimizableGraph &g)
int main (int argc, char **argv)
Function Documentation
template<typename T > bool anonymizeLandmarkEdge (HyperGraph::Edge * e_, OptimizableGraph & g)
Definition at line 40 of file g2o_anonymize_observations.cpp.
References g2o::OptimizableGraph::setEdgeVertex().
{
   T* e= dynamic_cast<T*> (e_);
   if (!e)
     return false;
   g.setEdgeVertex(e,1,0);
   return true;
 }
template<typename T > bool anonymizePoseEdge (HyperGraph::Edge * e_, OptimizableGraph & g)
Definition at line 49 of file g2o_anonymize_observations.cpp.
References g2o::HyperGraph::Vertex::id(), and g2o::OptimizableGraph::setEdgeVertex().
{
   T* e= dynamic_cast<T*> (e_);
   if (!e)
     return false;
   HyperGraph::Vertex* from = e->vertex(0);
   HyperGraph::Vertex* to   = e->vertex(1);
   if (from && to && from!=to){
     int deltaId = abs(from->id() - to->id());
     if (deltaId>1) {
       if (from->id()>to->id()){
         g.setEdgeVertex(e,0,0);
       } else {
         g.setEdgeVertex(e,1,0);
       }
       return true;
     }
   }
   return false;
 }
int main (int argc, char ** argv)
Definition at line 70 of file g2o_anonymize_observations.cpp.
References g2o::HyperGraph::edges(), graph, g2o::OptimizableGraph::load(), g2o::CommandArgs::param(), g2o::CommandArgs::paramLeftOver(), g2o::CommandArgs::parseArgs(), and g2o::OptimizableGraph::save().
{
   CommandArgs arg;
   std::string outputFilename;
   std::string inputFilename;
   arg.param("o", outputFilename, "anon.g2o", "output file" );
   arg.paramLeftOver("graph-output", inputFilename, "", "graph file which will be read", true);
   arg.parseArgs(argc, argv);
   OptimizableGraph graph;
   if (inputFilename.size() == 0) {
     cerr << "No input data specified" << endl;
     return 0;
   } else if (inputFilename == "-") {
     cerr << "Read input from stdin" << endl;
     if (!graph.load(cin)) {
       cerr << "Error loading graph" << endl;
       return 2;
     }
   } else {
     cerr << "Read input from " << inputFilename << endl;
     ifstream ifs(inputFilename.c_str());
     if (!ifs) {
       cerr << "Failed to open file" << endl;
       return 1;
     }
     if (!graph.load(ifs)) {
       cerr << "Error loading graph" << endl;
       return 2;
     }
   }
   for (HyperGraph::EdgeSet::iterator it = graph.edges().begin(); it!=graph.edges().end(); it++){
     HyperGraph::Edge* e = *it;
     if (anonymizeLandmarkEdge<EdgeSE2PointXY>(e, graph)) continue;
     if (anonymizeLandmarkEdge<EdgeSE2PointXYOffset>(e, graph)) continue;
     if (anonymizeLandmarkEdge<EdgeSE2PointXYBearing>(e, graph)) continue;
     if (anonymizePoseEdge<EdgeSE2>(e, graph)) continue;
     if (anonymizePoseEdge<EdgeSE2Offset>(e, graph)) continue;
   }
   ofstream os (outputFilename.c_str());
   graph.save(os);
 }