g2o: /home/xuezhisd/CLionProjects/g2o/g2o/examples/interactive_slam/g2o_interactive/g2o_online.cpp File Reference
g2o_online.cpp File Reference
#include <iostream>
#include <iomanip>
#include <csignal>
#include <cstdlib>
#include "g2o/stuff/macros.h"
#include "g2o/stuff/command_args.h"
#include "g2o/stuff/timeutil.h"
#include "slam_parser/interface/parser_interface.h"
#include "g2o_slam_interface.h"
#include "graph_optimizer_sparse_online.h"
Functions
void sigquit_handler (int sig)
int main (int argc, char **argv)
Variables
static bool hasToStop =false
Function Documentation
int main (int argc, char ** argv)
Definition at line 58 of file g2o_online.cpp.
References hasToStop, g2o::CommandArgs::param(), g2o::CommandArgs::parseArgs(), SlamParser::ParserInterface::parseCommand(), g2o::SparseOptimizer::setForceStopFlag(), g2o::G2oSlamInterface::setUpdateGraphEachN(), g2o::SparseOptimizer::setVerbose(), and g2o::SparseOptimizerOnline::vizWithGnuplot.
 {
   bool pcg;
   int updateEachN;
   bool vis;
   bool verbose;
   // command line parsing
   CommandArgs arg;
   arg.param("update", updateEachN, 10, "update the graph after inserting N nodes");
   arg.param("pcg", pcg, false, "use PCG instead of Cholesky");
   arg.param("v", verbose, false, "verbose output of the optimization process");
   arg.param("g", vis, false, "gnuplot visualization");
   arg.parseArgs(argc, argv);
   SparseOptimizerOnline optimizer(pcg);
   //SparseOptimizer optimizer;
   optimizer.setVerbose(verbose);
   optimizer.setForceStopFlag(&hasToStop);
   optimizer.vizWithGnuplot = vis;
   G2oSlamInterface slamInterface(&optimizer);
   slamInterface.setUpdateGraphEachN(updateEachN);
   SlamParser::ParserInterface parserInterface(&slamInterface);
   while (parserInterface.parseCommand(cin))
   {
     // do something additional if needed
   }
   return 0;
 }
void sigquit_handler (int sig)
Definition at line 46 of file g2o_online.cpp.
References __PRETTY_FUNCTION__, and hasToStop.
 {
   if (sig == SIGINT) {
     hasToStop = 1;
     static int cnt = 0;
     if (cnt++ == 2) {
       cerr << __PRETTY_FUNCTION__ << " forcing exit" << endl;
       exit(1);
     }
   }
 }
Variable Documentation
bool hasToStop =false static
Definition at line 41 of file g2o_online.cpp.
Referenced by main(), and sigquit_handler().