g2o: /home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_cli/g2o_common.cpp File Reference
g2o_common.cpp File Reference
#include "g2o_common.h"
#include "dl_wrapper.h"
#include "g2o/stuff/string_tools.h"
#include "g2o/stuff/filesys_tools.h"
#include <vector>
#include <iostream>
#include <cstdlib>
Namespaces
g2o
Macros
#define SO_EXT "so"
#define PATH_SEPARATOR ";"
#define G2O_LIBRARY_POSTFIX ""
Functions
static void fakeFunctionForWindows ()
HMODULE getMyInstance ()
void g2o::findArguments (const std::string &option, vector< string > &args, int argc, char **argv)
void g2o::loadStandardTypes (DlWrapper &dlTypesWrapper, int argc, char **argv)
void g2o::loadStandardSolver (DlWrapper &dlSolverWrapper, int argc, char **argv)
Variables
static const string TYPES_PATTERN =string("*_types_*")+string(G2O_LIBRARY_POSTFIX)+string(".")+string(SO_EXT)
static const string SOLVERS_PATTERN =string("*_solver_*")+string(G2O_LIBRARY_POSTFIX)+string(".")+string(SO_EXT)
Macro Definition Documentation
#define G2O_LIBRARY_POSTFIX ""
Definition at line 78 of file g2o_common.cpp.
Referenced by ADD_LIBRARY().
#define PATH_SEPARATOR ";"
Definition at line 61 of file g2o_common.cpp.
Referenced by g2o::loadStandardSolver(), and g2o::loadStandardTypes().
#define SO_EXT "so"
Definition at line 46 of file g2o_common.cpp.
Function Documentation
static void fakeFunctionForWindows () static
Definition at line 63 of file g2o_common.cpp.
Referenced by getMyInstance().
 {}
HMODULE getMyInstance ()
Definition at line 65 of file g2o_common.cpp.
References fakeFunctionForWindows().
Referenced by g2o::loadStandardSolver(), and g2o::loadStandardTypes().
 {
   MEMORY_BASIC_INFORMATION mbi;
   if (VirtualQuery((const void *)&fakeFunctionForWindows, &mbi, sizeof(mbi))) {
     return (HMODULE) mbi.AllocationBase;
   }
   return NULL;
 }
Variable Documentation
const string SOLVERS_PATTERN =string("*_solver_*")+string(G2O_LIBRARY_POSTFIX)+string(".")+string(SO_EXT) static
Definition at line 82 of file g2o_common.cpp.
Referenced by g2o::loadStandardSolver().
const string TYPES_PATTERN =string("*_types_*")+string(G2O_LIBRARY_POSTFIX)+string(".")+string(SO_EXT) static
Definition at line 81 of file g2o_common.cpp.
Referenced by g2o::loadStandardTypes().