g2o: /home/xuezhisd/CLionProjects/g2o/g2o/examples/interactive_slam/g2o_incremental/g2o_incremental.cpp File Reference
g2o_incremental.cpp File Reference
#include <iostream>
#include <cassert>
#include <csignal>
#include "g2o/stuff/macros.h"
#include "g2o/stuff/command_args.h"
#include "g2o/stuff/string_tools.h"
#include "g2o/stuff/tictoc.h"
#include "slam_parser/interface/parser_interface.h"
#include "g2o/examples/interactive_slam/g2o_interactive/g2o_slam_interface.h"
#include "graph_optimizer_sparse_incremental.h"
Classes
struct EdgeInformation
Store the information parsed from a g2o file.
struct IncrementalEdgesCompare
Sort Edges for inserting them sequentially.
Functions
void sigquit_handler (int sig)
int main (int argc, char **argv)
Variables
static bool hasToStop =false
Function Documentation
int main (int argc, char ** argv)
Definition at line 80 of file g2o_incremental.cpp.
References g2o::G2oSlamInterface::addEdge(), g2o::G2oSlamInterface::addNode(), EdgeInformation::fromId, hasToStop, EdgeInformation::information, EdgeInformation::measurement, g2o::CommandArgs::param(), g2o::CommandArgs::parseArgs(), SlamParser::ParserInterface::parseCommand(), g2o::readLine(), g2o::OptimizableGraph::save(), g2o::G2oSlamInterface::setBatchSolveEachN(), g2o::SparseOptimizer::setForceStopFlag(), g2o::G2oSlamInterface::setUpdateGraphEachN(), g2o::SparseOptimizer::setVerbose(), g2o::G2oSlamInterface::solve(), g2o::tictoc(), EdgeInformation::toId, g2o::HyperGraph::vertices(), and g2o::SparseOptimizerOnline::vizWithGnuplot.
 {
   string inputFilename;
   string outputFilename;
   int updateEachN;
   int batchEachN;
   bool verbose;
   bool vis;
   // command line parsing
   CommandArgs arg;
   arg.param("batch", batchEachN, 100, "solve by a batch Cholesky after inserting N nodes");
   arg.param("update", updateEachN, 10, "update the graph after inserting N nodes");
   arg.param("v", verbose, false, "verbose output of the optimization process");
   arg.param("g", vis, false, "gnuplot visualization");
   arg.param("o", outputFilename, "", "output the final graph");
   arg.param("i", inputFilename, "", "input file (default g2o format), if not given read via stdin");
   arg.parseArgs(argc, argv);
   SparseOptimizerIncremental optimizer;
   optimizer.setVerbose(verbose);
   optimizer.setForceStopFlag(&hasToStop);
   optimizer.vizWithGnuplot = vis;
   G2oSlamInterface slamInterface(&optimizer);
   slamInterface.setUpdateGraphEachN(updateEachN);
   slamInterface.setBatchSolveEachN(batchEachN);
   cerr << "Updating every " << updateEachN << endl;
   cerr << "Batch step every " << batchEachN << endl;
   if (inputFilename.size() > 0) { // operating on a file
     vector<EdgeInformation> edgesFromGraph;
     // HACK force tictoc statistics
 #ifdef _MSC_VER
     _putenv_s("G2O_ENABLE_TICTOC", "1");
 #else
     setenv("G2O_ENABLE_TICTOC", "1", 1);
 #endif
     // parse the edge from the file
     int graphDimension = 0;
     cerr << "Parsing " << inputFilename << " ... ";
     tictoc("parsing");
     ifstream ifs(inputFilename.c_str());
     if (!ifs) {
       cerr << "Failure to open " << inputFilename << endl;
       return 1;
     }
     stringstream currentLine;
     while (readLine(ifs, currentLine)) {
       string token;
       currentLine >> token;
       if (token == "EDGE_SE2") {
         graphDimension = 3;
         edgesFromGraph.push_back(EdgeInformation());
         EdgeInformation& currentEdge = edgesFromGraph.back();
         currentLine >> currentEdge.fromId >> currentEdge.toId;
         currentEdge.measurement.resize(3);
         currentLine >> currentEdge.measurement[0] >> currentEdge.measurement[1] >> currentEdge.measurement[2];
         currentEdge.information.resize(6);
         for (int i = 0; i < 6; ++i)
           currentLine >> currentEdge.information[i];
       } else if (token == "EDGE_SE3:QUAT") {
         graphDimension = 6;
         edgesFromGraph.push_back(EdgeInformation());
         EdgeInformation& currentEdge = edgesFromGraph.back();
         currentLine >> currentEdge.fromId >> currentEdge.toId;
         currentEdge.measurement.resize(7);
         for (size_t i = 0; i < currentEdge.measurement.size(); ++i)
           currentLine >> currentEdge.measurement[i];
         currentEdge.information.resize(21);
         for (size_t i = 0; i < currentEdge.information.size(); ++i)
           currentLine >> currentEdge.information[i];
       }
     }
     assert(graphDimension > 0);
     sort(edgesFromGraph.begin(), edgesFromGraph.end(), IncrementalEdgesCompare());
     tictoc("parsing");
     cerr << "done." << endl;
     // adding edges to the graph. Add all edges connecting a node and then call optimize
     tictoc("inc_optimize");
     bool freshlySolved = false;
     int lastNode = 2;
     slamInterface.addNode("", 0, graphDimension, vector<double>());
     for (vector<EdgeInformation>::const_iterator it = edgesFromGraph.begin(); it != edgesFromGraph.end(); ++it) {
       const EdgeInformation& e = *it;
       int minNodeId = max(e.fromId, e.toId);
       if (minNodeId > lastNode) {
         //cerr << "try to solve" << endl;
         lastNode = minNodeId;
         freshlySolved = true;
         G2oSlamInterface::SolveResult solverState = slamInterface.solve();
         if (!verbose) {
           switch (solverState) {
             case G2oSlamInterface::SOLVED:
               cout << "."; //<< flush;
               break;
             case G2oSlamInterface::SOLVED_BATCH:
               cout << "b " << optimizer.vertices().size() << endl;
               break;
             default:
               break;
           }
         }
       }
       //cerr << "adding " << e.fromId << " " << e.toId << endl;
       slamInterface.addEdge("", 0, graphDimension, e.fromId, e.toId, e.measurement, e.information);
       freshlySolved = false;
     }
     if (! freshlySolved) {
       G2oSlamInterface::SolveResult solverState = slamInterface.solve();
       if (!verbose) {
         switch (solverState) {
           case G2oSlamInterface::SOLVED:
             cout << "." << endl;
             break;
           case G2oSlamInterface::SOLVED_BATCH:
             cout << "b " << optimizer.vertices().size() << endl;
             break;
           default:
             break;
         }
       }
     }
     tictoc("inc_optimize");
   } else {
     // Reading the protocol via stdin
     SlamParser::ParserInterface parserInterface(&slamInterface);
     while (parserInterface.parseCommand(cin)) {}
   }
   if (outputFilename.size() > 0) {
     cerr << "Saving " << outputFilename << endl;
     optimizer.save(outputFilename.c_str());
   }
   return 0;
 }
void sigquit_handler (int sig)
Definition at line 68 of file g2o_incremental.cpp.
References __PRETTY_FUNCTION__, and hasToStop.
 {
   if (sig == SIGINT) {
     hasToStop = 1;
     static int cnt = 0;
     if (cnt++ == 2) {
       cerr << __PRETTY_FUNCTION__ << " forcing exit" << endl;
       exit(1);
     }
   }
 }
Variable Documentation
bool hasToStop =false static
Definition at line 31 of file g2o_incremental.cpp.
Referenced by main(), and sigquit_handler().