g2o: /home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_viewer/g2o_viewer.cpp File Reference
g2o_viewer.cpp File Reference
#include <iostream>
#include "run_g2o_viewer.h"
#include "g2o/core/optimizable_graph.h"
#include "g2o/apps/g2o_cli/g2o_common.h"
#include "g2o/apps/g2o_cli/dl_wrapper.h"
#include "g2o/stuff/command_args.h"
#include <QApplication>
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 32 of file g2o_viewer.cpp.
References g2o::loadStandardSolver(), g2o::loadStandardTypes(), and g2o::CommandArgs::param().
 {
   OptimizableGraph::initMultiThreading();
   QApplication qapp(argc, argv);
   CommandArgs arg;
 #ifndef G2O_DISABLE_DYNAMIC_LOADING_OF_LIBRARIES
   string dummy;
   arg.param("solverlib", dummy, "", "specify a solver library which will be loaded");
   arg.param("typeslib", dummy, "", "specify a types library which will be loaded");
   // loading the standard solver /  types
   DlWrapper dlTypesWrapper;
   loadStandardTypes(dlTypesWrapper, argc, argv);
   // register all the solvers
   DlWrapper dlSolverWrapper;
   loadStandardSolver(dlSolverWrapper, argc, argv);
 #endif
   // run the viewer
   return RunG2OViewer::run(argc, argv, arg);
 }