g2o: Utils
Utils
Files
file misc.h
some general case utility functions
file timeutil.h
utility functions for handling time related stuff
Namespaces
g2o
Macros
#define DO_EVERY_TS(secs, currentTime, code)
#define DO_EVERY(secs, code) DO_EVERY_TS(secs, g2o::get_time(), code)
Executes code, only if secs are gone since last exec.
#define MEASURE_TIME(text, code)
#define MEASURE_FUNCTION_TIME g2o::ScopeTime scopeTime(__PRETTY_FUNCTION__)
Functions
std::string g2o::trim (const std::string &s)
std::string g2o::trimLeft (const std::string &s)
std::string g2o::trimRight (const std::string &s)
std::string g2o::strToLower (const std::string &s)
std::string g2o::strToUpper (const std::string &s)
template<typename OutputIterator >
OutputIterator g2o::readInts (const char *str, OutputIterator out)
template<typename OutputIterator >
OutputIterator g2o::readFloats (const char *str, OutputIterator out)
std::string g2o::formatString (const char *fmt,...)
int g2o::strPrintf (std::string &str, const char *fmt,...)
template<typename T >
bool g2o::convertString (const std::string &s, T &x, bool failIfLeftoverChars=true)
template<typename T >
T g2o::stringToType (const std::string &s, bool failIfLeftoverChars=true)
bool g2o::strStartsWith (const std::string &s, const std::string &start)
bool g2o::strEndsWith (const std::string &s, const std::string &end)
std::string g2o::strExpandFilename (const std::string &filename)
std::vector< std::string > g2o::strSplit (const std::string &str, const std::string &delimiters)
int g2o::readLine (std::istream &is, std::stringstream &currentLine)
Detailed Description
Macro Definition Documentation
#define DO_EVERY (secs, code) DO_EVERY_TS(secs, g2o::get_time(), code)
Executes code, only if secs are gone since last exec.
Definition at line 66 of file timeutil.h.
#define DO_EVERY_TS (secs, currentTime, code)
Value:
if (1) {\
  static double s_lastDone_ = (currentTime); \
  double s_now_ = (currentTime); \
  if (s_lastDone_ > s_now_) \
    s_lastDone_ = s_now_; \
  if (s_now_ - s_lastDone_ > (secs)) { \
    code; \
    s_lastDone_ = s_now_; \
  }\
} else \
  (void)0
Executes code, only if secs are gone since last exec. extended version, in which the current time is given, e.g., timestamp of IPC message
Definition at line 50 of file timeutil.h.
#define MEASURE_FUNCTION_TIME g2o::ScopeTime scopeTime(__PRETTY_FUNCTION__)
Definition at line 127 of file timeutil.h.
#define MEASURE_TIME (text, code)
Value:
if(1) { \
    double _start_time_ = g2o::get_time(); \
    code; \
    fprintf(stderr, "%s took %f sec\n", text, g2o::get_time() - _start_time_); \
  } else \
    (void) 0
Definition at line 70 of file timeutil.h.
Function Documentation
template<typename T > bool g2o::convertString (const std::string & s, T & x, bool failIfLeftoverChars = true)
convert a string into an other type.
Definition at line 125 of file string_tools.h.
 {
   std::istringstream i(s);
   char c;
   if (!(i >> x) || (failIfLeftoverChars && i.get(c)))
     return false;
   return true;
 }
G2O_STUFF_API std::string g2o::formatString (const char * fmt, ...)
format a string and return a std::string. Format is just like printf, see man 3 printf
Definition at line 95 of file string_tools.cpp.
References __PRETTY_FUNCTION__.
Referenced by gnudump_edges(), gnudump_features(), and g2o::readFloats().
 {
   char* auxPtr = NULL;
   va_list arg_list;
   va_start(arg_list, fmt);
   int numChar = vasprintf(&auxPtr, fmt, arg_list);
   va_end(arg_list);
   string retString;
   if (numChar != -1)
     retString = auxPtr;
   else {
     cerr << __PRETTY_FUNCTION__ << ": Error while allocating memory" << endl;
   }
   free(auxPtr);
   return retString;
 }
template<typename OutputIterator > OutputIterator g2o::readFloats (const char * str, OutputIterator out)
read float values (seperated by spaces) from a string and store them in the given OutputIterator.
Definition at line 96 of file string_tools.h.
References g2o::formatString(), G2O_ATTRIBUTE_FORMAT12, G2O_ATTRIBUTE_FORMAT23, G2O_STUFF_API, and g2o::strPrintf().
 {
   char* cl  = (char*)str;
   char* cle = cl;
   while (1) {
     double val = strtod(cl, &cle);
     if (cl == cle)
       break;
     *out++ = val;
     cl = cle;
   }
   return out;
 }
template<typename OutputIterator > OutputIterator g2o::readInts (const char * str, OutputIterator out)
read integer values (seperated by spaces) from a string and store them in the given OutputIterator.
Definition at line 77 of file string_tools.h.
 {
   char* cl  = (char*)str;
   char* cle = cl;
   while (1) {
     long int id = strtol(cl, &cle, 10);
     if (cl == cle)
       break;
     *out++ = id;
     cl = cle;
   }
   return out;
 }
G2O_STUFF_API int g2o::readLine (std::istream & is, std::stringstream & currentLine)
read a line from is into currentLine.
Returns
the number of characters read into currentLine (excluding newline), -1 on eof()
Definition at line 172 of file string_tools.cpp.
Referenced by main(), g2o::ParameterContainer::read(), g2o::Gm2dlIO::readGm2dl(), g2o::Gm2dlIO::readRobotLaser(), g2o::OptimizableGraph::setFixed(), and g2o::stringToType().
 {
   if (is.eof())
     return -1;
   currentLine.str("");
   currentLine.clear();
   is.get(*currentLine.rdbuf());
   if (is.fail()) // fail is set on empty lines
     is.clear();
   G2O_FSKIP_LINE(is); // read \n not read by get()
   return static_cast<int>(currentLine.str().size());
 }
G2O_STUFF_API bool g2o::strEndsWith (const std::string & str, const std::string & substr)
return true, if str ends with substr
Definition at line 165 of file string_tools.cpp.
Referenced by str2solver(), and g2o::stringToType().
 {
   if (s.size() < end.size())
     return false;
   return equal(end.rbegin(), end.rend(), s.rbegin());
 }
G2O_STUFF_API std::string g2o::strExpandFilename (const std::string & filename)
expand the given filename like a posix shell, e.g., ~ $CARMEN_HOME and other will get expanded. Also command substitution, e.g. pwd will give the current directory.
Definition at line 124 of file string_tools.cpp.
References __PRETTY_FUNCTION__.
Referenced by g2o::stringToType().
 {
 #if (defined (UNIX) || defined(CYGWIN)) && !defined(ANDROID)
   string result = filename;
   wordexp_t p;
   wordexp(filename.c_str(), &p, 0);
   if(p.we_wordc > 0) {
     result = p.we_wordv[0];
   }
   wordfree(&p);
   return result;
 #else
   (void) filename;
   std::cerr << "WARNING: " << __PRETTY_FUNCTION__ << " not implemented" << std::endl;
   return std::string();
 #endif
 }
template<typename T > T g2o::stringToType (const std::string & s, bool failIfLeftoverChars = true)
convert a string into an other type. Return the converted value. Throw error if parsing is wrong.
Definition at line 139 of file string_tools.h.
References g2o::convertString(), G2O_STUFF_API, g2o::readLine(), g2o::strEndsWith(), g2o::strExpandFilename(), g2o::strSplit(), and g2o::strStartsWith().
 {
   T x;
   convertString(s, x, failIfLeftoverChars);
   return x;
 }
G2O_STUFF_API int g2o::strPrintf (std::string & str, const char * fmt, ...)
replacement function for sprintf which fills a std::string instead of a char*
Definition at line 112 of file string_tools.cpp.
Referenced by g2o::readFloats().
 {
   char* auxPtr = NULL;
   va_list arg_list;
   va_start(arg_list, fmt);
   int numChars = vasprintf(&auxPtr, fmt, arg_list);
   va_end(arg_list);
   str = auxPtr;
   free(auxPtr);
   return numChars;
 }
G2O_STUFF_API std::vector< std::string > g2o::strSplit (const std::string & s, const std::string & delim)
split a string into token based on the characters given in delim
Definition at line 143 of file string_tools.cpp.
Referenced by g2o::loadStandardSolver(), g2o::loadStandardTypes(), g2o::OptimizableGraph::setRenamedTypesFromString(), g2o::stringToType(), and g2o::PropertyMap::updateMapFromString().
 {
   std::vector<std::string> tokens;
   string::size_type lastPos = 0;
   string::size_type pos     = 0;
   do {
     pos = str.find_first_of(delimiters, lastPos);
     tokens.push_back(str.substr(lastPos, pos - lastPos));
     lastPos = pos + 1;
   }  while (string::npos != pos);
   return tokens;
 }
G2O_STUFF_API bool g2o::strStartsWith (const std::string & str, const std::string & substr)
return true, if str starts with substr
Definition at line 158 of file string_tools.cpp.
Referenced by str2solver(), and g2o::stringToType().
 {
   if (s.size() < start.size())
     return false;
   return equal(start.begin(), start.end(), s.begin());
 }
G2O_STUFF_API std::string g2o::strToLower (const std::string & s)
convert the string to lower case
Definition at line 81 of file string_tools.cpp.
References transform().
Referenced by str2method().
 {
   string ret;
   std::transform(s.begin(), s.end(), back_inserter(ret), (int(*)(int)) std::tolower);
   return ret;
 }
G2O_STUFF_API std::string g2o::strToUpper (const std::string & s)
convert a string to upper case
Definition at line 88 of file string_tools.cpp.
References transform().
 {
   string ret;
   std::transform(s.begin(), s.end(), back_inserter(ret), (int(*)(int)) std::toupper);
   return ret;
 }
G2O_STUFF_API std::string g2o::trim (const std::string & s)
remove whitespaces from the start/end of a string
Definition at line 48 of file string_tools.cpp.
Referenced by g2o::OptimizableGraph::setRenamedTypesFromString(), and g2o::PropertyMap::updateMapFromString().
 {
   if(s.length() == 0)
     return s;
   string::size_type b = s.find_first_not_of(" \t\n");
   string::size_type e = s.find_last_not_of(" \t\n");
   if(b == string::npos)
     return "";
   return std::string(s, b, e - b + 1);
 }
G2O_STUFF_API std::string g2o::trimLeft (const std::string & s)
remove whitespaces from the left side of the string
Definition at line 59 of file string_tools.cpp.
 {
   if(s.length() == 0)
     return s;
   string::size_type b = s.find_first_not_of(" \t\n");
   string::size_type e = s.length() - 1;
   if(b == string::npos)
     return "";
   return std::string(s, b, e - b + 1);
 }
G2O_STUFF_API std::string g2o::trimRight (const std::string & s)
remove whitespaced from the right side of the string
Definition at line 70 of file string_tools.cpp.
 {
   if(s.length() == 0)
     return s;
   string::size_type b = 0;
   string::size_type e = s.find_last_not_of(" \t\n");
   if(b == string::npos)
     return "";
   return std::string(s, b, e - b + 1);
 }