g2o: libviewer
libviewer
Namespaces
g2o
g2o::opengl
Macros
#define G2O_OPENGL_API
Functions
void g2o::opengl::drawBox (GLfloat l, GLfloat w, GLfloat h)
void g2o::opengl::drawPlane (GLfloat l, GLfloat w)
void g2o::opengl::drawSphere (GLfloat radius)
void g2o::opengl::drawEllipsoid (GLfloat r1, GLfloat r2, GLfloat r3)
void g2o::opengl::drawCone (GLfloat radius, GLfloat height)
void g2o::opengl::drawDisk (GLfloat radius)
void g2o::opengl::drawCylinder (GLfloat radius, GLfloat height)
void g2o::opengl::drawPyramid (GLfloat length, GLfloat height)
void g2o::opengl::drawRangeRing (GLfloat range, GLfloat fov, GLfloat range_width)
void g2o::opengl::drawSlice (GLfloat radius, GLfloat height, GLfloat fov, int slices_per_circle)
void g2o::opengl::drawPoseBox ()
void g2o::opengl::drawArrow2D (float len, float head_width, float head_len)
void g2o::opengl::drawPoint (float pointSize)
Detailed Description
Macro Definition Documentation
#define G2O_OPENGL_API
Definition at line 44 of file opengl_primitives.h.
Function Documentation
void G2O_OPENGL_API g2o::opengl::drawArrow2D (float len, float head_width, float head_len)
draw a 2D arrow along the x axis with the given len
Definition at line 59 of file opengl_primitives.cpp.
Referenced by g2o::VertexSE2WriteGnuplotAction::operator()(), g2o::EdgeSE2WriteGnuplotAction::operator()(), and g2o::VertexSE3WriteGnuplotAction::operator()().
 {
   glBegin(GL_LINES);
   glVertex2f(0.f, 0.f);
   glVertex2f(len, 0.f);
   glEnd();
   glNormal3f(0.f,0.f,1.f);
   glBegin(GL_TRIANGLES);
   glVertex2f(len, 0.f);
   glVertex2f(len - head_len,  0.5f*head_width);
   glVertex2f(len - head_len, -0.5f*head_width);
   glEnd();
 }
void G2O_OPENGL_API g2o::opengl::drawBox (GLfloat l, GLfloat w, GLfloat h)
draw a box that is centered in the current coordinate frame
Parameters
l length of the box (x dimension)
w width of the box (y dimension)
h height of the box (z dimension)
Definition at line 108 of file opengl_primitives.cpp.
Referenced by g2o::opengl::drawPoseBox(), g2o::CacheSE3Offset::setOffsetParam(), and g2o::VertexTag::write().
 {
   GLfloat sx = l*0.5f;
   GLfloat sy = w*0.5f;
   GLfloat sz = h*0.5f;
   glBegin(GL_QUADS);
   // bottom
   glNormal3f( 0.0f, 0.0f,-1.0f);
   glVertex3f(-sx, -sy, -sz);
   glVertex3f(-sx, sy, -sz);
   glVertex3f(sx, sy, -sz);
   glVertex3f(sx, -sy, -sz);
   // top
   glNormal3f( 0.0f, 0.0f,1.0f);
   glVertex3f(-sx, -sy, sz);
   glVertex3f(-sx, sy, sz);
   glVertex3f(sx, sy, sz);
   glVertex3f(sx, -sy, sz);
   // back
   glNormal3f(-1.0f, 0.0f, 0.0f);
   glVertex3f(-sx, -sy, -sz);
   glVertex3f(-sx, sy, -sz);
   glVertex3f(-sx, sy, sz);
   glVertex3f(-sx, -sy, sz);
   // front
   glNormal3f( 1.0f, 0.0f, 0.0f);
   glVertex3f(sx, -sy, -sz);
   glVertex3f(sx, sy, -sz);
   glVertex3f(sx, sy, sz);
   glVertex3f(sx, -sy, sz);
   // left
   glNormal3f( 0.0f, -1.0f, 0.0f);
   glVertex3f(-sx, -sy, -sz);
   glVertex3f(sx, -sy, -sz);
   glVertex3f(sx, -sy, sz);
   glVertex3f(-sx, -sy, sz);
   //right
   glNormal3f( 0.0f, 1.0f, 0.0f);
   glVertex3f(-sx, sy, -sz);
   glVertex3f(sx, sy, -sz);
   glVertex3f(sx, sy, sz);
   glVertex3f(-sx, sy, sz);
   glEnd();
 }
void G2O_OPENGL_API g2o::opengl::drawCone (GLfloat radius, GLfloat height)
draw a cone
Definition at line 186 of file opengl_primitives.cpp.
References g2o::opengl::GLUWrapper::getQuadradic().
 {
   glPushMatrix();
   glRotatef(-90.f, 1.f, 0.f, 0.f);
   glTranslatef(0.f, 0.f, - height/2.0f);
   gluCylinder(GLUWrapper::getQuadradic(), radius, 0.f, height, 32, 1);
   gluDisk(GLUWrapper::getQuadradic(), 0, radius, 32, 1);
   glPopMatrix();
 }
void G2O_OPENGL_API g2o::opengl::drawCylinder (GLfloat radius, GLfloat height)
draw a (closed) cylinder
Parameters
radius the radius of the cylinder
height the height of the cylinder
Definition at line 196 of file opengl_primitives.cpp.
References g2o::opengl::GLUWrapper::getQuadradic().
 {
   glPushMatrix();
   glRotatef(-90, 1.f, 0.f, 0.f);
   glTranslatef(0.f, 0.f, + height/2.0f);
   gluDisk(GLUWrapper::getQuadradic(), 0.f, radius, 32, 1);
   glTranslatef(0, 0, - height);
   gluCylinder(GLUWrapper::getQuadradic(), radius, radius, height, 32, 1);
   glRotatef(180, 1.f, 0.f, 0.f);
   gluDisk(GLUWrapper::getQuadradic(), 0, radius, 32, 1);
   glPopMatrix();
 }
void G2O_OPENGL_API g2o::opengl::drawDisk (GLfloat radius)
draw a disk
Definition at line 209 of file opengl_primitives.cpp.
References g2o::opengl::GLUWrapper::getQuadradic().
 {
   glRotatef(90, 0.f, 1.f, 0.f);
   gluDisk(GLUWrapper::getQuadradic(), 0, radius, 32, 1);
 }
void G2O_OPENGL_API g2o::opengl::drawEllipsoid (GLfloat r1, GLfloat r2, GLfloat r3)
draw a ellipsoid whose center is in the origin of the current coordinate frame
Parameters
r1 radius along x axis
r2 radius along y axis
r3 radius along z axis
Definition at line 173 of file opengl_primitives.cpp.
References g2o::opengl::GLUWrapper::getQuadradic().
 {
   GLboolean hasNormalization = glIsEnabled(GL_NORMALIZE);
   if (!hasNormalization)
     glEnable(GL_NORMALIZE);
   glPushMatrix();
   glScalef(r1, r2, r3);
   gluSphere(GLUWrapper::getQuadradic(), 1.0f, 32, 32);
   glPopMatrix();
   if (!hasNormalization)
     glDisable(GL_NORMALIZE);
 }
void G2O_OPENGL_API g2o::opengl::drawPlane (GLfloat l, GLfloat w)
draw a plane in x-y dimension with a height of zero
Parameters
l length in x
w width in y
Definition at line 154 of file opengl_primitives.cpp.
 {
   GLfloat sx = l*0.5f;
   GLfloat sy = w*0.5f;
   glBegin(GL_QUADS);
   glNormal3f( 0.0f, 0.0f, 1.0f);
   glVertex3f(-sx, -sy, 0.f);
   glVertex3f(-sx, sy, 0.f);
   glVertex3f(sx, sy, 0.f);
   glVertex3f(sx, -sy, 0.f);
   glEnd();
 }
void G2O_OPENGL_API g2o::opengl::drawPoint (float pointSize)
draw a point in the origin, having a size of pointSize
Definition at line 301 of file opengl_primitives.cpp.
Referenced by g2o::VertexPointXYWriteGnuplotAction::operator()(), and g2o::VertexPointXYZ::write().
{
     glPointSize(pointSize);
     glBegin(GL_POINTS);
     glVertex3f(0,0,0);
     glEnd();
   }
void G2O_OPENGL_API g2o::opengl::drawPoseBox ()
draws a box used to represent a 6d pose
Definition at line 74 of file opengl_primitives.cpp.
References g2o::opengl::drawBox().
 {
   glPushMatrix();
   glScalef(0.5f,1.f,1.f);
   glPushMatrix();
   glScalef(1.f,0.25f,0.5f);
   glTranslatef(-0.5f,0.5f,0.f);
   glColor3f(1.0f, 0.3f, 0.3f);
   drawBox(1.f, 1.f, 1.f);
   glPopMatrix();
   glPushMatrix();
   glScalef(1.f,0.25f,0.5f);
   glTranslatef(-0.5f,-0.5f,0.f);
   glColor3f(1.0f, 0.1f, 0.1f);
   drawBox(1.f, 1.f, 1.f);
   glPopMatrix();
   glPushMatrix();
   glScalef(1.f,0.25f,0.5f);
   glTranslatef(+0.5f,0.5f,0.f);
   glColor3f(0.3f, 0.3f, 1.0f);
   drawBox(1.f, 1.f, 1.f);
   glPopMatrix();
   glPushMatrix();
   glScalef(1.f,0.25f,0.5f);
   glTranslatef(+0.5f,-0.5f,0.f);
   glColor3f(0.1f, 0.1f, 1.f);
   drawBox(1.f, 1.f, 1.f);
   glPopMatrix();
   glPopMatrix();
 }
void G2O_OPENGL_API g2o::opengl::drawPyramid (GLfloat length, GLfloat height)
draw a pyramid
Definition at line 215 of file opengl_primitives.cpp.
References g2o::opengl::GLUWrapper::getQuadradic().
Referenced by g2o::CacheCamera::updateImpl().
 {
   glPushMatrix();
   glTranslatef(0.f, 0.f, - height/2.0f);
   glRotatef(45, 0.f, 0.f, 1.f);
   gluCylinder(GLUWrapper::getQuadradic(), length, 0.f, height, 4, 1);
   gluDisk(GLUWrapper::getQuadradic(), 0, length, 4, 1);
   glPopMatrix();
 }
void G2O_OPENGL_API g2o::opengl::drawRangeRing (GLfloat range, GLfloat fov, GLfloat range_width = 0.05)
draw a range ring
Parameters
range the range (radius) of the partial ring
fov Field Of View of the range sensor
range_width specify how thick the ring should be drawn
Definition at line 225 of file opengl_primitives.cpp.
References g2o::opengl::GLUWrapper::getQuadradic().
 {
   glPushMatrix();
   glRotatef((fov/2.0f) - 90, 0.f, 0.f, 1.f);
   gluPartialDisk(GLUWrapper::getQuadradic(), range, range + range_width, 32, 1, 0.f, fov);
   glPopMatrix();
 }
void G2O_OPENGL_API g2o::opengl::drawSlice (GLfloat radius, GLfloat height, GLfloat fov, int slices_per_circle = 32)
draw a slice of a cylinder (approximated with slices_per_circle triangles for the complete circle)
Parameters
radius the radius of the cylinder
height the height of the cylinder
fov the "fov" of the slice (om degree)
slices_per_circle the number of triangle used to approximate the fulle circle
Definition at line 233 of file opengl_primitives.cpp.
References M_PI.
 {
   double fov_rad = fov/180.*M_PI; // convert to rad
   int num_slices = int(slices_per_circle * (fov_rad / (2*M_PI))) + 1;
   double angle_step = fov_rad / num_slices;
   double angle_step_half = angle_step * 0.5;
   GLfloat height_half = height * 0.5f;
   GLfloat lower_z = -height_half;
   GLfloat upper_z =  height_half;
   GLfloat last_x = float(std::cos(-fov_rad * 0.5f) * radius);
   GLfloat last_y = float(std::sin(-fov_rad * 0.5f) * radius);
   glPushMatrix();
   glBegin(GL_TRIANGLES);
   glNormal3f((float)std::sin(-fov_rad * 0.5), (float)-std::cos(-fov_rad * 0.5), 0.f);
   glVertex3f(0.f, 0.f, upper_z);
   glVertex3f(0.f, 0.f, lower_z);
   glVertex3f(last_x, last_y, upper_z);
   glVertex3f(last_x, last_y, upper_z);
   glVertex3f(last_x, last_y, lower_z);
   glVertex3f(0.f, 0.f, lower_z);
   double start_angle = -0.5*fov_rad + angle_step;
   double angle       = start_angle;
   for (int i = 0; i < num_slices; ++i) {
     GLfloat x = float(std::cos(angle) * radius);
     GLfloat y = float(std::sin(angle) * radius);
     GLfloat front_normal_x = (float)std::cos(angle + angle_step_half);
     GLfloat front_normal_y = (float)std::sin(angle + angle_step_half);
     // lower triangle
     glNormal3f(0.f, 0.f, -1.f);
     glVertex3f(0.f, 0.f, lower_z);
     glVertex3f(x, y, lower_z);
     glVertex3f(last_x, last_y, lower_z);
     // upper
     glNormal3f(0.f, 0.f, 1.f);
     glVertex3f(0.f, 0.f, upper_z);
     glVertex3f(x, y, upper_z);
     glVertex3f(last_x, last_y, upper_z);
     //front rectangle (we use two triangles)
     glNormal3f(front_normal_x, front_normal_y, 0.f);
     glVertex3f(last_x, last_y, upper_z);
     glVertex3f(last_x, last_y, lower_z);
     glVertex3f(x, y, upper_z);
     glVertex3f(x, y, upper_z);
     glVertex3f(x, y, lower_z);
     glVertex3f(last_x, last_y, lower_z);
     last_x = x;
     last_y = y;
     angle += angle_step;
   }
   glNormal3f(float(-std::sin(fov_rad * 0.5)), float(std::cos(fov_rad * 0.5)), -0.f);
   glVertex3f(0.f, 0.f, upper_z);
   glVertex3f(0.f, 0.f, lower_z);
   glVertex3f(last_x, last_y, upper_z);
   glVertex3f(last_x, last_y, upper_z);
   glVertex3f(last_x, last_y, lower_z);
   glVertex3f(0.f, 0.f, lower_z);
   glEnd();
   glPopMatrix();
 }
void G2O_OPENGL_API g2o::opengl::drawSphere (GLfloat radius)
draw a sphere whose center is in the origin of the current coordinate frame
Parameters
radius the radius of the sphere
Definition at line 168 of file opengl_primitives.cpp.
References g2o::opengl::GLUWrapper::getQuadradic().
 {
   gluSphere(GLUWrapper::getQuadradic(), radius, 32, 32);
 }