g2o: /home/xuezhisd/CLionProjects/g2o/g2o/types/slam3d_addons/line3d_test.cpp File Reference
line3d_test.cpp File Reference
#include "line3d.h"
#include "g2o/types/slam3d/isometry3d_mappings.h"
#include "g2o/types/slam3d/isometry3d_gradients.h"
#include <iostream>
Functions
template<typename T >
ostream & printVector (ostream &os, const T &t)
int main (int, char **)
Function Documentation
int main (int , char **)
Definition at line 20 of file line3d_test.cpp.
References g2o::internal::fromVectorMQT(), g2o::internal::normalizeCartesianLine(), printVector(), g2o::Line3D::toCartesian(), and g2o::internal::transformCartesianLine().
 {
   Vector6d t;
   t <<  -3, -2, -4, .2, .1, .3;
   Isometry3D T = fromVectorMQT(t);
   cout << "transform" << endl;
   cout << T.matrix() << endl;
   Vector6d cl1;
   cl1 << 20, 50, -70, .1, .2, .3;
   cl1 =normalizeCartesianLine(cl1);
   cout << "cartesian line L1: "; printVector(cout, cl1); cout << endl;
   Line3D pl1 = Line3D::fromCartesian(cl1);
   cout << "pluecker line L1: "; printVector(cout, pl1); cout << endl;
   cout << "cartesian line L1, reconstructed from puecker: "; printVector(cout, pl1.toCartesian()); cout << endl;
   Vector6d cl2=transformCartesianLine(T,cl1);
   Line3D pl2 = T*pl1;;
   cout << "transformed line L2: "; printVector(cout, cl2); cout << endl;
   cout << "transformed pline L2: "; printVector(cout, pl2); cout << endl;
   cout << "error of cartesian line L2, reconstructed from puecker: "; printVector(cout, cl2 - pl2.toCartesian());
   cout << endl;
   return 0;
 }
template<typename T > ostream& printVector (ostream & os, const T & t)
Definition at line 12 of file line3d_test.cpp.
Referenced by main().
 {
   for (int i=0; i<t.rows(); i++){
     os << t(i) << " ";
   }
   return os;
 }