g2o: g2o::types_six_dof_expmap Namespace Reference
g2o::types_six_dof_expmap Namespace Reference
Functions
void init ()
Function Documentation
void g2o::types_six_dof_expmap::init ()
Definition at line 43 of file types_icp.cpp.
References g2o::types_icp::initialized.
Referenced by g2o::G2O_ATTRIBUTE_CONSTRUCTOR(), g2o::Slam2DViewer::init(), and g2o::G2oQGLViewer::init().
     {
       if (types_icp::initialized)
         return;
       //cerr << "Calling " << __FILE__ << " " << __PRETTY_FUNCTION__ << endl;
       Edge_V_V_GICP::dRidx << 0.0,0.0,0.0,
         0.0,0.0,2.0,
         0.0,-2.0,0.0;
       Edge_V_V_GICP::dRidy  << 0.0,0.0,-2.0,
         0.0,0.0,0.0,
         2.0,0.0,0.0;
       Edge_V_V_GICP::dRidz  << 0.0,2.0,0.0,
         -2.0,0.0,0.0,
         0.0,0.0,0.0;
       VertexSCam::dRidx << 0.0,0.0,0.0,
         0.0,0.0,2.0,
         0.0,-2.0,0.0;
       VertexSCam::dRidy  << 0.0,0.0,-2.0,
         0.0,0.0,0.0,
         2.0,0.0,0.0;
       VertexSCam::dRidz  << 0.0,2.0,0.0,
         -2.0,0.0,0.0,
         0.0,0.0,0.0;
       types_icp::initialized = 1;
     }