g2o: g2o::internal Namespace Reference
g2o::internal Namespace Reference
Namespaces
g2o
Functions
int computeUpperTriangleIndex (int i, int j)
template<typename MatrixType >
void axpy (const MatrixType &A, const Eigen::Map< const Eigen::VectorXd > &x, int xoff, Eigen::Map< Eigen::VectorXd > &y, int yoff)
template<int t>
void axpy (const Eigen::Matrix< double, Eigen::Dynamic, t > &A, const Eigen::Map< const Eigen::VectorXd > &x, int xoff, Eigen::Map< Eigen::VectorXd > &y, int yoff)
template<>
void axpy< Eigen::MatrixXd > (const Eigen::MatrixXd &A, const Eigen::Map< const Eigen::VectorXd > &x, int xoff, Eigen::Map< Eigen::VectorXd > &y, int yoff)
template<typename MatrixType >
void atxpy (const MatrixType &A, const Eigen::Map< const Eigen::VectorXd > &x, int xoff, Eigen::Map< Eigen::VectorXd > &y, int yoff)
template<int t>
void atxpy (const Eigen::Matrix< double, Eigen::Dynamic, t > &A, const Eigen::Map< const Eigen::VectorXd > &x, int xoff, Eigen::Map< Eigen::VectorXd > &y, int yoff)
template<>
void atxpy< Eigen::MatrixXd > (const Eigen::MatrixXd &A, const Eigen::Map< const Eigen::VectorXd > &x, int xoff, Eigen::Map< Eigen::VectorXd > &y, int yoff)
template<typename MatrixType >
void pcg_axy (const MatrixType &A, const VectorXD &x, int xoff, VectorXD &y, int yoff)
template<>
void pcg_axy (const MatrixXD &A, const VectorXD &x, int xoff, VectorXD &y, int yoff)
template<typename MatrixType >
void pcg_axpy (const MatrixType &A, const VectorXD &x, int xoff, VectorXD &y, int yoff)
template<>
void pcg_axpy (const MatrixXD &A, const VectorXD &x, int xoff, VectorXD &y, int yoff)
template<typename MatrixType >
void pcg_atxpy (const MatrixType &A, const VectorXD &x, int xoff, VectorXD &y, int yoff)
template<>
void pcg_atxpy (const MatrixXD &A, const VectorXD &x, int xoff, VectorXD &y, int yoff)
void compute_dq_dR_w (Eigen::Matrix< double, 3, 9 > &dq_dR_w, const double &qw, const double &r00, const double &r10, const double &r20, const double &r01, const double &r11, const double &r21, const double &r02, const double &r12, const double &r22)
void compute_dq_dR_x (Eigen::Matrix< double, 3, 9 > &dq_dR_x, const double &qx, const double &r00, const double &r10, const double &r20, const double &r01, const double &r11, const double &r21, const double &r02, const double &r12, const double &r22)
void compute_dq_dR_y (Eigen::Matrix< double, 3, 9 > &dq_dR_y, const double &qy, const double &r00, const double &r10, const double &r20, const double &r01, const double &r11, const double &r21, const double &r02, const double &r12, const double &r22)
void compute_dq_dR_z (Eigen::Matrix< double, 3, 9 > &dq_dR_z, const double &qz, const double &r00, const double &r10, const double &r20, const double &r01, const double &r11, const double &r21, const double &r02, const double &r12, const double &r22)
void compute_dR_dq (Eigen::Matrix< double, 9, 3 > &dR_dq, const double &qx, const double &qy, const double &qz, const double &qw)
int _q2m (double &S, double &qw, const double &r00, const double &r10, const double &r20, const double &r01, const double &r11, const double &r21, const double &r02, const double &r12, const double &r22)
void compute_dq_dR (Eigen::Matrix< double, 3, 9, Eigen::ColMajor > &dq_dR, const double &r11, const double &r21, const double &r31, const double &r12, const double &r22, const double &r32, const double &r13, const double &r23, const double &r33)
void G2O_TYPES_SLAM3D_API compute_dR_dq (Eigen::Matrix< double, 9, 3, Eigen::ColMajor > &dR_dq, const double &qx, const double &qy, const double &qz, const double &qw)
template<typename Derived , typename DerivedOther >
void skew (Eigen::MatrixBase< Derived > &s, const Eigen::MatrixBase< DerivedOther > &v)
template<typename Derived , typename DerivedOther >
void skewT (Eigen::MatrixBase< Derived > &s, const Eigen::MatrixBase< DerivedOther > &v)
template<typename Derived , typename DerivedOther >
void skew (Eigen::MatrixBase< Derived > &Sx, Eigen::MatrixBase< Derived > &Sy, Eigen::MatrixBase< Derived > &Sz, const Eigen::MatrixBase< DerivedOther > &R)
template<typename Derived , typename DerivedOther >
void skewT (Eigen::MatrixBase< Derived > &Sx, Eigen::MatrixBase< Derived > &Sy, Eigen::MatrixBase< Derived > &Sz, const Eigen::MatrixBase< DerivedOther > &R)
template<typename Derived >
void computeEdgeSE3Gradient (Isometry3D &E, Eigen::MatrixBase< Derived > const &JiConstRef, Eigen::MatrixBase< Derived > const &JjConstRef, const Isometry3D &Z, const Isometry3D &Xi, const Isometry3D &Xj, const Isometry3D &Pi, const Isometry3D &Pj)
template<typename Derived >
void computeEdgeSE3Gradient (Isometry3D &E, Eigen::MatrixBase< Derived > const &JiConstRef, Eigen::MatrixBase< Derived > const &JjConstRef, const Isometry3D &Z, const Isometry3D &Xi, const Isometry3D &Xj)
template<typename Derived >
void computeEdgeSE3PriorGradient (Isometry3D &E, const Eigen::MatrixBase< Derived > &JConstRef, const Isometry3D &Z, const Isometry3D &X, const Isometry3D &P=Isometry3D())
Eigen::Quaterniond normalized (const Eigen::Quaterniond &q)
Eigen::Quaterniond & normalize (Eigen::Quaterniond &q)
Vector3D toEuler (const Matrix3D &R)
Matrix3D fromEuler (const Vector3D &v)
Vector3D toCompactQuaternion (const Matrix3D &R)
Matrix3D fromCompactQuaternion (const Vector3D &v)
Vector6d toVectorMQT (const Isometry3D &t)
Vector6d toVectorET (const Isometry3D &t)
Vector7d toVectorQT (const Isometry3D &t)
Isometry3D fromVectorMQT (const Vector6d &v)
Isometry3D fromVectorET (const Vector6d &v)
Isometry3D fromVectorQT (const Vector7d &v)
SE3Quat toSE3Quat (const Isometry3D &t)
Isometry3D fromSE3Quat (const SE3Quat &t)
Isometry3D::ConstLinearPart extractRotation (const Isometry3D &A)
template<typename Derived >
void nearestOrthogonalMatrix (const Eigen::MatrixBase< Derived > &R)
template<typename Derived >
void approximateNearestOrthogonalMatrix (const Eigen::MatrixBase< Derived > &R)
Vector6d transformCartesianLine (const Isometry3D &t, const Vector6d &line)
Vector6d normalizeCartesianLine (const Vector6d &line)
Detailed Description
internal functions used inside g2o. Those functions may disappear or change their meaning without further notification
Function Documentation
int g2o::internal::_q2m (double & S, double & qw, const double & r00, const double & r10, const double & r20, const double & r01, const double & r11, const double & r21, const double & r02, const double & r12, const double & r22)
Definition at line 9 of file dquat2mat.cpp.
Referenced by compute_dq_dR().
{
       double tr=r00 + r11 + r22;
       if (tr > 0) {
         S = sqrt(tr + 1.0) * 2; // S=4*qw
         qw = 0.25 * S;
         // qx = (r21 - r12) / S;
         // qy = (r02 - r20) / S;
         // qz = (r10 - r01) / S;
         return 0;
       } else if ((r00 > r11)&(r00 > r22)) {
         S = sqrt(1.0 + r00 - r11 - r22) * 2; // S=4*qx
         qw = (r21 - r12) / S;
         // qx = 0.25 * S;
         // qy = (r01 + r10) / S;
         // qz = (r02 + r20) / S;
         return 1;
       } else if (r11 > r22) {
         S = sqrt(1.0 + r11 - r00 - r22) * 2; // S=4*qy
         qw = (r02 - r20) / S;
         // qx = (r01 + r10) / S;
         // qy = 0.25 * S;
         // qz = (r12 + r21) / S;
         return 2;
       } else {
         S = sqrt(1.0 + r22 - r00 - r11) * 2; // S=4*qz
         qw = (r10 - r01) / S;
         // qx = (r02 + r20) / S;
         // qy = (r12 + r21) / S;
         // qz = 0.25 * S;
         return 3;
       }
     }
template<typename Derived > void g2o::internal::approximateNearestOrthogonalMatrix (const Eigen::MatrixBase< Derived > & R)
compute a fast approximation for the nearest orthogonal rotation matrix. The function computes the residual E = RR^T - I which is then used as follows: R := R - 1/2 R E
Definition at line 85 of file isometry3d_mappings.h.
References fromCompactQuaternion(), fromEuler(), fromSE3Quat(), fromVectorET(), fromVectorMQT(), fromVectorQT(), G2O_TYPES_SLAM3D_API, normalize(), normalized(), toCompactQuaternion(), toEuler(), toSE3Quat(), toVectorET(), toVectorMQT(), and toVectorQT().
Referenced by main(), and g2o::VertexSE3::oplusImpl().
     {
       Matrix3D E = R.transpose() * R;
       E.diagonal().array() -= 1;
       const_cast<Eigen::MatrixBase<Derived>&>(R) -= 0.5 * R * E;
     }
template<typename MatrixType > void g2o::internal::atxpy (const MatrixType & A, const Eigen::Map< const Eigen::VectorXd > & x, int xoff, Eigen::Map< Eigen::VectorXd > & y, int yoff) inline
Definition at line 54 of file matrix_operations.h.
     {
       y.segment<MatrixType::ColsAtCompileTime>(yoff) += A.transpose() * x.segment<MatrixType::RowsAtCompileTime>(xoff);
     }
template<int t> void g2o::internal::atxpy (const Eigen::Matrix< double, Eigen::Dynamic, t > & A, const Eigen::Map< const Eigen::VectorXd > & x, int xoff, Eigen::Map< Eigen::VectorXd > & y, int yoff) inline
Definition at line 60 of file matrix_operations.h.
     {
       y.segment<Eigen::Matrix<double, Eigen::Dynamic, t>::ColsAtCompileTime>(yoff) += A.transpose() * x.segment(xoff, A.rows());
     }
template<> void g2o::internal::atxpy< Eigen::MatrixXd > (const Eigen::MatrixXd & A, const Eigen::Map< const Eigen::VectorXd > & x, int xoff, Eigen::Map< Eigen::VectorXd > & y, int yoff) inline
Definition at line 66 of file matrix_operations.h.
     {
       y.segment(yoff, A.cols()) += A.transpose() * x.segment(xoff, A.rows());
     }
template<typename MatrixType > void g2o::internal::axpy (const MatrixType & A, const Eigen::Map< const Eigen::VectorXd > & x, int xoff, Eigen::Map< Eigen::VectorXd > & y, int yoff) inline
Definition at line 36 of file matrix_operations.h.
     {
       y.segment<MatrixType::RowsAtCompileTime>(yoff) += A * x.segment<MatrixType::ColsAtCompileTime>(xoff);
     }
template<int t> void g2o::internal::axpy (const Eigen::Matrix< double, Eigen::Dynamic, t > & A, const Eigen::Map< const Eigen::VectorXd > & x, int xoff, Eigen::Map< Eigen::VectorXd > & y, int yoff) inline
Definition at line 42 of file matrix_operations.h.
     {
       y.segment(yoff, A.rows()) += A * x.segment<Eigen::Matrix<double, Eigen::Dynamic, t>::ColsAtCompileTime>(xoff);
     }
template<> void g2o::internal::axpy< Eigen::MatrixXd > (const Eigen::MatrixXd & A, const Eigen::Map< const Eigen::VectorXd > & x, int xoff, Eigen::Map< Eigen::VectorXd > & y, int yoff) inline
Definition at line 48 of file matrix_operations.h.
     {
       y.segment(yoff, A.rows()) += A * x.segment(xoff, A.cols());
     }
void G2O_TYPES_SLAM3D_API g2o::internal::compute_dq_dR (Eigen::Matrix< double, 3, 9, Eigen::ColMajor > & dq_dR, const double & r11, const double & r21, const double & r31, const double & r12, const double & r22, const double & r32, const double & r13, const double & r23, const double & r33)
Definition at line 42 of file dquat2mat.cpp.
References _q2m(), compute_dq_dR_w(), compute_dq_dR_x(), compute_dq_dR_y(), and compute_dq_dR_z().
Referenced by computeEdgeSE3Gradient(), computeEdgeSE3PriorGradient(), and main().
{
       double qw;
       double S;
       int whichCase=_q2m( S, qw, r11 ,  r21 ,  r31 ,  r12 ,  r22 ,  r32 ,  r13 ,  r23 ,  r33 );
       S*=.25;
       switch(whichCase){
       case 0: compute_dq_dR_w(dq_dR, S, r11 ,  r21 ,  r31 ,  r12 ,  r22 ,  r32 ,  r13 ,  r23 ,  r33 );
         break;
       case 1: compute_dq_dR_x(dq_dR, S, r11 ,  r21 ,  r31 ,  r12 ,  r22 ,  r32 ,  r13 ,  r23 ,  r33 );
         break;
       case 2: compute_dq_dR_y(dq_dR, S, r11 ,  r21 ,  r31 ,  r12 ,  r22 ,  r32 ,  r13 ,  r23 ,  r33 );
         break;
       case 3: compute_dq_dR_z(dq_dR, S, r11 ,  r21 ,  r31 ,  r12 ,  r22 ,  r32 ,  r13 ,  r23 ,  r33 );
         break;
       }
       if (qw<=0)
         dq_dR *= -1;
     }
void g2o::internal::compute_dq_dR_w (Eigen::Matrix< double, 3, 9 > & dq_dR_w, const double & qw, const double & r00, const double & r10, const double & r20, const double & r01, const double & r11, const double & r21, const double & r02, const double & r12, const double & r22)
Definition at line 2 of file dquat2mat.cpp.
Referenced by compute_dq_dR().
               {
   namespace internal {
     using namespace std;
 #include "dquat2mat_maxima_generated.cpp"
     int _q2m(double& S, double& qw, const double&  r00 , const double&  r10 , const double&  r20 , const double&  r01 , const double&  r11 , const double&  r21 , const double&  r02 , const double&  r12 , const double&  r22 ){
       double tr=r00 + r11 + r22;
       if (tr > 0) {
         S = sqrt(tr + 1.0) * 2; // S=4*qw
         qw = 0.25 * S;
         // qx = (r21 - r12) / S;
         // qy = (r02 - r20) / S;
         // qz = (r10 - r01) / S;
         return 0;
       } else if ((r00 > r11)&(r00 > r22)) {
         S = sqrt(1.0 + r00 - r11 - r22) * 2; // S=4*qx
         qw = (r21 - r12) / S;
         // qx = 0.25 * S;
         // qy = (r01 + r10) / S;
         // qz = (r02 + r20) / S;
         return 1;
       } else if (r11 > r22) {
         S = sqrt(1.0 + r11 - r00 - r22) * 2; // S=4*qy
         qw = (r02 - r20) / S;
         // qx = (r01 + r10) / S;
         // qy = 0.25 * S;
         // qz = (r12 + r21) / S;
         return 2;
       } else {
         S = sqrt(1.0 + r22 - r00 - r11) * 2; // S=4*qz
         qw = (r10 - r01) / S;
         // qx = (r02 + r20) / S;
         // qy = (r12 + r21) / S;
         // qz = 0.25 * S;
         return 3;
       }
     }
void g2o::internal::compute_dq_dR_x (Eigen::Matrix< double, 3, 9 > & dq_dR_x, const double & qx, const double & r00, const double & r10, const double & r20, const double & r01, const double & r11, const double & r21, const double & r02, const double & r12, const double & r22)
Definition at line 41 of file dquat2mat.cpp.
Referenced by compute_dq_dR().
{
       double qw;
       double S;
       int whichCase=_q2m( S, qw, r11 ,  r21 ,  r31 ,  r12 ,  r22 ,  r32 ,  r13 ,  r23 ,  r33 );
       S*=.25;
       switch(whichCase){
       case 0: compute_dq_dR_w(dq_dR, S, r11 ,  r21 ,  r31 ,  r12 ,  r22 ,  r32 ,  r13 ,  r23 ,  r33 );
         break;
       case 1: compute_dq_dR_x(dq_dR, S, r11 ,  r21 ,  r31 ,  r12 ,  r22 ,  r32 ,  r13 ,  r23 ,  r33 );
         break;
       case 2: compute_dq_dR_y(dq_dR, S, r11 ,  r21 ,  r31 ,  r12 ,  r22 ,  r32 ,  r13 ,  r23 ,  r33 );
         break;
       case 3: compute_dq_dR_z(dq_dR, S, r11 ,  r21 ,  r31 ,  r12 ,  r22 ,  r32 ,  r13 ,  r23 ,  r33 );
         break;
       }
       if (qw<=0)
         dq_dR *= -1;
     }
   }
 }
void g2o::internal::compute_dq_dR_y (Eigen::Matrix< double, 3, 9 > & dq_dR_y, const double & qy, const double & r00, const double & r10, const double & r20, const double & r01, const double & r11, const double & r21, const double & r02, const double & r12, const double & r22)
Definition at line 83 of file dquat2mat.cpp.
Referenced by compute_dq_dR().
void g2o::internal::compute_dq_dR_z (Eigen::Matrix< double, 3, 9 > & dq_dR_z, const double & qz, const double & r00, const double & r10, const double & r20, const double & r01, const double & r11, const double & r21, const double & r02, const double & r12, const double & r22)
Definition at line 125 of file dquat2mat.cpp.
Referenced by compute_dq_dR().
void G2O_TYPES_SLAM3D_API g2o::internal::compute_dR_dq (Eigen::Matrix< double, 9, 3, Eigen::ColMajor > & dR_dq, const double & qx, const double & qy, const double & qz, const double & qw)
void g2o::internal::compute_dR_dq (Eigen::Matrix< double, 9, 3 > & dR_dq, const double & qx, const double & qy, const double & qz, const double & qw)
Definition at line 167 of file dquat2mat.cpp.
template<typename Derived > void g2o::internal::computeEdgeSE3Gradient (Isometry3D & E, Eigen::MatrixBase< Derived > const & JiConstRef, Eigen::MatrixBase< Derived > const & JjConstRef, const Isometry3D & Z, const Isometry3D & Xi, const Isometry3D & Xj, const Isometry3D & Pi, const Isometry3D & Pj)
Definition at line 87 of file isometry3d_gradients.h.
References compute_dq_dR(), extractRotation(), skew(), and skewT().
Referenced by g2o::EdgeSE3::linearizeOplus(), and g2o::EdgeSE3Offset::linearizeOplus().
   {
     Eigen::MatrixBase<Derived>& Ji = const_cast<Eigen::MatrixBase<Derived>&>(JiConstRef);
     Eigen::MatrixBase<Derived>& Jj = const_cast<Eigen::MatrixBase<Derived>&>(JjConstRef);
     Ji.derived().resize(6,6);
     Jj.derived().resize(6,6);
     // compute the error at the linearization point
     const Isometry3D A=Z.inverse()*Pi.inverse();
     const Isometry3D B=Xi.inverse()*Xj;
     const Isometry3D& C=Pj;
     const Isometry3D AB=A*B;
     const Isometry3D BC=B*C;
     E=AB*C;
     Isometry3D::ConstLinearPart Re = extractRotation(E);
     Isometry3D::ConstLinearPart Ra = extractRotation(A);
     //const Matrix3D Rb = extractRotation(B);
     Isometry3D::ConstLinearPart Rc = extractRotation(C);
     Isometry3D::ConstTranslationPart tc = C.translation();
     //Isometry3D::ConstTranslationParttab=AB.translation();
     Isometry3D::ConstLinearPart Rab = extractRotation(AB);
     Isometry3D::ConstTranslationPart tbc = BC.translation();
     Isometry3D::ConstLinearPart Rbc = extractRotation(BC);
     Eigen::Matrix<double, 3 , 9, Eigen::ColMajor>  dq_dR;
     compute_dq_dR (dq_dR,
         Re(0,0),Re(1,0),Re(2,0),
         Re(0,1),Re(1,1),Re(2,1),
         Re(0,2),Re(1,2),Re(2,2));
     Ji.setZero();
     Jj.setZero();
     // dte/dti
     Ji.template block<3,3>(0,0)=-Ra;
     // dte/dtj
     Jj.template block<3,3>(0,0)=Rab;
     // dte/dqi
     {
       Matrix3D S;
       skewT(S,tbc);
       Ji.template block<3,3>(0,3)=Ra*S;
     }
     // dte/dqj
     {
       Matrix3D S;
       skew(S,tc);
       Jj.template block<3,3>(0,3)=Rab*S;
     }
     // dre/dqi
     {
       double buf[27];
       Eigen::Map<Eigen::Matrix<double, 9, 3, Eigen::ColMajor> > M(buf);
       Matrix3D Sxt,Syt,Szt;
       internal::skewT(Sxt,Syt,Szt,Rbc);
 #ifdef __clang__
       Matrix3D temp = Rab * Sxt;
       Eigen::Map<Matrix3D> M2(temp.data());
       Eigen::Map<Matrix3D> Mx(buf);    Mx = M2;
       temp = Ra*Syt;
       Eigen::Map<Matrix3D> My(buf+9);  My = M2;
       temp = Ra*Szt;
       Eigen::Map<Matrix3D> Mz(buf+18); Mz = M2;
 #else
       Eigen::Map<Matrix3D> Mx(buf);    Mx = Ra*Sxt;
       Eigen::Map<Matrix3D> My(buf+9);  My = Ra*Syt;
       Eigen::Map<Matrix3D> Mz(buf+18); Mz = Ra*Szt;
 #endif
       Ji.template block<3,3>(3,3) = dq_dR * M;
     }
     // dre/dqj
     {
       double buf[27];
       Eigen::Map <Eigen::Matrix<double, 9, 3, Eigen::ColMajor> > M(buf);
       Matrix3D Sx,Sy,Sz;
       internal::skew(Sx,Sy,Sz,Rc);
 #ifdef __clang__
       Matrix3D temp = Rab * Sx;
       Eigen::Map<Matrix3D> M2(temp.data());
       Eigen::Map<Matrix3D> Mx(buf);    Mx = M2;
       temp = Rab*Sy;
       Eigen::Map<Matrix3D> My(buf+9);  My = M2;
       temp = Rab*Sz;
       Eigen::Map<Matrix3D> Mz(buf+18); Mz = M2;
 #else
       Eigen::Map<Matrix3D> Mx(buf);    Mx = Rab*Sx;
       Eigen::Map<Matrix3D> My(buf+9);  My = Rab*Sy;
       Eigen::Map<Matrix3D> Mz(buf+18); Mz = Rab*Sz;
 #endif
       Jj.template block<3,3>(3,3) = dq_dR * M;
     }
   }
template<typename Derived > void g2o::internal::computeEdgeSE3Gradient (Isometry3D & E, Eigen::MatrixBase< Derived > const & JiConstRef, Eigen::MatrixBase< Derived > const & JjConstRef, const Isometry3D & Z, const Isometry3D & Xi, const Isometry3D & Xj)
Definition at line 194 of file isometry3d_gradients.h.
References compute_dq_dR(), extractRotation(), skew(), and skewT().
   {
     Eigen::MatrixBase<Derived>& Ji = const_cast<Eigen::MatrixBase<Derived>&>(JiConstRef);
     Eigen::MatrixBase<Derived>& Jj = const_cast<Eigen::MatrixBase<Derived>&>(JjConstRef);
     Ji.derived().resize(6,6);
     Jj.derived().resize(6,6);
     // compute the error at the linearization point
     const Isometry3D A=Z.inverse();
     const Isometry3D B=Xi.inverse()*Xj;
     E=A*B;
     Isometry3D::ConstLinearPart Re = extractRotation(E);
     Isometry3D::ConstLinearPart Ra = extractRotation(A);
     Isometry3D::ConstLinearPart Rb = extractRotation(B);
     Isometry3D::ConstTranslationPart tb = B.translation();
     Eigen::Matrix<double, 3, 9, Eigen::ColMajor>  dq_dR;
     compute_dq_dR (dq_dR,
         Re(0,0),Re(1,0),Re(2,0),
         Re(0,1),Re(1,1),Re(2,1),
         Re(0,2),Re(1,2),Re(2,2));
     Ji.setZero();
     Jj.setZero();
     // dte/dti
     Ji.template block<3,3>(0,0)=-Ra;
     // dte/dtj
     Jj.template block<3,3>(0,0)=Re;
     // dte/dqi
     {
       Matrix3D S;
       skewT(S,tb);
       Ji.template block<3,3>(0,3)=Ra*S;
     }
     // dte/dqj: this is zero
     double buf[27];
     Eigen::Map<Eigen::Matrix<double, 9, 3, Eigen::ColMajor> > M(buf);
     Matrix3D Sxt,Syt,Szt;
     // dre/dqi
     {
       skewT(Sxt,Syt,Szt,Rb);
       Eigen::Map<Matrix3D> Mx(buf);    Mx.noalias() = Ra*Sxt;
       Eigen::Map<Matrix3D> My(buf+9);  My.noalias() = Ra*Syt;
       Eigen::Map<Matrix3D> Mz(buf+18); Mz.noalias() = Ra*Szt;
       Ji.template block<3,3>(3,3) = dq_dR * M;
     }
     // dre/dqj
     {
       Matrix3D& Sx = Sxt;
       Matrix3D& Sy = Syt;
       Matrix3D& Sz = Szt;
       skew(Sx,Sy,Sz,Matrix3D::Identity());
       Eigen::Map<Matrix3D> Mx(buf);    Mx.noalias() = Re*Sx;
       Eigen::Map<Matrix3D> My(buf+9);  My.noalias() = Re*Sy;
       Eigen::Map<Matrix3D> Mz(buf+18); Mz.noalias() = Re*Sz;
       Jj.template block<3,3>(3,3) = dq_dR * M;
     }
   }
template<typename Derived > void g2o::internal::computeEdgeSE3PriorGradient (Isometry3D & E, const Eigen::MatrixBase< Derived > & JConstRef, const Isometry3D & Z, const Isometry3D & X, const Isometry3D & P = Isometry3D())
Definition at line 267 of file isometry3d_gradients.h.
References compute_dq_dR(), extractRotation(), and skew().
Referenced by g2o::deprecated::EdgeSE3Prior::linearizeOplus(), and g2o::EdgeSE3Prior::linearizeOplus().
   {
     Eigen::MatrixBase<Derived>& J = const_cast<Eigen::MatrixBase<Derived>&>(JConstRef);
     J.derived().resize(6,6);
     // compute the error at the linearization point
     const Isometry3D A = Z.inverse()*X;
     const Isometry3D& B = P;
     Isometry3D::ConstLinearPart Ra = extractRotation(A);
     Isometry3D::ConstLinearPart Rb = extractRotation(B);
     Isometry3D::ConstTranslationPart tb = B.translation();
     E = A*B;
     Isometry3D::ConstLinearPart Re = extractRotation(E);
     Eigen::Matrix<double, 3, 9, Eigen::ColMajor> dq_dR;
     compute_dq_dR (dq_dR,
         Re(0,0),Re(1,0),Re(2,0),
         Re(0,1),Re(1,1),Re(2,1),
         Re(0,2),Re(1,2),Re(2,2));
     J.setZero();
     // dte/dt
     J.template block<3,3>(0,0)=Ra;
     // dte/dq =0
     // dte/dqj
     {
       Matrix3D S;
       skew(S,tb);
       J.template block<3,3>(0,3)=Ra*S;
     }
     // dre/dt =0
     // dre/dq
     {
       double buf[27];
       Eigen::Map<Eigen::Matrix<double, 9, 3, Eigen::ColMajor> > M(buf);
       Matrix3D Sx,Sy,Sz;
       internal::skew(Sx,Sy,Sz,Rb);
 #ifdef __clang__
       Matrix3D temp = Ra * Sx;
       Eigen::Map<Matrix3D> M2(temp.data());
       Eigen::Map<Matrix3D> Mx(buf);    Mx = M2;
       temp = Ra*Sy;
       Eigen::Map<Matrix3D> My(buf+9);  My = M2;
       temp = Ra*Sz;
       Eigen::Map<Matrix3D> Mz(buf+18); Mz = M2;
 #else
       Eigen::Map<Matrix3D> Mx(buf);    Mx = Ra*Sx;
       Eigen::Map<Matrix3D> My(buf+9);  My = Ra*Sy;
       Eigen::Map<Matrix3D> Mz(buf+18); Mz = Ra*Sz;
 #endif
       J.template block<3,3>(3,3) = dq_dR * M;
     }
   }
int g2o::internal::computeUpperTriangleIndex (int i, int j) inline
Definition at line 29 of file base_multi_edge.h.
               {
Isometry3D::ConstLinearPart g2o::internal::extractRotation (const Isometry3D & A) inline
extract the rotation matrix from an Isometry3D matrix. Eigen itself performs an SVD decomposition to recover the nearest orthogonal matrix, since its rotation() function also handles a scaling matrix. An Isometry3D does not have a scaling portion and we assume that the Isometry3D is numerically stable while we compute the error and the Jacobians. Hence, we directly extract the rotation block out of the full matrix.
Note, we could also call .linear() on the Isometry3D. However, I dislike the name of that function a bit.
Definition at line 58 of file isometry3d_mappings.h.
Referenced by computeEdgeSE3Gradient(), computeEdgeSE3PriorGradient(), g2o::EdgeSE3Prior::initialEstimate(), toVectorET(), toVectorMQT(), and toVectorQT().
     {
       return A.matrix().topLeftCorner<3,3>();
     }
Matrix3D g2o::internal::fromCompactQuaternion (const Vector3D & v)
(qx qy, qz) -> Rotation matrix, whereas (qx, qy, qz) are assumed to be part of a quaternion which was normalized with the function above.
Definition at line 84 of file isometry3d_mappings.cpp.
Referenced by approximateNearestOrthogonalMatrix(), fromVectorMQT(), and main().
{
       double w = 1-v.squaredNorm();
       if (w<0)
         return Matrix3D::Identity();
       else
         w=sqrt(w);
       return Eigen::Quaterniond(w, v[0], v[1], v[2]).toRotationMatrix();
     }
Matrix3D g2o::internal::fromEuler (const Vector3D & v)
Euler angles (roll, pitch, yaw) -> Rotation matrix
Definition at line 59 of file isometry3d_mappings.cpp.
Referenced by approximateNearestOrthogonalMatrix(), fromVectorET(), and main().
{
       //UNOPTIMIZED
       double roll  = v[0];
       double pitch = v[1];
       double yaw   = v[2];
       double sy = sin(yaw*0.5);
       double cy = cos(yaw*0.5);
       double sp = sin(pitch*0.5);
       double cp = cos(pitch*0.5);
       double sr = sin(roll*0.5);
       double cr = cos(roll*0.5);
       double w = cr*cp*cy + sr*sp*sy;
       double x = sr*cp*cy - cr*sp*sy;
       double y = cr*sp*cy + sr*cp*sy;
       double z = cr*cp*sy - sr*sp*cy;
       return Eigen::Quaterniond(w,x,y,z).toRotationMatrix();
     }
Isometry3D g2o::internal::fromSE3Quat (const SE3Quat & t)
convert from an old SE3Quat into Isometry3D
Definition at line 144 of file isometry3d_mappings.cpp.
References g2o::SE3Quat::rotation(), and g2o::SE3Quat::translation().
Referenced by approximateNearestOrthogonalMatrix(), and g2o::VertexSE3::G2O_ATTRIBUTE_DEPRECATED().
     {
       Isometry3D result = (Isometry3D) t.rotation();
       result.translation() = t.translation();
       return result;
     }
Isometry3D g2o::internal::fromVectorET (const Vector6d & v)
(x, y, z, roll, pitch, yaw) -> Isometry3D
Definition at line 124 of file isometry3d_mappings.cpp.
References fromEuler().
Referenced by g2o::G2oSlamInterface::addEdge(), approximateNearestOrthogonalMatrix(), main(), g2o::VertexSE3Euler::read(), and g2o::EdgeSE3Euler::read().
{
       Isometry3D t;
       t = fromEuler(v.block<3,1>(3,0));
       t.translation() = v.block<3,1>(0,0);
       return t;
     }
Isometry3D g2o::internal::fromVectorMQT (const Vector6d & v)
(x, y, z, qx, qy, qz) -> Isometry3D
Definition at line 117 of file isometry3d_mappings.cpp.
References fromCompactQuaternion().
Referenced by g2o::SensorOdometry3D::addNoise(), g2o::SensorPose3DOffset::addNoise(), g2o::SensorPose3D::addNoise(), g2o::SensorSE3Prior::addNoise(), approximateNearestOrthogonalMatrix(), main(), g2o::VertexSE3::oplusImpl(), g2o::OnlineVertexSE3::oplusUpdatedEstimate(), and g2o::VertexSE3::setMinimalEstimateDataImpl().
{
       Isometry3D t;
       t = fromCompactQuaternion(v.block<3,1>(3,0));
       t.translation() = v.block<3,1>(0,0);
       return t;
     }
Isometry3D g2o::internal::fromVectorQT (const Vector7d & v)
(x, y, z, qx, qy, qz, qw) -> Isometry3D
Definition at line 131 of file isometry3d_mappings.cpp.
Referenced by g2o::G2oSlamInterface::addEdge(), approximateNearestOrthogonalMatrix(), g2o::jac_quat3_euler3(), main(), g2o::EdgeSE3::read(), g2o::ParameterStereoCamera::read(), g2o::ParameterCamera::read(), g2o::EdgeSE3Prior::read(), g2o::EdgeSE3Offset::read(), g2o::EdgeSE3Calib::read(), g2o::ParameterSE3Offset::read(), g2o::VertexSE3::read(), g2o::VertexSE3::setEstimateDataImpl(), g2o::EdgeSE3::setMeasurementData(), and g2o::EdgeSE3Prior::setMeasurementData().
{
       Isometry3D t;
       t=Eigen::Quaterniond(v[6], v[3], v[4], v[5]).toRotationMatrix();
       t.translation() = v.head<3>();
       return t;
     }
template<typename Derived > void g2o::internal::nearestOrthogonalMatrix (const Eigen::MatrixBase< Derived > & R)
computes the nearest orthogonal matrix of a rotation matrix which might be affected by numerical inaccuracies. We periodically call this function after performinag a large number of updates on vertices. This function computes an SVD to reconstruct the nearest orthogonal matrix.
Definition at line 70 of file isometry3d_mappings.h.
Referenced by main().
     {
       Eigen::JacobiSVD<Matrix3D> svd(R, Eigen::ComputeFullU | Eigen::ComputeFullV);
       double det = (svd.matrixU() * svd.matrixV().adjoint()).determinant();
       Matrix3D scaledU(svd.matrixU());
       scaledU.col(0) /= det;
       const_cast<Eigen::MatrixBase<Derived>&>(R) = scaledU * svd.matrixV().transpose();
     }
Eigen::Quaterniond& g2o::internal::normalize (Eigen::Quaterniond & q)
as above, but in-place
Definition at line 38 of file isometry3d_mappings.cpp.
Referenced by g2o::G2oSlamInterface::addEdge(), approximateNearestOrthogonalMatrix(), g2o::Plane3D::fromVector(), normalized(), g2o::Plane3D::oplus(), g2o::EdgeSE3::read(), g2o::ParameterStereoCamera::read(), g2o::ParameterCamera::read(), g2o::EdgeSE3Calib::read(), g2o::EdgeSE3Offset::read(), g2o::ParameterSE3Offset::read(), and toCompactQuaternion().
{
       q.normalize();
       if (q.w()<0) {
         q.coeffs() *= -1;
       }
       return q;
     }
G2O_TYPES_SLAM3D_ADDONS_API Vector6d g2o::internal::normalizeCartesianLine (const Vector6d & line)
Definition at line 115 of file line3d.cpp.
Referenced by main(), g2o::Line3D::ominus(), and transformCartesianLine().
{
       Vector3D p0 = line.head<3>();
       Vector3D d0 = line.tail<3>();
       d0.normalize();
       p0-=d0*(d0.dot(p0));
       Vector6d nl;
       nl.head<3>()=p0;
       nl.tail<3>()=d0;
       return nl;
     }
Eigen::Quaterniond g2o::internal::normalized (const Eigen::Quaterniond & q)
normalize the quaternion, such that ||q|| == 1 and q.w() > 0
Definition at line 32 of file isometry3d_mappings.cpp.
References normalize().
Referenced by approximateNearestOrthogonalMatrix().
{
       Eigen::Quaterniond q2(q);
       normalize(q2);
       return q2;
     }
template<typename MatrixType > void g2o::internal::pcg_atxpy (const MatrixType & A, const VectorXD & x, int xoff, VectorXD & y, int yoff) inline
Definition at line 67 of file linear_solver_pcg.h.
                                { return _tolerance;}
template<> void g2o::internal::pcg_atxpy (const MatrixXD & A, const VectorXD & x, int xoff, VectorXD & y, int yoff) inline
Definition at line 73 of file linear_solver_pcg.h.
                                { return _tolerance;}
       void setTolerance(double tolerance) { _tolerance = tolerance;}
template<typename MatrixType > void g2o::internal::pcg_axpy (const MatrixType & A, const VectorXD & x, int xoff, VectorXD & y, int yoff) inline
Definition at line 55 of file linear_solver_pcg.h.
       {
template<> void g2o::internal::pcg_axpy (const MatrixXD & A, const VectorXD & x, int xoff, VectorXD & y, int yoff) inline
Definition at line 61 of file linear_solver_pcg.h.
       {
       }
       virtual bool init()
template<typename MatrixType > void g2o::internal::pcg_axy (const MatrixType & A, const VectorXD & x, int xoff, VectorXD & y, int yoff) inline
Definition at line 42 of file linear_solver_pcg.h.
                         : public LinearSolver<MatrixType>
template<> void g2o::internal::pcg_axy (const MatrixXD & A, const VectorXD & x, int xoff, VectorXD & y, int yoff) inline
Definition at line 48 of file linear_solver_pcg.h.
   {
     public:
       LinearSolverPCG() :
       LinearSolver<MatrixType>()
template<typename Derived , typename DerivedOther > void g2o::internal::skew (Eigen::MatrixBase< Derived > & s, const Eigen::MatrixBase< DerivedOther > & v) inline
Definition at line 43 of file isometry3d_gradients.h.
Referenced by computeEdgeSE3Gradient(), and computeEdgeSE3PriorGradient().
{
       const double x=2*v(0);
       const double y=2*v(1);
       const double z=2*v(2);
       s <<  0.,  z, -y, -z,  0,  x,  y, -x,  0;
     }
template<typename Derived , typename DerivedOther > void g2o::internal::skew (Eigen::MatrixBase< Derived > & Sx, Eigen::MatrixBase< Derived > & Sy, Eigen::MatrixBase< Derived > & Sz, const Eigen::MatrixBase< DerivedOther > & R)
Definition at line 59 of file isometry3d_gradients.h.
{
       const double
         r11=2*R(0,0), r12=2*R(0,1), r13=2*R(0,2),
         r21=2*R(1,0), r22=2*R(1,1), r23=2*R(1,2),
         r31=2*R(2,0), r32=2*R(2,1), r33=2*R(2,2);
       Sx <<    0,    0,    0,  -r31, -r32, -r33,   r21,   r22,  r23;
       Sy <<  r31,  r32,  r33,     0,    0,    0,  -r11,  -r12, -r13;
       Sz << -r21, -r22, -r23,   r11,   r12, r13,     0,    0,    0;
     }
template<typename Derived , typename DerivedOther > void g2o::internal::skewT (Eigen::MatrixBase< Derived > & s, const Eigen::MatrixBase< DerivedOther > & v) inline
Definition at line 51 of file isometry3d_gradients.h.
Referenced by computeEdgeSE3Gradient().
{
       const double x=2*v(0);
       const double y=2*v(1);
       const double z=2*v(2);
       s <<  0., -z,  y,  z,  0, -x,  -y,  x,  0;
     }
template<typename Derived , typename DerivedOther > void g2o::internal::skewT (Eigen::MatrixBase< Derived > & Sx, Eigen::MatrixBase< Derived > & Sy, Eigen::MatrixBase< Derived > & Sz, const Eigen::MatrixBase< DerivedOther > & R) inline
Definition at line 73 of file isometry3d_gradients.h.
{
       const double
         r11=2*R(0,0), r12=2*R(0,1), r13=2*R(0,2),
         r21=2*R(1,0), r22=2*R(1,1), r23=2*R(1,2),
         r31=2*R(2,0), r32=2*R(2,1), r33=2*R(2,2);
       Sx <<    0,    0,    0,   r31,  r32,   r33,  -r21,  -r22, -r23;
       Sy << -r31, -r32, -r33,     0,    0,     0,   r11,   r12,  r13;
       Sz <<  r21,  r22,  r23,  -r11,  -r12, -r13,     0,    0,    0;
     }
Vector3D g2o::internal::toCompactQuaternion (const Matrix3D & R)
Rotation matrix -> (qx qy, qz)
Definition at line 77 of file isometry3d_mappings.cpp.
References normalize().
Referenced by approximateNearestOrthogonalMatrix(), main(), and toVectorMQT().
{
       Eigen::Quaterniond q(R);
       normalize(q);
       // return (x,y,z) of the quaternion
       return q.coeffs().head<3>();
     }
Vector3D g2o::internal::toEuler (const Matrix3D & R)
Rotation matrix -> Euler angles (roll, pitch, yaw)
Definition at line 47 of file isometry3d_mappings.cpp.
Referenced by approximateNearestOrthogonalMatrix(), main(), g2o::G2oSlamInterface::printVertex(), and toVectorET().
{
       Eigen::Quaterniond q(R);
       const double& q0 = q.w();
       const double& q1 = q.x();
       const double& q2 = q.y();
       const double& q3 = q.z();
       double roll = atan2(2*(q0*q1+q2*q3), 1-2*(q1*q1+q2*q2));
       double pitch = asin(2*(q0*q2-q3*q1));
       double yaw = atan2(2*(q0*q3+q1*q2), 1-2*(q2*q2+q3*q3));
       return Vector3D(roll, pitch, yaw);
     }
SE3Quat g2o::internal::toSE3Quat (const Isometry3D & t)
convert an Isometry3D to the old SE3Quat class
Definition at line 138 of file isometry3d_mappings.cpp.
Referenced by approximateNearestOrthogonalMatrix(), and g2o::VertexSE3::G2O_ATTRIBUTE_DEPRECATED().
     {
       SE3Quat result(t.matrix().topLeftCorner<3,3>(), t.translation());
       return result;
     }
Vector6d g2o::internal::toVectorET (const Isometry3D & t)
Isometry3D -> (x, y, z, roll, pitch, yaw)
Definition at line 101 of file isometry3d_mappings.cpp.
References extractRotation(), and toEuler().
Referenced by approximateNearestOrthogonalMatrix(), g2o::jac_quat3_euler3(), main(), g2o::VertexSE3Euler::write(), and g2o::EdgeSE3Euler::write().
{
       Vector6d v;
       v.block<3,1>(3,0)=toEuler(extractRotation(t));
       v.block<3,1>(0,0) = t.translation();
       return v;
     }
Vector6d g2o::internal::toVectorMQT (const Isometry3D & t)
Isometry3D -> (x, y, z, qx, qy, qz)
Definition at line 94 of file isometry3d_mappings.cpp.
References extractRotation(), and toCompactQuaternion().
Referenced by approximateNearestOrthogonalMatrix(), g2o::OnlineEdgeSE3::chi2(), g2o::EdgeSE3::computeError(), g2o::EdgeSE3Calib::computeError(), g2o::EdgeSE3Prior::computeError(), g2o::EdgeSE3Offset::computeError(), g2o::VertexSE3::getMinimalEstimateData(), main(), g2o::EdgeSE3WriteGnuplotAction::operator()(), and g2o::VertexSE3WriteGnuplotAction::operator()().
{
       Vector6d v;
       v.block<3,1>(3,0) = toCompactQuaternion(extractRotation(t));
       v.block<3,1>(0,0) = t.translation();
       return v;
     }
Vector7d g2o::internal::toVectorQT (const Isometry3D & t)
Isometry3D -> (x, y, z, qx, qy, qz, qw)
Definition at line 108 of file isometry3d_mappings.cpp.
References extractRotation().
Referenced by approximateNearestOrthogonalMatrix(), g2o::VertexSE3::getEstimateData(), g2o::EdgeSE3::getMeasurementData(), g2o::EdgeSE3Prior::getMeasurementData(), g2o::jac_quat3_euler3(), main(), g2o::EdgeSE3::write(), g2o::ParameterStereoCamera::write(), g2o::ParameterCamera::write(), g2o::EdgeSE3Prior::write(), g2o::EdgeSE3Calib::write(), g2o::EdgeSE3Offset::write(), g2o::ParameterSE3Offset::write(), and g2o::VertexSE3::write().
{
       Eigen::Quaterniond q(extractRotation(t));
       q.normalize();
       Vector7d v;
       v[3] = q.x(); v[4] = q.y(); v[5] = q.z(); v[6] = q.w();
       v.block<3,1>(0,0) = t.translation();
       return v;
     }
G2O_TYPES_SLAM3D_ADDONS_API Vector6d g2o::internal::transformCartesianLine (const Isometry3D & t, const Vector6d & line)
Definition at line 108 of file line3d.cpp.
References normalizeCartesianLine().
Referenced by main(), and g2o::Line3D::ominus().
{
       Vector6d l;
       l.head<3>() = t*line.head<3>();
       l.tail<3>() = t.linear()*line.tail<3>();
       return normalizeCartesianLine(l);
     }