g2o: /home/xuezhisd/CLionProjects/g2o/g2o/examples/plane_slam/plane_test.cpp File Reference
plane_test.cpp File Reference
#include <list>
#include <iostream>
#include "plane3d.h"
Typedefs
typedef std::list< Plane3D * > PlaneList
Functions
ostream & operator<< (ostream &os, const Plane3D &p)
void transform (PlaneList &l, const SE3Quat &t)
ostream & operator<< (ostream &os, const PlaneList &l)
int main ()
Typedef Documentation
typedef std::list<Plane3D*> PlaneList
Definition at line 15 of file plane_test.cpp.
Function Documentation
int main ()
Definition at line 33 of file plane_test.cpp.
References g2o::Plane3D::azimuth(), g2o::Plane3D::elevation(), g2o::Plane3D::fromVector(), g2o::Plane3D::normal(), g2o::Plane3D::ominus(), g2o::Plane3D::oplus(), and transform().
             {
   Plane3D p;
   cerr << "p0  " << p << endl;
   Eigen::Vector4d v;
   v << 0.5 , 0.2 , 0.1 , 10;
   Plane3D p1;
   p1.fromVector(v);
   cerr << "p1  " << p1 << endl;
   Plane3D p2 = p1;
   cerr << "p2  " << p2 << endl;
   cerr << "azimuth " << Plane3D::azimuth(p1.normal()) << endl;
   cerr << "elevation " << Plane3D::elevation(p1.normal()) << endl;
   Vector3d mv = p2.ominus(p1);
   cerr << "p ominus p " << mv[0] << " " << mv[1] << " " << mv[2] << endl;
   p1.fromVector(Eigen::Vector4d(2,2,100,10));
   cerr << "p1  " << p1 << endl;
   cerr << "azimuth " << Plane3D::azimuth(p1.normal()) << endl;
   cerr << "elevation " << Plane3D::elevation(p1.normal()) << endl;
   p2.fromVector(Eigen::Vector4d(-2,-2,100,100));
   cerr << "p2  " << p2 << endl;
   cerr << "azimuth " << Plane3D::azimuth(p2.normal()) << endl;
   cerr << "elevation " << Plane3D::elevation(p2.normal()) << endl;
   mv = p2.ominus(p1);
   cerr << "p ominus p " << mv[0] << " " << mv[1] << " " << mv[2] << endl;
   Plane3D p3=p1;
   cerr << "p3  " << p3 << endl;
   p3.oplus(mv);
   cerr << "p3.oplus(mv) " << p3 << endl;
   PlaneList l;
   Plane3D* pp = new Plane3D();
   Eigen::Vector4d coeffs;
   coeffs << 1., 0., 0., 1.;
   pp->fromVector(coeffs);
   l.push_back(pp);
   pp = new Plane3D();
   coeffs << 0., 1., 0., 1.;
   pp->fromVector(coeffs);
   l.push_back(pp);
   pp = new Plane3D();
   coeffs << 0., 0., 1., 1.;
   pp->fromVector(coeffs);
   l.push_back(pp);
   cerr << l << endl;
   AngleAxisd r(AngleAxisd(0.0, Vector3d::UnitZ())
       * AngleAxisd(0., Vector3d::UnitY())
       * AngleAxisd(0., Vector3d::UnitX()));
   SE3Quat t(r.toRotationMatrix(), Vector3d(0.9,0,0));
   cerr << t << endl;
   transform(l,t);
   cerr << l << endl;
   return 0;
 }
ostream& operator<< (ostream & os, const Plane3D & p)
Definition at line 9 of file plane_test.cpp.
References g2o::Plane3D::toVector().
{
   Eigen::Vector4d v=p.toVector();
   os << "coeffs: " << v[0] << " " << v[1] << " " << v[2] << " " << v[3];
   return os;
 }
ostream& operator<< (ostream & os, const PlaneList & l)
Definition at line 24 of file plane_test.cpp.
{
   for (PlaneList::const_iterator it=l.begin(); it!=l.end(); it++){
     const Plane3D *p = *it;
     os << *p << endl;
   }
   return os;
 }
void transform (PlaneList & l, const SE3Quat & t)
Definition at line 17 of file plane_test.cpp.
Referenced by g2o::Edge_V_V_GICP::computeError(), main(), g2o::strToLower(), and g2o::strToUpper().
{
   for (PlaneList::iterator it=l.begin(); it!=l.end(); it++){
     Plane3D *p = *it;
     *p = t*(*p);
   }
 }