g2o: /home/xuezhisd/CLionProjects/g2o/g2o/examples/calibration_odom_laser/sclam_odom_laser.cpp File Reference
sclam_odom_laser.cpp File Reference
#include <iostream>
#include <map>
#include <csignal>
#include <fstream>
#include "sclam_helpers.h"
#include "gm2dl_io.h"
#include "g2o/stuff/macros.h"
#include "g2o/stuff/color_macros.h"
#include "g2o/stuff/command_args.h"
#include "g2o/stuff/filesys_tools.h"
#include "g2o/stuff/string_tools.h"
#include "g2o/stuff/timeutil.h"
#include "g2o/core/sparse_optimizer.h"
#include "g2o/core/hyper_dijkstra.h"
#include "g2o/types/sclam2d/vertex_odom_differential_params.h"
#include "g2o/types/sclam2d/odometry_measurement.h"
#include "g2o/types/slam2d/vertex_se2.h"
#include "g2o/types/data/robot_laser.h"
#include "g2o/types/data/data_queue.h"
Functions
void sigquit_handler (int sig)
int main (int argc, char **argv)
Variables
static bool hasToStop = false
Function Documentation
int main (int argc, char ** argv)
Definition at line 69 of file sclam_odom_laser.cpp.
References g2o::addOdometryCalibLinksDifferential(), g2o::allocateSolverForSclam(), g2o::DataQueue::buffer(), g2o::OptimizableGraph::chi2(), CL_RED, g2o::SparseOptimizer::computeActiveErrors(), g2o::HyperGraph::edges(), g2o::BaseVertex< D, T >::estimate(), g2o::SparseOptimizer::findGauge(), g2o::OptimizableGraph::Vertex::fixed(), g2o::SE2::fromVector(), g2o::SparseOptimizer::gaugeFreedom(), hasToStop, g2o::HyperGraph::Vertex::id(), g2o::SparseOptimizer::initializeOptimization(), g2o::SE2::inverse(), g2o::MotionMeasurement::measurement(), g2o::RobotLaser::odomPose(), g2o::SparseOptimizer::optimize(), g2o::CommandArgs::param(), g2o::CommandArgs::paramLeftOver(), g2o::CommandArgs::parseArgs(), g2o::SE2::rotation(), g2o::OptimizableGraph::save(), g2o::OptimizableGraph::Vertex::setFixed(), g2o::SparseOptimizer::setForceStopFlag(), g2o::SparseOptimizer::setVerbose(), g2o::VelocityMeasurement::setVl(), g2o::VelocityMeasurement::setVr(), g2o::HyperDijkstra::shortestPaths(), sigquit_handler(), g2o::RobotData::timestamp(), g2o::SE2::toVector(), g2o::SE2::translation(), g2o::OptimizableGraph::vertex(), g2o::HyperGraph::vertices(), g2o::HyperDijkstra::visited(), g2o::VelocityMeasurement::vl(), and g2o::VelocityMeasurement::vr().
 {
   bool fixLaser;
   int maxIterations;
   bool verbose;
   string inputFilename;
   string outputfilename;
   string rawFilename;
   string odomTestFilename;
   string dumpGraphFilename;
   // command line parsing
   CommandArgs commandLineArguments;
   commandLineArguments.param("i", maxIterations, 10, "perform n iterations");
   commandLineArguments.param("v", verbose, false, "verbose output of the optimization process");
   commandLineArguments.param("o", outputfilename, "", "output final version of the graph");
   commandLineArguments.param("test", odomTestFilename, "", "apply odometry calibration to some test data");
   commandLineArguments.param("dump", dumpGraphFilename, "", "write the graph to the disk");
   commandLineArguments.param("fixLaser", fixLaser, false, "keep the laser offset fixed during optimization");
   commandLineArguments.paramLeftOver("gm2dl-input", inputFilename, "", "gm2dl file which will be processed");
   commandLineArguments.paramLeftOver("raw-log", rawFilename, "", "raw log file containing the odometry");
   commandLineArguments.parseArgs(argc, argv);
   SparseOptimizer optimizer;
   optimizer.setVerbose(verbose);
   optimizer.setForceStopFlag(&hasToStop);
   allocateSolverForSclam(optimizer);
   // loading
   if (! Gm2dlIO::readGm2dl(inputFilename, optimizer, false)) {
     cerr << "Error while loading gm2dl file" << endl;
   }
   DataQueue robotLaserQueue;
   int numLaserOdom = Gm2dlIO::readRobotLaser(rawFilename, robotLaserQueue);
   if (numLaserOdom == 0) {
     cerr << "No raw information read" << endl;
     return 0;
   }
   cerr << "Read " << numLaserOdom << " laser readings from file" << endl;
   bool gaugeFreedom = optimizer.gaugeFreedom();
   OptimizableGraph::Vertex* gauge = optimizer.findGauge();
   if (gaugeFreedom) {
     if (! gauge) {
       cerr <<  "# cannot find a vertex to fix in this thing" << endl;
       return 2;
     } else {
       cerr << "# graph is fixed by node " << gauge->id() << endl;
       gauge->setFixed(true);
     }
   } else {
     cerr << "# graph is fixed by priors" << endl;
   }
   addOdometryCalibLinksDifferential(optimizer, robotLaserQueue);
   // sanity check
   HyperDijkstra d(&optimizer);
   UniformCostFunction f;
   d.shortestPaths(gauge, &f);
   //cerr << PVAR(d.visited().size()) << endl;
   if (d.visited().size()!=optimizer.vertices().size()) {
     cerr << CL_RED("Warning: d.visited().size() != optimizer.vertices().size()") << endl;
     cerr << "visited: " << d.visited().size() << endl;
     cerr << "vertices: " << optimizer.vertices().size() << endl;
     if (1)
       for (SparseOptimizer::VertexIDMap::const_iterator it = optimizer.vertices().begin(); it != optimizer.vertices().end(); ++it) {
         OptimizableGraph::Vertex* v = static_cast<OptimizableGraph::Vertex*>(it->second);
         if (d.visited().count(v) == 0) {
           cerr << "\t unvisited vertex " << it->first << " " << (void*)v << endl;
           v->setFixed(true);
         }
       }
   }
   for (SparseOptimizer::VertexIDMap::const_iterator it = optimizer.vertices().begin(); it != optimizer.vertices().end(); ++it) {
     OptimizableGraph::Vertex* v = static_cast<OptimizableGraph::Vertex*>(it->second);
     if (v->fixed()) {
       cerr << "\t fixed vertex " << it->first << endl;
     }
   }
   VertexSE2* laserOffset = dynamic_cast<VertexSE2*>(optimizer.vertex(Gm2dlIO::ID_LASERPOSE));
   VertexOdomDifferentialParams* odomParamsVertex = dynamic_cast<VertexOdomDifferentialParams*>(optimizer.vertex(Gm2dlIO::ID_ODOMCALIB));
   if (fixLaser) {
     cerr << "Fix position of the laser offset" << endl;
     laserOffset->setFixed(true);
   }
   signal(SIGINT, sigquit_handler);
   cerr << "Doing full estimation" << endl;
   optimizer.initializeOptimization();
   optimizer.computeActiveErrors();
   cerr << "Initial chi2 = " << FIXED(optimizer.chi2()) << endl;
   int i=optimizer.optimize(maxIterations);
   if (maxIterations > 0 && !i){
     cerr << "optimize failed, result might be invalid" << endl;
   }
   if (laserOffset) {
     cerr << "Calibrated laser offset (x, y, theta):" << laserOffset->estimate().toVector().transpose() << endl;
   }
   if (odomParamsVertex) {
     cerr << "Odometry parameters (scaling factors (v_l, v_r, b)): " << odomParamsVertex->estimate().transpose() << endl;
   }
   cerr << "vertices: " << optimizer.vertices().size() << endl;
   cerr << "edges: " << optimizer.edges().size() << endl;
   if (dumpGraphFilename.size() > 0) {
     cerr << "Writing " << dumpGraphFilename << " ... ";
     optimizer.save(dumpGraphFilename.c_str());
     cerr << "done." << endl;
   }
   // optional input of a seperate file for applying the odometry calibration
   if (odomTestFilename.size() > 0) {
     DataQueue testRobotLaserQueue;
     int numTestOdom = Gm2dlIO::readRobotLaser(odomTestFilename, testRobotLaserQueue);
     if (numTestOdom == 0) {
       cerr << "Unable to read test data" << endl;
     } else {
       ofstream rawStream("odometry_raw.txt");
       ofstream calibratedStream("odometry_calibrated.txt");
       const Vector3d& odomCalib = odomParamsVertex->estimate();
       RobotLaser* prev = dynamic_cast<RobotLaser*>(testRobotLaserQueue.buffer().begin()->second);
       SE2 prevCalibratedPose = prev->odomPose();
       for (DataQueue::Buffer::const_iterator it = testRobotLaserQueue.buffer().begin(); it != testRobotLaserQueue.buffer().end(); ++it) {
         RobotLaser* cur = dynamic_cast<RobotLaser*>(it->second);
         assert(cur);
         double dt = cur->timestamp() - prev->timestamp();
         SE2 motion = prev->odomPose().inverse() * cur->odomPose();
         // convert to velocity measurment
         MotionMeasurement motionMeasurement(motion.translation().x(), motion.translation().y(), motion.rotation().angle(), dt);
         VelocityMeasurement velocityMeasurement = OdomConvert::convertToVelocity(motionMeasurement);
         // apply calibration
         VelocityMeasurement calibratedVelocityMeasurment = velocityMeasurement;
         calibratedVelocityMeasurment.setVl(odomCalib(0) * calibratedVelocityMeasurment.vl());
         calibratedVelocityMeasurment.setVr(odomCalib(1) * calibratedVelocityMeasurment.vr());
         MotionMeasurement mm = OdomConvert::convertToMotion(calibratedVelocityMeasurment, odomCalib(2));
         // combine calibrated odometry with the previous pose
         SE2 remappedOdom;
         remappedOdom.fromVector(mm.measurement());
         SE2 calOdomPose = prevCalibratedPose * remappedOdom;
         // write output
         rawStream << prev->odomPose().translation().x() << " " << prev->odomPose().translation().y() << " " << prev->odomPose().rotation().angle() << endl;
         calibratedStream << calOdomPose.translation().x() << " " << calOdomPose.translation().y() << " " << calOdomPose.rotation().angle() << endl;
         prevCalibratedPose = calOdomPose;
         prev = cur;
       }
     }
   }
   if (outputfilename.size() > 0) {
     Gm2dlIO::updateLaserData(optimizer);
     cerr << "Writing " << outputfilename << " ... ";
     bool writeStatus = Gm2dlIO::writeGm2dl(outputfilename, optimizer);
     cerr << (writeStatus ? "done." : "failed") << endl;
   }
   return 0;
 }
void sigquit_handler (int sig)
Definition at line 57 of file sclam_odom_laser.cpp.
References hasToStop.
Referenced by main().
 {
   if (sig == SIGINT) {
     hasToStop = true;
     static int cnt = 0;
     if (cnt++ == 2) {
       cerr << " forcing exit" << endl;
       exit(1);
     }
   }
 }
Variable Documentation
bool hasToStop = false static
Definition at line 55 of file sclam_odom_laser.cpp.
Referenced by main(), and sigquit_handler().