g2o: Simulator Struct Reference
Simulator Struct Reference
Public Member Functions
Simulator (OptimizableGraph *graph_)
void sense (int robotIndex)
void move (int robotIndex, const Isometry3d &newRobotPose)
void relativeMove (int robotIndex, const Isometry3d &delta)
Public Member Functions inherited from SimulatorItem
SimulatorItem (OptimizableGraph *graph_)
OptimizableGraph * graph ()
virtual ~SimulatorItem ()
Public Attributes
int _lastVertexId
WorldItemSet _world
RobotVector _robots
Additional Inherited Members
Protected Attributes inherited from SimulatorItem
OptimizableGraph * _graph
Detailed Description
Definition at line 160 of file simulator_3d_plane.cpp.
Constructor & Destructor Documentation
Simulator::Simulator (OptimizableGraph * graph_) inline
Definition at line 161 of file simulator_3d_plane.cpp.
 : SimulatorItem(graph_), _lastVertexId(0){}
Member Function Documentation
void Simulator::move (int robotIndex, const Isometry3d & newRobotPose) inline
Definition at line 170 of file simulator_3d_plane.cpp.
References g2o::Robot< RobotPoseObject >::move().
Referenced by main().
{
     Robot* r=_robots[robotIndex];
     r->move(newRobotPose, _lastVertexId);
   }
void Simulator::relativeMove (int robotIndex, const Isometry3d & delta) inline
Definition at line 175 of file simulator_3d_plane.cpp.
References g2o::Robot< RobotPoseObject >::relativeMove().
Referenced by main().
{
     Robot* r=_robots[robotIndex];
     r->relativeMove(delta, _lastVertexId);
   }
void Simulator::sense (int robotIndex) inline
Definition at line 162 of file simulator_3d_plane.cpp.
References g2o::BaseRobot::sense().
Referenced by main().
{
     Robot* r=_robots[robotIndex];
     for (WorldItemSet::iterator it=_world.begin(); it!=_world.end(); it++){
       WorldItem* item=*it;
       r->sense(item);
     }
   }
Member Data Documentation
int Simulator::_lastVertexId
Definition at line 180 of file simulator_3d_plane.cpp.
Referenced by main().
RobotVector Simulator::_robots
Definition at line 182 of file simulator_3d_plane.cpp.
Referenced by main().
WorldItemSet Simulator::_world
Definition at line 181 of file simulator_3d_plane.cpp.
Referenced by main().
The documentation for this struct was generated from the following file:
/home/xuezhisd/CLionProjects/g2o/g2o/examples/plane_slam/simulator_3d_plane.cpp