g2o: g2o::BackBoneTreeAction Struct Reference
g2o::BackBoneTreeAction Struct Reference
#include <backbone_tree_action.h>
Public Member Functions
BackBoneTreeAction (SparseOptimizer *optimizer, std::string vertexTag, int level, int step)
void init ()
initializes the visit and clears the internal structures
VertexStarMap & vertexStarMap ()
map vertex->star. Contains the most recent vertex assignment
VertexStarMultimap & vertexStarMultiMap ()
multimap vertex->star. Contains all the vertex assignments to all stars
HyperGraph::EdgeSet & freeEdges ()
edges that are not yet assigned to any star
virtual double perform (HyperGraph::Vertex *v, HyperGraph::Vertex *vParent, HyperGraph::Edge *e, double distance)
Public Member Functions inherited from g2o::HyperDijkstra::TreeAction
virtual double perform (HyperGraph::Vertex *v, HyperGraph::Vertex *vParent, HyperGraph::Edge *e)
Protected Member Functions
void addToMap (Star *s, HyperGraph::Vertex *v)
Star * getStar (HyperGraph::Vertex *v)
bool fillStar (Star *s, HyperGraph::Edge *e_)
helper function that adds to a star an edge and all its vertices
Protected Attributes
SparseOptimizer * _optimizer
std::string _vertexTag
int _level
int _step
VertexStarMap _vsMap
VertexStarMultimap _vsMmap
HyperGraph::EdgeSet _freeEdges
Factory * _factory
Detailed Description
Dijkstra traversal action that constructs a backbone skeleton on the graph. It assumes that the traversal contains only edges and vertices belonging to classes that can be used to construct a backbone. After a visit is invoked, it returns vector of stars to which the backbone nodes have been assigned
Definition at line 20 of file backbone_tree_action.h.
Constructor & Destructor Documentation
g2o::BackBoneTreeAction::BackBoneTreeAction (SparseOptimizer * optimizer, std::string vertexTag, int level, int step)
creates a tree action for constructing the backbone
Parameters
optimizer the optimizer on which the stars are constructed
vertexTag the tag of the vertices to use as backbone nodes
level the level of the lowLevelEdges of the stars in the backbone
step depth in tree after which a new star is initialized
Definition at line 9 of file backbone_tree_action.cpp.
References _factory, init(), and g2o::Factory::instance().
                                                                                                             :
     _optimizer(optimizer),
     _vertexTag(vertexTag),
     _level(level),
     _step(step) {
     _factory=Factory::instance();
     init();
   }
Member Function Documentation
void g2o::BackBoneTreeAction::addToMap (Star * s, HyperGraph::Vertex * v) protected
helper function for adding a vertex to a star. If the vertex is already in _vertexToEdgeMap it replaces the associated star. _vertexStarMultimap is only augmented, thus it contains all associations
Parameters
s the star
v the vertex
Definition at line 56 of file backbone_tree_action.cpp.
References g2o::Star::_lowLevelVertices, _vsMap, and _vsMmap.
Referenced by freeEdges(), and perform().
{
     OptimizableGraph::Vertex* v= (OptimizableGraph::Vertex*)v_;
     VertexStarMap::iterator it=_vsMap.find(v);
     if (it!=_vsMap.end())
       it->second = s;
     else
       _vsMap.insert(make_pair(v,s));
     _vsMmap.insert(make_pair(v,s));
     s->_lowLevelVertices.insert(v);
   }
bool g2o::BackBoneTreeAction::fillStar (Star * s, HyperGraph::Edge * e_) protected
helper function that adds to a star an edge and all its vertices
Definition at line 75 of file backbone_tree_action.cpp.
References _freeEdges, g2o::Star::_lowLevelEdges, g2o::Star::_lowLevelVertices, and g2o::HyperGraph::Edge::vertices().
Referenced by freeEdges(), and perform().
{
     OptimizableGraph::Edge* e = (OptimizableGraph::Edge*) e_;
     HyperGraph::EdgeSet::iterator it=_freeEdges.find(e);
     if (it!=_freeEdges.end()) {
       _freeEdges.erase(it);
       s->_lowLevelEdges.insert(e);
       for (size_t i=0; i<e->vertices().size(); i++){
   s->_lowLevelVertices.insert(e->vertices()[i]);
       }
       return true;
     }
     return false;
   }
HyperGraph::EdgeSet& g2o::BackBoneTreeAction::freeEdges () inline
edges that are not yet assigned to any star
Definition at line 38 of file backbone_tree_action.h.
References _freeEdges, addToMap(), fillStar(), getStar(), and perform().
 {return _freeEdges;}
Star * g2o::BackBoneTreeAction::getStar (HyperGraph::Vertex * v) protected
helper function to retrieve the most recent star of a vertex.
Parameters
v the vertex
Definition at line 67 of file backbone_tree_action.cpp.
References _vsMap.
Referenced by freeEdges(), and perform().
{
     OptimizableGraph::Vertex* v= (OptimizableGraph::Vertex*)v_;
     VertexStarMap::iterator it=_vsMap.find(v);
     if (it==_vsMap.end())
       return 0;
     return it->second;
   }
void g2o::BackBoneTreeAction::init ()
initializes the visit and clears the internal structures
Definition at line 18 of file backbone_tree_action.cpp.
References _freeEdges, _level, _optimizer, _vsMap, _vsMmap, g2o::HyperGraph::edges(), and g2o::OptimizableGraph::Edge::level().
Referenced by BackBoneTreeAction().
{
     _vsMap.clear();
     _vsMmap.clear();
     _freeEdges.clear();
     for (HyperGraph::EdgeSet::iterator it=_optimizer->edges().begin(); it!=_optimizer->edges().end(); it++){
       OptimizableGraph::Edge* e = (OptimizableGraph::Edge*)(*it);
       if (e->level()==_level) {
   _freeEdges.insert(e);
       }
     }
   }
double g2o::BackBoneTreeAction::perform (HyperGraph::Vertex * v, HyperGraph::Vertex * vParent, HyperGraph::Edge * e, double distance) virtual
action to be performed during the descent of the dijkstra tree. it constructs stars according to the dijkstra tree A new star is created every time the depth increases of _step.
Parameters
v the vertex
vParent the parent vertex
e the edge between v and its parent
distance the depth in the tree
Reimplemented from g2o::HyperDijkstra::TreeAction.
Definition at line 30 of file backbone_tree_action.cpp.
References _factory, g2o::Star::_gauge, _level, _optimizer, _step, _vertexTag, addToMap(), fillStar(), getStar(), and g2o::Factory::tag().
Referenced by freeEdges().
{
     int depth=(int) distance;
     if (_factory->tag(v)!= _vertexTag)
       return 0;
     Star* parentStar=getStar(vParent);
     if (! parentStar){
       parentStar=new Star(_level+1,_optimizer);
       addToMap(parentStar, vParent);
       parentStar->_gauge.insert(vParent);
     }
     addToMap(parentStar,v);
     fillStar(parentStar, e);
     // every _step levels you go down in the tree, create a new star
     if (depth && ! (depth%_step )){
       Star* star=new Star(_level+1, _optimizer);
       addToMap(star,v);
       star->_gauge.insert(v);
     }
     return 1;
   }
VertexStarMap& g2o::BackBoneTreeAction::vertexStarMap () inline
map vertex->star. Contains the most recent vertex assignment
Definition at line 34 of file backbone_tree_action.h.
References _vsMap.
 {return _vsMap;}
VertexStarMultimap& g2o::BackBoneTreeAction::vertexStarMultiMap () inline
multimap vertex->star. Contains all the vertex assignments to all stars
Definition at line 36 of file backbone_tree_action.h.
References _vsMmap.
 {return _vsMmap;}
Member Data Documentation
Factory* g2o::BackBoneTreeAction::_factory protected
Definition at line 78 of file backbone_tree_action.h.
Referenced by BackBoneTreeAction(), and perform().
HyperGraph::EdgeSet g2o::BackBoneTreeAction::_freeEdges protected
Definition at line 77 of file backbone_tree_action.h.
Referenced by fillStar(), freeEdges(), and init().
int g2o::BackBoneTreeAction::_level protected
Definition at line 72 of file backbone_tree_action.h.
Referenced by init(), and perform().
SparseOptimizer* g2o::BackBoneTreeAction::_optimizer protected
Definition at line 70 of file backbone_tree_action.h.
Referenced by init(), and perform().
int g2o::BackBoneTreeAction::_step protected
Definition at line 73 of file backbone_tree_action.h.
Referenced by perform().
std::string g2o::BackBoneTreeAction::_vertexTag protected
Definition at line 71 of file backbone_tree_action.h.
Referenced by perform().
VertexStarMap g2o::BackBoneTreeAction::_vsMap protected
Definition at line 75 of file backbone_tree_action.h.
Referenced by addToMap(), getStar(), init(), and vertexStarMap().
VertexStarMultimap g2o::BackBoneTreeAction::_vsMmap protected
Definition at line 76 of file backbone_tree_action.h.
Referenced by addToMap(), init(), and vertexStarMultiMap().
The documentation for this struct was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_hierarchical/backbone_tree_action.h
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_hierarchical/backbone_tree_action.cpp