g2o: LineInfo Struct Reference
LineInfo Struct Reference
Public Member Functions
LineInfo (VertexSegment2D *s)
LineInfo (VertexSegment2D *s)
Public Attributes
VertexLine2D * line
VertexPointXY * p1
VertexPointXY * p2
Detailed Description
Definition at line 99 of file converteSegmentLine.cpp.
Constructor & Destructor Documentation
LineInfo::LineInfo (VertexSegment2D * s) inline
Definition at line 100 of file converteSegmentLine.cpp.
References g2o::computeLineParameters(), g2o::VertexSegment2D::estimateP1(), g2o::VertexSegment2D::estimateP2(), and g2o::HyperGraph::Vertex::id().
{
     line=new VertexLine2D();
     line->setId(s->id());
     line->setEstimate(computeLineParameters(s->estimateP1(), s->estimateP2()));
     p1=0;
     p2=0;
   }
LineInfo::LineInfo (VertexSegment2D * s) inline
Definition at line 60 of file convertSegmentLine.cpp.
References g2o::computeLineParameters(), g2o::VertexSegment2D::estimateP1(), g2o::VertexSegment2D::estimateP2(), and g2o::HyperGraph::Vertex::id().
{
     line=new VertexLine2D();
     line->setId(s->id());
     line->setEstimate(computeLineParameters(s->estimateP1(), s->estimateP2()));
     p1=0;
     p2=0;
   }
Member Data Documentation
VertexLine2D * LineInfo::line
Definition at line 107 of file converteSegmentLine.cpp.
Referenced by main().
VertexPointXY * LineInfo::p1
Definition at line 108 of file converteSegmentLine.cpp.
Referenced by main().
VertexPointXY * LineInfo::p2
Definition at line 109 of file converteSegmentLine.cpp.
Referenced by main().
The documentation for this struct was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_simulator/converteSegmentLine.cpp
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_simulator/convertSegmentLine.cpp