g2o: g2o::Star Struct Reference
g2o::Star Struct Reference
#include <star.h>
Public Member Functions
Star (int level, SparseOptimizer *optimizer)
bool labelStarEdges (int iterations, EdgeLabeler *labeler)
int level () const
returns the level of the lower edges in the star
SparseOptimizer * optimizer ()
returns the optimizer
HyperGraph::EdgeSet & lowLevelEdges ()
low level edge set
HyperGraph::EdgeSet & starEdges ()
high level edge set
HyperGraph::EdgeSet & starFrontierEdges ()
edges in the high level that lead to some node owned by a different star
HyperGraph::VertexSet & gauge ()
set of nodes to keep fixed in the optimization
HyperGraph::VertexSet & lowLevelVertices ()
set of all vertices in the low level
Public Attributes
int _level
level of the star
SparseOptimizer * _optimizer
optimizer
HyperGraph::EdgeSet _lowLevelEdges
edges in the lower level
HyperGraph::EdgeSet _starEdges
edges in the star
HyperGraph::EdgeSet _starFrontierEdges
edges in the star that lead to some other star
HyperGraph::VertexSet _gauge
vertices that are fixed (center of the star)
HyperGraph::VertexSet _lowLevelVertices
vertices that are fixed (center of the star)
Detailed Description
Class that represents a subgraph in the hierarchical optimization. The subgraph is consisting of
a set of "central" nodes forming the gauge
a set of edges and vertices in the lower (denser) level
a set of edges in the higher level, each one going from the gauge to one of the vertices in the lower level These edges form the "star" view at the higher level
Additionally, a star provides a function to compute the parameters for each of the edges in the higher level, based on the actual configuration of the state variables. It does so by using an EdgeLabeler class.
Definition at line 26 of file star.h.
Constructor & Destructor Documentation
g2o::Star::Star (int level, SparseOptimizer * optimizer)
constructs a star at level l in the graph of the sparse optimizer passed as argument
Parameters
level the (higher) level of the star
optimizer the optimizer
Definition at line 7 of file star.cpp.
 : _level(level), _optimizer(optimizer) {}
Member Function Documentation
HyperGraph::VertexSet& g2o::Star::gauge () inline
set of nodes to keep fixed in the optimization
Definition at line 49 of file star.h.
References _gauge.
Referenced by g2o::computeBorder(), g2o::computeSimpleStars(), and main().
 {return _gauge;}
bool g2o::Star::labelStarEdges (int iterations, EdgeLabeler * labeler)
labels the edges in the star by first optimizing the low level edges, then by calling the labelEdge of the labeler.
Parameters
iterations the number of iterations of the optimizer
labeler the labeler
Definition at line 9 of file star.cpp.
References _gauge, _lowLevelEdges, _optimizer, _starEdges, g2o::SparseOptimizer::activeVertices(), g2o::OptimizationAlgorithmWithHessian::buildLinearStructure(), g2o::SparseOptimizer::computeActiveErrors(), g2o::SparseOptimizer::computeInitialGuess(), g2o::OptimizableGraph::Vertex::hessianIndex(), g2o::HyperGraph::Vertex::id(), g2o::SparseOptimizer::indexMapping(), g2o::OptimizationAlgorithm::init(), g2o::SparseOptimizer::initializeOptimization(), g2o::EdgeLabeler::labelEdges(), g2o::SparseOptimizer::optimize(), optimizer(), g2o::OptimizableGraph::Vertex::pop(), g2o::OptimizableGraph::Vertex::push(), g2o::OptimizableGraph::Vertex::setFixed(), g2o::SparseOptimizer::solver(), g2o::OptimizationAlgorithmWithHessian::updateLinearSystem(), and g2o::HyperGraph::Edge::vertices().
Referenced by g2o::assignHierarchicalEdges(), and g2o::computeSimpleStars().
{
     // mark all vertices in the lowLevelEdges as floating
     bool ok=true;
     std::set<OptimizableGraph::Vertex*> vset;
     for (HyperGraph::EdgeSet::iterator it=_lowLevelEdges.begin(); it!=_lowLevelEdges.end(); it++){
       HyperGraph::Edge* e=*it;
       for (size_t i=0; i<e->vertices().size(); i++){
         OptimizableGraph::Vertex* v=(OptimizableGraph::Vertex*)e->vertices()[i];
         v->setFixed(false);
         vset.insert(v);
       }
     }
     for (std::set<OptimizableGraph::Vertex*>::iterator it=vset.begin(); it!=vset.end(); it++){
       OptimizableGraph::Vertex* v = *it;
       v->push();
     }
     // fix all vertices in the gauge
     //cerr << "fixing gauge: ";
     for (HyperGraph::VertexSet::iterator it = _gauge.begin(); it!=_gauge.end(); it++){
       OptimizableGraph::Vertex* v=(OptimizableGraph::Vertex*)*it;
       //cerr << v->id() << " ";
       v->setFixed(true);
     }
     //cerr << endl;
     if (iterations>0){
       _optimizer->initializeOptimization(_lowLevelEdges);
       _optimizer->computeInitialGuess();
       int result=_optimizer->optimize(iterations);
       if (result<1){
         cerr << "Vertices num: " << _optimizer->activeVertices().size() << "ids: ";
         for (size_t i=0; i<_optimizer->indexMapping().size(); i++){
           cerr << _optimizer->indexMapping()[i]->id() << " " ;
         }
         cerr << endl;
         cerr << "!!! optimization failure" << endl;
         cerr << "star size=" << _lowLevelEdges.size() << endl;
         cerr << "gauge: ";
         for (HyperGraph::VertexSet::iterator it=_gauge.begin(); it!=_gauge.end(); it++){
           OptimizableGraph::Vertex* v = (OptimizableGraph::Vertex*)*it;
           cerr << "[" << v->id() << " " << v->hessianIndex() << "] ";
         }
         cerr << endl;
         ok=false;
       }
     }  else {
       optimizer()->initializeOptimization(_lowLevelEdges);
       // cerr << "guess" << endl;
       //optimizer()->computeInitialGuess();
       // cerr << "solver init" << endl;
       optimizer()->solver()->init();
       // cerr << "structure" << endl;
       OptimizationAlgorithmWithHessian* solverWithHessian = dynamic_cast<OptimizationAlgorithmWithHessian*> (optimizer()->solver());
       if (!solverWithHessian->buildLinearStructure())
         cerr << "FATAL: failure while building linear structure" << endl;
       // cerr << "errors" << endl;
       optimizer()->computeActiveErrors();
       // cerr << "system" << endl;
       solverWithHessian->updateLinearSystem();
     }
     std::set<OptimizableGraph::Edge*> star;
     for(HyperGraph::EdgeSet::iterator it=_starEdges.begin(); it!=_starEdges.end(); it++){
       star.insert((OptimizableGraph::Edge*)*it);
     }
     if (ok) {
       int result = labeler->labelEdges(star);
       if (result < 0)
         ok=false;
     }
     // release all vertices in the gauge
     for (std::set<OptimizableGraph::Vertex*>::iterator it=vset.begin(); it!=vset.end(); it++){
       OptimizableGraph::Vertex* v = *it;
       v->pop();
     }
     for (HyperGraph::VertexSet::iterator it=_gauge.begin(); it!=_gauge.end(); it++){
       OptimizableGraph::Vertex* v=(OptimizableGraph::Vertex*)*it;
       v->setFixed(false);
     }
     return ok;
   }
int g2o::Star::level () const inline
returns the level of the lower edges in the star
Definition at line 39 of file star.h.
References _level.
 { return _level; };
HyperGraph::EdgeSet& g2o::Star::lowLevelEdges () inline
low level edge set
Definition at line 43 of file star.h.
References _lowLevelEdges.
Referenced by g2o::assignHierarchicalEdges(), g2o::computeSimpleStars(), and g2o::constructEdgeStarMap().
 {return _lowLevelEdges;}
HyperGraph::VertexSet& g2o::Star::lowLevelVertices () inline
set of all vertices in the low level
Definition at line 51 of file star.h.
References _lowLevelVertices.
Referenced by g2o::assignHierarchicalEdges().
 {return _lowLevelVertices;}
SparseOptimizer* g2o::Star::optimizer () inline
returns the optimizer
Definition at line 41 of file star.h.
References _optimizer.
Referenced by g2o::computeSimpleStars(), and labelStarEdges().
 { return _optimizer;}
HyperGraph::EdgeSet& g2o::Star::starEdges () inline
high level edge set
Definition at line 45 of file star.h.
References _starEdges.
Referenced by g2o::constructEdgeStarMap().
 {return _starEdges;}
HyperGraph::EdgeSet& g2o::Star::starFrontierEdges () inline
edges in the high level that lead to some node owned by a different star
Definition at line 47 of file star.h.
References _starFrontierEdges.
Referenced by g2o::computeBorder(), and main().
 {return _starFrontierEdges;}
Member Data Documentation
HyperGraph::VertexSet g2o::Star::_gauge
vertices that are fixed (center of the star)
Definition at line 64 of file star.h.
Referenced by g2o::assignHierarchicalEdges(), g2o::computeSimpleStars(), gauge(), labelStarEdges(), and g2o::BackBoneTreeAction::perform().
int g2o::Star::_level
level of the star
Definition at line 54 of file star.h.
Referenced by level().
HyperGraph::EdgeSet g2o::Star::_lowLevelEdges
edges in the lower level
Definition at line 58 of file star.h.
Referenced by g2o::assignHierarchicalEdges(), g2o::computeSimpleStars(), g2o::BackBoneTreeAction::fillStar(), labelStarEdges(), and lowLevelEdges().
HyperGraph::VertexSet g2o::Star::_lowLevelVertices
vertices that are fixed (center of the star)
Definition at line 66 of file star.h.
Referenced by g2o::BackBoneTreeAction::addToMap(), g2o::assignHierarchicalEdges(), g2o::computeSimpleStars(), g2o::BackBoneTreeAction::fillStar(), and lowLevelVertices().
SparseOptimizer* g2o::Star::_optimizer
optimizer
Definition at line 56 of file star.h.
Referenced by labelStarEdges(), and optimizer().
HyperGraph::EdgeSet g2o::Star::_starEdges
edges in the star
Definition at line 60 of file star.h.
Referenced by g2o::assignHierarchicalEdges(), g2o::computeBorder(), g2o::computeSimpleStars(), labelStarEdges(), main(), and starEdges().
HyperGraph::EdgeSet g2o::Star::_starFrontierEdges
edges in the star that lead to some other star
Definition at line 62 of file star.h.
Referenced by starFrontierEdges().
The documentation for this struct was generated from the following files:
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_hierarchical/star.h
/home/xuezhisd/CLionProjects/g2o/g2o/apps/g2o_hierarchical/star.cpp