g2o: InvChi2CostFunction Struct Reference
InvChi2CostFunction Struct Reference
Public Member Functions
virtual double operator() (HyperGraph::Edge *edge, HyperGraph::Vertex *from, HyperGraph::Vertex *to)
Public Member Functions inherited from g2o::HyperDijkstra::CostFunction
virtual ~CostFunction ()
Detailed Description
Definition at line 40 of file g2o-unfold.cpp.
Member Function Documentation
double InvChi2CostFunction::operator() (HyperGraph::Edge * edge, HyperGraph::Vertex * from, HyperGraph::Vertex * to) virtual
Implements g2o::HyperDijkstra::CostFunction.
Definition at line 44 of file g2o-unfold.cpp.
References g2o::OptimizableGraph::Edge::chi2(), g2o::OptimizableGraph::Edge::computeError(), and g2o::OptimizableGraph::Edge::robustKernel().
{
   OptimizableGraph::Edge* e = dynamic_cast<OptimizableGraph::Edge*>(edge);
 e->computeError();
 if(e->robustKernel())
   e->robustifyError();
 return 1.0/(1e-6 + e->chi2());
 }
The documentation for this struct was generated from the following file:
/home/xuezhisd/CLionProjects/g2o/g2o/examples/g2o_unfold/g2o-unfold.cpp